### ISSUE TITLE
How do I AES decipher?

### ISSUE THREAD

**Issue by losh11** [krzyzanowskim/CryptoSwift#100]
I'm not too sure I understand your usage of AES encipher and decipher. I've looked online, and I could only find more questions, no answers. I'll tell you want I want to do, and if possible, would you give me a tutorial how to use it.

I've got a cipher text, represented as var 'cipher key' text. And the cipher text is labeled as 'text'.

var text = "U2FsdGVkX19RkcBR4H9U0LLszd07dnwRf+WKxV8V5nI="
var chiperkey = "Password1"

Now how do I decipher this? I can do this through online tools simply by inputting both into two fields, and can I do this with CryptoSwift. And how would I do this?

**Comment by krzyzanowskim** [comment]
You must not confuse string with bytes of data. You have to operate on bytes, so basically you have to decode your base64 encoded input and use it

https://github.com/krzyzanowskim/CryptoSwift/issues/88
