### ISSUE TITLE
Can this be fixed for Swift 2.0?

### ISSUE THREAD

**Issue by losh11** [krzyzanowskim/CryptoSwift#101]

**Comment by krzyzanowskim** [comment]
It's on branch swift20 https://github.com/krzyzanowskim/CryptoSwift/issues/91

**Comment by losh11** [comment]
Sorry to reopen this, but I'm on Xcode 7 beta 3 and am getting lots of errors and warnings when adding that to my project.

Look at this screenshot:- http://i.imgur.com/VpkhZgm.png

**Comment by krzyzanowskim** [comment]
are you sure you use branch swift20 ?

**Comment by zeusent** [comment]
Sorry for my dumb question and for re-opening this (in case I do with my comment). I was just wondering when are you planning on moving the Swift 2.0 branch to master. I'm using CryptoSwift as a dependency for one of my pods and can't specify the branch by doing so.

Thanks!

**Comment by krzyzanowskim** [comment]
when Apple release Swift 2.0 fibal version.

**Comment by zeusent** [comment]
Damn... That means CryptoSwift can't be used as a dependency until then right? Or is there a "secret" Cocoapod way that I'm unaware of? :)

**Comment by losh11** [comment]
Can't you add branch = swift20 in the podfile? You can use it as a
dependency, but it won't compile. Anyways, your code is in all swift 2.0 if
you want to release it. So you still have to wait for Apple to officially
enable public iOS 9 update for swift 2.0 on people's devices. There is
still backwards compatibility.

**Comment by zeusent** [comment]
Well I need it to be used in a podspec file added as a dependency to a pod of mine. And the podspec file only supports version and name parameters for dependencies ([source](http://guides.cocoapods.org/syntax/podspec.html#dependency)). Anyway... I guess I'll have to do without it the meantime...

**Comment by krzyzanowskim** [comment]
it have to be added to `Podfile`
```
pod 'CryptoSwift', :git => "https://github.com/krzyzanowskim/CryptoSwift", :branch => "develop"

pod 'PodWithDependency'
```

no way to specify branch dependency in podspec, however this is question to CocoaPods team.
