### ISSUE TITLE
UTF8 AES encryption

### ISSUE THREAD

**Issue by ptmjanish** [krzyzanowskim/CryptoSwift#102]
How to AES encrypt a UTF8 using cryptoswift?. Currently i'm able to encrypt integer only.

**Comment by ptmjanish** [comment]
Found Out.

**Comment by ptmjanish** [comment]
I would be asking this rubbish again. I was out of CryptoSwift for my last project. I'm back with the same issue. I lost the last project I did as I am working on a different machine right now. Currently I'm unable to encrypt a string using AES encryption. The return value of the encrypt function is UInt8 array. How can i encrypt a string using AES256?

**Comment by krzyzanowskim** [comment]
check the issues here or README for conversion to from [Uint8] and NSData

**Comment by ptmjanish** [comment]
I think you have misunderstood my question. I don't want to encrypt any integer or integer array and convert it to any other type. I want to encrypt a string using AES encryption method. Is that possible? and How?

**Comment by krzyzanowskim** [comment]
not directly, there is not such thing like encryption of string. You have to opetate on bytes, then convert it to whatever representation tou want.

**Comment by ptmjanish** [comment]
Ok. Thanks
