### ISSUE TITLE
cannot load submodule

### ISSUE THREAD

**Issue by ptmjanish** [krzyzanowskim/CryptoSwift#103]
error: cannot find underlying module for 'Cryptoswift' at import Cryptoswift. The encryption was working well, but right now it fails. Cannot fix the issue
Using cocoa pod 0.37.2

**Comment by krzyzanowskim** [comment]
looks like you have problem with you project setup. Either you changed something or dont know. It doesnt look like CryptoSwift issue, does it?

**Comment by ptmjanish** [comment]
Thanks.. I changed something, trying to find it out.
