### ISSUE TITLE
MD5 produces incorrect results

### ISSUE THREAD

**Issue by keith** [krzyzanowskim/CryptoSwift#104]
Using `Lyft`

```
"Lyft".md5 == "6fad5084dd41242695277924e4a6f16"
```

The expected output is `6fad50840dd41242695277924e4a6f16`

The difference is the `0` before the `dd`. This also means the generated MD5 is 31 characters instead of the expected 32.

**Comment by keith** [comment]
Apparently we made a local change that broke this. Ha.

**Comment by krzyzanowskim** [comment]
✔️ don't do local changes 😆
