### ISSUE TITLE
Why the result of NSData.hexString is different from NSData.toHexString()

### ISSUE THREAD

**Issue by MonkeyDNighter** [krzyzanowskim/CryptoSwift#105]
for example:
the result of NSData.hexString is d7 a2 42 a6 46 2e 08 4d 86 b9 81 08 40 5e 38 74 b9 7b e7 c2
but the result of NSData.toHexString() is D7A242A6462E084D86B98108405E3874B97BE7C2
I think hexString has not called toHexString() function.
But where is the result of hexString from?

```
extension NSData {
    public var hexString: String {
        return self.toHexString()
    }
    .....
}
```

**Comment by krzyzanowskim** [comment]
I can;t reproduce on my machine, can you please prepare project where this issue is visible, to further investigation?

**Comment by crc1559** [comment]
I have been having the same problems as well. For my app, whenever I upload data to a server, the next time I call <NSDATA>.hexString it returns a lowercase string with spaces. 

Stranger still, sometimes it will return a hexString comprised of octets.

I have added the lines
s = s.uppercaseString.stringByReplacingOccurrencesOfString(" ", withString: "")
to the func toHexString() but it only works if I haven't uploaded data to my server.

I had to end up using the above line after my calls to hexString to create an uppercase string with no spaces

**Comment by krzyzanowskim** [comment]
Can you please create project where this issue is reproducible? I have no idea what is going on with this one.

**Comment by krzyzanowskim** [comment]
hm... [looks](https://twitter.com/tricertops/status/632554503716360192) [like](https://github.com/nst/iOS-Runtime-Headers/blob/master/Frameworks/CoreFoundation.framework/NSData.h#L155) it interfere with internal private implementation of "hexString" of NSData

**Comment by krzyzanowskim** [comment]
as a resolution to the issue I removed hexString property and make toHexString() public function.
