### ISSUE TITLE
Umbrella header for module 'CryptoSwift' does not include header 'CryptoSwift.h'

### ISSUE THREAD

**Issue by winzig** [krzyzanowskim/CryptoSwift#106]
Since updating from 0.11 to 0.12, I'm seeing this warning in Xcode 6.4 on OS X El Capitan's latest beta:

`Umbrella header for module 'CryptoSwift' does not include header 'CryptoSwift.h'`

**Comment by krzyzanowskim** [comment]
any idea how to resolve this warning ?

**Comment by winzig** [comment]
I just realized, for whatever reason, I am no longer seeing this warning. Not sure what caused it, but I will close this now. :-)
