### ISSUE TITLE
building w/Xcode 7b4, swift 2.0

### ISSUE THREAD

**Issue by gaming-hacker** [krzyzanowskim/CryptoSwift#108]
CryptoSwift-Universal builds framework but when building CryptoSwift, i get the following error and no Framework

CryptoSwiftTests
(null): Directory not found for option '-F/Applications/Hacks/Xcode-7.0.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.0.sdk/Developer/Library/Frameworks'

**Comment by krzyzanowskim** [comment]
@jagreenwood can you help with this ?

**Comment by gaming-hacker** [comment]
there is no such directory structure Developer/Library/Frameworks under /iPhoneOS9.0.sdk  it has the usual Library/ System/ usr/

**Comment by krzyzanowskim** [comment]
Thanks @gaming-hacker Something to be fixed? can you please look at the script and recent issues and update it a little? I'm not really interested in maintaining it by my own, so if it can be fixed, please PR, if not I consider remove the feature from the project.

**Comment by gaming-hacker** [comment]
i'll have a look.

**Comment by gaming-hacker** [comment]
it's interesting, when i build a release version, the framework has only has arm and i386.  when i build the debug version, all the modules are there, arm, arm64, i386 and x86_64

**Comment by gaming-hacker** [comment]
i've got some other things more pressing but will return to this when i can.
