### ISSUE TITLE
PKCS padding not working version: 0.0.12

### ISSUE THREAD

**Issue by danzaph** [krzyzanowskim/CryptoSwift#109]
I noticed that PKCS padding is not being added for this call:
let csEncrypted = AES(key: key, iv: iv, blockMode: .CBC)?.encrypt(message, padding: PKCS7()) 
version: 0.0.12
Installed via CocoaPods

**Comment by krzyzanowskim** [comment]
can you provide some tests with results?

**Comment by danzaph** [comment]
Oops, it was my error! Stil thinking of arrays as "C" arrays that don't have a length so I was not checking the return length.
