### ISSUE TITLE
Unable to get same AES value than my backend 

### ISSUE THREAD

**Issue by ed-mejia** [krzyzanowskim/CryptoSwift#110]
Hi, My backend is using this code/website to handle AES
http://aesencryption.net/

No matter what, I'm unable to match the values returned by the website with the ones generate by my App.

Example: 

WEBSITE:
text to encrypt: password
key: 1234567890123456
128 Bit AES
Result of encryption in base64: 2SwpEtK78y0jgLX1zgy+oQ==

APP:
text to encrypt: password
key: 1234567890123456
128 Bit AES ?
Result of encryption in base64: mcM3yWWT+8sre6MjlFUpww==

This is my code:
let key = "1234567890123456".utf8Array
            let iv = Cipher.randomIV(AES.blockSize)
            let encrypted = AES(key: key, iv: iv, blockMode: .ECB)?.encrypt("password".utf8Array, padding: PKCS7())

let encryptedBase64 = NSData.withBytes(encrypted!).base64EncodedStringWithOptions(NSDataBase64EncodingOptions.allZeros)

What I can see from the PHP code exposed in the website at the bottom is that they create a Cipher like this:

Cipher cipher = Cipher.getInstance("AES/ECB/PKCS5Padding");

The only value that differs is the padding from PKCS5 to PKCS7 used by CryptoSwift, I tried to change that value but seems that all code in PKCS5.swift is commented for some reason.

Any tips on this?

**Comment by krzyzanowskim** [comment]
I can't say how this website work in PHP. Please be so kind and attach project I can just run to verify the issue (attached code custom function utf8Array() I can't tell how work)

You can check this conversation I had about PHP https://github.com/krzyzanowskim/CryptoSwift/issues/20 there is something with PHP.

Side note: there is no difference between PKCS5 and PKCS7 Padding in this case.

**Comment by ed-mejia** [comment]
Thanks @krzyzanowskim I checked #20 and I was able to get the same result from PHP, Swift encrypted values, thank you!
