### ISSUE TITLE
Segmentation fault 11 when updating to 0.0.12

### ISSUE THREAD

**Issue by kayvink** [krzyzanowskim/CryptoSwift#111]
After I updating to version 0.0.12 I keep getting a Swift Compile error:

`Command faied tue to signal: Segmentation fault: 11`

`CryptoSwift` gives the following warning: Swift Compiler Warning: Umbrella header for module `CryptoSwift` does not include header `CryptoSwift.h`

**Comment by krzyzanowskim** [comment]
https://github.com/krzyzanowskim/CryptoSwift/issues/106

**Comment by kayvink** [comment]
I see, I'm on Yosemite. Didn't manage to resolve the issue. Downgraded back to 0.0.10

**Comment by krzyzanowskim** [comment]
Anyway It's just a warning that disappear magically and appear ;)
If this is cocoapods thing, try recreate Pods from the ground. Try add project manually.

**Comment by kayvink** [comment]
Haha, delete derived data 🙌🏻.

No, but I tried clean/clean build folder/restart/update cocoa pods. No luck.

**Comment by krzyzanowskim** [comment]
try with new project and send me that project, I can look at the project file.

**Comment by krzyzanowskim** [comment]
@kayvink  any update for that ?

**Comment by kayvink** [comment]
Yes, tried it on an empty project but it compiles just fine. Then also tried to import an Obj-c pod and it still works without throwing any errors.
