### ISSUE TITLE
How to make this work! Just import a framework

### ISSUE THREAD

**Issue by ed-mejia** [krzyzanowskim/CryptoSwift#113]
Hi,

I would like to use CryptoSwift as a simple framework in my project

*) I Don't want to use the installation method described in the read me file because I don't want to have a submodule within my project neither use cocoa pods (not everyone love it) 
*) I would like to be able to just simple build the framework and drag and drop it into my project and start using it, just like any other framework in the world (Fabric, Crashlytics, Ads services, etc)

I Just tried, build the framework and included it into my Embedded Binary project settings, and was able to compile, run ok on the simulator... but once you quit simulator from XCode execution and try to run the app from the simulator alone it just crash over and over again. 

This may be just a simple configuration issue but I'm unable to figure it out.

If any one have an idea or hint would be great.

Thanks.

**Comment by krzyzanowskim** [comment]
Well... this is quite general question "how build universal framework binary" and it's beyond support I can give to you here, though, I can forward you to Apple Developers Forum.

I'm sure you read README and found information about "CryptoSwift-Universal" which is (I think) what you looking for. It's just a helper but gives you idea what is the flow of building binary frameworks.

> Alternatively, you can build the Universal Framework and link it in your Xcode project. Aggregate target CryptoSwift-Universal runs a script to build a universal framework. The script currently copies the framework to the Framework directory. (The path to CryptoSwift directory cannot contain any space)

![screen shot 2015-08-22 at 10 59 31](https://cloud.githubusercontent.com/assets/758033/9423256/f572d530-48bc-11e5-8397-eddbaf367e8c.png)

**Comment by ed-mejia** [comment]
Hey! @krzyzanowskim Thanks for you quick response, and thanks for pointing me to that, I was able to do what I wanted in that way.
