### ISSUE TITLE
Swift 1.2 architecture problem

### ISSUE THREAD

**Issue by Persilos** [krzyzanowskim/CryptoSwift#117]
Hi, i just update my Xcode to 6.4 and swift to 1.2.
My app worked but now i cant compile, i have these errors:
<img width="1395" alt="capture d ecran 2015-08-27 a 13 52 48" src="https://cloud.githubusercontent.com/assets/8830732/9519840/a09bc544-4cc2-11e5-8c81-39575fa77365.png">
Do you have any solutions for this ? 

Regards

**Comment by krzyzanowskim** [comment]
it some problem with your project setup, hard to tell. Depends how you integrate you need to follow installation instruction from README.md

**Comment by Persilos** [comment]
i installed CryptoSwift with CocoaPods.
After first compilation fail, i update CryptoSwift but bug persist.

This is my architectures setup:
<img width="902" alt="capture d ecran 2015-08-27 a 14 11 36" src="https://cloud.githubusercontent.com/assets/8830732/9520190/3e61afc6-4cc5-11e5-8dc5-811d9ec87160.png">

**Comment by Persilos** [comment]
I fixed it. I just delete the derived data folders.. Thanks :)

**Comment by krzyzanowskim** [comment]
epic! :+1:

**Comment by DaveWoodCom** [comment]
@Persilos Check out my app Watchdog for Xcode, this is why it exists, to save everyone time by dealing with DerivedData for you. Link: https://itunes.apple.com/us/app/watchdog-for-xcode/id734258109?mt=12&uo=4&at=11lMGu  Promo Code: http://tokn.co/09mj9ftt

**Comment by krzyzanowskim** [comment]
yea, I can recomend
