### ISSUE TITLE
Remove Foundation dependency #PurePureSwift

### ISSUE THREAD

**Issue by robmaceachern** [krzyzanowskim/CryptoSwift#118]
Would you consider changes to drop the Foundation dependency? Dropping it doesn't get us much right now but when Apple releases the Linux port of the Swift compiler and standard library it would be nice to be able to use this library on server-side apps or in any other environment that doesn't have access to Foundation. :smile:

**Comment by krzyzanowskim** [comment]
Linux compiler comes out?

**Comment by robmaceachern** [comment]
Apple has said that they'll be releasing a Linux port of the Swift compiler and standard library before the end of the year. AFAIK, they won't be supplying a port of Foundation. I've edited the issue description to be more clear.

**Comment by krzyzanowskim** [comment]
Actually there is not much dependency on Foundation (from what I recall). Some NSData left, however I think [RawData](https://github.com/krzyzanowskim/RawData) can be used in that place. Can't really avoid dependency on everything of course. Darwin module (C stdlib kind of) is necessary at the lowest level.

**Comment by robmaceachern** [comment]
Are there many Darwin calls being made right now?

Foundation includes a pretty big extension to String, so there might be a few more non-obvious dependencies in the code but hopefully there isn't.

**Comment by krzyzanowskim** [comment]
This is done on develop branch already. Foundation dependency is optional and separated.
