### ISSUE TITLE
Getting same encrypted value for different data AES

### ISSUE THREAD

**Issue by ptmjanish** [krzyzanowskim/CryptoSwift#122]
Hi Marcin,
     I wrote a function with string as a parameter to encode it into byte array and encrypt using AES and return the encrypted data. When I call the function with different values, I get the same value after encryption. There is no problem in the code. It's encrypting perfect, but returns the same data for different values. 

I checked the received parameters in the function.
Here is my result in the console

Received parameter: Any Subject
Received parameter: New Message
Encrypted subject: [29, 173, 60, 246, 203, 15, 80, 151, 193, 239, 99, 231, 48, 115, 40, 88]
Encrypted message: [29, 173, 60, 246, 203, 15, 80, 151, 193, 239, 99, 231, 48, 115, 40, 88]

**Comment by krzyzanowskim** [comment]
what exactly you trying to archive? show the essential code here. All you need is probably convert [UInt8] to NSData and do whatever you need with that.

**Comment by ptmjanish** [comment]
I'm trying to encrypt the subject and content of a mail.
I'll Show you my code, and I'm getting the the result as above

 encryptedsubject = AESencrypt("Any Subject")
 encryptedmessage = AESencrypt("New Message")

func base64ToByteArray(base64String: String) -> [UInt8]? {
        if let nsdata = NSData(base64EncodedString: base64String, options: nil) {
            var bytes = [UInt8](count: nsdata.length, repeatedValue: 0)
            nsdata.getBytes(&bytes, length: nsdata.length)
            return bytes
        }
        return nil // Invalid input
    }
    
    func AESencrypt(anything: String) -> [UInt8]
    {
        
        println("Received parameter: \(anything)")
        let utf8str = subjectmail.dataUsingEncoding(NSUTF8StringEncoding)
        let str64 = utf8str?.base64EncodedStringWithOptions(NSDataBase64EncodingOptions.allZeros)
        
        var strbytes: [UInt8] = base64ToByteArray(str64!)!
       var encryptedstr = AES(key: key, iv: iv, blockMode: CipherBlockMode.CBC)!.encrypt(strbytes, padding: PKCS7())!
        
        return encryptedstr
    }

**Comment by krzyzanowskim** [comment]
this is what you looking for:

```swift
        let key:[UInt8] = [0x2b,0x7e,0x15,0x16,0x28,0xae,0xd2,0xa6,0xab,0xf7,0x15,0x88,0x09,0xcf,0x4f,0x3c];
        let iv:[UInt8] = [0x00,0x01,0x02,0x03,0x04,0x05,0x06,0x07,0x08,0x09,0x0A,0x0B,0x0C,0x0D,0x0E,0x0F]
        
        let bytes1 = "Any Subject".dataUsingEncoding(NSUTF8StringEncoding)?.arrayOfBytes()
        let bytes2 = "New Message".dataUsingEncoding(NSUTF8StringEncoding)?.arrayOfBytes()
        
        do {
            let encrypted1 = try AES(key: key, iv: iv, blockMode: CipherBlockMode.CBC)!.encrypt(bytes1!, padding: PKCS7())
            let encrypted2 = try AES(key: key, iv: iv, blockMode: CipherBlockMode.CBC)!.encrypt(bytes2!, padding: PKCS7())
            
            print(encrypted1)
            print(encrypted2)
        } catch {
            print("fail")
        }
```

**Comment by ptmjanish** [comment]
Currently, I am not upgraded to swift 2.0. So cannot use do try catch. But the thing is working. I'm getting the expected results. Thank you.
