### ISSUE TITLE
Example of AES test vector

### ISSUE THREAD

**Issue by youdy3000** [krzyzanowskim/CryptoSwift#124]
Hi all,

I am very thankful for this great library.  Thanks @krzyzanowskim.  

For people starting with CryptoSwift, please can someone suggest the lines of code to initlialize the following values & get the encrypted data?

Encryption key: 2b7e151628aed2a6abf7158809cf4f3c
Initialization vector: 000102030405060708090A0B0C0D0E0F
Test vector: 6bc1bee22e409f96e93d7e117393172a
Cipher text: 7649abac8119b246cee98e9b12e9197d

I wanted to use AES Test Vectors to make sure code is working correctly.  I have used this site before:
http://www.inconteam.com/software-development/41-encryption/55-aes-test-vectors#aes-cbc-128

What confused me is the Readme.Md; the encrypted / decrypted values are expecting the key and IV as a String format and the message in NSData format.  But then the Key is set to a UInt8 byte array?

// 1. set key and random IV
let key = [0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00] as [UInt8]
let iv = Cipher.randomIV(AES.blockSize)

// 2. encrypt
let encrypted = AES(key: key, iv: iv, blockMode: .CBC)?.encrypt(message, padding: PKCS7())

// 3. decrypt with the same key and IV
let decrypted = AES(key: key, iv: iv, blockMode: .CBC)?.decrypt(encryptedData, padding: PKCS7())

**Comment by krzyzanowskim** [comment]
2b7e151628aed2a6abf7158809cf4f3c is hex representation you can use to build array of [UInt8] simply by declaring [0x2b, 0x7e, 0x15,.... etc]

IV and Key are both [UInt8] parameters https://github.com/krzyzanowskim/CryptoSwift/blob/master/CryptoSwift/Cipher.swift#L36 

if there is mistake in README, feel free to fix it with PR, would love to merge if it can be explained in better way.

**Comment by youdy3000** [comment]
Hi @krzyzanowskim 

Sorry for the basic question about initialize my key, IV and plaintext correctly.  I am beating my head against a brick wall.  Am I missing a convenience initialize function?  Here is what I tried. 

ATTEMPT 1:
let key: [UInt8] = [0x2B,0x7E,0x15,0x16,0x28,0xAE,0xD2,0xA6,0xAB,0xF7,0x15,0x88,0x09,0xCF,0x4F,0x3C] as [UInt8]
        let iv: [UInt8] = [0x00,0x01,0x02,0x03,0x04,0x05,0x06,0x07,0x08,0x09,0x0A,0x0B,0x0C,0x0D,0x0E,0x0F] as [UInt8]
        let plaintextInt = [0x6B,0xC1,0xBE,0xE2,0x2E,0x40,0x9F,0x96,0xE9,0x3D,0x7E,0x11,0x73,0x93,0x17,0x2A] as [UInt8]
        do {
            let result = try Cipher.AES(key: bytesKey, iv: bytesIV, blockMode: .CBC).encrypt(bytesPlaintext)
            print("THE CIPHERTEXT should be 7649abac8119b246cee98e9b12e9197d")
        } catch {
            print(error)
        }

I don't get the ciphertext that I expect (which is here: http://www.inconteam.com/software-development/41-encryption/55-aes-test-vectors#aes-cbc-128)

ATTEMPT 2:

        let stringKey = "2b7e151628aed2a6abf7158809cf4f3c"
        let nsDataKey: NSData = stringKey.dataUsingEncoding(NSUTF8StringEncoding)!
        let bytesKey:[UInt8] = nsDataKey.arrayOfBytes()
        
        let stringIV = "000102030405060708090A0B0C0D0E0F"
        let nsDataIV: NSData = stringIV.dataUsingEncoding(NSUTF8StringEncoding)!
        let bytesIV:[UInt8] = nsDataIV.arrayOfBytes()

        let stringPlaintext = "6bc1bee22e409f96e93d7e117393172a"
        let nsDataPlaintext: NSData = stringPlaintext.dataUsingEncoding(NSUTF8StringEncoding)!
        let bytesPlaintext:[UInt8] = nsDataPlaintext.arrayOfBytes()

When I call then Cipher.AES it says my IV is too large for the block size. It is.  The IV converted into 32 byte array.

**Comment by youdy3000** [comment]
An answer is worth a coffee in London :o)

**Comment by krzyzanowskim** [comment]
sounds like a challenge to me ;)

**Comment by krzyzanowskim** [comment]
`stringKey` is string, but this is hex representation of bytes 0x2b, 0x7e, 0xe1 etc... you can't just replace string "2b" and expect byte with value 43 (which is 0x2b). this is why ` let nsDataKey: NSData = stringKey.dataUsingEncoding(NSUTF8StringEncoding)!` is invalid approach. What you get two bytes  0x32, 0x63.

that's it.

**Comment by youdy3000** [comment]
How would you go from a string of hex characters and get them into a uInt byte array?

Some years ago I followed this tutorial on PHP's MCrypt. http://www.chilkatsoft.com/p/php_aes.asp  This type of example helped me greatly.

**Comment by youdy3000** [comment]
ATTEMPT 3 failed..(I made the same mistake as ATTEMPT 2).

        var key = [UInt8]()
        let stringKey = "2b7e151628aed2a6abf7158809cf4f3c"
        key += stringKey.utf8
        
        var iv = [UInt8]()
        let stringIV = "000102030405060708090A0B0C0D0E0F"
        iv += stringIV.utf8
        
        var plaintext = [UInt8]()
        let stringPlaintext = "6bc1bee22e409f96e93d7e117393172a"
        plaintext += stringPlaintext.utf8

let result = try Cipher.AES(key: key, iv: iv, blockMode: .CBC).encrypt(plaintext)

**Comment by krzyzanowskim** [comment]
in that case you need function that will parse string with hex and produce bytes values. There is no such function in CryptoSwift. You can make one if you want.

**Comment by youdy3000** [comment]
Ah ok.  Let me investigate whether I can find something or write something..
I checked my old PHP AES code.  Looks like I was using the PHP Pack function to achieve what I wanted..  http://php.net/manual/en/function.pack.php
