### ISSUE TITLE
Confused on how to install it

### ISSUE THREAD

**Issue by CanOpener** [krzyzanowskim/CryptoSwift#127]
As the README said i cloned the project into my top level project directory (The one with the projectName.xcodeproj file and the projectName and projectNameTests folders)

I then opened my Xcode project and dragged CryptoSwift.xcodeproj into my project

I then clicked on my project and went to build phases and target dependencies but i can't add CryptoSwift.framework to it.

![screen shot 2015-09-19 at 14 36 31](https://cloud.githubusercontent.com/assets/9440166/9976435/09f1ad44-5edc-11e5-8cea-f67d0ba88f3b.png)

Could someone tell me what i'm doing wrong? i've heard so many good things about this CryptoSwift and can't wait to try it!

**Comment by krzyzanowskim** [comment]
Not sure why you can't select CryptoSwift from the screen you attached. Anyway, please check this blog post: http://blog.krzyzanowskim.com/2015/01/28/how-to-install-cryptoswift/ I hope that helps.

**Comment by youdy3000** [comment]
Hi @CanOpener, I did it the Git way.  Regretting it now.  It worked but I tried to revert back to clean.  This was a complete pain.

Like with my other 3rd party libraries, next time I will install CryptoSwift using it as a Podfile.  If you want to know how read this tutorial http://www.raywenderlich.com/64546/introduction-to-cocoapods-2

**Comment by krzyzanowskim** [comment]
you can try Carthage, or go with precompiled framework. Manual integration is manual and most primitive, and it always require more work to keep it update.

**Comment by CanOpener** [comment]
Thanks i got it over CocoaPods :)
