### ISSUE TITLE
I can't get CryptoSwift v0.0.14 from master with pod ,last version pod only get CryptoSwift v0.0.6

### ISSUE THREAD

**Issue by Jsonmess** [krzyzanowskim/CryptoSwift#130]

**Comment by antvs** [comment]
Have you tried to update your CocoaPods repo?
Execute this command:
`pod repo update`

**Comment by krzyzanowskim** [comment]
Not sure if I can help with that, check your cocoapods installation, it looks like there is something wrong with it, or ask Cococapods fellows about that. It looks good here: https://cocoapods.org/?q=cryptoswif
