### ISSUE TITLE
CRC32 calculation

### ISSUE THREAD

**Issue by bolom** [krzyzanowskim/CryptoSwift#131]
Hi Guys

I am starting with CrypoSwfit. I am trying to convert this java code

          if(mcrc==0) {
                        Checksum checksum = new CRC32();
                        checksum.update(pDataResult, 0, iDest);
                        long checksumValue = checksum.getValue();
                        mcrc=1;
                        liCrc32=(int)checksumValue;
                    }

                    if (this.mbTxCrc16) {
                        bData = (byte)(lcCrc16 >>> bContCrc * 8 & '\u00ff');
                    }
                    else {
                        bData = (byte)(liCrc32 >>> bContCrc * 8 & 0xFF);
                    }
                    ++bContCrc;

I have did that for the moment

                  if(mcrc==0)
                {
         
                   let data  = NSData.withBytes([0x01,0x02,0x03])
                   let crc = data.crc32()
                   let checksumValue  =  crc?.checksum().value
                    mcrc=1
                    liCrc32 = Int(checksumValue)
                }
                if let a = mbRxCrc16 as? Bool {
                    if a == true
                    {
                        bData = UInt8(Int16(lcCrc16) >> Int16(8 * bContCrc) & 0x00FF)
                    }
                    else
                    {
                        bData = UInt8(Int32(liCrc32) >> Int32(8 * bContCrc) & 0xFF)
                        
                    }
                } else {
                    bData = UInt8(Int32(liCrc32) >> Int32(8 * bContCrc) & 0xFF)
                }
                
all help will be appriciate

bolo

**Comment by krzyzanowskim** [comment]
great, is there any issue with CryptoSwift ? I found you asked this on [StackOverflow](http://stackoverflow.com/questions/32795261/crc32-calculation-with-the-lib-cryptoswift) If there is no issue with CryptoSwift itself, let's move there.

**Comment by bolom** [comment]
I don't think it's an issue but more a question. I am not sure where i should post this question

**Comment by krzyzanowskim** [comment]
Sure. StackOverflow is good place for that.

**Comment by bolom** [comment]
@krzyzanowskim ok
