### ISSUE TITLE
dyld: Library not loaded

### ISSUE THREAD

**Issue by mars-rover** [krzyzanowskim/CryptoSwift#132]
Hi:
    I encounter a problem when I add CryptoSwift.framework to my project, The error is:

dyld: Library not loaded: @rpath/CryptoSwift.framework/CryptoSwift
  Referenced from: /private/var/mobile/Containers/Bundle/Application/B20B49DF-AACB-4356-A3D9-399BAE676672/AWiFi.app/AWiFi
  Reason: image not found
Thanks a lot!!

**Comment by mars-rover** [comment]
By the way, I used Xcode7.0

**Comment by krzyzanowskim** [comment]
you need embed framework. this is project setting.

**Comment by mars-rover** [comment]
Do you mean that There is no way to compile CryptoSwift to a framework?

**Comment by krzyzanowskim** [comment]
it is, but you have to embed framework, every framework. this error suggest you did not.

**Comment by mars-rover** [comment]
I am not very understand about this "drag the CryptoSwift.xcodeproj file into your Xcode project, and add CryptoSwift.framework as a dependency to your target"

**Comment by krzyzanowskim** [comment]
sure, which part is not clear?

you may want to check in google for details. this looks helpful: http://www.rockhoppertech.com/blog/swift-framework-creation/#building

**Comment by mars-rover** [comment]
I have tried the way, but failed again...I just want the AES part, But I was jammed in CryptoSwift. framework, Do you have any good way? Thanks very much?

**Comment by krzyzanowskim** [comment]
I think all you missed this step:
> Now select your App and choose the General tab for the app target. Drag CryptoSwift.framework to "Embedded Binaries"

Not sure if I get the AES part question.

**Comment by mars-rover** [comment]
![11](https://cloud.githubusercontent.com/assets/12674288/10130604/85eba07c-65fc-11e5-8c89-ed60873e3e8a.png)

**Comment by krzyzanowskim** [comment]
the code if valid for current version 0.0.15

Don't know what to say at this point. You must have some mess with the setup. Can't tell what went wrong to be honest.

If you have problem with manual setup of frameworks, try Cocoapods or Carthage it may make you life easier.

**Comment by clozr** [comment]
If you are embedding the framework then don't add to it Link Binary With Libraries section. If you have done it remove it.
