### ISSUE TITLE
[develop] No such module 'Darwin.libc'

### ISSUE THREAD

**Issue by Sali0m** [krzyzanowskim/CryptoSwift#134]
i just did a pod update from the develop branch and i can't compile anymore, it tells me there is a missing library: Darwin.libc which was used in the commit : https://github.com/krzyzanowskim/CryptoSwift/commit/5efd01ecbef6949be655751a86efb4149e084825

I tryed to find the lib, but couldn't locate it (maybe my search criterias were not the good ones xD)

**Comment by krzyzanowskim** [comment]
Interesting... try change it to `import Darwin` and let me know. Darwin is "system" module.

**Comment by Sali0m** [comment]
it works when i do it like you said :)

**Comment by krzyzanowskim** [comment]
Do you have Command Line Tools installed on you machine? wonder if that is related.

**Comment by Sali0m** [comment]
Yep, it's been installed with xcode.

**Comment by krzyzanowskim** [comment]
I'll change it to "Import Darwin". Don't know why it's not always working, what is the indicator to have it working.

**Comment by Sali0m** [comment]
Ok thanks :smiley: 

till then i just change it manually when we do a pod update :wink:
