### ISSUE TITLE
tvOS

### ISSUE THREAD

**Issue by DaveWoodCom** [krzyzanowskim/CryptoSwift#136]
Hey Marcin,

I've created a tvOS compatible version of the framework, based on the current /develop branch. I'd like to send you a pull request, but I don't think this should go into /develop yet as it requires Xcode 7.1 Beta 2. I don't think I can suggest a new branch in the PR though. If you create a branch from /develop for me, I'll send the PR for that branch.

You can check the code here: https://github.com/DaveWoodCom/CryptoSwift/tree/feature/tvOS for now.

**Comment by krzyzanowskim** [comment]
awesome. What is the nature of these changes? can you elaborate a bit? is this something 7.1 beta2 specific?

**Comment by DaveWoodCom** [comment]
It creates a new target for tvOS, so CryptoSwift can be used with Apple TV apps. To make this work, I've changed the project settings from using a default PRODUCT_MODULE_NAME to a hard coded one of "CryptoSwift". This is so that both the iOS and the tvOS frameworks can access things via the CryptoSwift namespace i.e. `CryptoSwift.Poly1305.authenticate()`.

I've also renamed the iOS target to "CryptoSwift (iOS)" to differentiate them when they're listed in selection dialogs etc.

<img width="477" alt="iOS and tvOS frameworks now available" src="https://cloud.githubusercontent.com/assets/1012467/10270021/cabd9960-6ab3-11e5-9459-1c31d9679d93.png">

Note, there's a warning when building the projects "warning: no umbrella header found for target '...', module map will not be generated". It has no effect and may be just a bug in the beta Xcode (or a new requirement?).

**Comment by krzyzanowskim** [comment]
ok, I get it. The same apply to OS X target (there is not merger PR for that btw.) and watchOS target (or not?). What are the other options to handle it nicely? this kind of changes need to be checked for Carthage and CocoaPods.

**Comment by DaveWoodCom** [comment]
Yes, could use OS X and watchOS targets as well (there's an old PR in the list for an OS X target, but probably better to just do it from scratch now). They could be added to the /develop branch since they'll work with the current version of Xcode. I can probably make those and submit a PR for them this week (time permitting).

Carthage should be good with my current branch, since I made the scheme shared. CocoaPods will need an updated pod spec, but that can be done closer to the official tvOS release.

**Comment by krzyzanowskim** [comment]
how this is handled by other frameworks, like Alamofire etc? multiple targets is PITA to be honest ;)

**Comment by DaveWoodCom** [comment]
Yes, this is how it's done. 

<img width="499" alt="screen shot 2015-10-07 at 12 00 57 pm" src="https://cloud.githubusercontent.com/assets/1012467/10343300/31ca83d2-6ceb-11e5-8b31-d97d11808998.png">

**Comment by krzyzanowskim** [comment]
ok, let's start with this on develop branch, willing to make Pull Request ?

**Comment by DaveWoodCom** [comment]
You're sure you want it on the /develop branch? That will make it so you need Xcode 7.1 to use /develop for anything, even non-tvOS apps?

**Comment by krzyzanowskim** [comment]
develop is for Xcode 7.0 today, can you make it for Xcode 7.0.1 ?

**Comment by DaveWoodCom** [comment]
tvOS requires Xcode 7.1 Beta.

**Comment by krzyzanowskim** [comment]
damn. ok. if you want, can you make it for ios/osx/watchos? then separated for tvos, I'll just merge it later.

**Comment by krzyzanowskim** [comment]
@DaveWoodCom can you prepare this change (without tvOS) ASAP? or I can do this.

**Comment by DaveWoodCom** [comment]
I can get it done tomorrow.

**Comment by krzyzanowskim** [comment]
I started this work on branch

**Comment by DaveWoodCom** [comment]
Ha, I just did it as well. Was just testing and about to push it up for a pull request.

**Comment by krzyzanowskim** [comment]
uhm, sorry, watchOS is still missing though, can you check and finish what's on develop now ?

**Comment by DaveWoodCom** [comment]
sure.

**Comment by DaveWoodCom** [comment]
PR sent #140

**Comment by DaveWoodCom** [comment]
FYI, here's an updated branch with all of the new targets and tvOS (needs Xcode 7.1 of course): https://github.com/DaveWoodCom/CryptoSwift/tree/feature/xcode_7.1

**Comment by krzyzanowskim** [comment]
@DaveWoodCom now, when 0.1.x is released we can add tvOS target on develop ;-)

**Comment by zeusent** [comment]
Sorry for re-opening this, but I'm trying to install **0.1.1** via CocoaPods and I get the following error:

>The platform of the target \`MyTarget\` (tvOS 9.0) is not compatible with \`CryptoSwift (0.1.1)\`, which does not support \`tvos\`

Any idea if this will be fixed soon? Or maybe I'm doing something wrong?

**Comment by krzyzanowskim** [comment]
tvOS is not available via CocoaPods yet, unless you use this in your Podfile

```
pod 'CryptoSwift', :git => "https://github.com/krzyzanowskim/CryptoSwift", :branch => "master"
```

**Comment by DaveWoodCom** [comment]
Now that 7.1 is out, I'll submit a PR for the tvOS branch. I'll be when I get back to my machine, later today.

**Comment by zeusent** [comment]
Got it! Thanks!

**Comment by krzyzanowskim** [comment]
@DaveWoodCom I've done it yesterday, pls verify

**Comment by thaak-teleboy** [comment]
@krzyzanowskim: I am trying to use CryptoSwift in my framework for tvOS and have a pod dependency on CryptoSwift. Unfortunately I am receiving the following error message.

`The platform of the target 'Pods' (tvOS 9.0) is not compatible with 'CryptoSwift (0.1.1)', which does not support 'tvos'.`

I think it refers to the same issue reported by zeusent before. I can not use it with cocoapods either.
Only by the workaround:

`pod 'CryptoSwift', :git => "https://github.com/krzyzanowskim/CryptoSwift", :branch => "master"`

**Comment by krzyzanowskim** [comment]
pls make PR for the branch, I'm happy to merge it ASAP
