### ISSUE TITLE
dyld: Library not loaded: @rpath/libswiftAppKit.dylib

### ISSUE THREAD

**Issue by anilkumarbp** [krzyzanowskim/CryptoSwift#137]
Hi,

I am trying to use the library through cocoapods and when i build my project i get this error:

dyld: Library not loaded: @rpath/libswiftAppKit.dylib
  Referenced from: /Users/anil.kumar/Library/Developer/Xcode/DerivedData/src-eazezrghbafldbggbcexqohopyug/Build/Products/Debug/CryptoSwift.framework/Versions/A/CryptoSwift
  Reason: image not found

Xocde Version : Version 7.0 (7A220)
Swift Version : Swift 2.0

Am i missing something ?

**Comment by krzyzanowskim** [comment]
try this:

> Now select your App and choose the General tab for the app target. Drag CryptoSwift.framework to "Embedded Binaries"

**Comment by anilkumarbp** [comment]
Btw my application is a OSX Command Line application. I tried adding Embedded Binaries. Is this an issue with CocoaPods + OSX command line tool application ? 

Would upgrading to Xcode 7 beta 5 upgrade ? Appreciate your help in this. 

Thanks.

**Comment by krzyzanowskim** [comment]
I don't know how frameworks work with CLI applications to be honest. It should be statically linked. No idea. Try not use CocoaPods for CLI.

Try ask on Developer Forum about that.

**Comment by alvinvarghese** [comment]
Deleting derived data didn't help you ??

**Comment by krzyzanowskim** [comment]
@jpsim suggests here: https://twitter.com/simjp/status/651763430823608321 that you need to update rpath. I hope that helps.

**Comment by krzyzanowskim** [comment]
this is good reference: https://github.com/QueryKit/querykit-cli/blob/master/Makefile#L17-L18

**Comment by kylef** [comment]
More information:

- Executables look in their `rpath` for their framework dependencies
- Frameworks you depend on should be found in the rpath
- You can use `install_name_tool` to modify or change the path.

I've written down more detailed instructions on the README for Commander which can  be found at https://github.com/kylef/Commander/blob/master/README.md#installation

**Comment by AndrewHoos** [comment]
rpath also known as Runpath Search Paths in Xcode build settings should likely include `@loader_path/../Frameworks` for bundle targets like tests
