### ISSUE TITLE
support watch os 2.0

### ISSUE THREAD

**Issue by fscz** [krzyzanowskim/CryptoSwift#138]
In podspec add:

s.watchos.platform  = :watchos, '2.0'

**Comment by fscz** [comment]
got this from here:
https://github.com/neonichu/native-watchOS-example

**Comment by krzyzanowskim** [comment]
@fscz can you verify if this is enough? if so I'll add it asap.

**Comment by fscz** [comment]
I have tried it and was able to compile, however at runtime I get the infamous:
dyld: Library not loaded ...
Reason: Image not found 

error

**Comment by krzyzanowskim** [comment]
I don't know how to deal with "Reason: Image not found" Xcode issues to be honest. It is something with frameworks.... That'd be great if you figure it out and leave here for future reference ;) this is the most common question asked.

**Comment by fscz** [comment]
I think it is a bug in CocoaPods. The WatchOS 2.0 targets have to be setup differently in some way than "normal" targets. I have tried to fix it manually to no avail. Will talk to some guy who knows a bit more about XCode than I do.

**Comment by fscz** [comment]
Ok, after some tinkering I finally ran. pod deintegrate && pod install and then it just worked.

I have added the following to your podspec.

s.watchos.platform = :watchos, '2.0'
s.watchos.deployment_target = "2.0"

**Comment by krzyzanowskim** [comment]
thanks! added b803ab06c14931c5e73a3ed72df16973b2b1d1a8
