### ISSUE TITLE
Decrypt in Ruby

### ISSUE THREAD

**Issue by Deekor** [krzyzanowskim/CryptoSwift#139]
Not sure how much experience you have with ruby (I saw one ruby repo on your profile) but I am having a hard time getting `CryptoSwift` to play nicely with `Ruby's OpenSSL AES`

My Swift code:
     
    let key = ("12345678901234567890123456789012" as NSString).dataUsingEncoding(NSUTF8StringEncoding)?.arrayOfBytes() //32 chars because im testing AES 256
    let iv = Cipher.randomIV(AES.blockSize)
    let data = NSData(bytes: iv, length: Int(iv.count))
    let ivstring = data.base64EncodedStringWithOptions(NSDataBase64EncodingOptions(rawValue: 0));
    print(ivstring)

    let message = "Hello World".dataUsingEncoding(NSUTF8StringEncoding)?.arrayOfBytes()

        do
        {

            let encrypted = try AES(key: key!, iv: iv, blockMode: .CBC)?.encrypt(message!, padding: PKCS7())
            let decrypted = try AES(key: key!, iv: iv, blockMode: .CBC)?.decrypt(encrypted!, padding: PKCS7())

            let encData = NSData(bytes: encrypted!, length: Int(encrypted!.count))
            let base64String: String = encData.base64EncodedStringWithOptions(NSDataBase64EncodingOptions(rawValue: 0));
            let result = String(base64String)
            print(result)
            
            let decData = NSData(bytes: decrypted!, length: Int(decrypted!.count))
            let result2 = NSString(data: decData, encoding: NSUTF8StringEncoding)
            print(result2!)

        }
        catch
        {
            
        }

Which outputs:
   
    7oR9lu+ROC7PW7bDqXcRxw==
    XzZj2OTTbA8zaedeoVh0KA==
    Hello World

Then over in Ruby I do:

    key = "12345678901234567890123456789012"
    iv = "7oR9lu+ROC7PW7bDqXcRxw=="

    encrypted = "XzZj2OTTbA8zaedeoVh0KA=="

    decipher = OpenSSL::Cipher::AES.new(256, :CBC)
    decipher.decrypt
    decipher.key = key
    decipher.iv = iv
    plain = decipher.update(encrypted) + decipher.final

The ruby code throws an error on the last line `plain = decipher.update(encrypted) + decipher.final` stating:

    OpenSSL::Cipher::CipherError
    =================================================
    > wrong final block length
    

I'm obviously not the most experienced person in encryption but any help you could give me would be very much appreciated!

**Comment by krzyzanowskim** [comment]
is `decipher.update(encrypted)` accept base64 string as input at all?

**Comment by Deekor** [comment]
It should. I was able to encrypt and decrypt a base64 in ruby just fine.

**Comment by krzyzanowskim** [comment]
the it looks ok to me. I'm not really familiar with Ruby OpenSSL wrapper but it doesn't looks like it decode base64 string to data. At least according to documentation. http://ruby-doc.org/stdlib-2.0.0/libdoc/openssl/rdoc/OpenSSL/Cipher.html

**Comment by Deekor** [comment]
Can you pint where in the doc makes you think that?

**Comment by Deekor** [comment]
Isnt this using base64? http://ruby-doc.org/stdlib-2.0.0/libdoc/openssl/rdoc/OpenSSL/Cipher.html#class-OpenSSL::Cipher-label-Encrypting+and+decrypting+some+data

**Comment by krzyzanowskim** [comment]
it doesn't looks like to me. It gets string as input and treat is as data. It won't decode base64 automatically IMHO. Just try to decode it first.

**Comment by Deekor** [comment]
You were right `Base64.decode64(...)` on both the `iv` and `encrypted` did the trick. Thanks for your help!
