### ISSUE TITLE
Foundation folder not included when install with CocoaPods

### ISSUE THREAD

**Issue by thehellsoul** [krzyzanowskim/CryptoSwift#143]
Well, i have to download zip file, copy-paste Foundation folder to CryptoSwift folder under Pods, add it to CryptoSwift folder in XCode and change target membership to CryptoSwift to make it work.

**Comment by krzyzanowskim** [comment]
oh crap, will update podspec asap.

**Comment by krzyzanowskim** [comment]
Fixed with hotfix release 0.1.1
