### ISSUE TITLE
Error when using carthage with version 0.1.1

### ISSUE THREAD

**Issue by ramirez** [krzyzanowskim/CryptoSwift#144]
Hi, 

I have been using CryptoSwift via Carthage for a few weeks now and it was working fine. Today I tried to upgrade to 0.1.1, but after doing a carthage update, I'm getting:

```
$ carthage update --platform iOS` 
A shell task failed with exit code 66:`
xcodebuild: error: Scheme CryptoSwift-Universal is not currently configured for the build action.
```

Any ideas why this could be happening?

Thanks!

L.

**Comment by krzyzanowskim** [comment]
this target CryptoSwift-Universal has been removed.

**Comment by ramirez** [comment]
I see. I just deleted the repo dowloaded by carthage and started over and it worked.

Thx.

L.
