### ISSUE TITLE
Help wanted: Encrypt string and get specific value?

### ISSUE THREAD

**Issue by galinyonchev** [krzyzanowskim/CryptoSwift#145]
I have chosen scrypt hashing algorithm, for a 64 bytes length, with a fixed seed, then converted to hex

Hashing "A12345678Z" leads to: 25fac84a1cc3a8f6706848d1016cfe7e9d3631691306dcacae68c11c7b54f0bf89e7a7fc51f7fcc19671775acb21c8d928c4c96bb66d915925de58b8b36ab251

seed is “HeanpyftAkWilfUd”

On server, I am using this implementation : https://github.com/ricmoo/pyscrypt

scrypt.hash(“A12345678Z", “HeanpyftAkWilfUd").encode('hex’) -> 25fac84a1cc3a8f6706848d1016cfe7e9d3631691306dcacae68c11c7b54f0bf89e7a7fc51f7fcc19671775acb21c8d928c4c96bb66d915925de58b8b36ab251

How to make it work with CryptoSwift in my app? I want to encrypt this string "A12345678Z" and get this value: 
25fac84a1cc3a8f6706848d1016cfe7e9d3631691306dcacae68c11c7b54f0bf89e7a7fc51f7fcc19671775acb21c8d928c4c96bb66d915925de58b8b36ab251

Is it possible?

**Comment by krzyzanowskim** [comment]
yes, you expect bytes in hex representation as string. just call toHexString() on array of bytes

**Comment by galinyonchev** [comment]
Can you please give me an example - a piece of code?

**Comment by krzyzanowskim** [comment]
from README:
```swift
let encryptedBytes: [UInt8] = try "my secret string".encrypt(AES(key: "secret0key000000", iv: "0123456789012345")
```

and now
```swift
let hex: String = encryptedBytes.toHexString()
```

**Comment by galinyonchev** [comment]
Thank you!
I am newbie in encryption, so I don't understand a lot of things. I tried the following piece of code:

        let encryptedBytes: [UInt8] = try! "A12345678Z".encrypt(AES(key: "HeanpyftAkWilfUd", iv: "HeanpyftAkWilfUd"))
        let hex: String = encryptedBytes.toHexString()

But it prints something different than the expected answer (25fac84a1cc3a8f6706848d1016cfe7e9d3631691306dcacae68c11c7b54f0bf89e7a7fc51f7fcc19671775acb21c8d928c4c96bb66d915925de58b8b36ab251). What values to set for key and iv in my case? I want to have the same string in my app and in my server.

**Comment by krzyzanowskim** [comment]
Wel..  it was just an example of usage. You have to figure out what do you want to archive here. I'm not familiar with this python code. What I see it is PBKDF, which is not yet available in CryptoSwift so you can't use it.
