### ISSUE TITLE
carthage failed

### ISSUE THREAD

**Issue by hibento** [krzyzanowskim/CryptoSwift#148]
Hi there,

I tried to build your latest versions (> 0.0.16) using carthage, but they both failed - version 0.0.16 works fine:

     The following build commands failed:
     CompileSwift normal x86_64 ../Carthage/Checkouts/CryptoSwift/CryptoSwiftTests/HMACTests.swift
     CompileSwift normal x86_64 ../Carthage/Checkouts/CryptoSwift/CryptoSwiftTests/Poly1305Tests.swift
     CompileSwift normal x86_64 ../Carthage/Checkouts/CryptoSwift/CryptoSwiftTests/Helpers.swift
     CompileSwift normal x86_64 ../Carthage/Checkouts/CryptoSwift/CryptoSwiftTests/HashTests.swift
     CompileSwift normal x86_64 ../Carthage/Checkouts/CryptoSwift/CryptoSwiftTests/ChaCha20Tests.swift
     CompileSwift normal x86_64 ../Carthage/Checkouts/CryptoSwift/CryptoSwiftTests/ExtensionsTest.swift
     CompileSwift normal x86_64 ../Carthage/Checkouts/CryptoSwift/CryptoSwiftTests/PaddingTests.swift
     CompileSwift normal x86_64 ../Carthage/Checkouts/CryptoSwift/CryptoSwiftTests/AESTests.swift
     CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler (9 failures)
     warning: no umbrella header found for target 'CryptoSwift watchOS', module map will not be generated
     warning: no umbrella header found for target 'CryptoSwift watchOS', module map will not be generated

     ../Carthage/Checkouts/CryptoSwift/CryptoSwiftTests/HMACTests.swift:9:18: error: module 'CryptoSwift' was not compiled for testing
     ../Carthage/Checkouts/CryptoSwift/CryptoSwiftTests/Poly1305Tests.swift:9:18: error: module 'CryptoSwift' was not compiled for testing
     ...
     A shell task failed with exit code 65:
     ** BUILD FAILED **

Any ideas how to solve this?

**Comment by krzyzanowskim** [comment]
yeap, Carthage thing. Duplicate #146 #144

**Comment by hibento** [comment]
My fault, should have take a look at the existing (and closed) issues.
