### ISSUE TITLE
use pod compile error

### ISSUE THREAD

**Issue by louiseliu** [krzyzanowskim/CryptoSwift#15]
i use pod:
eg:
pod 'CryptoSwift'

when i compile,something wrong

Pods/CryptoSwift/CryptoSwift/Authenticator.swift:31:20: Use of unresolved identifier 'CryptoSwift'

**Comment by krzyzanowskim** [comment]
show me your Cocoapods version. Is it fine with submodule setup?

**Comment by krzyzanowskim** [comment]
Cant preproduce 

```
$ pod --version
0.36.0.beta.1

$ pod install
Analyzing dependencies
Downloading dependencies
Installing CryptoSwift (0.0.4)
Generating Pods project
Integrating client project
```
[!] From now on use `test.xcworkspace`.

![screen shot 2015-01-17 at 14 13 05](https://cloud.githubusercontent.com/assets/758033/5788905/f9354762-9e52-11e4-8f57-b9cd24c2eb23.png)

Can you prepare test project?

**Comment by louiseliu** [comment]
thank you!  oh, i use pod 0.3.6.

**Comment by debo2372** [comment]
Hello, I tried installing CryptoSwift using CocoaPods. The current version is 0.36.3. I even managed to create a test project but for some reason I get an error saying "Cannot load underlying module for 'CryptoSwift'" when I type "import CryptoSwift".
