### ISSUE TITLE
Issues with CocoaPods and CryptoSwift

### ISSUE THREAD

**Issue by someoneAnyone** [krzyzanowskim/CryptoSwift#150]
I'm getting the following issue when I use CocoaPods version 0.39.9.
```
dyld: Library not loaded: @rpath/libswiftsimd.dylib
  Referenced from: /Users/xxxx/Library/Developer/Xcode/DerivedData/product-edyidqtcbchovufenighjjxguvbb/Build/Products/Debug-iphonesimulator/CryptoSwift.framework/CryptoSwift
  Reason: image not found
```
 Any ideas why? Everything works fine before I add CryptoSwift to my pod file.

```
target 'FrameworkTarget' do
    pod 'Alamofire'
    pod 'SwiftyJSON'
    pod 'CryptoSwift'
    pod 'KeychainAccess'
    pod 'DateTools'
end

```

**Comment by krzyzanowskim** [comment]
strange, delete deriven data and try with a new project. you can attach the project here so I can take a look at it, try to reproduce. Weird that libswiftsimd is referenced at all

**Comment by someoneAnyone** [comment]
I've tried cleaning and deleting derived folder. I'll work on getting my project published.

**Comment by someoneAnyone** [comment]
Could have it have anything to do with my trying to put it into my own framework?

**Comment by krzyzanowskim** [comment]
Can't tell, ask CocoaPods, maybe. I have no idea what is this about. Can't reproduce too.

**Comment by krzyzanowskim** [comment]
you should try with 0.39.0 (this is the latest version today). Please update me.

**Comment by eneko** [comment]
Hi there! I'm actually having this issue too. The error is very similar:

    (dlopen_preflight(/Users/enekoalonso/Library/Developer/CoreSimulator/Devices/C501C3F1-11D6-4126-A093-6A09BE2DA14B/data/Containers/Bundle/Application/2CF99343-ACB0-4856-AABF-130BE117443D/xxxxUITests-Runner.app/PlugIns/xxxxUITests.xctest/xxxxUITests): Library not loaded: @rpath/libswiftsimd.dylib
  Referenced from: /Users/enekoalonso/Library/Developer/Xcode/DerivedData/xxxx-dckygpxbcfxwdpalvjjdoflkwsbv/Build/Products/Debug-iphonesimulator/CryptoSwift.framework/CryptoSwift
  Reason: image not found)

The issue only happens with CryptoSwift, on this project which was targeted for iOS 9 (though I have changed the target to iOS 8 with no luck). This project is for iPad only. I am using CocoaPods 0.39.0.

**Comment by krzyzanowskim** [comment]
Can you try with Carthage? it may be Cocoapods issue. I wonder if that's the case with Xcode 7.0, there was some new revelations introduced to XCode 7.1.

**Comment by krzyzanowskim** [comment]
@eneko I juts tried setup with Cocoapods 0.39.0 and all went just file

```Podfile
use_frameworks!

pod "CryptoSwift"
```

**Comment by eneko** [comment]
Sorry for the lack of feedback here, I was traveling the last couple of days. Thank you for trying it out, I'll let you know if I find the root cause.

**Comment by someoneAnyone** [comment]
It seems to be working better now... maybe I had a bad version of Cocoapods.

**Comment by jmnavarro** [comment]
I've just had the same issue with cocoapods 0.39.0 and I had to downgrade to 0.38.2 to make it work

**Comment by DanielSumara** [comment]
When I use your framework embedded in my one, I received this error. To fix it I change "Embedded Content Contains Swift Code" to Yes in Build Settings of CryptoSwift project.

**Comment by krzyzanowskim** [comment]
It shouldn't be necessary. The same setup as for Alamofire (from the list). The `simd` import is unecessary and is removed on `develop` branch - that should resolve this issue.
