### ISSUE TITLE
CryptoSwift was compiled with optimization - stepping may behave oddly; variables may not be available.

### ISSUE THREAD

**Issue by Deekor** [krzyzanowskim/CryptoSwift#152]
I'm seeing this warning:

`CryptoSwift was compiled with optimization - stepping may behave oddly; variables may not be available.`

Not sure whats causing it or how to get it to go away. It might be causing a crash but I am not completely positive on that yet.

**Comment by krzyzanowskim** [comment]
well.... it's been compiled in optimization is rather good, not bad. In what context you're seeing such warning ?

**Comment by krzyzanowskim** [comment]
@Deekor is this debugger message or what? If your CryptoSwift is build in Release mode... it's kind of expected.
