### ISSUE TITLE
want help aes256

### ISSUE THREAD

**Issue by xing-ou** [krzyzanowskim/CryptoSwift#153]
hi,i am new in encryt, i just get a key = "376b89c67b61477399978b6396518cb5" and a iv = ef980024e4d74af9aabbeaa67c49de95  ,here is how i use crypto swift:

let base64:String = try! "123456".encrypt(AES(key: "376b89c67b61477399978b6396518cb5", iv: "ef980024e4d74af9aabbeaa67c49de95", blockMode: CipherBlockMode.CBC))
 
and i always get a error at the following assert:

 public init(key:[UInt8], iv:[UInt8], blockMode:CipherBlockMode = .CBC) throws {
        self.key = key
        self.iv = iv
        self.blockMode = blockMode
        
        if (blockMode.needIV && iv.count != AES.blockSize) {
            assert(false, "Block size and Initialization Vector must be the same length!")
            throw Error.InvalidInitializationVector
        }
    }

i just want to know how to  encrypt a str  with  key and iv using  ase256 ?

i want some help

**Comment by thehellsoul** [comment]
Because of line 34: **public static let blockSize:Int = 16 // 128 /8**
this is my temporary solution:
line 34: change to **public static var blockSize:Int = 16 // 128 /8**
line 93: add **AES.blockSize = key.count**

**Comment by krzyzanowskim** [comment]
block size for AES is constant 16 bytes and so IV have to be 16 bytes long, while key for 256 is 32 bytes long.

**Comment by xing-ou** [comment]
oh  ,seem to be a stupid question ,thank for you explain

**Comment by kalpeshjjethva** [comment]
can anyone explain what is "iv" in aes256?

**Comment by krzyzanowskim** [comment]
@kalpeshjjethva Start here
[CryptoSwift: Cryptography You Can Do, Marcin Krzyżanowski, Jun 5, 2015](https://news.realm.io/news/swift-summit-marcin-krzyzanowski-cryptoswift-cryptography/)

![screen shot 2017-07-04 at 10 09 35](https://user-images.githubusercontent.com/758033/27820964-e75d3b04-60a0-11e7-9a9d-24e3c9f2d46d.png)
