### ISSUE TITLE
Xcode7.1 and CryptoSwift0.1.1 problem

### ISSUE THREAD

**Issue by ekahoo** [krzyzanowskim/CryptoSwift#154]
Halo, 

After upgrade to Xcode 7.1, I find that frameworks of CryptoSwift0.1.1 cannot use and becomes red.
I tried delete and re-drag CryptoSwift.xcodeproj. Problem still exists.

FYR: 
![screen shot 2015-10-28 at 11 56 54 am](https://cloud.githubusercontent.com/assets/12869892/10779385/051ef288-7d6b-11e5-941b-4b13071b795d.png)

**Comment by krzyzanowskim** [comment]
Targets chaned, You probably need reinstall since target change the name and your setup is probably invalid since then. The "red" doesnt mean anything, but if you cant link to the framework, pleare double check the setup

**Comment by ekahoo** [comment]
Halo krzyzanowskim,

I think that it may due to Xcode7.1 contains new deployment target 9.1.
I delete current CryptoSwift and re-do following but problem still exists.

1. Unzip CryptoSwift-0.1.1.zip
2. Drag the CryptoSwift.xcodeproj file into Xcode project
3. Select my App project and choose the General tab for the app target. 
4. Drag CryptoSwift/Products/framework(ios) to Embedded Binaries

My class cannot use 'import CryptoSwift' as showing 'No such module 'CryptoSwift''

**Comment by krzyzanowskim** [comment]
@ekahoo  try integrate with Carthage or Cocoapods for now, and let me know if that is working.

**Comment by krzyzanowskim** [comment]
Can't confirm this issue issue, here is my setup with the current version.

![screen shot 2015-10-30 at 00 06 53](https://cloud.githubusercontent.com/assets/758033/10834511/25a26852-7e9a-11e5-8c01-6cc8f1838459.png)

**Comment by hibento** [comment]
I'm using 0.0.1 and Xcode 7.1 without any problems - but I had to clean carthage's cache as mentioned.
