### ISSUE TITLE
Hex Key issue

### ISSUE THREAD

**Issue by edge33** [krzyzanowskim/CryptoSwift#156]
Hello, I have a working infrastructure, composed by a php server and a javascript client, that encrypts stuff using Cryptojs. the issue is: I have a hex key for aes 256 working on both javascript ( encrypting ) and php ( decrypting ). according to CryptoSwift api, I need a key string that is converted to bytearray.

when i use my hex key and convert it to bytearray, i get the error "size-mismatch" for key and iv for as-256. Is there any chance I can solve this? can you help me?

**Comment by krzyzanowskim** [comment]
how do you convert hex key to bytearray? Hex parser need takes two characters and convert to single byte.
