### ISSUE TITLE
'try!' expression unexpectedly raised an error: CryptoSwift.AES.Error.BlockSizeExceeded:

### ISSUE THREAD

**Issue by Clever91** [krzyzanowskim/CryptoSwift#158]
'try!' expression unexpectedly raised an error: CryptoSwift.AES.Error.BlockSizeExceeded. I don't understand why get issue
I use like this:

private func decodeResponseData(bytes: [UInt8])->String {
        let dencryptedBytes: [UInt8]
            dencryptedBytes = try! bytes.decrypt(AES(key: self.CONNECTION_KEY, iv: self.CONNECTION_IV))
            print("Decoded Bytes: \(dencryptedBytes)")

        return Converter.bytesConvertToString(dencryptedBytes)
    }

**Comment by krzyzanowskim** [comment]
depends on input data, this error means that IV has wrong length. see this comment: https://github.com/krzyzanowskim/CryptoSwift/issues/153#issuecomment-150516192

**Comment by Clever91** [comment]
this my key and iv
    static let CONNECTION_KEY = "be8d5ba39cde4e41"
    static let CONNECTION_IV = "a5e5ff5dcd2a655c"

**Comment by Clever91** [comment]
when i create method, it don't work. it work without method

**Comment by krzyzanowskim** [comment]
? what do you mean by that

**Comment by krzyzanowskim** [comment]
I don't know, I'm not fully understand the report. Is is related to CryptoSwift module or to Swift in general? You can build sample project to reproduce the problem, I could investigate then.

**Comment by Clever91** [comment]
it is work:
let dencryptedBytes: [UInt8] = try! AES(key: UrlManager.CONNECTION_KEY, iv:UrlManager.CONNECTION_IV, blockMode: .CBC).encrypt(bytes)
but i don't know convert [UInt8] array  to string
plz, give me convert example if you can

**Comment by Clever91** [comment]
i create converter but it is not work

    static func bytesConvertToString(bytes: [UInt8])->String {
        if let str =  NSString(bytes: bytes, length: bytes.count, encoding: NSUTF8StringEncoding) as? String {
            return str
        } else {
            print("not a valid UTF-8 sequence")
        }
        return ""
    }

result: not a valid UTF-8 sequence

**Comment by krzyzanowskim** [comment]
it's because the result are bytes, not string, it just bytes. You may get hex representation of bytes, check here: https://github.com/krzyzanowskim/CryptoSwift#usage
