### ISSUE TITLE
only support iOS 8+

### ISSUE THREAD

**Issue by spritesun** [krzyzanowskim/CryptoSwift#16]
Request to support iOS 7 as well.

**Comment by krzyzanowskim** [comment]
Now I think it was bad decision. Will it ever work with 7.1 when embedded dylibs/frameworks only run on iOS 8 or later?

**Comment by krzyzanowskim** [comment]
According to discussion here https://github.com/CocoaPods/CocoaPods/issues/3193 I can't have deployment target set to version 7.1 any longer.

**Comment by dkhamsing** [comment]
Man this is a bummer

**Comment by krzyzanowskim** [comment]
You have to handle it by yourself by copying files to your project, not using framework, because framework is the limitation here.

**Comment by dkhamsing** [comment]
So your advice is, copy the files if supporting ios7?

**Comment by krzyzanowskim** [comment]
you can copy, or just add to your project, and yes this seems the only way to do so.

**Comment by dkhamsing** [comment]
thx
