### ISSUE TITLE
Build failed swift2.1 Xcode 7.1.1

### ISSUE THREAD

**Issue by lmktommy** [krzyzanowskim/CryptoSwift#160]
I failed to import CryptoSwift framework to my iOS project (Xcode 7.1.1 swift 2.1). After I checked it, if failed to build the framework when I ran command "build.sh". Please see the error as follow. Thank you for your help.

** BUILD FAILED **

The following build commands failed:
	Ld build/CryptoSwift.build/Release-iphoneos/CryptoSwift\ iOS.build/Objects-normal/armv7/CryptoSwift normal armv7
	Ld build/CryptoSwift.build/Release-iphoneos/CryptoSwift\ iOS.build/Objects-normal/arm64/CryptoSwift normal arm64
(2 failures)
Build settings from command line:
    SDKROOT = iphonesimulator9.1
    SYMROOT = /Users/tommy/.Trash/CryptoSwift-master/build

**Comment by krzyzanowskim** [comment]
hard to tell from the error you attached.

** BUILD SUCCEEDED **

**Comment by lmktommy** [comment]
What should I do can provide more info to u?

**Comment by krzyzanowskim** [comment]
full command line you run and full logs, I can't reproduce the issue now.

**Comment by lmktommy** [comment]
[log.txt](https://github.com/krzyzanowskim/CryptoSwift/files/34587/log.txt)

I ran command "./build.sh > ../log.txt"

Afterwards, I saw a framework file as picture below.
<img width="404" alt="screen shot 2015-11-14 at 6 33 03 pm" src="https://cloud.githubusercontent.com/assets/7955483/11163107/4d29f668-8afe-11e5-9e7a-4355ccd876c1.png">

Then, I create a brand new project in xcode (swift 2.1 and Xcode 7.1.1) and add the framework as picture below.
<img width="784" alt="screen shot 2015-11-14 at 6 37 27 pm" src="https://cloud.githubusercontent.com/assets/7955483/11163125/e8d360f4-8afe-11e5-8e22-18b0b3348401.png">

I cannot import library as picture below.
<img width="958" alt="screen shot 2015-11-14 at 6 39 09 pm" src="https://cloud.githubusercontent.com/assets/7955483/11163129/13fd8462-8aff-11e5-94d0-321bfaec3782.png">

I am sorry that I distrub you. Thank you for your help promptly.

**Comment by krzyzanowskim** [comment]
looks good here ![screen shot 2015-11-14 at 18 19 19](https://cloud.githubusercontent.com/assets/758033/11164835/3fb286e6-8afc-11e5-9a9e-9d3db52105d1.png)

the project: http://cl.ly/013u0n022d2t

**Comment by lmktommy** [comment]
Thank you. I had installed the program by using Cocoapods. Issue is solved.
