### ISSUE TITLE
AES CTR incorrectly requires cipher length to be multiple of block size

### ISSUE THREAD

**Issue by kostyan5** [krzyzanowskim/CryptoSwift#162]
By definition CTR mode does not require padding:  https://www.cryptopp.com/wiki/CTR_Mode.  However, cryptoswift throws BlockSizeExceeded error if the cipher is not a multiple of block size.

**Comment by krzyzanowskim** [comment]
So the thing is that padding is not required for CTR nor CFB, though padding is applied to every block mode unless specifically disabled:

```swift
func encrypt(bytes:[UInt8], padding:Padding? = PKCS7()) throws -> [UInt8] { ... }
```

when called 
```swift
encrypt(bytes)
```

then padding is applied by default, when called 
```swift
encrypt(bytes, padding: nil)
```

padding is not applied. I have no good idea how to change API in good way to enable/disable. If I disable it, it will break the forced parameter value.

**Comment by kostyan5** [comment]
The encrypt function correctly handles padding: nil.  But decrypt function does not check if padding is nil before throwing the error.

Can you simply check if the block mode is CTR and then not require padding?

**Comment by krzyzanowskim** [comment]
is indeed `encrypt(bytes, padding: nil)` handled right? from what I see it throw error.

**Comment by kostyan5** [comment]
Sorry, you're correct.  Both encrypt and decrypt throw errors.

**Comment by krzyzanowskim** [comment]
@kostyan5 pls verify the fix.

**Comment by kostyan5** [comment]
The error is no longer thrown but CTR encoded ciphers don't seem to decrypt correctly.  This could be related to padding or be a completely separate issue.

These two examples are from Stanford's Crypto Course and are supposed to decrypt to human readable text.  However, with CryptoSwift they decode to gibberish.  I implemented my own CTR and they decrypt correctly.

CTR key: 36f18357be4dbd77f050515c73fcf9f2
CTR Ciphertext 1: 
69dda8455c7dd4254bf353b773304eec0ec7702330098ce7f7520d1cbbb20fc388d1b0adb5054dbd7370849dbf0b88d393f252e764f1f5f7ad97ef79d59ce29f5f51eeca32eabedd9afa9329

CTR key: 36f18357be4dbd77f050515c73fcf9f2
CTR Ciphertext 2: 
770b80259ec33beb2561358a9f2dc617e46218c0a53cbeca695ae45faa8952aa0e311bde9d4e01726d3184c34451

**Comment by krzyzanowskim** [comment]
pls attach used code is possible

**Comment by kostyan5** [comment]
[AppDelegate.swift.pdf](https://github.com/krzyzanowskim/CryptoSwift/files/40243/AppDelegate.swift.pdf)

**Comment by krzyzanowskim** [comment]
post here link to source of this values from Stanford's Course you refering to, can't find it now.

**Comment by krzyzanowskim** [comment]
The difference is how you build the nonce value, your implementation simply increase last byte of IV (so you can encrypt at most 255 blocks if lucky), anyway the way I build nonce is half IV + counter for the other half and this in accordance with the specification

> nonce is regarded as a 64-bit binary number, and ctr is constructed by appending to this number 64 zero-bits

Please elaborate why you think that current implementation is invalid

**Comment by kostyan5** [comment]
My implementation was just a quick test.  You're right, a full implementation would have to do a 128-bit increment.  I tried doing this and it also doesn't work:

 let aes = try! AES.init(key: key3.uint8!, iv: [UInt8](cipher3.uint8![0...15]), blockMode: .CTR)
 let decrypted = try! aes.decrypt([UInt8](cipher3.uint8![16..<cipher3.uint8!.count]), padding: nil)

In this case, the nonce part is the same for your implementation and mine.  Also, since IV is part of the message, it should just be automatically extracted in the decrypt function, rather than being set in the init.

**Comment by krzyzanowskim** [comment]
Now I don't understand, pls be more specific ;-) why do you mean by "since IV is part of the message...".

**Comment by kostyan5** [comment]
IV is prepended to the cipher and sent along with it.  To get the IV for a particular message, you simple take the first 16 bytes.  http://3.bp.blogspot.com/-lxWKr3pCV2Q/UUfh1XqPgSI/AAAAAAAAB7Y/AiOjV9CFhIo/s1600/cbc2.png

**Comment by krzyzanowskim** [comment]
I'm not sure what is your source? IV is not part of message. Half of IV is used to build nonce for CTR. You can add IV to your message if you want, though it's up to you - it's not the part of encryption itself.

**Comment by kostyan5** [comment]
Ok, I'm not argue that point because I don't know enough.  How would I decrypt cipher 3 using CryptoSwift, in pdf I posted earlier, given that first 16 bytes is the IV with simple counter mode?

**Comment by krzyzanowskim** [comment]
like this

```swift
        let key:[UInt8] =        [0x36,0xf1,0x83,0x57,0xbe,0x4d,0xbd,0x77,0xf0,0x50,0x51,0x5c,0x73,0xfc,0xf9,0xf2]
        let ciphertext:[UInt8] = [0x69,0xdd,0xa8,0x45,0x5c,0x7d,0xd4,0x25,0x4b,0xf3,0x53,0xb7,0x73,0x30,0x4e,0xec,0x0e,0xc7,0x70,0x23,0x30,0x09,0x8c,0xe7,0xf7,0x52,0x0d,0x1c,0xbb,0xb2,0x0f,0xc3,0x88,0xd1,0xb0,0xad,0xb5,0x05,0x4d,0xbd,0x73,0x70,0x84,0x9d,0xbf,0x0b,0x88,0xd3,0x93,0xf2,0x52,0xe7,0x64,0xf1,0xf5,0xf7,0xad,0x97,0xef,0x79,0xd5,0x9c,0xe2,0x9f,0x5f,0x51,0xee,0xca,0x32,0xea,0xbe,0xdd,0x9a,0xfa,0x93,0x29]
        let iv = [UInt8](ciphertext[0...15])

        let aes = try! AES(key: key, iv: iv, blockMode: .CTR)
        let decrypted = try! aes.decrypt(ciphertext, padding: nil)
```

**Comment by krzyzanowskim** [comment]
I was wrong about this. I reviewed my implementation and will fix it soon.

**Comment by kostyan5** [comment]
Can you briefly describe the what was causing the problem?

**Comment by krzyzanowskim** [comment]
the way I handled given IV was wrong. fix: https://github.com/krzyzanowskim/CryptoSwift/commit/b2b36d879b169fc33b7a3ffdb115d9bb42faf833
