### ISSUE TITLE
Linking against dylib not safe for use in application extensions warning

### ISSUE THREAD

**Issue by rinatkhanov** [krzyzanowskim/CryptoSwift#164]
Seeing this warning when installing CryptoSwift to my extension target with CocoaPods:
`linking against dylib not safe for use in application extensions`

Unless I am missing something, looks like it's [pretty easy to fix](https://github.com/ankurp/Dollar.swift/issues/144).

**Comment by krzyzanowskim** [comment]
"Require Only App-Extension-Safe API" is set to "Yes" (except the watchOS target).
