### ISSUE TITLE
no umbrella header found for target 'CryptoSwift watchOS'

### ISSUE THREAD

**Issue by mattlanham** [krzyzanowskim/CryptoSwift#169]
Hey, hoping you can help me on this one, can't seem to figure out how to get around it, when I run carthage update I am getting the following error:

```
** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
warning: no umbrella header found for target 'CryptoSwift watchOS', module map will not be generated
warning: no umbrella header found for target 'CryptoSwift watchOS', module map will not be generated
A shell task failed with exit code 65:
** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
```

Thanks for your help!

**Comment by krzyzanowskim** [comment]
I'm not sure why this is an issue

**Comment by soffes** [comment]
Guessing the header wasn't added to the watch target or isn't marked as public for that twrget. Definitely works via Carthage on Mac and iOS. I can take a look later if you haven't figured it out.

**Comment by mattlanham** [comment]
Is there a way I can specify it only to build the iOS / Mac version and skip WatchOS to avoid it failing?

**Comment by krzyzanowskim** [comment]
@soffes there is no umbrella header in CryptoSwift, should I do something about it ?

**Comment by soffes** [comment]
See #170

**Comment by krzyzanowskim** [comment]
ok, I wonder why it is necessary at all. Umbrella header is for Objective-C compatibility right? what if framework is Swift only?

**Comment by mattlanham** [comment]
I still seem to be having the same issue @soffes @krzyzanowskim - is there some kind of cache I need to clear, I've tried deleting the Carthage directory and running 'carthage update' but it continues to fail on the same issue.

**Comment by mattlanham** [comment]
I had a look in the logs to see if I could find more info, here's some more output:

```
Build settings from command line:
    ONLY_ACTIVE_ARCH = NO
    SDKROOT = appletvsimulator9.0

=== BUILD TARGET SwiftyJSON tvOS OF PROJECT SwiftyJSON WITH CONFIGURATION Release ===

Check dependencies
target 'SwiftyJSON tvOS' has bitcode disabled (ENABLE_BITCODE = NO), but it is required for the 'appletvos' platform
```

**Comment by krzyzanowskim** [comment]
bitcode and appletv: https://github.com/krzyzanowskim/CryptoSwift/pull/155

**Comment by krzyzanowskim** [comment]
anyway "SwiftyJSON" is other project, isn't it ?

**Comment by mattlanham** [comment]
Strange, I do have both in my project, but in console I am seeing:

```
*** Building scheme "Alamofire OSX" in Alamofire.xcworkspace
*** Building scheme "Alamofire watchOS" in Alamofire.xcworkspace
*** Building scheme "Alamofire iOS" in Alamofire.xcworkspace
*** Building scheme "CryptoSwift OSX" in CryptoSwift.xcodeproj
*** Building scheme "CryptoSwift watchOS" in CryptoSwift.xcodeproj
*** Building scheme "CryptoSwift iOS" in CryptoSwift.xcodeproj
*** Building scheme "SwiftyJSON OSX" in SwiftyJSON.xcworkspace
*** Building scheme "SwiftyJSON tvOS" in SwiftyJSON.xcworkspace
** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
warning: no umbrella header found for target 'CryptoSwift watchOS', module map will not be generated
warning: no umbrella header found for target 'CryptoSwift watchOS', module map will not be generated
A shell task failed with exit code 65:
** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
```

And then in the log file, it was a reference to SwiftyJSON

**Comment by krzyzanowskim** [comment]
strange, try remove "SwiftyJSON" for a sec. and see if all go well. If so, it may be good idea to report the issue to Carthage project.

**Comment by mattlanham** [comment]
Yea i've tried that, still getting the same error unfortunately, is there anyway I can stop it trying to build for WatchOS ?

**Comment by krzyzanowskim** [comment]
I have no idea. @soffes we may need you here again.

**Comment by krzyzanowskim** [comment]
@mattlanham can you please ask this quetion in Carthage project? There is not really more I can do about this with CryptoSwift project I think.

**Comment by krzyzanowskim** [comment]
any update? is there anything I can do about it ?

**Comment by mattlanham** [comment]
Sorry hadn't yet submitted it to Carthage, have no though so hopefully someone can help us out.

**Comment by mattlanham** [comment]
See the comment here: https://github.com/Carthage/Carthage/issues/977 looks like we need a new release of the framework?

**Comment by krzyzanowskim** [comment]
this change is merged to develop, shouldn't be problem.

**Comment by hibento** [comment]
Could it be possible that you - accidentally - deleted the PR #170? The current master / develop has the same issue again, with commit 8430c7ba6099735a76ea7a982bce3d807e1df756 you removed the headers CryptoSwift.h from the build schemes.

**Comment by krzyzanowskim** [comment]
feel free to make new pr, ill merge it

**Comment by krzyzanowskim** [comment]
thanks!
