### ISSUE TITLE
How To...

### ISSUE THREAD

**Issue by dawidheftman** [krzyzanowskim/CryptoSwift#17]
Is there a posibility that you describe the Workflow how to implement your Encryption in a existing Xcode 6 Swift IOS 8 project?

With a example.... ? One Button to start the AES ecryption and a textfield for the Input and Output Label ? ... That everybody understand it?

**Comment by krzyzanowskim** [comment]
Its pretty much this (from README.md)

````
// padding
let paddedData = PKCS7(data: dataToEncrypt).addPadding(AES.blockSizeBytes())

// AES setup with CBC block mode and PKCS#7 data padding
let aesEncrypted = Cipher.AES(setup).encrypt(paddedData)

```

is it not clear enough?

**Comment by dawidheftman** [comment]
It's Not a Problem to Use it ... For me its a Problem to implement Your Code in a existing  Swift Project ...

If You give me a step for step advice i pay for it

Von meinem iPhone gesendet

**Comment by krzyzanowskim** [comment]
Check README for AES code, and this screencast for installation details: http://vimeo.com/117975336
