### ISSUE TITLE
Without Data Padding <Bug?>

### ISSUE THREAD

**Issue by SunshinyNeko** [krzyzanowskim/CryptoSwift#174]
Hi, I opened an issue at https://github.com/krzyzanowskim/CryptoSwift/issues/173

But I rewrite code to test aes-256-cfb encryption, the encrypted data seems not right. See pictures below:

Data encrypted by CryptoSwift-develop branch on OS X 10.10:
<img width="1007" alt="screen shot 2015-12-07 at 15 26 13" src="https://cloud.githubusercontent.com/assets/15274326/11621436/e940f8d0-9cf6-11e5-8de5-d41de419e814.png">

CryptoSwift:
```
["77", "ef"]
["77", "98", "c9", "2c", "45"]
```

Data encrypted by Node.js 4.2.3 on OS X 10.10: 
<img width="803" alt="screen shot 2015-12-07 at 15 15 27" src="https://cloud.githubusercontent.com/assets/15274326/11621412/a36781bc-9cf6-11e5-847c-06e6422ba66e.png">

Node.js:
```
<Buffer 77 ef>
<Buffer cf a5 66 8a 3e>
```

Here is code:

```
    func testAES() {
        let key = [UInt8](count: 32, repeatedValue: 1)
        let iv = [UInt8](count: 16, repeatedValue: 0)
        print(key)
        print(iv)
        
        let aes256cfb = try! AES(key: key, iv: iv, blockMode: .CFB)
        
        let en1 = try! aes256cfb.encrypt([0x5, 0x77], padding: nil)
        print(en1.map({ i in String(format: "%2x", i)}))
        
        let en2 = try! aes256cfb.encrypt([0x5, 0x0, 0x3, 0x89, 0x20], padding: nil)
        print(en2.map({ i in String(format: "%2x", i)}))
    }
```

The first two bytes are same, but the rest bytes are not same. Why? How to fix it? Is my code writing wrong?

**Comment by krzyzanowskim** [comment]
Can't verify bycause my node is little rusty and don't have env for that, though but from what I see you use it wrong, effectively you encrypt different set of data on both expecting the same result.
