### ISSUE TITLE
Problems building on Linux

### ISSUE THREAD

**Issue by brado** [krzyzanowskim/CryptoSwift#177]
I have followed the instructions to install a submodule, and in Xcode my code compiles and unit tests execute cleanly. When I switch over to compiling on Linux, however, I'm getting numerous errors in the CryptoSwift ...+Foundation.swift classes of the nature (2 examples shown): 

```
Packages/CryptoSwift-0.2.0/Sources/CryptoSwift/Foundation/String+FoundationExtension.swift:16:16: error: value of type 'NSData' has no member 'base64EncodedStringWithOptions'
        return NSData(bytes: encrypted).base64EncodedStringWithOptions(NSDataBase64EncodingOptions.Encoding64CharacterLineLength)
               ^~~~~~~~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
and
```
Packages/CryptoSwift-0.2.0/Sources/CryptoSwift/Foundation/Rabbit+Foundation.swift:21:26: error: value of type 'String' has no member 'dataUsingEncoding'
        guard let kkey = key.dataUsingEncoding(NSUTF8StringEncoding, allowLossyConversion: false)?.arrayOfBytes(),
                         ^~~ ~~~~~~~~~~~~~~~~~
```
Any ideas what I'm doing wrong, or how to fix this? 

Thanks.

**Comment by krzyzanowskim** [comment]
do you use Swift Package Manager ?

**Comment by brado** [comment]
Yes.

**Comment by krzyzanowskim** [comment]
Fixed 4809f3bc1257d805f61fac7d4f77c9dba5afb14a

I don;t know why this is issue at all. String bridge works differently on Mac and Swift with the very same Swift Snapshot

**Comment by jckarter** [comment]
Can you file a bug with us at bugs.swift.org too? We want this stuff to behave the same on Darwin and Linux.

**Comment by brado** [comment]
I'm not completely following -- is this just a showstopper for the time being?

**Comment by krzyzanowskim** [comment]
@brado Linux issue has been addressed, can you verify?

**Comment by brado** [comment]
Nope....I have the same build issues as before.

**Comment by krzyzanowskim** [comment]
well... I built it on Ubuntu without problem. have you deleted `.build` dictionary and building current codebase ?

**Comment by krzyzanowskim** [comment]
err... something is really wrong with Linux Swift.

I see strange `error: 'String' is not convertible to 'NSString'`

**Comment by krzyzanowskim** [comment]
@jckarter https://bugs.swift.org/browse/SR-351

**Comment by CoderAFI** [comment]
anybody solve the problem?

**Comment by krzyzanowskim** [comment]
@CoderAFI this is Linux Swift port issue and have to be fixed there ;-((((

**Comment by krzyzanowskim** [comment]
I could disable some parts for Linux... this doesn't seem good solution and easy to overlook then this problem will be fixed upstream.

**Comment by keith** [comment]
I mentioned this on that ticket as well but this is a "known issue" on the corelibs-foundation repo: https://github.com/apple/swift-corelibs-foundation/blob/master/Docs/Issues.md#known-issues

**Comment by krzyzanowskim** [comment]
wish I know workaround

**Comment by keith** [comment]
In theory you can fix this by explicitly bridging the types using the temporary `Bridgeable` protocol. Just add `.bridge()` to the calls that matter. You could do this only for linux as well:

```swift
#if os(Linux)
   return foo.bridge()
#else
   return foo
#endif
```

**Comment by jparishy** [comment]
Yeah, that's pretty much what I did until they sort that out. I default to always using bridge() and just defined it for OS X as an extension on String & NSString: https://github.com/jparishy/Swerver/blob/master/Sources/String.swift#L25

**Comment by krzyzanowskim** [comment]
@keith uhm... this is so ugly, my fingers skip the keyboard when doing that ;-)

**Comment by krzyzanowskim** [comment]
workaround applied to master
