### ISSUE TITLE
AES index out of range

### ISSUE THREAD

**Issue by AnthonyOSX** [krzyzanowskim/CryptoSwift#178]
Code:
```
let key = "73127ED99BA54C10AD67A9F27C4C1792"
        let iv = "1234567890123456"
        let message = "test"
        
        do {
            let encrypted = try message.aesEncrypt(key, iv: iv)
            let decrypted = try encrypted.aesDecrypt(key, iv: iv)
            
            print("Key: \(key)")
            print("IV: \(iv)")
            print("Encrypted: \(encrypted)")
            print("Decrypted: \(decrypted)")
```

Extensions:
```
extension String {
    
    func aesEncrypt(key: String, iv: String) throws -> String {
        return try NSData.withBytes(AES(key: key, iv: iv).encrypt([UInt8](self.utf8))).base64EncodedStringWithOptions([])
    }
    
    func aesDecrypt(key: String, iv: String) throws -> String? {
        return try String(data: NSData.withBytes(AES(key: key, iv: iv).decrypt([UInt8](self.utf8))), encoding: NSUTF8StringEncoding)
    }
    
}
```

Exception occurs in AES.swift on line 206 during decryption. More than likely I'm completely overlooking something.

**Comment by krzyzanowskim** [comment]
Your encrypted string is encoded with base64 and you should decode base64 before AES decryption.

**Comment by AnthonyOSX** [comment]
Attempt to decode using the following throws an exception trying to unwrap a nil optional (decodedString):
```
func base64Decoded() -> String {
    let decodedData = NSData(base64EncodedString: self, options: [])
    let decodedString = NSString(data: decodedData!, encoding: NSUTF8StringEncoding)
        
    return decodedString! as String
}
```

**Comment by krzyzanowskim** [comment]
I think it fail on `decodedString! as String`, isn't it? that's because `decodedData` bytes can't form valid string (as expected, it's just bytes). Decoded base64 string are bytes, not string.

**Comment by AnthonyOSX** [comment]
Wait, will the AES cipher automatically base 64 encode the result? If so it seems I'm encoding twice....

A perfect addition to this library would be be method overloads for returning string representations of the data. Having to deal with byte arrays, encoded as who knows what, is very cumbersome and leads to many unpredictable errors.

**Comment by krzyzanowskim** [comment]
AES is not doing base64 encoding by itself. Resulted bytes (encrypted bytes) are not encoded in anyway, it's simply raw data - result of encryption.

Base64 is one of possible representation of raw data. Other is HEX representation, another is base32 etc. I'm not sure if I follow what you propose.

**Comment by AnthonyOSX** [comment]
What I'm doing is writing two String extensions methods to simplify handling of AES encryption (in my case for sending over the wire, hence base 64). The encryption method from my original functions perfectly fine, however the decryption fails due to the base 64 encoding you mentioned. What I can't seem to figure out is how to decode my base 64 encoded AES result for decryption.

In short:
AES encrypt -> base 64 encode -> decode from base 64 -> decrypt

**Comment by AnthonyOSX** [comment]
Figured it out.

**Comment by krzyzanowskim** [comment]
👍
