### ISSUE TITLE
What is wrong with my project

### ISSUE THREAD

**Issue by RealHector** [krzyzanowskim/CryptoSwift#18]
import CryptoSwift by cocoasPod, then it build error

![h](https://cloud.githubusercontent.com/assets/2427755/5934012/d5768e12-a703-11e4-9a15-a61aa59c959c.jpg)

**Comment by krzyzanowskim** [comment]
Check #15
You need beta version of Cocoapods to use Swift frameworks.

**Comment by krzyzanowskim** [comment]
You can see full process on this screencast: http://vimeo.com/117975336
