### ISSUE TITLE
Support embedding source code directly into project ...?

### ISSUE THREAD

**Issue by breathe** [krzyzanowskim/CryptoSwift#181]
I need a small amount of functionality provided by crypto swift in the context of a swift framework I'm building -- it would be easier/nicer if I could compile the functionality I need directly into my framework and avoid making crypto swift an external dependency ...  It seems like this would be trivial -- however the current CryptoSwift codebase uses module qualified names in a few locations to disambiguate between enum cases and classes with the same name -- for example in Authenticator.swift -- CryptoSwift.Poly1305 is used to refer to the class because in the enum definition context, Poly1305 refers to the case with that same name ...  

Would a pull request that renamed things to avoid needing to use module-qualified class names be accepted?

**Comment by krzyzanowskim** [comment]
It was necessary last time I looked at this, you can check if this is still valid.
https://github.com/krzyzanowskim/CryptoSwift/pull/84

**Comment by MKGitHub** [comment]
Any news on this? Latest Mac OS X…

**Comment by krzyzanowskim** [comment]
To be honest I don't see enought benefits (for this project) with conditional builds per feature/class/struct
It would be very hard to maintain and potentially error prone.
