### ISSUE TITLE
Cannot build iOS CryptoSwift using Carthage

### ISSUE THREAD

**Issue by danwatco** [krzyzanowskim/CryptoSwift#182]
When I try `carthage update --platform iOS` I get a build error and it cannot build the framework. The error is to large for here. The last few lines are,

`error: could not build module 'Foundation'
<unknown>:0: error: could not build Objective-C module 'CryptoSwift'
A shell task failed with exit code 65`

**Comment by krzyzanowskim** [comment]
¯\_(ツ)_/¯ https://github.com/krzyzanowskim/CryptoSwift/issues?q=is%3Aissue+carthage+is%3Aclosed

Please ask on Carthage support

**Comment by danwatco** [comment]
Alright, thanks.
