### ISSUE TITLE
iOS 7 support?

### ISSUE THREAD

**Issue by piresbruno** [krzyzanowskim/CryptoSwift#185]
Does CryptoSwift still supports iOS 7?
I've copied the library files into my project, but i'm getting compare errors, mostly because of the CryptoSwift namespace usage and an an issue with the IntExtensions on the ShiftLeft function.

**Comment by krzyzanowskim** [comment]
it's not officialy supported, though it was requested several of times. #181 #16 #68

**Comment by krzyzanowskim** [comment]
closed as duplicate
