### ISSUE TITLE
AES with key 64

### ISSUE THREAD

**Issue by netgfx** [krzyzanowskim/CryptoSwift#186]
Hello I'm trying to encrypt with a key of count = 64 which results in 512 (count * 8)

And I'm always getting the "Unknown AES variant" message because of this:

```
switch (self.key.count * 8) {
        case 128:
            return .aes128
        case 192:
            return .aes192
        case 256:
            return .aes256
        default:
            preconditionFailure("Unknown AES variant for given key.")
        }
```
Is there a reason for this limitation? What can I do to bypass this? Add another ```case 512``` for example?

Thanks.

**Comment by krzyzanowskim** [comment]
There is no "AES 512" because AES is defined for keys 128, 192, 256, not for 512 or any other value.

**Comment by malisanjay5433** [comment]
@krzyzanowskim Hey dude how can i fix this issue. After migrating Swift 3 and was working absolutely fine last month. But now suddenly crashing App.
fatal error: Unknown AES variant for given key
CryptoSwift/AES.swift, line 48

`public var variant:Variant {
        switch (self.key.count * 8) {
        case 128:
            return .aes128
        case 192:
            return .aes192
        case 256:
            return .aes256
        default:
            preconditionFailure("Unknown AES variant for given key.")
        }
    }
`

**Comment by krzyzanowskim** [comment]
@malisanjay5433 looks like your AES key length is invalid.

**Comment by malisanjay5433** [comment]
This Extension i am using.
` func aesEncrypt(_ key: String, iv: String) throws -> String{
        let data = self.data(using: String.Encoding.utf8)
        let enc = try AES(key: key, iv: iv, blockMode:.ECB).encrypt(data!)
        let encData = Data(bytes: UnsafePointer<UInt8>(enc), count: Int(enc.count))
        let base64String: String = encData.base64EncodedString(options: NSData.Base64EncodingOptions(rawValue: 0));
        let result = String(base64String)
        return result!
    }
    func aesDecrypt(_ key: String, iv: String) throws -> String {
        let data = Data(base64Encoded: self, options:NSData.Base64DecodingOptions(rawValue: 0))
        let dec = try AES(key: key, iv: iv, blockMode:.ECB).decrypt(data!)
        let decData = Data(bytes: UnsafePointer<UInt8>(dec), count: Int(dec.count))
        let result = NSString(data: decData, encoding: String.Encoding.utf8.rawValue)
        return String(result!)
    }
`

**Comment by krzyzanowskim** [comment]
whoever created this extension first (I think I saw it couple of times), have made you bad favor IMHO. It's unecessary and introduce unecessary complication to quite simple task:
1. decode base64 to bytes
2. decrypt bytes

there is [String.decryptBase64ToString()] helper as part of CryptoSwift
(https://github.com/krzyzanowskim/CryptoSwift/blob/master/Sources/CryptoSwift/Foundation/String%2BFoundationExtension.swift#L14)

When it comes to you problem, the problem is PROBABLY your input data, not the code itself. AES key is too short for any AES variant. because
> There is no "AES 512" because AES is defined for keys 128, 192, 256, not for 512 or any other value.

**Comment by netgfx** [comment]
When I had this problem, the server had to change his encryption as well because the server was sending a response that could not be decrypted by cryproSwift (probably this was correct). However using that server payload with another JS library in the past decrypted correctly (probably something not correct encryption-wize).

So yeah @malisanjay5433 check your server payload.

**Comment by malisanjay5433** [comment]
Thanks man.

**Comment by malisanjay5433** [comment]
@netgfx Sure i will check. before it was working let me check with server team.

**Comment by omy2301** [comment]
i am getting error Argument labels '(key:, iv:, blockMode:)' do not match any available overloads.

**Comment by netgfx** [comment]
what kind of cryptography method are you using? AES? and what version? (128? 256?)

**Comment by krzyzanowskim** [comment]
The initializer changed over the time. Check the readme
