### ISSUE TITLE
CryptoSwift decode via php

### ISSUE THREAD

**Issue by netgfx** [krzyzanowskim/CryptoSwift#188]
Hello,

I'm trying to decode a string encrypted via cryptoSwift with php but it can only read the IV bytes correctly, everything else is not decoding correctly.
```
plaintextData = "test".dataUsingEncoding(NSUTF8StringEncoding, allowLossyConversion: false)!
        let ivData:[UInt8] = "1234567891234567".dataUsingEncoding(NSUTF8StringEncoding, allowLossyConversion: false)!.arrayOfBytes() //AES.randomIV(16)
        let cipherdata:[UInt8]
        do {
            cipherdata = try! AES(key: keyData.arrayOfBytes(), iv: ivData, blockMode: .CBC).encrypt(plaintextData.arrayOfBytes(), padding: PKCS7())
        } catch AES.Error.BlockSizeExceeded {
            // block size exceeded
        } catch {
            // some error
        }
        let transferData = NSMutableData(bytes: ivData, length: 16)
        let _cipherdata = NSData(bytes:cipherdata)
        transferData.appendData(_cipherdata)
        let base64:String = transferData.base64EncodedStringWithOptions(NSDataBase64EncodingOptions(rawValue: 0))
        let test = NSData(base64EncodedString: base64, options: NSDataBase64DecodingOptions())!
```

Could someone help me and let me know what is the best way to decode this with php?
Thanks.

**Comment by krzyzanowskim** [comment]
depends what you'll use in PHP you may have library that expect some data construction that is not "vanilla encrypted data". See https://github.com/krzyzanowskim/CryptoSwift/issues/20

**Comment by netgfx** [comment]
Yes I'm using the php from here: https://gist.github.com/tlarevo/63840cdd421937ba9174#file-php-compatible-swift-aes-encryption-using-cryptoswift-swift
But the equivalent of Swift presented there is not up-to-date

**Comment by krzyzanowskim** [comment]
fee free to update swift part to current version of API. Shoulndt be hard to do so.
