### ISSUE TITLE
CryptoSwift Advanced AES Example ArraySlice Error

### ISSUE THREAD

**Issue by niki4ov** [krzyzanowskim/CryptoSwift#189]
Hello,

After following the installation directions and implementing Advanced AES Example, I get an error for decrypted that is: fatal error: ArraySlice index out of range (lldb) that is originating from let decypted... line.

If you could provide any help with this issue I would greatly appreciate it!

Advaned AES Example:

        let input: [UInt8] = [0,1,2,3,4,5,6,7,8,9]
        
        let key: [UInt8] = [0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00]
        let iv: [UInt8] = AES.randomIV(AES.blockSize)
        
        do {
            let encrypted: [UInt8] = try AES(key: key, iv: iv, blockMode: .CBC).encrypt(input, padding: PKCS7())
            let decrypted: [UInt8] = try AES(key: key, iv: iv, blockMode: .CBC).decrypt(input, padding: PKCS7())
        } catch AES.Error.BlockSizeExceeded {
            // block size exceeded
        } catch {
            // some error
        }

![screen shot 2016-01-20 at 2 02 57 pm](https://cloud.githubusercontent.com/assets/8095884/12464598/984e2b46-bf7e-11e5-9e6d-b3b5cd45b0fc.png)
![screen shot 2016-01-20 at 2 03 07 pm](https://cloud.githubusercontent.com/assets/8095884/12464599/9868237a-bf7e-11e5-83e9-342685232877.png)
![screen shot 2016-01-20 at 2 02 45 pm](https://cloud.githubusercontent.com/assets/8095884/12464600/9880d65e-bf7e-11e5-90ae-ff29c31ee6e5.png)

**Comment by krzyzanowskim** [comment]
Please try with code from develop branch. I think it's fixed there. Ref. #184

**Comment by krzyzanowskim** [comment]
@niki4ov you're trying to decrypt `input` value instead of `encrypted`.

Change the line to this and it be will all ok:
```swift
let decrypted: [UInt8] = try AES(key: key, iv: iv, blockMode: .CBC).decrypt(encrypted, padding: PKCS7())
```

**Comment by krzyzanowskim** [comment]
and yes, this is README issue I'm going to fix it now ;)

**Comment by niki4ov** [comment]
Thank you for prompt reply! Was amazing how easy it was to implement CryptoSwift for the rest of of my needs after this issue.
