### ISSUE TITLE
Throwing exception if running on iphone

### ISSUE THREAD

**Issue by sumitjain7** [krzyzanowskim/CryptoSwift#19]
Hi,

This worked great on simulator. But when I tried debugging on iPhone, my app crashed with the error:
dyld: Library not loaded: @rpath/CryptoSwift.framework/CryptoSwift
  Referenced from: /private/var/mobile/Containers/Bundle/Application/886EC182-DCC7-4BE6-9842-022BEF2AE16A/MyApp.app/MyApp
  Reason: image not found

**Comment by krzyzanowskim** [comment]
Look here http://stackoverflow.com/a/26383255/699944

**Comment by krzyzanowskim** [comment]
This is either matter of setup of your project, or Cocoapods issue. Try recreate project file with newest cocoapodst toolset.

**Comment by clozr** [comment]
If you are embedding the framework then don't add to it Link Binary With Libraries section. If you have done it remove it.
