### ISSUE TITLE
When I decrypt I got nil error

### ISSUE THREAD

**Issue by htarwara6245** [krzyzanowskim/CryptoSwift#194]
I am trying to connect SOAP web service with my project using your encryption.I send device unique id and source id to the web service using key and vector set by theirs for encryption.Because of the device id and source id are string,I encrypt like that

```
        var k = "1234567890abcdef"
        var iv = "abcdef1234567890"
        let uuid = UIDevice.currentDevice().identifierForVendor!.UUIDString

        let deviceID = uuid
        let sourceID = "iOS"

        let encryptedDeviceID: String = try! deviceID.encrypt(AES(key: k, iv: iv))
        let encryptedSourceID: String = try! sourceID.encrypt(AES(key: k, iv: iv))

```

And when the response get back from server,it send me with AES-128 encrypted string and when i decrypted it back the response which was at SOAP body

```
        let datastring = NSString(data: data!, encoding:NSUTF8StringEncoding) as! String
                
        let xml = SWXMLHash.parse(datastring)
                
        let body =  xml["soap:Envelope"]["soap:Body"]
                
        //print("Body is : \(body)")
        let result =  (body["InitiateDeviceResponse"]["InitiateDeviceResult"].element?.text)! as String
                
        let data: NSData = NSData(base64EncodedString: result, options: NSDataBase64DecodingOptions(rawValue: 0))!

        let decrypted = try! data.decrypt(AES(key: self.k, iv: self.iv))//Your Crypto Code
                
        let jsonString: String = String(data: decrypted, encoding: NSUTF8StringEncoding)! // That Line bring me nil error. 
```

I created a comment where I got the nil error.

This is the response data that i got from SOAP : "q3xnpwB3d3+UCW1zt6LM4ePQAVkOw/ZRF5qBB7J2YTdqlZaWSzZR+oXEAOlgkt43AoY2BhqjBltf1e7ZRNs5XIPHTOkNqgYfAPzfsGUPo+8=" which is result.Then why it showed me nil after it passed the decrypt?

http://puu.sh/mJYFM/c856c9fe1a.png

**Comment by krzyzanowskim** [comment]
Can you please prepare ready to copy&paste and execute code? I don't really want to write it by myself and guess the input values.

**Comment by htarwara6245** [comment]
I am really sorry to let you know such error.Actually it was wrong decrypting problem with my backend server and i decrypt in wrong way.So,it show me nil.So,i will talk back to backend developer how to decrypt his response back using your library and let you know.That is my classified work,so,can i send it via mail,If you don't mind?

**Comment by krzyzanowskim** [comment]
sure

**Comment by htarwara6245** [comment]
Really sorry about my stupid code because i was beginner at there.Now,I finally understand some.And really thanks for offering such library.I will update my another issue and close that.Thank you for your help

**Comment by krzyzanowskim** [comment]
no worries
