### ISSUE TITLE
Slow compilation times

### ISSUE THREAD

**Issue by czechboy0** [krzyzanowskim/CryptoSwift#195]
Hi Marcin,

as you know, I'm a big fan of CryptoSwift and I'm using it in [Buildasaur](https://github.com/czechboy0/Buildasaur). However, I've noticed that compiling CryptoSwift seems orders of magnitude slower than any other Pod I use. I ran the compilation profiler described [here](http://irace.me/swift-profiling/) and here's a gist with the results (sorted from slowest): https://gist.github.com/czechboy0/316b7293ceea8388496b

You can see that `func toUInt32Array(slice: ArraySlice<UInt8>) -> Array<UInt32>` in `Utils.swift` takes almost **10 seconds** to compile, followed by decryption in AES with over 6 seconds. The next ones drop down to hundreds of milliseconds, which is still pretty high but not a dealbreaker. 

If you could fix these two, it'd decrease the compilation time by ~15 seconds, which I'd definitely appreciate (as would likely everyone else).

Let me know your thoughts or whether I should take a look at it myself.

**Comment by krzyzanowskim** [comment]
👏
