### ISSUE TITLE
Can't Encrypt an Hash

### ISSUE THREAD

**Issue by tjulianb42** [krzyzanowskim/CryptoSwift#197]
Hi, I just updated CryptoSwift into my Xcode Project and now I got an error Static member 'init(stringInterpolationSegment:)' cannot be used on instance of type 'String'

Why do I have that error now ? Here's my syntax:
<img width="1005" alt="capture d ecran 2016-01-26 a 19 07 36" src="https://cloud.githubusercontent.com/assets/8038925/12589901/76e66b08-c460-11e5-83e0-b865799a01d3.png">

Thanks !

**Comment by krzyzanowskim** [comment]
hard to tell anything more than ¯\_(ツ)_/¯ ;-) String extension is there with current version 0.2.2

**Comment by krzyzanowskim** [comment]
Sorry, can't do anything about this one, doesn't seems to be CryptoSwift issue.
