### ISSUE TITLE
How are you supposed to use this?

### ISSUE THREAD

**Issue by pogland** [krzyzanowskim/CryptoSwift#201]
This is so complicated! Whatever way I try to get it, I can never get Xcode to find it. Could someone please say a way to implement this or show a video on how to do this. BTW, I do not want to download an app.

**Comment by krzyzanowskim** [comment]
Hi.

If none of the Installation instruction is working for you:  https://github.com/krzyzanowskim/CryptoSwift#installation maybe try ask Xcode team to improve the process of integration.

Best.
