### ISSUE TITLE
Unable to link CryptoSwift.framework in WatchOS

### ISSUE THREAD

**Issue by diegovigano** [krzyzanowskim/CryptoSwift#204]
Hi

I just built the CryptoSwift.framework file successfully but once I import it in the Linked Frameworks section of my WatchOS Extension my code stop compiling (error below)

ld: framework not found CryptoSwift
clang: error: linker command failed with exit code 1 (use -v to see invocation)

There's some additional step that must be performed for WatchOS Extension?

Thank you and great job!

Diego.

**Comment by krzyzanowskim** [comment]
I'm not expert in Xcode configuration for WatchOS but there is dedicated build target for WatchOS, I think you should use that one.

**Comment by diegovigano** [comment]
I succeeded in importing :)
You do not have to use "Link Binary with libraries" (placed under Build Phases). 

You have to drag&drop the .framework file (compiled with the WatchOS target as you suggested) in your WatchOS extension files (allowing the copy of the file if needed).

Then you have to edit the **Other Linker Flags** key located in the _Build Settings_ panel of the extension adding the following flags:

-weak_framework
CryptoSwift

and it now works. Feel free to add these lines to the wiki if you want, maybe someone was struggling with the same issue.

Thanks again!
Diego

**Comment by krzyzanowskim** [comment]
I may forget, feel free to create PR with that, will be happy to merge.
