### ISSUE TITLE
About Modules

### ISSUE THREAD

**Issue by mohpor** [krzyzanowskim/CryptoSwift#206]
Hi,
This is a nice framework I enjoy using whenever I need to do any kind of hashing or encryption (except for RSA) ...

Regarding #181 request, recently, I had to use AES encryption in one of my swift frameworks and it turned out to be an interesting task of cherry picking it from the entire library. I wanted to copy minimal code required to use AES in my framework. Given the fact that this framework's structure is absolutely gorgeous, and the fact that no single project would ever need all these methods, I was wondering if there could be a way to export a library based on what you need (perhaps using appropriate custom compiler flags) and/or ay other way to simplifying this cherry picking process. 
I have seen such thing in big frameworks like GDAL or the like.

It is just an enhancement suggestion and nothing more.
Thanks for sharing this framework and Cheers.
M.

**Comment by krzyzanowskim** [comment]
Making framework as separate framework would need some sort of code duplication, or generator... it all seems overcomplicate simple things.

Closed as duplicate #181
