### ISSUE TITLE
PBKDF2

### ISSUE THREAD

**Issue by andredsp** [krzyzanowskim/CryptoSwift#207]
Can we expect PBKDF2 support any time soon? Neverthless, it's a nice piece of work. Thank you.

**Comment by andredsp** [comment]
I forgot to mention that I found some commented code on PKCS5.swift about the subject. Does it works?

**Comment by krzyzanowskim** [comment]
no, it doesn't. Once I was about to start work on it, then run out of time

**Comment by krzyzanowskim** [comment]
Hey. I just pushed PBKDF2 to the `develop` branch. Pease check it there.

**Comment by dtorreci4ejg** [comment]
When I copy-paste the line `let value = try! PKCS5.PBKDF2(password: password, salt: salt, iterations: 4096, hashVariant: .sha256).calculate()` from the `README.MD` for the `develop` branch, I get this error:

> 'PKCS5.PBKDF2' cannot be constructed because it has no accessible initializers

Help please?

**Comment by krzyzanowskim** [comment]
should be OK now (methods wasn't marked as public)

**Comment by krzyzanowskim** [comment]
I'm closing this one. PBKDF2 is available on `develop` branch and will be merged to master for next release.
