### ISSUE TITLE
Using AES 256 with CryptoSwift

### ISSUE THREAD

**Issue by pogland** [krzyzanowskim/CryptoSwift#209]
How do you encrypt and decrypt with AES 256 in CryptoSwift? If you respond to this question, please do not show a link to the page <a href="https://github.com/krzyzanowskim/CryptoSwift#usage">here</a>. I have asked a question about this topic and the response was terrible and the question was closed without me responding saying the response is good! And PLEASE DO NOT use PKCS7 padding.

**Comment by krzyzanowskim** [comment]
Hey. This is not the best github issue, dont you think?

I encourage you to look over other closed questions and read README carefully, check functions parameters etc. If you still dont know what to do and need assistance, I may provide you with consultancy, in that case contact me via email.
