### ISSUE TITLE
Does not properly build with latest Linux Swift snapshot

### ISSUE THREAD

**Issue by jabwd** [krzyzanowskim/CryptoSwift#216]
`CryptoSwift-0.2.3/Sources/CryptoSwift/SHA2.swift:276:20: error: expression was too complex to be solved in reasonable time; consider breaking up the expression into distinct sub-expressions
            result += [UInt8(item & 0xff), UInt8((item >> 8) & 0xff), UInt8((item >> 16) & 0xff), UInt8((item >> 24) & 0xff),`

Swift version:

`Swift version 3.0-dev (LLVM a7663bb722, Clang 4ca3c7fa28, Swift 1c2f40e246)`

Reporting it here for information ( fixed it for now in my cloned repo ), but I'm wondering whether this is a compiler bug rather than a bug in this project.

**Comment by krzyzanowskim** [comment]
this is Swift regression. There is PR for that anyway - this kibd of workarounds shouldnt be necessary at all

**Comment by krzyzanowskim** [comment]
workaround is available on "develop" branch.
