### ISSUE TITLE
compilation failure on Ubuntu 14.04

### ISSUE THREAD

**Issue by tannernelson** [krzyzanowskim/CryptoSwift#217]
I'm seeing this error when building CryptoSwift on Ubuntu 14.04 for debug and release modes. 

```shell
tanner@Albert:~/vapor$ swift build
Compiling Swift Module 'CryptoSwift' (40 sources)
<unknown>:0: error: unable to execute command: Killed
<unknown>:0: error: compile command failed due to signal (use -v to see invocation)
<unknown>:0: error: unable to execute command: Killed
<unknown>:0: error: compile command failed due to signal (use -v to see invocation)
<unknown>:0: error: build had 1 command failures
error: exit(1): ["/home/tanner/swift/usr/bin/swift-build-tool", "-f", "/home/tanner/vapor/.build/debug/CryptoSwift.o/llbuild.yaml"]
```

**Comment by tannernelson** [comment]
Swift Version

```shell
tanner@Albert:~/vapor$ swift --version
Swift version 3.0-dev (LLVM f95d47afa7, Clang f66c5bb67b, Swift b745691a38)
Target: x86_64-unknown-linux-gnu```

**Comment by krzyzanowskim** [comment]
it may be Swift 3 problem. Try `develop` branch - there is Swift regression reported here: #216

**Comment by tannernelson** [comment]
https://github.com/qutheory/crypto/commit/0461202e013b8ff2ea07f4d05e42cf5dd373ccd0

I forked the develop branch so I could use it with SPM. This is the latest commit I was compiling.

**Comment by krzyzanowskim** [comment]
yes, workaround is on the branch. I hope it will be fixed in swift anyway

**Comment by tannernelson** [comment]
Are you just compiling CryptoSwift against OS X then?

**Comment by krzyzanowskim** [comment]
master is for current stable version. Swift 3.0 is development version and problems like this should be fixed ther in the first place. Its good to report it to swift team.

**Comment by tannernelson** [comment]
So tagged CryptoSwift releases compile with Swift 2.2 snapshots?

**Comment by krzyzanowskim** [comment]
I can't guarantee that is compile with any snapshot. This is very good example of why. The code is proper, it worked and is working with current stable version of Swift and it should work, then some change to Swift makes compiler crazy and not it can't do simple math. 

As I said, you should checkout `develop` branch of CryptoSwift. I still hope Swift team address this issues with next version before the release.

**Comment by tannernelson** [comment]
Yeah, I feel your pain. Those poor Swift guys are probably swamped with issues like this. 

The error I opened this issue with happened on the develop branch. I had to fork this repo and merge / tag the develop branch into master to get around the "too complex" error. Works on OS X and even Travis said it worked...but no luck on DigitalOcean. 

Definitely Swift's fault so I'll close this issue.
