### ISSUE TITLE
Elliptic curve encode/decode

### ISSUE THREAD

**Issue by ramunasjurgilas** [krzyzanowskim/CryptoSwift#220]
I did generated private key inside Secure Enclave. As written in documentation the key was generated using Elliptic Curve algorithm. Now I need to encrypt and decrypt data using this key.  I can not found this functionality in the code. Dose this implementation exists CryptoSwift?

**Comment by krzyzanowskim** [comment]
no, it doesn't ;-(

**Comment by ramunasjurgilas** [comment]
Thanks. :( Do you know? Can it be implemented at all?

**Comment by krzyzanowskim** [comment]
I can be.
