### ISSUE TITLE
Decryption difference in IOS & Android in using negative(signed) byte in crypto swift

### ISSUE THREAD

**Issue by NPRABHAK-AMGEN** [krzyzanowskim/CryptoSwift#222]
I am not getting same decryption result in IOS & Android if any negative(signed) value present in byte array. In Android I am getting same encrypted value while decrypting but in IOS using crypto swift I am not getting same result.

Here below is my key & iv
` let dynamicKey : [UInt8] = [87, 6, 87, 4, 5, 7, 86, 15, 11, 82, 4, 0, 52, 54, 53, 48]
`
My encrypted data =` let encryptedData: [UInt64] = [-68, 101, -127, -14, 35, -47, -115, 118, 54, 91, 12, 67, 21, 29, -64, 111]`

The result I am expecting is = [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] but what I getting is = [93, 87, 209, 216, 136, 8, 9, 72, 131,231, 74, 139, 166, 28, 126, 54]

I see the negative byte is the only problem here. In android it just decrypt well but in crypto swift it doesn't work.

Android method
```
  SecretKeySpec skeySpec = new SecretKeySpec(key, "AES");
            Cipher cipher = Cipher.getInstance("AES/CBC/NoPadding");

            cipher.init(Cipher.DECRYPT_MODE, skeySpec, ivParameterSpec);
            decrypted = cipher.doFinal(encryptedData);
```

Awaiting for your suggestion for fix.

**Comment by krzyzanowskim** [comment]
UInt8 dont have negative values at all. Im not fully follow what are you doing with cryptoswift. im pretty sure your passing invalid data here or there nd expecting invalid output.

**Comment by NPRABHAK-AMGEN** [comment]
Actually I am passing same key and encrypted data to crypto swift which used in android but result are different. I wonder how in android it return correct output even though input was wrong. 

I just done a experiment like converted all negatives into positive in android and after decrypting getting same result which crypto swift returns.

**Comment by krzyzanowskim** [comment]
to give you support here, I should ask you to attach your code since I cant tell any more just guessing how the exact code looks like

**Comment by NPRABHAK-AMGEN** [comment]
Hi krzyzanowskim,  the issue here is my encrypted data from external device has signed array of Int value i.e `[-68, 101, -127, -14, 35, -47, -115, 118, 54, 91, 12, 67, 21, 29, -64, 111]` But here in crypto swift it doesn't support signed value decryption so if I decrypt this using signed array of Int `let encryptedData: [Int8] =  [-68, 101, -127, -14, 35, -47, -115, 118, 54, 91, 12, 67, 21, 29, -64, 111]` using commonCrypto it works.

**Comment by NPRABHAK-AMGEN** [comment]
If you want to experiment this is the encrypted data` [-68, 101, -127, -14, 35, -47, -115, 118, 54, 91, 12, 67, 21, 29, -64, 111]` , Key: `[87, 6, 87, 4, 5, 7, 86, 15, 11, 82, 4, 0, 52, 54, 53, 48`] and actual data before encryption is `[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]`.

I used AES 128, CBC mode and no padding.

**Comment by krzyzanowskim** [comment]
in that case convert signed Int8 to unsigned Int8 (byte) - this is what you probably need. It's all about stream of bits in right order. 

I don't know how you get negative values out of UInt8, it's not clear to me, you have to convert output to something, I don't know. If you think there is cipher issue, please create test case to verify.

you can paste code here, create gist, create project, whatever that let me reproduce the issue.

**Comment by NPRABHAK-AMGEN** [comment]
Actually my app communicating with external device which is returns negative value i.e Signed array of Int8 [Int8]. (Encrypted data)

You are right converting [Int8] to [UInt8] and giving it as input to decryption method fixed my problem. 

So there is no cipher issue but If you add some utill method which will convert signed to unsigned and vice versa or dynamically detecting type and converting into a single form i.e [UInt8] while decryption will be great. Thanks
