### ISSUE TITLE
Add Support for Xcode 7.3

### ISSUE THREAD

**Issue by aowens430** [krzyzanowskim/CryptoSwift#224]
I'm doing some testing with Xcode 7.3 beta, however during build it throws CryptoSwift "was created by an older version of the compiler; rebuild CryptoSwift". Perhaps I am missing something, but if not, can we add support for 7.3? Thank you.

**Comment by krzyzanowskim** [comment]
this sounds like some xcode issue. is it precompiled with carthage maybe?
xcode 7.3 and next version of swift support is available on. branch develop

**Comment by aowens430** [comment]
It was done with Carthage, I ran a carthage update --platform iOS and the cartfile contains ( github "krzyzanowskim/CryptoSwift" "develop") am I missing something?

**Comment by krzyzanowskim** [comment]
ask on carthage, this is carthage related issue, cant hep you with that. some build is cached apperently
