### ISSUE TITLE
Complie in the swift package manager error.

### ISSUE THREAD

**Issue by CoderAFI** [krzyzanowskim/CryptoSwift#226]
CryptoSwift/CSArrayType+Extensions.swift:29:16: error:
 use of unresolved identifier 'NSData'
        return NSData(bytes: bytesArray).base64EncodedStringWithOptions([])

**Comment by CoderAFI** [comment]
Using swiftspm at devleop branch

**Comment by kiokumicu** [comment]
I got another error
```
SHA2.swift:276:20: error: expression was too complex to be solved in reasonable time; consider breaking up the expression into distinct sub-expressions
            result += [UInt8(item & 0xff), UInt8((item >> 8) & 0xff), UInt8((item >> 16) & 0xff), UInt8((item >> 24) & 0xff),
```

**Comment by krzyzanowskim** [comment]
use `develop` branch, this Swift issue is addressed there https://github.com/krzyzanowskim/CryptoSwift/tree/develop

**Comment by kiokumicu** [comment]
@krzyzanowskim i see same code in master and develop branch

**Comment by krzyzanowskim** [comment]
I'll take a look at it tomorrow, after upgrade to latest xcode.

**Comment by kiokumicu** [comment]
Do you have time to look at this problem?

**Comment by krzyzanowskim** [comment]
yes, and I didn't notice problem with branch `develop` and Xcode 7.3 (7D175). Are you sure you have problem with Swift 2.2 ?
