### ISSUE TITLE
Decrypt data fail from php for big data

### ISSUE THREAD

**Issue by B-Gio-KGJ** [krzyzanowskim/CryptoSwift#227]
Hi,

I use [this](https://gist.github.com/tlarevo/63840cdd421937ba9174) to encrypt data.

For text data "test" ( `aesEncryptWithStaticIV()` )
cryptoSwift give me encrypted result "`065TnFFNwQFRjPZk6l8luw==`"
and PHP successfuly decrypt it.

But with 'real' data (eg: "`progression|*|D4E1B270-06DD-4A8C-A418-0CA955EB6738|*|25|*|342|*|159|*|10|*|1457454939636.0`") php don't decrypt correctly the data.

here is php decrypt function : 

```
function decrypt($str) {
	$code = base64_decode ( urldecode ( $data ) );
	$iv = $this->iv;
	$td = mcrypt_module_open('rijndael-128', '', 'cbc', $iv);
	mcrypt_generic_init($td, $this->key, $iv);
	$decrypted = mdecrypt_generic($td, $code);
	mcrypt_generic_deinit($td);
	mcrypt_module_close($td);
	return trim(preg_replace('/[\x00-\x1F\x80-\xFF]/', '', $decrypted));
}

```

and here, swift procedure to encrypt data : 
`let dump = try! data.stringByAddingPercentEncodingForRFC3986()!.aesEncrypt()`

What i'm make wrong ?

regards,

**Comment by krzyzanowskim** [comment]
@B-Gio-KGJ  ?
