### ISSUE TITLE
C-Style deprecated in a future version of Swift

### ISSUE THREAD

**Issue by ricgreenfield** [krzyzanowskim/CryptoSwift#228]
Hello everybosy, i have this C-Style for statment deprecated with the new Swift 2.2 and Xcode 7.3...any help to resolve?

```
for (var i = 0; i < tmpMessage.length; i = i + chunkSizeBytes, leftMessageBytes -= chunkSizeBytes) {
```

**Comment by krzyzanowskim** [comment]
update CryptoSwift codebase to v. 0.3
