### ISSUE TITLE
Frameworks highlighted in red no module found

### ISSUE THREAD

**Issue by alexrmacleod** [krzyzanowskim/CryptoSwift#229]
Caution this may be a simpleton issue; Spent the past two hrs trying to get cryptoSwift working. Got it running in a small test project but I can't seem to add cryptoSwift to my current project. 

I followed the instillation steps meticulously to no avail. I tried everything I can think of. at a loss here.

Heres a url to a picture of my project showing the frameworks in red and the "no module found error"
[https://drive.google.com/file/d/0B5feUHWffxoWZElxNzNabnNJMDQ/view?usp=sharing](url)
   
Heres a url of a picture of my derived data folder which is mysteriously missing the cryptoSwift frameworks:
[https://drive.google.com/file/d/0B5feUHWffxoWbTd5Vi1ud2s2aWc/view?usp=sharing](url)

I did notice the below at the end of the instillation steps. But I am not sure exactly what this whats me to do!
- "You may need to choose the one you need to build CryptoSwift.framework for your application." But am not sure how to build the cryptoSwift.framework

**Comment by krzyzanowskim** [comment]
it depends on how you itegrate frameworks and state of your project, different actions may be needed to integrate external dependencies. This is why Cocoapods/Carthage projects exisist and I encourage you to use it.

**Comment by alexrmacleod** [comment]
So if I use Carthage to import crypto swift it will work? 

Also which one should I go with? Cocoa pods or Carthage? Which one is more popular?

**Comment by krzyzanowskim** [comment]
it will work either way, though xcode setup may be hard. I'd say Cocoapods is the easiest way to integrate frameworks

**Comment by wjlafrance** [comment]
To offer a different opinion, I'm integrating this lib with Carthage and found it super simple. Just add it to your Cartfile, `carthage update`, and then drag in the built framework as you normally do.
