### ISSUE TITLE
Get encyrpted data to string

### ISSUE THREAD

**Issue by bradbernard** [krzyzanowskim/CryptoSwift#23]
I am trying to use encryption/decryption in iOS (swift) and also in PHP using AES 256. I am using code that encrypts a string with a key and returns a NSData?. However I can't send that to a PHP script so I want to convert it to a string. 

let encryptedString = NSString(data: encryptedData, encoding: NSUTF8StringEncoding)

But it always comes out to nil... Am I doing something wrong?

**Comment by krzyzanowskim** [comment]
Encrypted data is not a string. See #20.

**Comment by bradbernard** [comment]
Awesome, thanks for the pointer.
