### ISSUE TITLE
Error while installing through carthage 

### ISSUE THREAD

**Issue by idevaj** [krzyzanowskim/CryptoSwift#231]
Getting this error while installing through carthage
The following build commands failed:
	CompileSwift normal x86_64 /Users/ABC/Documents/Projects/XY/SourceCode/xyz/Carthage/Checkouts/CryptoSwift/Sources/CryptoSwift/BlockMode/CipherBlockMode.swift
	CompileSwift normal x86_64 /Users/ABC/Documents/Projects/XY/SourceCode/xyz/Carthage/Checkouts/CryptoSwift/Sources/CryptoSwift/BytesSequence.swift
	CompileSwift normal x86_64 /Users/ABC/Documents/Projects/XY/SourceCode/xyz//Carthage/Checkouts/CryptoSwift/Sources/CryptoSwift/AES.swift
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(4 failures)

**Comment by krzyzanowskim** [comment]
¯\_(ツ)_/¯ probably carthage related problem. Not much info here

**Comment by krzyzanowskim** [comment]
Closing with suggestion look at past Carthage related issues: https://github.com/krzyzanowskim/CryptoSwift/issues?q=is%3Aissue+carthage
eventually please report problem to Carthage repository

**Comment by idevaj** [comment]
i have the latest version of carthage that is 0.15.2 
could you provide some specific details
