### ISSUE TITLE
Swift 2.2 Master Release?

### ISSUE THREAD

**Issue by razvandub** [krzyzanowskim/CryptoSwift#232]
Hi, 

When do you plan to release a (up-to-date) Swift 2.2 version with no warnings? 

Thanks.

**Comment by krzyzanowskim** [comment]
yes

**Comment by kaishin** [comment]
@razvandub See #230.

**Comment by razvandub** [comment]
Not sure why the thumbs down... was asking when a release is scheduled.

**Comment by kaishin** [comment]
@razvandub It depends on the project, but issue are not a venue for asking generic questions. I just expressed my opinion. Feel free to to disagree with it.

**Comment by catalandres** [comment]
Hey, it's up to you how you want to manage issues, but if it's not solved yet maybe it shouldn't be closed.

**Comment by krzyzanowskim** [comment]
@catalandres it's solved and available on master branch. The PR #230 is merged.

**Comment by krzyzanowskim** [comment]
[0.3.1](https://github.com/krzyzanowskim/CryptoSwift/releases/tag/0.3.1) is released

**Comment by razvandub** [comment]
Thanks.
