### ISSUE TITLE
CipherError

### ISSUE THREAD

**Issue by guichico** [krzyzanowskim/CryptoSwift#233]
Hello.

I am generating encrypted string this way...

`let base64String = try (json as String).encrypt(AES(key: "secret0key000000", iv: "0123456789012345")).toBase64()`

and when I try to decrypt I get the following error...
Error Domain=CryptoSwift.CipherError Code=1 "(null)"

The decrypt code is that...
`let decrypted = try (dataString as! String).decryptBase64ToString(AES(key: "secret0key000000", iv: "0123456789012345"))`

**Comment by krzyzanowskim** [comment]
what is the value of "json" and what is the value of "dataString" ?

**Comment by guichico** [comment]
"json" is a NSString of a json value, like this `"{\n  \"value\" : 9,\n  \"id\" : \"1\"\n  }"`
and "dataString" is the encrypted value of "json"

**Comment by krzyzanowskim** [comment]
what **exactly** are these values you're using?
