### ISSUE TITLE
AES 256 Help Needed

### ISSUE THREAD

**Issue by kamalupasena** [krzyzanowskim/CryptoSwift#235]
I am currently use AES in my java code for String this is my Java Code

```
`private static Cipher initCypher(int mode) {
        Cipher cipher = null;
        String secret = "Bv@4X$XwAIT%3cHl";
        try {
            Key key = new SecretKeySpec(secret.getBytes("UTF-8"), "AES");
            cipher = Cipher.getInstance("AES");
            cipher.init(mode, key);
        } catch (NoSuchAlgorithmException | NoSuchPaddingException | InvalidKeyException | UnsupportedEncodingException e) {
            e.printStackTrace();
        }
        return cipher;
    }
​
    // Encrypt
    public static String encrypt(String msg) {
        try {
            Cipher cipher = initCypher(Cipher.ENCRYPT_MODE);
            byte[] encryptedData = cipher.doFinal(msg.getBytes());
            return new String(Base64.encodeBase64(encryptedData), "UTF-8");
        } catch (UnsupportedEncodingException | BadPaddingException | IllegalBlockSizeException e) {
            e.printStackTrace();
        }
        return "";
    }
​
    // Decrypt
    public static String decrypt(String encryptedMsg) {
        try {
            Cipher cipher = initCypher(Cipher.DECRYPT_MODE);
            byte[] data = Base64.decodeBase64(encryptedMsg.getBytes("UTF-8"));
            byte[] plainData = cipher.doFinal(data);
            return new String(plainData);
        } catch (IllegalBlockSizeException | UnsupportedEncodingException | BadPaddingException | ArrayIndexOutOfBoundsException e) {
            e.printStackTrace();
        }
        return encryptedMsg;
    }`

```
How can archive this encryption and decryption in  CryptoSwift because i dont use iv key in Java

**Comment by kamalupasena** [comment]
@krzyzanowskim  can you help me ?

**Comment by krzyzanowskim** [comment]
I'm not sure what are defaults for block mode and paddig for `Cipher("AES")` as documentation https://docs.oracle.com/javase/7/docs/api/javax/crypto/Cipher.html don't really mention that. I assume it's `"AES/CBC/Padding"` and default IV (zeroes), thought you can check the IV with `cipher.getIV()`. It may be ECB by default and in this case IV is not needed... I'm not sure about that.

**Comment by kamalupasena** [comment]
Thank you for the answer @krzyzanowskim  I'll look into it

**Comment by kamalupasena** [comment]
One small question i am currently `decryptBase64ToString` can you tell me how can i pass Padding to this function ?
```try!  encryptedText.decryptBase64ToString(AES(key: "Bv@4X$XwAIT%3cHl", iv: "0000000000000000", blockMode: .CBC)) ```

**Comment by krzyzanowskim** [comment]
you can't. This convenience method uses default padding (PKCS7). If you need no padding, you have to implement it by your own.

**Comment by kamalupasena** [comment]
ah Ok Thank you

**Comment by krzyzanowskim** [comment]
I found it valid to make it possible to specify padding option with AES constructor and this way use it with all helpers, that's why I've made change to make it happen. It's available on `develop` branch (check README for parameters)

**Comment by kamalupasena** [comment]
Thank you so much , ill check that out

**Comment by kamalupasena** [comment]
@krzyzanowskim  i feel like its a bug or i do it wrong when i am trying to encrypt a long text (more than 256 characters) encryption and decryption now working correctly its work find with the small text, now i am using AES with `ECB` and `PKCS7` padding

**Comment by krzyzanowskim** [comment]
why do you feels so?

**Comment by kamalupasena** [comment]
because i don't know i am doing something wrong or its a bug from the `CryptoSwift` and its only appear on text message with more than 256 characters only

**Comment by krzyzanowskim** [comment]
I meant, why? can you show us the bug youre seeing?

**Comment by kamalupasena** [comment]
![img_0197](https://cloud.githubusercontent.com/assets/5517484/14239008/f8555efe-fa54-11e5-9722-03da6966b62a.jpg)

i have added original string and the result string (blue colour one in the result string) if its work fine  i should be getting same string for both places

**Comment by krzyzanowskim** [comment]
hm... I dont understand. Could you be please be more specific, like with the code and input/output data? Test case would be awesome. thanks.
I cant spot the problem tbh.

**Comment by kamalupasena** [comment]
ok sure 

this is my input string 

`Hello this is a really long message that i am trying to encrypt using crypto swift but there is a bug when we are trying to convert really long message`

and this is the result i am getting after decrypt it 

`N+l4SXvi1ndlPUdgMPdsES4iX/pN/6eZxOntWy67/eNfrlyHFB1jaOAWCBQykfth\r\ne4crbX5xiRt3Sbcw7O6ze7HOD72XkQmXV8LGKTpObqzrOxMLVj8zV2aBd2CDxyZZ\r\n+fooZDStnmdDoUA68qOVIPhQIUHlSRDWJ7OiD12W39EEm9Zn4ID9gzYVfdjT/1Fu\r\nDNlC1yYM1T47XvVFx5o7RQ==`

**Comment by krzyzanowskim** [comment]
Can't confirm any issue with given test. If you think there is a bug, please create proper test case for that.

```swift
    func testAES_encrypt_ecb_long() {
        let key: [UInt8] = [56, 118, 37, 51, 125, 78, 103, 107, 119, 40, 74, 88, 117, 112, 123, 75, 122, 89, 72, 36, 46, 91, 106, 60, 54, 110, 34, 126, 69, 126, 61, 87]
        let iv: [UInt8] = [69, 122, 99, 87, 83, 112, 110, 65, 54, 109, 107, 89, 73, 122, 74, 49]
        let message = "Hello this is a really long message that i am trying to encrypt using crypto swift but there is a bug when we are trying to convert really long message"
        let aes = try! AES(key: key, iv: iv, blockMode: .ECB, padding: PKCS7())
        let encrypted = try! message.encrypt(aes)
        let decrypted = try! encrypted.decrypt(aes)
        XCTAssert(message.utf8.lazy.map({ $0 as UInt8 }) == decrypted, "decryption failed");
    }
```

**Comment by kamalupasena** [comment]
@krzyzanowskim  Sorry it's not a bug  i made some mistake when i am trying to convert the encrypted byte array into base 64 String thats why its not decrypted as expected , thank you very much for the help

**Comment by krzyzanowskim** [comment]
👍
