### ISSUE TITLE
Bit will be deprecated in Swift 3

### ISSUE THREAD

**Issue by catalandres** [krzyzanowskim/CryptoSwift#236]
Warning message compiling with Carthage:

`warning: 'Bit' is deprecated: Bit is deprecated as of Swift 3. Use Int instead.`

Here is a list of the involved files and line numbers:

**BitExtension.swift:**
9:11, 10:24, 11:21, 12:20, 15:16

**UInt8Extension.swift:**
50:17, 55:21, 58:26, 58:69, 65:32, 73:18, 75:24

**IntExtension.swift:**
26:17

**Generics.swift:**
23:58, 27:18

**Poly1305.swift:**
250:19, 251:48

**Comment by krzyzanowskim** [comment]
Closed as duplicate #232

**Comment by krzyzanowskim** [comment]
[0.3.1](https://github.com/krzyzanowskim/CryptoSwift/releases/tag/0.3.1) is released
