### ISSUE TITLE
EXEC_BAD_ACCESS when running tests

### ISSUE THREAD

**Issue by hamchapman** [krzyzanowskim/CryptoSwift#237]
I only need the HMAC part of CryptoSwift for the library I'm working on and so I decided to just manually copy and paste the parts of CryptoSwift that I need into my library (only need the sha256 variant).

I did that: https://github.com/pusher/pusher-websocket-swift/pull/36

And it works for the example iOS app I have in that repo. However, whenever I try and run the tests I get  `EXEC_BAD_ACCESS(code=2, address=...)`

![screen shot 2016-04-04 at 14 48 53](https://cloud.githubusercontent.com/assets/2475150/14250099/ced7452c-fa74-11e5-9076-200eca87cb92.png)

Any ideas as to what could be causing this? It seems strange that it only seems to happen in the tests target.

**Comment by krzyzanowskim** [comment]
Hi,

Don't do that, but if you have to then I offer professional support to all my open source projects, just email me.

https://twitter.com/krzyzanowskim/status/716391748168245248
