### ISSUE TITLE
Swift 3.0 Warnings

### ISSUE THREAD

**Issue by mehfuzh** [krzyzanowskim/CryptoSwift#238]
I am getting several Swift 3.0 warnings after updating to the latest Xcode version.

BitExtension.swift:9:11: 'Bit' is deprecated: Bit is deprecated as of Swift 3. Use Int instead.
Rabbit.swift:67:32: '++' is deprecated: it will be removed in Swift 3
Rabbit.swift:126:9: C-style for statement is deprecated and will be removed in a future version of Swift

Thanks
Mehfuz

**Comment by krzyzanowskim** [comment]
You must have use outdated version of CryptoSwift.

**Comment by mehfuzh** [comment]
I am installing it from cocoapods ? Is that outdated ?

**Comment by krzyzanowskim** [comment]
Shouldn't, but the warnings you described were addressed with release 0.3.0 and up, maybe you have cached something... dunno.

**Comment by mehfuzh** [comment]
pod clean does the trick.
