### ISSUE TITLE
Unsupported Architectures

### ISSUE THREAD

**Issue by lostatseajoshua** [krzyzanowskim/CryptoSwift#239]
I used the build script to build Crypto framework and added it to my project.
When I try to upload to App Store through archive with the framework installed I receive three errors.
#### Errors: 
 1. "Unsupported Architectures. The executable for .app/Frameworks/CryptoSwift.framework contains unsupported architectures '[x86_64, i386]'."

 2. "The binary is invalid. The encryption info in the LC_ENCRYPTION_INFO load command is either missing or invalid, or the binary is already encrypted. This binary does not seem to have been built with Apple's linker."

3. ".app/Frameworks/CryptoSwift.framework' is not a Position Independent Executable. Please ensure that your build settings are configured to create PIE executables. For more information refer to Technical Q&A QA1788 - Building a Position Independent Executable in the iOS Developer Library."

Any help is very appreciated thank you in advance.

**Comment by krzyzanowskim** [comment]
you may need adjust the script.


Sorry to admit that but I will remove it shortly from the repo or at least comment as 3prty and not really maintained. Dealing with build system is horrible enough to avoid as much as possible :-)

**Comment by eightiscottmckenzie** [comment]
@lostatseajoshua The framework that is pulled down by Carthage is fat; supporting x86_64, i386. When you run the copy-frameworks script in your build cases this will be removed. (See Carthage docs about this.)
