### ISSUE TITLE
Swift 3.0 support - bitcode support

### ISSUE THREAD

**Issue by colemancda** [krzyzanowskim/CryptoSwift#240]
I created a `Swift3` branch on my fork and am working on Swift 3.0 support.

**Comment by krzyzanowskim** [comment]
👍 

nonetherless... I'd rather wait for first beta of Swift 3.0 because language evolve so much it's hard to keep the pace now.

**Comment by krzyzanowskim** [comment]
anyway feel free PR to "swift3" branch when ready.

**Comment by colemancda** [comment]
Thanks!

	Coleman,

**Comment by colemancda** [comment]
@krzyzanowskim PR #241 is ready for merge.

**Comment by colemancda** [comment]
@krzyzanowskim PR #244 is a cleaner version of #241 (only 3 commits). 
Also got the unit tests to build and run on Linux.

**Comment by kinosang** [comment]
Great.

I'm a newbie to Swift and I'm working on Mac OS X with Trunk Development Version of swift. How can I specify the branch in `Package.swift`?

**Comment by krzyzanowskim** [comment]
Swift 3 codebase is available from [**swift3**](https://github.com/krzyzanowskim/CryptoSwift/tree/swift3) branch.

This is highly preliminary support for Swift 3 and everything may change.

**Comment by kdawgwilk** [comment]
The swift3 branch is not currently compiling with Xcode 8 beta 2.  I have tried converting it for a PR but I have no idea what I am doing.  I will keep trying but maybe someone wouldn't mind lending a hand

**Comment by krzyzanowskim** [comment]
@kdawgwilk well... what problem you notice? I don't see any problem. It build clean here. I updated few warning after beta 2 releases too.

**Comment by kdawgwilk** [comment]
Well I was right about one thing, I have no idea what I am doing haha I was trying to use the swift3 branch with SPM and couldn't get it to pull the right code.  I ended up adding a tag `0.0.0` locally to the repo and then using this line in my Package.swift
``` swift
.Package(url: "../../CryptoSwift", Version(0,0,0))
```

**Comment by enagorny** [comment]
Does anyone manage to install it via Carthage?

**Comment by zaubara** [comment]
Nope, Carthage build fails:
ld: could not open bitcode temp file: ~/Library/Developer/Xcode/DerivedData/CryptoSwift-atffddhtudmrxxcpxecijdiwirnu/Build/Intermediates/CryptoSwift.build/Release-iphoneos/CryptoSwift iOS.build/Objects-normal/armv7/CryptoSwift.lto.opt.bc for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

For a quick workaround, you may be able to disable bitcode generation.

**Comment by krzyzanowskim** [comment]
Did you tried ask on Carthage repo? As far as I know the version from "master" worked.

**Comment by zaubara** [comment]
Master worked, thank you. Other repos work fine with swift3 and carthage, so I would expect the issue to be cryptoswift related - i've seen that you use custom Flags for bitcode generation, maybe something changed with the linker? Although it's weird that it compiles fine in xcode.

**Comment by colemancda** [comment]
@enagorny I was able to get it working https://github.com/colemancda/CryptoSwift/tree/swift3

**Comment by colemancda** [comment]
While I am able to get the framework build for Xcode 8 Beta 2, it fails when trying to archive.

```
ld: could not open bitcode temp file: /Users/coleman/Library/Developer/Xcode/DerivedData/CryptoSwift-aqelvtvgrnfgtvdawftqwsuhukrj/Build/Intermediates/ArchiveIntermediates/CryptoSwift iOS/IntermediateBuildFilesPath/CryptoSwift.build/Release-iphoneos/CryptoSwift iOS.build/Objects-normal/arm64/CryptoSwift.lto.opt.bc for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by colemancda** [comment]
See https://forums.developer.apple.com/thread/11098

**Comment by kgn** [comment]
I'm able to build the framework in Xcode 8 beta 2, but when I try it through Carthage it fails with this reason:

```
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Anyone else getting this?

**Comment by colemancda** [comment]
Yes, all release builds for frameworks are broken. Try my PR https://github.com/krzyzanowskim/CryptoSwift/pull/282

	Coleman,

**Comment by colemancda** [comment]
If you wanna fix it locally, try this

CODE_SIGNING_REQUIRED = NO
CODE_SIGN_IDENTITY = Don't Code sign

**Comment by krzyzanowskim** [comment]
@colemancda  I see no good reason to disable bitcode

**Comment by zaubara** [comment]
Disabling bitcode obviously can't be the solution to this (which is why I forked and changed it, but didn't create a PR), but for people being dependent on the framework this seems to be the most straightforward option.
There might be a solution that actually works, but if we can't fix it within the project, we'll probably have to wait for a more stable XC beta3.

**Comment by enagorny** [comment]
XC beta3 already available

**Comment by colemancda** [comment]
Bitcode is disable because Xcode is messed up
https://twitter.com/steipete/status/755377159066226692

**Comment by krzyzanowskim** [comment]
@colemancda this is not the case. OpenSSL is different story. Not related to building regular frameworks.

**Comment by colemancda** [comment]
All I know is I am getting the same error unless I disable bitcode, then it works fine.

	Coleman,

**Comment by colemancda** [comment]
Also, its not just your framework. KeychainAccess and most of my 3rd party libraries are completely broken in Xcode 8 b3. Disabling Bitcode usually fixes that error.

	Coleman,

**Comment by krzyzanowskim** [comment]
Does Xcode beta 4 fixed the problem?

**Comment by uny** [comment]
Xcode 8 beta 5 also have the same problem.

**Comment by krzyzanowskim** [comment]
I still believe they will fix this, it's just ridicolous. Pls file bugs to https://bugreport.apple.com/ and maybe to http://bugs.swift.org

**Comment by krzyzanowskim** [comment]
suspect LLVM_LTO now (thanks @uny)

**Comment by MichielDeMey** [comment]
We should consider adding support for Swift's Package Manager.

Simply append `@swift-3` to the release tag to denote that build as a "swift 3" specific build of that version. This way we can maintain support for both Swift versions.

More information here: https://github.com/apple/swift-package-manager/blob/master/Documentation/Usage.md#version-specific-tag-selection

**Comment by krzyzanowskim** [comment]
@MichielDeMey how about separate issue to discuss that?

**Comment by MichielDeMey** [comment]
@krzyzanowskim Sounds like a good idea. 👍

**Comment by mipstian** [comment]
If it helps, I've ran into the same `could not open bitcode temp file` issue in an app of mine, and disabling LTO fixed it. I'm assuming disabling bitcode fixes it as well – seems we just can't have both as of Xcode 8 beta 6.

**Comment by ChMaxou** [comment]
Sorry for the noob question, but how can I make sure I install the swift 3 branch of this repo in my project?

**Comment by krzyzanowskim** [comment]
@ChMaxou switch to swift3 branch and download zip archive. Or clone swift3 branch with git. 
![screen shot 2016-09-08 at 09 59 39](https://cloud.githubusercontent.com/assets/758033/18341622/1c93b03c-75ab-11e6-9274-e0cd6eee5cdc.png)

**Comment by mipstian** [comment]
I was able to build with monolithic LTO *and* bitcode in Xcode 8 GM.

**Comment by ChMaxou** [comment]
OK the git wasn't working for me, so I downloaded it and moved the files in my project. Everything seems fine, however I do not see the "Embed Framework" section in Build Phases, and I can't import CryptoSwift in my swift files.

**Comment by krzyzanowskim** [comment]
@ChMaxou his onstallation question you have, is not really to this issue. Its more Xcode question, try look at google how to add framework to Xcode project manually, there is bunch of answers on stackoverflow too.

**Comment by ChMaxou** [comment]
I've tried but can't find any way to get the installation to work. I don't even see the framework in the Swift 3 version.

**Comment by krzyzanowskim** [comment]
¯\_(ツ)_/¯ try cocoapods

**Comment by krzyzanowskim** [comment]
I'm closing, it seems fixed by Xcode. Feel free to reopen if you find it accurate.

**Comment by appstute-prasad** [comment]
I have installed CryptoSwift through cocoapods in xcode8, swift 3, but i got error in file AES.swift line no. 144 that "Expression was to complex to be in responsive time : consider breaking up the expression into distinct subexpressions, What to do with this error? Below is the code

` var b0 = UInt32(block[block.startIndex + 0 + (0 << 2)]) << 0 | UInt32(block[block.startIndex + 1 + (0 << 2)]) << 8 | UInt32(block[block.startIndex + 2 + (0 << 2)]) << 16
            b0 = b0 | UInt32(block[block.startIndex + 3 + (0 << 2)]) << 24
        var b1 = UInt32(block[block.startIndex + 0 + (1 << 2)]) << 0 | UInt32(block[block.startIndex + 1 + (1 << 2)]) << 8 | UInt32(block[block.startIndex + 2 + (1 << 2)]) << 16
            b1 = b1 | UInt32(block[block.startIndex + 3 + (1 << 2)]) << 24
        var b2 = UInt32(block[block.startIndex + 0 + (2 << 2)]) << 0 | UInt32(block[block.startIndex + 1 + (2 << 2)]) << 8 | UInt32(block[block.startIndex + 2 + (2 << 2)]) << 16
            b2 = b2 | UInt32(block[block.startIndex + 3 + (2 << 2)]) << 24
        var b3 = UInt32(block[block.startIndex + 0 + (3 << 2)]) << 0 | UInt32(block[block.startIndex + 1 + (3 << 2)]) << 8 | UInt32(block[block.startIndex + 2 + (3 << 2)]) << 16`

is there any way to get swift 3 support for CryptoSwift

**Comment by krzyzanowskim** [comment]
Swift 3 is supported since 0.5.3, so for a very long time. What you experience is compiler run on slow machine (probably CI), not the code. In that case you need this workaround: https://github.com/krzyzanowskim/CryptoSwift/issues/418#issuecomment-291589701

**Comment by appstute-prasad** [comment]
@krzyzanowskim hi, I am stuck at decrypting aes 128 string to json, I am receiving data in bytes but when i tried to convert it using JSONSerialization i got error "The data couldn’t be read because it isn't in correct format, what to do with this.
