### ISSUE TITLE
Base64 crashes when keys mismatch

### ISSUE THREAD

**Issue by ProgrammerMatt** [krzyzanowskim/CryptoSwift#247]
I am writing a small program that is supposed to take a variable key to encrypt and a variable key to decrypt. If the keys match, the encryption and decryption work fine. However, if I encrypt with say, "a", and decrypt with "b" as my keys, then the program crashes. Is this expected behavior? I was hoping I'd just get junk text.

**Comment by krzyzanowskim** [comment]
Hi,

It's hard to say if this is expected, can you please tell how comparing "a" and "b" cause crash and if it has roots in CryptoSwift codebase or somewhere else ?
