### ISSUE TITLE
Padding type problem in swift 3 branch

### ISSUE THREAD

**Issue by B-Gio-KGJ** [krzyzanowskim/CryptoSwift#248]
Hi,

I update my project for prepare support of swift 3.

for decrypt, i used this : 
`AES(key: key, iv: iv, blockMode:.CBC).decrypt(data!.arrayOfBytes(), padding: PKCS7())`

and with swift 3 version : 
`AES(key: key, iv: iv, blockMode: .CBC, padding: PKCS7).decrypt(data!.arrayOfBytes())`

but i got error : 

> Argument type 'PKCS7.type does not conform to expected type 'Padding'

**Comment by krzyzanowskim** [comment]
`PKCS()`

**Comment by carlosen14** [comment]
`try AES(key: key, iv: iv, blockMode:.CBC, padding: PKCS7()).encrypt(data!.bytes)`

**Comment by JayrajGohil** [comment]
I have issue with decrypt data. Following is my line:
let data = NSData(base64Encoded: self, options: NSData.Base64DecodingOptions(rawValue: 0))
let dec = try AES(key: key, iv: iv, blockMode:.CBC, padding: PKCS7()).decrypt(data!.bytes)

but I got error:
Argument type 'UnsafeRawPointer' does not conform to expected type 'Collection'

**Comment by krzyzanowskim** [comment]
Use Data, not NSData
