### ISSUE TITLE
How to decrypt an encrypted NSData

### ISSUE THREAD

**Issue by soheilbm** [krzyzanowskim/CryptoSwift#249]
I have a plist file which I encrypt it with opensll. Like below:
`openssl enc -aes-256-cbc -salt -in info.plist -out file.data -pass pass:RandomPass`

How can I use CryptoSwift inside my app to decrypt this file.data file?

I keep getting the error of "Block size and Initialization Vector must be the same length!"

**Comment by krzyzanowskim** [comment]
Do you pass Initialization Vector of size AES block size (AES.blockSize)?

**Comment by krzyzanowskim** [comment]
To unravel this mystery we have to know format of file build by OpenSSL.
That is - first 16 bytes is salt (IV). The data format is "OpenSSL__" + 8 random bytes + encrypted data.

if you get first 16 bytes as IV and everything else as actual message to decrypt, you'll be able to decrypt message encrypted by OpenSSL command.
