### ISSUE TITLE
[Linux] Build Fail

### ISSUE THREAD

**Issue by McClementine** [krzyzanowskim/CryptoSwift#251]
I thought I fixed it, was mistaken. When attempting to build, this error is thrown:

CSArrayType+Extensions.swift:29:16: error: use of unresolved identifier 'NSData'
        return NSData(bytes: bytesArray).base64EncodedStringWithOptions([])
               ^~~~~~
/Users/Jonathan/Desktop/Infinity/Packages/CryptoSwift-0.3.1/Sources/CryptoSwift/CSArrayType+Extensions.swift:35:33: error: use of unresolved identifier 'NSData'
        guard let decodedData = NSData(base64EncodedString: base64, options: []) else {
                                ^~~~~~
<unknown>:0: error: build had 1 command failures

**Comment by krzyzanowskim** [comment]
ok, now I see it. NSData is used by CSArrayType+Extensions.swift
It should be separated and moved to CSArrayType+Foundation.swift
