### ISSUE TITLE
CryptoSwift binary is invalid won't upload archive to app store

### ISSUE THREAD

**Issue by alexrmacleod** [krzyzanowskim/CryptoSwift#252]
At a loss here not sure what my next move should be. please advise, pictures are self explanatory. 

![screen shot 2016-04-28 at 8 52 50 pm](https://cloud.githubusercontent.com/assets/7895493/14886464/8c7d9060-0d83-11e6-9a86-3033c4880ed0.png)
![screen shot 2016-04-28 at 8 53 00 pm](https://cloud.githubusercontent.com/assets/7895493/14886471/90a69254-0d83-11e6-8d14-6c9b9aaaaaa7.png)

**Comment by krzyzanowskim** [comment]
looks like you build it incorrectly. How do you integrate framework?

**Comment by alexrmacleod** [comment]
I used carthage. Should I try update it, I imported the framework using a cartfile a month ago, but didn't specify the version. Appreciate the fast response. any ideas? 

![screen shot 2016-04-28 at 9 46 36 pm](https://cloud.githubusercontent.com/assets/7895493/14888013/c47285dc-0d8a-11e6-924a-9499ea141f25.png)

**Comment by krzyzanowskim** [comment]
i'm not carthage expert, deleting all caches should help you

**Comment by alexrmacleod** [comment]
Is there an iOS app in the apple app store running this cryptoSwift framework?

Thanks for the fast responses, will look into this tomorrow and see if I can find a fix.

**Comment by krzyzanowskim** [comment]
surely.... you can find it listed in let's say Fabric.app acknowledgements.

Your problem is Carthage related, search closed tickets for similar problem with Carthage.

**Comment by alexrmacleod** [comment]
Found solution! thanks for pointing out that the issue is carthage related.

[http://stackoverflow.com/questions/30547283/submit-to-app-store-issues/30866648#30866648](url)
