### ISSUE TITLE
Enhancement, not a bug - Creating HMAC

### ISSUE THREAD

**Issue by jpurple** [krzyzanowskim/CryptoSwift#255]
I need to add HMAC functionality to a Swift app which is otherwise pure swift. I have been trying to use CryptoSwift to achieve this. I ended up using a module.map and using CommonCrypto via that method instead of using CryptoSwift. I would still like to go back to using CryptoSwift.

If there is not HMAC functionality in CryptoSwift, I'd like to suggest it as a feature request. Or if it can provide HMAC functionality, how could I create a message digest with a message and a key that outputs a SHA1 string which I could use in an HMAC header? (As in the following line.)

`let hmacDigest = message.hmac(.SHA1, key: "ABC123")`

Thank you!
Jack

**Comment by krzyzanowskim** [comment]
https://github.com/krzyzanowskim/CryptoSwift#usage
```
let hmac: [UInt8] = try! Authenticator.HMAC(key: "F8265BC741499F294846815A46684", variant: .sha1).authenticate(message)
```

**Comment by jpurple** [comment]
Thank you very much @krzyzanowskim I have tried using the [specific part of the help about HMAC](https://github.com/krzyzanowskim/CryptoSwift#message-authenticators-1) such as:

`let hmac: [UInt8] = try! Authenticator.HMAC(key: key, variant: .sha256).authenticate(message)`

But the problem I have is that I am getting a nil return. For example:

```
let array: [UInt8] = Array("ABC123".utf8)
        let message : [UInt8] = Array("sample message".utf8)
        
        let hmac: [UInt8] = try! Authenticator.HMAC(key: array, variant: .sha1).authenticate(message)
        var str = String(bytes: hmac, encoding: NSUTF8StringEncoding)
        print("Output:")
        print(str)
```

The above code results in the following printed to the console
```
Output:
nil
```

**Comment by krzyzanowskim** [comment]
This is correct behaviour. `hmac` is not a string, therefore conversion to String is failing.

```swift
var str = String(bytes: hmac, encoding: NSUTF8StringEncoding)
```

**Comment by jpurple** [comment]
Adding .toHexString() was the solution

Thanks!
