### ISSUE TITLE
Crash when using PBKDF2 on 32bits iOS devices due to Int.max?

### ISSUE THREAD

**Issue by eiprol** [krzyzanowskim/CryptoSwift#257]
First of all, great work with CryptoSwift! I'm doing some quick tests with the library in order to learn a bit more about this topic while practicing with Swift, and I'm finding a constant crash when trying to use a password as a key with PBKDF2 on certain devices.

I can't try it on any physical device prior iPhone 5s, but it's crashing on the simulator on any device prior that one, which I guess could be related to 32 bit limitation.

It's crashing on line 37 of PBKDF2.Swift, when trying to convert a Double to Int:

`if keyLength > Int(((pow(2,32) as Double) - 1) * hLen) {
`
Correct me if I'm wrong, but Int limit should be something like 2^31 on 32bits, right?
Would truncating it work, or would it create a not secure/invalid key?

Console is saying:
```
(myDebugPrint: pow value is 1099511627520.0)
fatal error: floating point value cannot be converted to Int because it is greater than Int.max
```
Before trying anything, I wanted to check this to see whether is a bug or not.

Just for the record, I'm calling the PBKDF2 using a variation of your example code:
(but not sure if I need this do{}catch{} or just force a try! though)

        let password: [UInt8] = myPass.utf8.map {$0}
        let salt: [UInt8] = "nXac8Sdm1l".utf8.map {$0}
        do{
            let value: [UInt8] = try PKCS5.PBKDF2(password: password, salt: salt, iterations: 4096, hashVariant: .sha256).calculate()
                completion(key: value)
        }catch{
            print("Error hashpassword ");
            //completion(key: nil)
        }

**Comment by krzyzanowskim** [comment]
downcast it to Int is indeed not the best idea. Either explicit UInt64 or Double should do the job

**Comment by krzyzanowskim** [comment]
@eiprol btw. iPhone 5s is 64bit so Int is 64bit.... unless you test it on iPhone5

**Comment by ThilinaHewagama** [comment]
Hi, can you please fix this issue
