### ISSUE TITLE
Upgrading from 0.3.1 to 0.4.1 causes build problems

### ISSUE THREAD

**Issue by eselkin** [krzyzanowskim/CryptoSwift#260]
Using AES method in encrypt method on a String produces build problems.
setup: using cocoapod 1.0.0 
with line: pod 'CryptoSwift', '0.4.1'
builds find with line: pod 'CryptoSwift', '0.3.1'
Errors though seem to be linker errors lacking symbols for architecture: let encrypted = try! "word".encrypt(AES(key: keyEnc, iv: ivEnc, blockMode: .CBC))

**Comment by krzyzanowskim** [comment]
linker errors suggests: delete derived data and rebuild project
