### ISSUE TITLE
AES.init throws when iv is nil (v0.4.1)

### ISSUE THREAD

**Issue by p2** [krzyzanowskim/CryptoSwift#261]
In version 0.4.1, `AES.init()` throws when `iv` is nil and is automatically initialized. This is because the check is performed against the method-local `iv` parameter instead of against `self.iv` [here](https://github.com/krzyzanowskim/CryptoSwift/blob/master/Sources/CryptoSwift/AES.swift#L105).

**Comment by krzyzanowskim** [comment]
Good find! thanks. Willing to prepare PR? (develop branch)

I really hate hidden var shadowing in Swift.

**Comment by p2** [comment]
Yes, that shadowing is definitely something to get used to coming from Obj-C!

PR sent. 👍🏼
