### ISSUE TITLE
import problem

### ISSUE THREAD

**Issue by pablocolson** [krzyzanowskim/CryptoSwift#263]
Hi, I do everything to install Crypto Swift but I can't make it work, help me please.
<img width="593" alt="screen shot 2016-05-25 at 14 48 47" src="https://cloud.githubusercontent.com/assets/18679487/15540474/d8b375e4-2287-11e6-9dd6-af118a4620bb.png">
<img width="469" alt="screen shot 2016-05-25 at 14 48 21" src="https://cloud.githubusercontent.com/assets/18679487/15540477/d8ffb260-2287-11e6-9370-25d7c5f7d494.png">
<img width="668" alt="screen shot 2016-05-25 at 14 48 08" src="https://cloud.githubusercontent.com/assets/18679487/15540478/d902e638-2287-11e6-8b28-261a30b6ba45.png">

**Comment by krzyzanowskim** [comment]
¯\_(ツ)_/¯
Xcode should do the job

**Comment by pablocolson** [comment]
When I import CryptoSwift I got this error :(
<img width="680" alt="screen shot 2016-05-25 at 15 53 47" src="https://cloud.githubusercontent.com/assets/18679487/15542398/e4a0aeb8-2290-11e6-8dd8-7c48ede1c1f8.png">

**Comment by krzyzanowskim** [comment]
yea, but I looks as it should work for you. Try CocoaPods, Xcode is easy to make a mistake with Xcode project.

**Comment by pablocolson** [comment]
Ok thanks I will try later ;)

**Comment by pablocolson** [comment]
So I tried the Pod method and still the same problem I do as they say on the pod site and style with the No such module thing, this is my configuration and my pod file

<img width="239" alt="screen shot 2016-05-25 at 23 44 32" src="https://cloud.githubusercontent.com/assets/18679487/15557322/af0e01c8-22d2-11e6-9b0e-94d6e114caea.png">
<img width="1166" alt="screen shot 2016-05-25 at 23 43 06" src="https://cloud.githubusercontent.com/assets/18679487/15557298/966c917a-22d2-11e6-8bb6-b2df2b897ce8.png">

**Comment by pablocolson** [comment]
I solved my problem by using Carthage thanks :)
