### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by maksTheAwesome** [krzyzanowskim/CryptoSwift#265]
Hello. First of all thank you for your library. I've tried it with my app and it works perfect locally. But when I try to use it with my back end API which uses [(CryptoJS)](https://www.npmjs.com/package/node-cryptojs-aes) I cannot get API response decrypted. Please help.

Here is the sample of server response:

`
{\"ct\":\"KH6YPPC4SOh+olyyoKHlOKSEUN++sH/s/oZuGQ1wiWuHwQGE/vXpeHTPCmN0emKMqt0XBvKAmxfciTONowGOMT1C1JYCtSiBqHJXPYLiPk9OH2U6b4XA4BhZE9C+VPJSbY/XbNIJdvbShJmxAeaOoBOIxycFWleiIpjKUre++FaR5mBmEFE96WLMwxnhnC0WdkkKJsF9VkGojH788yI+wzX9ptEgDmCtdKFLgM7yqZImTMIX7YGs3K4qzlmGjs7qQMKssCQuMvFBiX1uA7zRRjdrRYI8mR0qLmgOgYnOgEF8d94CzdJwYNCuOBdHQlSZZbrYT7i4MqSdC1Q2TCUhZNS7M91S4iE2E4JHD013+WfbIlctN1NU8ldPz94PN7CcNkhgTJSNwNmpdz+9rlMqkqCIG6NcctA4+O8rqgXkG6Gu7Z+Mg6QFWs+kcQTEW65Xxfi6n0pC6iqfTvsFBEddZYccyT+vW3yJRzskPQxj203TE+IcWdoZMoJkEmAYarkaMzLl5nIGuSCMwQ99uSGOUMLdiQeMzy1N4yhOD0QBxEGg/TCl/fdAwbsdTs2rYxbiDM/ZpW6xJbkHabG6zlgGFxEhff1jU6biORf0TrenVYzPO5LtEJFYEjAk8Y4eaGk0J1Ig6qfqa2hbZMRiH6aLkFhJxOOSc3VRoXB/06jWJQq4oLKCxbgaqalu7KfIuwnAk91UeL5BvjrA1eIzcwcfVKb2nVoF/ujoIkPOszmpkqejiO1/lfTAt4vnAsFLmYXdpGzYfT+//DVsYW1IRY2x5VSpCI6tLpQ1aJxupSJ+XGr3ipfc/R8+sfeXEPo3Ec8+t2T+v2KX/VP8H9Clf+idgOHaMqlKvxzTM9sjGTslGlUf10nmlFARRVro6WqwW/ULidtPwImJdbBVv+SCi+t92j0FBX9VrYPGH4gtdUvV3h72oADxMkOgAHwtdTCewrRA+f619y2O7mkHQYYI443ODHTGtT2qDxWQ+0wYNkhvI23FkIFgneUCQfTbF7EPPdXl7gUAk4Vt9gaDdz2esZi74zPMP/V3LaFxAGapryOAUmPHTVcRy2rcc8Yxj0Ad254RTEb/udTJ8jOYDd0qOcL4EICCyV4kxAlWEd3ef97ROMY/GCxxI6y+69ULQ5oXP9wpvlSaVSzibvfsXEtD0Rk5LRd8gDUaC1cYz4Zcdstl63J57H9QGRybrAcHGTndNc2R2UdWHOmf1I2XQ2HSiiW+2XMe3iK+BnT3rnY4gkKobLOFVrQmogCf8ifnA3LMK2DyFesyjpnv+g4lu5roV6Tx7ns1RqmIznpD7WtvyGYDjesYjhRHCY/5GqZnrsN5s+nXiurcqybsYVN6zV+wYpfaian7OTyOnKF+hdRP3uICNIQrXn8PIydJmh/n32mPqFSgghmNCm4oHQ5yurKOByx6zxBErfHKKu56YJQTO17YpsIBse21qDqoKxE4QvcynVIQuG9uEd2eRViJrWamXc/gWqqyFUanSdVT3m0Rw1bvezLEcSiLLkiYUbKUsXJEseVHfdNWONyeLopXgl7CM+HBWTS72sdH+vi53Vk9S2X4vR8ucD5yQLJthis+u/1XqGTiTrKO7Oh0E/pxc3/tSHYxrcP98l9dyhyR0vUes+fU2zkuVXSOlBMowgeKSh5iNLnsVahzjOILGkHsguCkyJyGI0b2EV0JF3h/kyy9g+k9q7o2Y5LMGHyraXALtJ80Hs5C+m2c2EI8L3JomEC1J5WA45L9/i8oFB3cvOg1UfHPpGy00WdqxuHQIxkLo7+gINkFhU5xIufkbDRQUKVQnvpaZrKHzgq+DrC9YgKyVweM/3pPcaAViXJbOZHUeAFSHo/tGkAwAzETO5lSmGN5WV/IOW1Mce/VuNoEZLVfN1ZKwJvduMWQ/tlinstXzKFfFu1/7IJAs86dKJTs/aVgCfGtsszlI+GnsBXdyceYsyMBlmJHp4Si8HwZiYEmGKOw6KEapWFvY0aY+HfGfg0atlrY1MxZflx/A8o0z1t6KYTC6/exqF6rFRNP73ISr/miDTJHXKNsluznr2qqwIxlcPBqSO/jDch6GuB4ucslYHNP4ktL5n0Lk6Z4PZz1ML8Ol7uUuzbejSgj5TwkmQZMN4f6GUMtRU2M0w672pBXCQYFqPk3RViFXMbfqhuYsWeDAjc9OHWOQMNyRfe3vfE+pr0wsboYGrHYijo4xgricAf34Py8UaLiJJLcmgcCnfgU1dl1dbYXiewie/rAd0ux66kS0/2NMW1+6u34LQgncYWamVw+keRTVFh9SeBtFUfkHBzCtAJDf84hXNIzhU9hlMsDUH9r2H1u6d5PZzogTO3IjNBlta13toNHrFBh4+8SUxHIsiPD4vcYU39d7h8qbvYVyW09ImJrlNrq2t3wSwfpjNX2fbdcJS+JeJO/SQRyq5/dxVkTVP0QmwGt/6pl0fMvqAudVjWoYo2luWAsqiqtEjLIP6Syc1nOwkrpgGUTh7Y5inorxeuBTs4A+rauUSzJgR00KK6UKIQJXvkTCHs1TpOT+OxtdY3uCoiH+PNEZ5W/Lbm7+oV7cwFkLKLsSG3Bq6w32AkTEvt6sMDsB2AcDGvfc3beNEFzsncovyaPRY0l3oE+5m6dKWnyuAzGP1sG96JPWkC14CqVZ8eygj2qOSuoYXc+ByRsu0M74c9UjmbcA1k3uHBgfnNVuSaYXil7drXO5o8RABE1W3o8Hzdqw3DBvKOaK+SbNMMB64qUzZkvckqpGnnqyveyIorEj4eVfTzw3oUeTnWmpDjYSKH9NTaGyAGRhW/DiMHMtcr/KQBftDeyTbuOMSgHD/EVVyXE8u7+yFfpPk0SZLgPise+pRTYSIqsHd26+lhT8zniEDtnkIDKxORARKELbARafPW6fRcjTV3euSZGjhWfW6HHZPAYsPDg8XQdRpNlaou/g07Hgsgn3qirPk4dCKke4V31+A/g3unQSMZfAipoJVQuaDoM8swMK+d9hZTzD9otmerbRBITVBhTZYWGGr78r39K30P3lqWTow1Fi9OqVdhYEwc=\",\"iv\":\"06dc0a3e19b05eae83c50136574ba6f8\",\"s\":\"436e016c51d76ed8\"}"}
`

Here is the key:
`let key = "8aa1ec1e6948b481d1ee450c94ffb2edc774877325df4d05aca2e5827497ed33"`

Code I use:
`
let aes = try! AES(key: key, iv: "06dc0a3e19b05eae83c50136574ba6f8")
        //let base64String = try! "my secret string".encrypt(AES(key: key, iv: "0123456789012345")).toBase64()
        do {
            let decrypted = try encrypted.decryptBase64ToString(aes)
            print("decrypted = \(decrypted)")
        } catch {
            print("error = \(error)")
        }
`
I've noticed that there is also "s" parameter aka "salt" sent by server that is not used by the library. Did I miss something?

expected result:

`
{"_id":"5687ad129b65920a00b56a9b","type":"user","created":"2016-01-02T10:57:22.851Z","uuid":"d9df3412cee97ec1d0a8c547f73e4bb6","secret":"307a14f6ffc667c7941e6263edca4149","profile":{"lastname":"mmm","gender":"Male","firstname":"mmm","email":"mmm@mmm.mmm","dob":"1993-10-31T00:00:00.000+0200"},"avatar":{"large":"https://graph.facebook.com/v2.4/1122734811071660/picture?width=120&height=120"},"location":{"country":{"filename":"greece","code":"GR","continent":"Europe","name":"Greece"},"state":{"id":"Aitolia kai Akarnania","country":"GR","name":"Aitolia kai Akarnania"}},"auth":{"facebook":{"userID":"1122734811071660"}},"notifications":{"new_window":{"sms":false,"email":true,"push":false},"new_live":{"sms":false,"email":true,"push":false},"new_premium":{"sms":true,"email":true,"push":false},"reminder":{"sms":true,"email":true,"push":false},"new_arcade":{"sms":true,"email":true,"push":false},"ranking":{"sms":false,"email":true,"push":false}},"metas":{},"stats":{"game":{"time":{"total":1084452,"maze":{"mean":180436,"stdev":423,"min":180013,"max":180859,"sum":360872},"wordsearch":{"mean":111639.5,"stdev":68379.5,"min":43260,"max":180019,"sum":223279},"trivia":{"mean":22410,"stdev":0,"min":22410,"max":22410,"sum":22410},"brokenword":{"mean":40399,"stdev":0,"min":40399,"max":40399,"sum":40399},"imagelabel":{"mean":38349.5,"stdev":22808.5,"min":15541,"max":61158,"sum":76699},"scramble":{"mean":180174,"stdev":0,"min":180174,"max":180174,"sum":180174},"sort":{"mean":180619,"stdev":0,"min":180619,"max":180619,"sum":180619}},"score":{"total":4500,"maze":{"mean":null,"stdev":null,"min":null,"max":null,"sum":0},"wordsearch":{"mean":1000,"stdev":0,"min":1000,"max":1000,"sum":1000},"trivia":{"mean":800,"stdev":0,"min":800,"max":800,"sum":800},"brokenword":{"mean":800,"stdev":0,"min":800,"max":800,"sum":800},"imagelabel":{"mean":950,"stdev":50,"min":900,"max":1000,"sum":1900},"scramble":{"mean":null,"stdev":null,"min":null,"max":null,"sum":0},"sort":{"mean":null,"stdev":null,"min":null,"max":null,"sum":0}}},"positions":{"position":{"avg":0}},"played":{"window":1,"total":232,"live":120,"arcade":101,"live-duplicate":10}},"credits":487,"utm":"false","perms":{"root":true},"undefined":null,"value":{"credits":520,"usd":52,"bought":3},"premium":true}
`

**Comment by krzyzanowskim** [comment]
`06dc0a3e19b05eae83c50136574ba6f8` is not what you think it is. In JavaScript, everything is String and this lead to this confusion.

`06dc0a3e19b05eae83c50136574ba6f8` is string representation of 16 bytes: `[0x06,0xdc,0x0a,0x3e,0x19,0xb0,0x5e,0xae,0x83,0xc5,0x01,0x36,0x57,0x4b,0xa6,0xf8]`. Passing string as IV or KEY means something very different than passing bytes encoded as string that represent bytes in hex notation.

What you need is to build valid KEY and IV values to decrypt data out of your input = you have to decode it to bytes first.

When it comes to `s`... it should be documented somewhere how this salt is used in output data as it's not part of the encryption itself (not part of the transformations). This forms some "protocol". Typically salt value is added to the resulting data (ref: https://github.com/krzyzanowskim/CryptoSwift/issues/249). From what I read, this module is trying to mimic OpenSSL format of salt - yet this value is optional. It's up to you to handle this part.

**Comment by maksTheAwesome** [comment]
Thank you for the fast reply.

I've changed my code to:

`
let key = "8aa1ec1e6948b481d1ee450c94ffb2edc774877325df4d05aca2e5827497ed33"
        var byteArray = [UInt8]()
        for char in key.utf8 {
            byteArray.append(char)
        }
        
        let iv = "06dc0a3e19b05eae83c50136574ba6f8"
        var ivbyteArray = [UInt8]()
        for char in iv.utf8 {
            ivbyteArray.append(char)
        }
        
        
        let aes = try! AES(key: byteArray, iv: ivbyteArray)
        do {
            let decrypted = try encrypted.decryptBase64ToString(aes)
            print("decrypted = \(decrypted)")
        } catch {
            print("error = \(error)")
        }
`

and get error = BlockSizeExceeded

I had to change block size to 32 to match iv.count
`public static let blockSize:Int = 32`

**Comment by krzyzanowskim** [comment]
Unfortunately, what you're doing is transforming UTF8 ASCII to bytes, it's not what you need. You need decode hex to byte, see https://wofford-ecs.org/DataAndVisualization/HexadecimalRepresentation/ (random link ;)

```swift
// "06dc0a3e19b05eae83c50136574ba6f8"
let iv = [0x06,0xdc,0x0a,0x3e,0x19,0xb0,0x5e,0xae,0x83,0xc5,0x01,0x36,0x57,0x4b,0xa6,0xf8] as [UInt8]
let key = [0x30,0x7a,0x14,0xf6,0xff,0xc6,0x67,0xc7,0x94,0x1e,0x62,0x63,0xed,0xca,0x41,0x49] as [UInt8]
...
```

**Comment by maksTheAwesome** [comment]
Thank you for your patience. Can you please take a look and say if this is what i suppose to do:

`func decrypt() {
        var encrypted = "TwQY1XIhFW+SHG9L8ONyUAH8XWbgY7Yhef/ibb6jKkMX+nDq2U78553/0hXlXvKnp6XsAGc0Zg+2AVkCcsHLKrJRsIlvGZmdckLParBZIa3Z2DRozegrKrctin2fK4pkn0xiidnbeth0uMdiNUrdFXoEIRQLfFobgqDz5VIRDw9tvhL3Ftz169ooEg1duTag0BQ5Qu4TP1K4VsTD78KWr4C2A4qYpj1bAQRJrsabDAhhbVjRGIoSy5D30H10e9RE9IEGDwSFuoXW0+2n5NhFSWpuWADV45t6FuNZ5Ptc/l1NjvPTi2CZGhiW4Vl8pX3HuzPeFpJE9UUNuPr2E8/vhqt8Hx+JjT0LOoszHCUJ4eWv2l6TEAwxk5I1MNz7XMKVrAYUt7jyu2Ob8iTE+zJAatIOkHhRI1HeU9wMevEs6sdP2jDQflm6Rb2v3vNhtRQwgqlCG+RNpSGG0zQUMtOKO6mrN/vJadMtPYjbgP1o5IcKrR5vvsvYI3aEJwrjkitpPY/hVK8OA8OvMZjuWsNcPeJFlww8adEgAWrBzZYGusZsooc8/O5obJVspzqrOHtFfAo8sBms2ovJEs5wgyCBEW33I1Ka8D1EJG+ncyR7h/rOjwpy8ynbWc0qBN9QKBNFRdxLqVRR8g6cHRrEzGvVPlx8AyPmfSAhzf/KppAX0YPmF1v29rjWKBCWOrSlISA7UulkZzHVdrGX3pEL+MPI2bQB9MyAjHHRKjAT2t6k8FFxKzvmckRULllm/K9Ax3DUqnmUbJ6sChBlG+Cl3VFEQZZwJ1Mjw09CKLGFCOi06bEBKp9apqBRkrYBosUnLAM6cnM7/tqItgD//Fx88bGqNL0wc8gygKsT+nVxc+VwcNis88pDcZht4Ey5eE3Wy8loKcEUZoC7T8//Qp72tmUrFZPULzn45lQMZ2Z83Fd115JoNIV/HjEOQgx88OgtPcs6Q3MP7KD5xxeKtQ6hoTT5WFzxetdGSeZffIZvRZHts05hBtjvND5N10lyISFIegD9kTbtlkSO2PQIDEmt3Xi2M/jP9+Tz9kbKUs2VqjB8hfh27f8/MrLNHJbOqGJmHBSwVQ9TvzTfeKbb090Hg3AQz3KbzlmFcoj6KcO1eHAKhixgOJfKX93NII2mfjfbSUgCtR/Sl/UEsHjYquQBlsGaQRSqr7dpgo55/aT055y+4V1LxLkOdTq6gnxPkzYUSmlTlsmxgmsyGKbWolvyBCz8NA7PnNLR3Ym/EHGucFMLhtDUAq07HItAhSZ/b6F6zsyMbEro8FbRK8DS9GI/3/KmhXgQ+0LdeCT/F2hAB/YnCnsjHBiLoMX+28vAhBZbEKkZUK94UxBVXuURs573s6j6yZMCBNb2cc2YFlw4LanzXi8jT8mRGZhBXsdqUQeZ58k0jNdYZPljM0m7Mqj7I5HjJiuyq3wTKdEFFIh3zoMNVmr9PGiwBq9nGjwuB3jGLYnJx1NX0xt+X8HnFytD7rkHImi8ljC4b+Fcv7K4saKx3BZCSq54SAzfrYQDOkbEG0Y+CxxXoqjiMMk9knJbyFcYYQ+xgtdAGyd+3RUK3xLhjozL8jioWhvhtse/MvLD8B8jbS6FfJDeB1ZDddfbHRBKdIEpvnhU/fUOdB+1kM59cMoZe0o9S22bzAS8pzv9Fv0OEeSQDsSZukzR4VgrLwj5z/eYfRwJOdqfkwEkL3EWJ3pAESTnVc8Ew1fOGTAnrmo9GYtIuoOWeeP9kvJef0YfTMTJ6jX/jzjsqpsz6YEVT4eGwES3ky817WfMya2R/8iVlrL5be5axzw7JIkjFhZTnsnLts58DCuoVqmTnGRDbAXIPxCDfqdw4J9rx03cnssuvf40rySgx7jUWxolz/Hs/u18mvy2e7+MnuO7hlnAmhfLGlrlt7uF9fnByZHgBaTfAWUg9WY05wmBN3n2ghbmqMACWFxvmZvTxoG8DiJHoBW6suV/3iQbKHpIBAFpP9mgeG9uoccnreH0tC4wDbQyCbFBeDewYF+2utopXHDqTRSzamV4sh0IigRU89LkxCqDKUKLebKqsa9Gd9FiN0Moa3H/FcpPChdcYcSVxOVDp6AKMnu6R9eeWUvYBDKE8liWkLsvB7GSweRi3m4l3DEar7HhO2NQBmzQ03RRgg5+BC4UtaSDHwU0BVV+Zh9KjTk2As1XjCoeUsYOS6LUa4DKx2UHKpe5jHb6ZcAmp8ZPfJy4TuwlzKSzuIBI92z3fFEeYTacxd9XMOR2jGN2RZAUMBDGQwXq0v3hH6TTDguAeLTB/eWGNNXodGtRfUI624afI6NZ2BrT5vHDMCKHBf/arw8NOW9h2Ek8s0vJq0A1435C30G0WQC73JrKw32jaYO8IvG0vnsZWF385sDaX3JNJ0L8l4BtQH8z/cUaiqUlAmtIbQ2opaNpniNZROe+z5/REO0XmFtit7vdDUq1HpRhTY/n3EoWe1ChhLbDVoM6TOXH2D51f40eJ0/Qs+Ch4dbrqYtYxEhkLJB+Ha+7ePSJqmUDSRQHXOGUKCnUh/vm425ZpuxIgE4E+KdslAuWTx1u1/WagVywjyj12OeZ84xsXVf0kJs1nCFvnkhb3wEjJrbSRbBvcBkP4zZsMTzcgFrzugqhtZ2LhZFtdUaQYa/tXjAF8DBdq+hlF+8RPul1riAczQoqDQkonYMH2WA9utWLWTYmPVJODLPEO5mL+yXqX9iCh3YycR8ssJgCkBmeN+yLydUoWLDfIC8NGnlcprpDqXrM0aDTwxADiBG4yWIgAxoZXCQEKIUxK0NuOssW9Z6tCB6yxDPzJdRqeOC2I2ky82YsIrLhPutspqycPAf4B8gbsUBcIqtflYhebiz50T3gk4gNS/2HNShGdzjPhjBvqk+GzETAu9t0JmbWBkuHq07r0lvM8zn474YHvzYIXOBUuZJKpGWPK+fvbEP1qXOTP4EkBSdgU0pcNO/Y7D3g4R26qTWmyWvnFKFAAGjXawwxKqBcdSJZxNkOgg/uekCAhRSwUq9qaeJHU1dl+M9OOwa7iGwlXtUPht0+1FGbN14="
        
        let key = "8aa1ec1e6948b481d1ee450c94ffb2edc774877325df4d05aca2e5827497ed33"
        let iv = "d6d6bd8ee407bc25a7b23d8d36b7bce9"
        
        let keyChars = Array(key.characters)
        let keyBytes = 0.stride(to: keyChars.count, by: 2).map {
            UInt8(String(keyChars[$0 ..< $0+2]), radix: 16) ?? 0
        }
        
        let ivChars = Array(iv.characters)
        let ivBytes = 0.stride(to: ivChars.count, by: 2).map {
            UInt8(String(ivChars[$0 ..< $0+2]), radix: 16) ?? 0
        }
        
        //let json = encrypted.json().stringByReplacingOccurrencesOfString("/", withString: "")
        let aes = try! AES(key: keyBytes, iv: ivBytes)
        do {
            let decrypted = try encrypted.decryptBase64ToString(aes)
            print("decrypted = \(decrypted)")
        } catch {
            print("error = \(error)")
        }
    }`

**Comment by krzyzanowskim** [comment]
```swift
let ivBytes = [0x06,0xdc,0x0a,0x3e,0x19,0xb0,0x5e,0xae,0x83,0xc5,0x01,0x36,0x57,0x4b,0xa6,0xf8] as [UInt8]
let keyBytes = [0x30,0x7a,0x14,0xf6,0xff,0xc6,0x67,0xc7,0x94,0x1e,0x62,0x63,0xed,0xca,0x41,0x49] as [UInt8]

//let json = encrypted.json().stringByReplacingOccurrencesOfString("/", withString: "")
    let aes = try! AES(key: keyBytes, iv: ivBytes)
    do {
        let decrypted = try encrypted.decryptBase64ToString(aes)
        print("decrypted = \(decrypted)")
    } catch {
        print("error = \(error)")
    }
```

**Comment by maksTheAwesome** [comment]
Sorry to bother you again but I tried this but it does not seem working for me. The result I get with your code sample is error = Decrypt.

**Comment by maksTheAwesome** [comment]
Can you please take a look at my sample project: https://github.com/maksTheAwesome/decryptorSample

I would not bother you but I'm banging my head of here.

**Comment by krzyzanowskim** [comment]
@maksTheAwesome It's not CryptoSwift problem, nor CommonCrypto (you can't decrypt it with CommonCrypto, can you?). Code with CryptoJS is failing too (in your sample project). It looks like unexpected input data format.

**Comment by maksTheAwesome** [comment]
Nope, I can't decrypt with CommonCrypto. Apparently other ways do not work for me either. In fact it is first time I am trying to figure out how all this staff works at all. I never thought that problem is in any of those libraries. A just was looking for a quick decision to decrypt a server response. 

I thought maybe you could change the code in that sample project to make work one of those methods actually work? Off course if that is not too much trouble for you. 

Thank you for your time a lot, anyway.
