### ISSUE TITLE
DES

### ISSUE THREAD

**Issue by JonathanDowning** [krzyzanowskim/CryptoSwift#266]
I'm quite keen to have a go at implementing the Data Encryption Standard for CryptoSwift. Is this something you'd be interested in merging if I were to do this?
Jon :)

**Comment by krzyzanowskim** [comment]
Surely, it may take some time though. Since I'm moving development to swift3 branch now you better start there and it's good to merge incrementally. Contact me directly with the plan so we could discuss that too.

**Comment by bottydim** [comment]
@JonathanDowning Hey, Jonathan have you made any progress in implementing DES. My team has encountered the same roadblock and we are willing to contribute or build the feature ourselves.

**Comment by krzyzanowskim** [comment]
@bottydim If you're interested in sponsoring this work, I can put in on my priority list

**Comment by ajaytothenew** [comment]
@krzyzanowskim  @bottydim Just wanted to know, if this library is able to support for DES Encryption & Decryption OR any other standard way to manage for the same.

**Comment by krzyzanowskim** [comment]
The library is able, but it's not implemented. Some preliminary work has been done locally, though.
You can use AES if that suits you.

**Comment by ajaytothenew** [comment]
Thanks.... but for me its DES as per the requirement. Hope soon we will have this encryption available for community developer.

**Comment by bottydim** [comment]
We used CommonCrypto with bridging headers, works perfectly
