### ISSUE TITLE
Tons of errors in CryptoSwift while using Xcode v8.0 beta

### ISSUE THREAD

**Issue by tariq235** [krzyzanowskim/CryptoSwift#267]
<img width="258" alt="screen shot 2016-06-14 at 6 58 06 am" src="https://cloud.githubusercontent.com/assets/349211/16045485/79c5f180-31fd-11e6-9b59-7af7ae453286.png">
Please help me with the immediate workaround for this issue because I have to use my code in wwdc labs.

**Comment by krzyzanowskim** [comment]
branch https://github.com/krzyzanowskim/CryptoSwift#swift-3

**Comment by tariq235** [comment]
@krzyzanowskim  can you please help me to install swift3 ?
I am using podfile 
`pod 'CryptoSwift', '0.4.1' `

How should i install swift3 branch ?

**Comment by krzyzanowskim** [comment]
```
pod 'CryptoSwift', :git => 'https://github.com/krzyzanowskim/CryptoSwift', :branch => 'swift3'
```


https://guides.cocoapods.org/using/the-podfile.html

**Comment by MayurKala0903** [comment]
I am not able to get the Swift 3 supported branch, please help me to get this.

**Comment by krzyzanowskim** [comment]
master branch is Swift3
