### ISSUE TITLE
Cryptors.swift Errors

### ISSUE THREAD

**Issue by jmg129** [krzyzanowskim/CryptoSwift#268]
Hi there, hope all is well. 

I've been trying to get this library to work with my project for a few days now and haven't had much luck. I imported the the library through Cocoapods. Upon building, I get 3 errors in the Cryptors.swift file:

1)     associatedtype EncryptorType: UpdatableCryptor - Expected Declaration
2)      func makeEncryptor() -> EncryptorType - Use of Undeclared Type
3)     func makeDecryptor() -> DecryptorType - Use of Undeclared Type

**Comment by krzyzanowskim** [comment]
share the project

**Comment by jmg129** [comment]
Well it is happening during build, even if the project does not import the library, it still throwing the error.

**Comment by krzyzanowskim** [comment]
that's why I asked you to share the project to reproduce it locally. It may be anything related to Xcode and Cocoapods.

**Comment by kirankonni** [comment]
Please use Xcode 7.3 to build

**Comment by krzyzanowskim** [comment]
@kirankonni depends on branch. it may be everything that's why I'd need project to reproduce the issue.

**Comment by jmg129** [comment]
[CSTest.zip](https://github.com/krzyzanowskim/CryptoSwift/files/320818/CSTest.zip)
Project attached.

**Comment by jmg129** [comment]
After updating xcode to version 7.3, it is working.

**Comment by jmg129** [comment]
Thank you krzyzanowskim and kirankonni.
