### ISSUE TITLE
error: A cryptographic verification failure has occurred.

### ISSUE THREAD

**Issue by domahutch** [krzyzanowskim/CryptoSwift#269]
I am getting this error when I try and build my Xcode project.

The rest of the error is 

`CodeSign` /Users/____/Library/Developer/Xcode/DerivedData/SIHT_2-fdyilqphibavqpgsffcfthbedlbf/Build/Products/Debug-iphoneos/CryptoSwift.framework
    cd "/Users/____/Documents/Sports-Club-Communication/SIHT 2/CryptoSwift"
    export CODESIGN_ALLOCATE=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    
Signing Identity:     "iPhone Developer: _________@gmail.com (2679659C75)"

    /usr/bin/codesign --force --sign 208BB30C64C3A289D81375FC52F057523031E6A1 --timestamp=none /Users/______/Library/Developer/Xcode/DerivedData/SIHT_2-fdyilqphibavqpgsffcfthbedlbf/Build/Products/Debug-iphoneos/CryptoSwift.framework`

**Comment by krzyzanowskim** [comment]
I'd love to help you but I have no idea since this is Xcode thing, isn't it? It's harder that anything in the world ;) Look at "Code signing identity" and play with it.

**Comment by krzyzanowskim** [comment]
btw. what target is it?
The setting is fragile, let me know if you figure out the setting that work for you, and what is your setup. You may want to look here: https://github.com/krzyzanowskim/CryptoSwift/pull/125
