### ISSUE TITLE
How To: Create CryptoSwift.framework

### ISSUE THREAD

**Issue by mgsotelo** [krzyzanowskim/CryptoSwift#27]
Could you please make a screencast on how to create CryptoSwift.framework and add it to a swift game project? I've been stuck for hours trying to figure out how to solve this issue. Thanks in advance :+1:

**Comment by bradbernard** [comment]
Second this. Every time I add it to my git project as sub module then add the xcodeproj file and then add embedded binary. I commit and push after doing that. But when someone clones the repo, it always says can't compile objective c module crypto swift. So I have to redo the steps above every time I clone the repo. Fixes?

**Comment by krzyzanowskim** [comment]
Cocoapods is ultimate solution: http://vimeo.com/117975336

**Comment by krzyzanowskim** [comment]
I'll try record similar one for manual installation anyway. Suggestion are welcome. If you think that installation description should be extended, please give me a hind/send me pull request with better one.

**Comment by bradbernard** [comment]
I used cocoa pods and it messed up my project. I have the facebook sdk included in my project and when I used cpods it would not recognize facebook. Is there no way for git/Xcode to be able to work together so I don't have to re add the crypto swift project file every time and re add the embedded binaries?

**Comment by bradbernard** [comment]
The installation works fine for me, I just can't get it to work when I push it to github and then clone I have to redo the install. No problem with install instructions just can't get it to work straight from clone.

**Comment by krzyzanowskim** [comment]
how about that ? is it still valid question?

**Comment by jagreenwood** [comment]
@krzyzanowskim yes I think this question is still valid. I'd prefer to consume this project as a framework.

**Comment by krzyzanowskim** [comment]
I read once again you problem here... and I think I don't understand it
- you clone the CryptoSwift
- then you setup your project by adding CryptoSwift as subproject etc...

and what then? re-downloading CryptoSwift project don't affect you project setup so you should't have to redo any setup.

**Comment by jagreenwood** [comment]
While including the project will absolutely work, it isn't ideal for many people.  I believe one of Apple's intentions for dynamic frameworks is to allow for distribution of just the framework to be consumed by projects.

The problem is Xcode doesn't build the framework to include all architecture slices.  #67 adds an aggregate target with a build script phase which does this.
