### ISSUE TITLE
RFC 2898 ignores dkLen

### ISSUE THREAD

**Issue by PanosSakkos** [krzyzanowskim/CryptoSwift#270]
Hi.

Seems like the PBKDF2 implementation is ignoring the keyLen value.

For example the call:

let d = try! PKCS5.PBKDF2(password: password, salt: salt, iterations: c, keyLength: dkLen, variant: .sha256).calculate().tohexString()

Will return a value that has 64 characters, no matter what the value of dkLen is 😟 

The RFC says

> 
>      4. Concatenate the blocks and extract the first dkLen octets to
>         produce a derived key DK:
>
>                   DK = T_1 || T_2 ||  ...  || T_l<0..r-1>

**Comment by krzyzanowskim** [comment]
true. thanks! 👍 
fix on its way.

**Comment by krzyzanowskim** [comment]
@PanosSakkos pls verify from branch `develop` and let me know.

**Comment by PanosSakkos** [comment]
Isn't it better to write a unit test excercising the case? 😄

**Comment by krzyzanowskim** [comment]
I did :) this is courtesy for another pair of eyes.
