### ISSUE TITLE
Swift 2.2 support

### ISSUE THREAD

**Issue by fmaxx** [krzyzanowskim/CryptoSwift#271]
Hello!
_pod 'CryptoSwift', :git => "https://github.com/krzyzanowskim/CryptoSwift", :branch => "swift21"_

I'm getting:
```
Maxims-MacBook-Pro:PayKickstarter maximfirsov$ pod install
Analyzing dependencies
Pre-downloading: `CryptoSwift` from `https://github.com/krzyzanowskim/CryptoSwift`, branch `swift21`
[!] Unable to find a specification for 'CryptoSwift'.

[!] Unable to load a podspec from `CryptoSwift.podspec`, skipping:

Pod::DSLError
```

**Comment by krzyzanowskim** [comment]
please ask Cocoapods guys first. podspec is there.

**Comment by krzyzanowskim** [comment]
you can try use tag "0.2.3" too. of specify that version, that was the last version for Swift 2.1

**Comment by krzyzanowskim** [comment]
Swift 2.2 is on master branch as this is current version of Swift. What is the issue?

**Comment by fmaxx** [comment]
@krzyzanowskim  sorry, my mistake, nice job!
Please close the issue
