### ISSUE TITLE
Installation over CocoaPods

### ISSUE THREAD

**Issue by karlybirdkarly** [krzyzanowskim/CryptoSwift#272]
Hi, I have this error after I installed the pod. 
This is what I have if I try submodule too. 
![screen shot 2016-06-20 at 10 34 12 am](https://cloud.githubusercontent.com/assets/12427239/16198125/c50a27ae-36d2-11e6-9416-b0a9a1116d49.png)
I did clean and rebuild. 
What do you think I am doing wrong?

**Comment by krzyzanowskim** [comment]
Hi, Probably you need update Xcode to 7.3 with Swift 2.2. Check https://github.com/krzyzanowskim/CryptoSwift/issues/268
