### ISSUE TITLE
CC_SHA1_DIGEST_LENGTH

### ISSUE THREAD

**Issue by simonnarang** [krzyzanowskim/CryptoSwift#273]
Hi there,
I am using spm 3.0 and can't import CommonCrypto to I am using CryptoSwift, which is very helpful🙏.
Is there a method like `CC_SHA1_DIGEST_LENGTH ` from CommonCrypto in CryptoSwift?
Thanks

**Comment by simonnarang** [comment]
Nevermind figured it out

**Comment by krzyzanowskim** [comment]
i dont remember id its public but there should be value for that... some variant or like this (sorry im remote)

**Comment by wackymaster** [comment]
@krzyzanowskim are you still remote?
I could really use some help finding out what that id is...
Thanks
