### ISSUE TITLE
Use of undeclared type CryptoSwift

### ISSUE THREAD

**Issue by marcinkuptel** [krzyzanowskim/CryptoSwift#28]
I just installed ```CryptoSwift``` via CocoaPods but can't build the pod because of the following errors:

- ```Use of undeclared type CryptoSwift```
- ```Use of unresolved identifier CryptoSwift```

This happens for example in ```Authenticator.swift```. Any idea what the issue might be?

**Comment by krzyzanowskim** [comment]
Which version of CocoaPods did you use ?

**Comment by marcinkuptel** [comment]
0.35.0

**Comment by krzyzanowskim** [comment]
ok, you need 0.36 to work with Swift.

**Comment by marcinkuptel** [comment]
Get it. Thanks for a quick response.

**Comment by DevPravin** [comment]
I am facing same issue (error) while installed CryptoSwift using CocoaPods.  
I am using CocoaPod  version 1.0.1

**Comment by krzyzanowskim** [comment]
try ask Cocoapods guys.
