### ISSUE TITLE
AES: makeEncryptor and makeDecryptor funcs are not found?

### ISSUE THREAD

**Issue by litt1e-p** [krzyzanowskim/CryptoSwift#283]
hi, it shows a error when I use CryptoSwift with cocoPods in my project
```swift
import CryptoSwift
let aes = try! AES(key: "passwordpassword", iv: "drowssapdrowssap")
var encryptor = aes.makeEncryptor()
var decryptor = aes.makeDecryptor()
```
but I found that they exist in your sample project and playground. did I use it in wrong way?

my environment: Xcode7.3, Swift2+

**Comment by krzyzanowskim** [comment]
what error?

**Comment by litt1e-p** [comment]
@krzyzanowskim cocosPods version '0.4.1' does not contain `makeEncryptor` or `makeDecryptor ` extensions, but I found them in version '0.5.1', it works now, thanks
