### ISSUE TITLE
Can i use CryptoSwift for XML parsing even on Linux

### ISSUE THREAD

**Issue by Ajayiosdeveloper** [krzyzanowskim/CryptoSwift#286]
Hello Team,
                   i want to parse XML Document and that should work even on Linux too.I need Xpath support also. Will this be possible using this library?.Excuse if i am asking out of the box.

Suggest me any other library as per the requirements if CryptoSwift  is not in the rescue.

Thanks.

**Comment by krzyzanowskim** [comment]
This is "Crypto related functions and helpers for Swift", not XML parser. You should look for XML parser to parse XML document.
