### ISSUE TITLE
EXEC_BAD_INSTRUCTION

### ISSUE THREAD

**Issue by bassrock** [krzyzanowskim/CryptoSwift#29]
I am trying to implement php encryption with ios decryption for data with Alamofire. 

When decrypting I keep getting a bad instruction right here: https://github.com/krzyzanowskim/CryptoSwift/blob/master/CryptoSwift/AES.swift#L218

Any ideas or did i stumble upon a bug?

**Comment by bradbernard** [comment]
I asked this a week or two ago and he led me step by step on how to implement it. I suggest looking at this: https://github.com/krzyzanowskim/CryptoSwift/issues/23

Cheers

**Comment by bassrock** [comment]
@bradbernard yea I am using the final outcome there as a reference. When I run my actual program I get a bad instruction, but in a playground I get a AES128 bit block exceeded.

**Comment by bradbernard** [comment]
Is your key 16 chars long? 128 bytes / 8 bytes per character = 16

**Comment by bassrock** [comment]
yep using ```abcdefghijklmnop``` for the time being

**Comment by bradbernard** [comment]
I see... well I am no cryptography expert (or swift expert) so I would just wait for Marcin to reply

**Comment by bassrock** [comment]
Here is the php encoding:
```php
$ciphertext_base64 = $this->encrypt($this->addPadding("test"), "abcdefghijklmnop");

    function addPadding($value)
    {
        $pad = 16 - (strlen($value) % 16);
        return $value.str_repeat(chr($pad), $pad);
    }

    function encrypt($plaintext, $key) {

        $ivSize = mcrypt_get_iv_size(MCRYPT_RIJNDAEL_128, MCRYPT_MODE_CBC);
        $iv = mcrypt_create_iv($ivSize, MCRYPT_DEV_RANDOM);

        $ciphertext = mcrypt_encrypt(MCRYPT_RIJNDAEL_128, $key, $plaintext, MCRYPT_MODE_CBC, $iv);
        //return base64_encode($ciphertext
        return base64_encode($ciphertext);
    }
```


Here is the swift playground decoding the php:
```swift
// Playground - noun: a place where people can play

import Foundation
import CryptoSwift

let keyData = "abcdefghijklmnop".dataUsingEncoding(NSUTF8StringEncoding, allowLossyConversion: false)!

let data = "qu+J2vGLtSFrZ/hIXosuvA==".dataUsingEncoding(NSUTF32StringEncoding, allowLossyConversion: false)!

let ivData = data.subdataWithRange(NSRange(location: 0, length: AES.blockSizeBytes()))
let encryptedData = data.subdataWithRange(NSRange(location: AES.blockSizeBytes(), length: data.length - AES.blockSizeBytes()))

let aes = AES(key: keyData, iv: ivData, blockMode: .CBC) // CBC is default

let decryptedData = aes?.decrypt(encryptedData, removePadding: true)
```

**Comment by bradbernard** [comment]
Gotcha, looks right to me so it might be an error.

**Comment by bassrock** [comment]
yep thats my thinking

**Comment by krzyzanowskim** [comment]
The real issue here is "AES 128-bit block exceeded!". It's because "encryptedData" is 84 bytes long, and it have to be padded to 128 first, if this is the message you really want to decrypt, because I see this problem with you code:

"qu+J2vGLtSFrZ/hIXosuvA==" looks like BASE64 encoded data and you should decode base64 first, see https://github.com/krzyzanowskim/CryptoSwift/issues/20#issuecomment-72358019 for reference.

After you decode it, make sure it came with padding from server side. If not, do not use "removePadding: true" option.

hope that help.

**Comment by bassrock** [comment]
@krzyzanowskim ah. did not catch that late last night. I did not see that it was done outside the decrypt function. Thanks!
