### ISSUE TITLE
Unable to build swift 3 branch on Xcode beta3

### ISSUE THREAD

**Issue by ed-mejia** [krzyzanowskim/CryptoSwift#292]
I'm getting a few errors when building on Xcode beta 3

![screen shot 2016-08-01 at 11 37 36 am](https://cloud.githubusercontent.com/assets/7431094/17281088/7e7751ce-57dc-11e6-9062-27ea13f27e1f.png)

I'm still getting into swift 3 so I'm a little bit lost with the error messages :(

**Comment by krzyzanowskim** [comment]
you need latest snapshot installed

**Comment by ed-mejia** [comment]
Hi @krzyzanowskim thanks for the response, I must admit it took me a while to understand what you were talking about '** snapshot**' , I never had to deal with this before (shame on me) but I learn and its good! :P 

By the way I got the latest [Swift snapshot](https://swift.org/download/#snapshots) but I'm getting now a lot of different errors, what I'm missing :(

![screen shot 2016-08-01 at 2 40 05 pm](https://cloud.githubusercontent.com/assets/7431094/17283660/50dfac06-57f6-11e6-8701-f47e9dedc7cb.png)

**Comment by krzyzanowskim** [comment]
New snapshot with new features. I have to download it and update.

btw. I mark the current snapshot I'm working with, using this [.swift-version](https://github.com/krzyzanowskim/CryptoSwift/blob/swift3/.swift-version) file for [swiftenv](https://github.com/kylef/swiftenv) (that I recommend)

**Comment by ed-mejia** [comment]
👍

**Comment by krzyzanowskim** [comment]
It's all now updated to latest snapshot DEVELOPMENT-SNAPSHOT-2016-07-29-a

**Comment by ed-mejia** [comment]
Hi @krzyzanowskim, I was wondering why are you using the latest snapshot instead of the latest one distributed via Xcode, I'm having a bad time migrating projects to swift 3 that have CryptoSwift as a dependency.. this is mainly because your code is ahead of the Xcode betas, most of the open source projects out there are keeping track and updating their code repos based on the latest release Xcode beta.

So I _(and I guess many others)_ are facing that for example I can't keep Alamofire and your lib sync in the same project since your lib requires to me to change the toolchain but if I do that then many other dependencies stop compiling because their swift3 branches are up to date with the latest Xcode beta only.

Any ideas?, Many thanks!

**Comment by krzyzanowskim** [comment]
I switched to snapshots just recently. Mostly because I don't want invest my time implementing new features and keep changing it with every Swift change.  In this days there's a lot of changes going on. Additionally Linux releases are not in sync with Xcode beta releases. It all makes the process complicated. We can expect more often Xcode beta releases now, though.

Version of Swift shipped with Xcode beta is rather unknown and really hard to sync with Linux releases or snapshot releases.

I will probably switch to `swift3-snapshots` branch hoping that it will be possible just merge changes to `swift3` branch.

**Comment by ed-mejia** [comment]
Hi @krzyzanowskim 

I understand, and I don't at the same time, you said: 

> Mostly because I don't want invest my time implementing new features and keep changing it with every Swift change.

ins't more likely to be doing more updates following the **swift-snapshot** than the official stable beta releases? 

On the other hand, I think your audience is more Mac/Xcode users than linux users, please correct me if I'm wrong, I'm pretty sure there are plenty of other libraries and projects relying on CryptoSwift on Mac/Xcode/Cocoapods than on linux, this bring the question (why sacrifice Xcode beta stability in order to support linux?)

Please don't take this as a critique, at the end of the day you are the owner of this project and is your decision how to better manage it, We must accept and respect that, This is more like a informative conversation :P

**Comment by krzyzanowskim** [comment]
Thank you for raising this concern. I understand and I agree.
I'll move to `swift3-snapshots` with current development as soon as I manage Xcode beta 4.

**Comment by krzyzanowskim** [comment]
swift3 branch is now in sync with Xcode beta 4

**Comment by ed-mejia** [comment]
@krzyzanowskim **Awesome**, thanks 👍 👍 👍
