### ISSUE TITLE
Not able to create AES with Base 64 encoded key

### ISSUE THREAD

**Issue by mgurnani** [krzyzanowskim/CryptoSwift#293]
Hello,
First - Thanks for sharing this library - it is indeed a nice work..

I have a case wherein I am passed a Base64 encoded 128 bit AES key. It is in ECB mode so no IV. When I try to initialize CryptoSwift AES with it, it fails.
Here is some more information:
Base 64 encoded AES 128 key : "skqoqgae7bMlHCK998o8tA=="
`func init() {
let keyString = "skqoqgae7bMlHCK998o8tA==";
do {
            let keyData = base64Decode(keyString);

            let keyStr = NSString(data: keyData, encoding: NSUTF8StringEncoding); // keyStr is nil

           // Verify bytes
            let bytes:Array<UInt8> = keyData.arrayOfBytes();

            let aes =  try AES(key: keyString, iv:"", blockMode: .ECB); // fails here

}  catch {
            print (error);
        }
}`
I found that the keyStr above is nil and hence Aes key fails to initialize. but the data has the correct bytes - verified using "keyData.arrayOfBytes()"
One thing I observed is there are negative values in the bytes array. Not sure if that is a reason. 
Is there a way I can initialize the Aes directly using the byte array? 

Appreciate any help you could provide.

Thanks!

**Comment by mgurnani** [comment]
If it helps - here's what I see in the byte array :

[-78, 74, -88, -86, 6, -98, -19, -77, 37, 28, 34, -67, -9, -54, 60, -76]

**Comment by krzyzanowskim** [comment]
Thanks. Are you sure what are you doing with this code?
1. keyString is base64 encoded data
2. keyData is decoded base64 data
3. now you're trying convert keyData and treat it as UTF8 string, but it's not valid sequence of bytes for string (keyStr), therefore
4. keyStr is nil and you're trying use it as input value for AES

You need key to encryption. AES(key...) parameter is not Optional type.

Your key bytes:
```
▿ 16 elements
  - 0 : 178
  - 1 : 74
  - 2 : 168
  - 3 : 170
  - 4 : 6
  - 5 : 158
  - 6 : 237
  - 7 : 179
  - 8 : 37
  - 9 : 28
  - 10 : 34
  - 11 : 189
  - 12 : 247
  - 13 : 202
  - 14 : 60
  - 15 : 180
```

Assuming your base64 encoded data is valid key, you can use it this way:

```swift
        let key = Array<UInt8>(base64: "skqoqgae7bMlHCK998o8tA==")
        let plaintext = Array<UInt8>(base64:"74b653e36430d7a9cd91a24d9944b032OrFeckrWo")
        do {
            let aes = try AES(key: key, iv: nil, blockMode: .ECB)
            let decrypted = try aes.decrypt(plaintext)
            print(decrypted.toHexString());
        } catch {
            print("failed");
        }
```
