### ISSUE TITLE
Unable to find a specification for 'CryptoSwift'. (branch: swift21)

### ISSUE THREAD

**Issue by jackyrx** [krzyzanowskim/CryptoSwift#297]
Swift 2.3, Xcode 
Xcode Version 8.0 beta 3 (8S174q)

```
Podfile
pod 'CryptoSwift', :git => "https://github.com/krzyzanowskim/CryptoSwift", :branch => "master"
```

after `pod install`

```
Analyzing dependencies
Pre-downloading: `CryptoSwift` from `https://github.com/krzyzanowskim/CryptoSwift`, branch `swift21`
[!] Unable to find a specification for 'CryptoSwift'.

[!] Unable to load a podspec from `CryptoSwift.podspec`, skipping:

Pod::DSLError
```

Besides, is there any branch for swift 2.3

Thanks

PS: Since this is the first time that contribute to Github in some open source project, please forgive my mistakes.

**Comment by krzyzanowskim** [comment]
Swift 2.3 is on master branch. Xcode 8 is Swift 3.

**Comment by jackyrx** [comment]
Thanks for reply first.

But Xcode 8 allow both Swift 3 & Swift 2.3.

So, can it be work with Swift 2.3 on Xcode 8 too.

**Comment by krzyzanowskim** [comment]
I think you can ask Cocoapods about installation issue like this, I dont think I can help you with that right now.

**Comment by krzyzanowskim** [comment]
@jackyrx I just recall it may be that you need use older version of Cocoapods. They changed podspec syntax, that may be root cause.
