### ISSUE TITLE
Use CommonCrypto when available?

### ISSUE THREAD

**Issue by xlc** [krzyzanowskim/CryptoSwift#300]
I need random access decryption which CommonCrypto doesn't support. But I really want hardware accelerated decryption because currently the decryption code is maxing out the CPU.

Is it possible to replace `AES.encryptBlock`/`AES.decryptBlock` with CommonCrypto and so I still gain all the flexibility of CryptoSwift and hardware accelerated encryption?

I am willing to implement it but does not know the algorithm well enough.

**Comment by krzyzanowskim** [comment]
CommonCrypto dependency is to way too much hassle. Hardware acceleration is not possible to inject directly to Swift.

I don't see convenient way to add hardware acceleration to this project with Swift as we know it today. It may change in the future though.
