### ISSUE TITLE
Swift 3.0 - Package Manager Support

### ISSUE THREAD

**Issue by MichielDeMey** [krzyzanowskim/CryptoSwift#307]
We should consider adding support for Swift's Package Manager.

Simply append @swift-3 to the release tag to denote that build as a "swift 3" specific build of that version. This way we can maintain support for both Swift versions.

More information here: https://github.com/apple/swift-package-manager/blob/master/Documentation/Usage.md#version-specific-tag-selection

**Comment by krzyzanowskim** [comment]
what about that swift3 branch API is different that master, so 0.5.2 and 0.5.2@swift-3 is not the same version.

**Comment by MichielDeMey** [comment]
We should probably get them both in sync before we tag them with the appropriate version.
We should be able to merge the master branch into the Swift 3 branch?

**Comment by krzyzanowskim** [comment]
work in progress is not versioned, swift3 brach will be merged to master branch on release date.

**Comment by rbukovansky** [comment]
You can tag in branch other than master. I was solving same issue with author of SwiftCLI https://github.com/jakeheis/SwiftCLI (Package Manager was not able to find Swift 3.0 version of SwiftCLI), so autor just created tag ("1.3.0-beta2") on branch where Swift 3.0 version is developed ("swift-3.0-beta6"). Then for Package Manager you just need to have this in your Package.swift file:

`.Package(url: "https://github.com/jakeheis/SwiftCLI", Version(1, 3, 0, prereleaseIdentifiers: ["beta2"]))`

Works like a charm then...

**Comment by MichielDeMey** [comment]
Nice, I had no idea the `prereleaseIdentifiers` property existed. Sounds like a feasible solution?

**Comment by krzyzanowskim** [comment]
Thanks! I'll use `prereleaseIdentifiers` for beta from swift3 branch.

**Comment by rbukovansky** [comment]
Please do. Can't wait to use your library. Thanks.

**Comment by rbukovansky** [comment]
Any updates on this? Thank you.

**Comment by krzyzanowskim** [comment]
this should do the job

```swift
.Package(url: "https://github.com/krzyzanowskim/CryptoSwift", Version(0, 6,0 , prereleaseIdentifiers: ["beta1"]))
```

btw. I need help with README updates to swift3 changes.

**Comment by rbukovansky** [comment]
Thanks.

What do you mean bout those README updates?

**Comment by krzyzanowskim** [comment]
I believe code it's not up to date to latest changes from swift3 branch. I have to update it before release.

**Comment by rbukovansky** [comment]
I believe you meant that README is not up to date... ;)

And you need help with updating it?

**Comment by krzyzanowskim** [comment]
yes, README, README :)

**Comment by krzyzanowskim** [comment]
I think we're good with this one, closing.
