### ISSUE TITLE
Compilation issues in Xcode 6.3 beta 2

### ISSUE THREAD

**Issue by winzig** [krzyzanowskim/CryptoSwift#31]
I've tried the master and swift12 branches, and am getting a lot of compilation errors either way. Known issue?

**Comment by krzyzanowskim** [comment]
yes actually, I close one issue at a time checking what changed and where. There is last one missing, I'll commit it asap.

**Comment by krzyzanowskim** [comment]
it is working now.

**Comment by winzig** [comment]
OK thanks. It's now compiling. (I'm assuming you've noticed the 7 warnings related to "will never be executed" in AES.swift and CipherBlockMode.swift.

**Comment by krzyzanowskim** [comment]
yes https://twitter.com/krzyzanowskim/status/571269943045558272 I hope they fix it soon ;)
