### ISSUE TITLE
extra bytes after decrypting AES 256 CBC

### ISSUE THREAD

**Issue by ashiqsulaimanbaryons** [krzyzanowskim/CryptoSwift#312]
When i am using this code. The Uint8 array generated after the decryption, constantly has 7 0's in the end.   [56, 56, 53, 98, 53, 101, 98, 99, 53, 98, 57, 49, 54, 57, 48, 98, 51, 55, 56, 49, 98, 101, 51, 51, 101, 102, 55, 55, 55, 98, 49, 48, 79, 114, 70, 101, 99, 107, 114, 87, 111, 0, 0, 0, 0, 0, 0, 0]
Just want to confirm if it is safe to remove the trailing 0's.

```swift
 do {
            let aes = try AES(key:  "0123456789abcdef", iv: "fedcba9876543210", blockMode: .CBC, padding: NoPadding())
            //print("the value of hexaval is  \(dataFromHexadecimalString(encryptedString))")
            let count = dataFromHexadecimalString(encryptedString)!.length / sizeof(UInt8)
            
            // create an array of Uint8
            var array = [UInt8](count: count, repeatedValue: 0)
            
            // copy bytes into array
            dataFromHexadecimalString(encryptedString)!.getBytes(&array, length:count * sizeof(UInt8))
            
            //print("the array is \(array)")
            var ciphertext = try aes.decrypt(Array<UInt8>(array))
            /// loop to remove the trailing zeros       
            print("the cipher is \(ciphertext)")
            //Convert [UInt8] to NSData
            let data = NSData(bytes: ciphertext, length: ciphertext.count)
            
            //Convert NSData to NSString
            let newNSString = NSString(data: data, encoding: NSUTF8StringEncoding)! as String
            
            //print("decrypted vlaue is \(newNSString)")
            
            apiKey = newNSString
            
            return newNSString
            
        } catch {
            print("Decryption error")
        }
       
        return "Error"
    }
```

**Comment by krzyzanowskim** [comment]
Please update code with input data.
Looks like you decided to use NoPadding() and it's up to you to handle padding.

**Comment by ashiqsulaimanbaryons** [comment]
Here is the input value. "5cbb915bd54458fd77aa86e9606533b563166eefebd3529866fb46609e7ad8f9e1ee2c09906ec08d00e024f9d47dd711"

**Comment by krzyzanowskim** [comment]
There are no extra bytes. Output and input number of bytes is exactly the same.

To answer your question, it doesn't look like you shouldn't remove trailing zeros. It's just an accident you get 0 there. It's enough to modify single byte and you won't get trailing zeros.

It's just by accident trailing 0 is string termination and when you build String out of it it's ignored.

```
do {
    let aes = try AES(key:  "0123456789abcdef", iv: "fedcba9876543210", blockMode: .CBC, padding: NoPadding())
    let bytes = Array<UInt8>(hex: "5cbb915bd54458fd77aa86e9606533b563166eefebd3529866fb46609e7ad8f9e1ee2c09906ec08d00e024f9d47dd711")
    bytes.count
    let ciphertext = try aes.decrypt(bytes)
    ciphertext.count
    print("the cipher is \(ciphertext)")
} catch {
    print("Decryption error")
}
```

**Comment by Piyush08** [comment]
I am also getting same issue:
Please check image below:

![Screenshot 2021-06-11 at 7 12 56 PM](https://user-images.githubusercontent.com/7929845/121696019-43e1e300-cae9-11eb-9670-8fd7e809f234.png)
