### ISSUE TITLE
AES OFB returning slightly different results

### ISSUE THREAD

**Issue by AndyQ** [krzyzanowskim/CryptoSwift#313]
I'm currently working on porting some code from Android over to iOS (fun!) which is encrypting some data using AES OFB, no padding, and I've just come across a slight difference in the last 4 bytes only.

My android code is actually using streams to encrypt the data (i've implemented the same too and get exactly the same results back).

Am I missing/doing something really obvious and can anyone shed any light on what it might be?

Many thanks!

My iOS code is doing something like (this is a simple test harness)
```
    func testEncryption() {
        let data = "646be706fa3a7566a6ef36194eb8df8dee366238"
        let key = "0f620d0c366309086206380403020172"
        let iv =  "44454641554c54000000000000000000"
        
        let dataBytes = hexStringToBytes(data)
        let keyBytes = hexStringToBytes(key)
        let ivBytes = hexStringToBytes(iv)
        
        let aes = try! AES(key: keyBytes, iv: ivBytes, blockMode: .OFB, padding: NoPadding())
        let encr = try! aes.encrypt( dataBytes)
        let str = encr.toHexString()
        
        print( "Str - \(str)")
        // Str = "a9ae1297b9f86ffd5bd2305be94dbc9a20428e3d"
        // Android returns: "a9ae1297b9f86ffd5bd2305be94dbc9a23f397a9"

        // NOTICE the last 4 bytes are different - 20428e3d vs 23f397a9
    }

    
    func hexStringToBytes(hexString: String) -> [UInt8] {
        guard let chars = hexString.cStringUsingEncoding(NSUTF8StringEncoding) else { return []}
        var i = 0
        let length = hexString.characters.count
        
        let data = NSMutableData(capacity: length/2)!
        var byteChars: [CChar] = [0, 0, 0]
        
        var wholeByte: CUnsignedLong = 0
        
        while i < length {
            byteChars[0] = chars[i]
            i+=1
            byteChars[1] = chars[i]
            i+=1
            wholeByte = strtoul(byteChars, nil, 16)
            data.appendBytes(&wholeByte, length: 1)
        }
        
        return data.arrayOfBytes()
    }
```

**Comment by AndyQ** [comment]
Doing a little more digging and it appears that the OFBModeWorker passes the iv into the cipherOperation for the first chunk and then uses the cipherText returned from the cipherOperation for the next.

Android is using the iv for each chunk.

Tested by creating a new aes.makeEncryptor() for each chunk and it now behaves the same.

No idea though which one is correct!

**Comment by krzyzanowskim** [comment]
That'd be unexpected to apply IV to each block in OFB mode because each output block cipher  depends on all previous ones. Maybe, in Android code you encrypt each block independently - that is not exactly the same.

**Comment by AndyQ** [comment]
Not sure it doesn't look like it though.
The android code is using the BouncyCastle provider and the AES/OFB/NoPadding Cipher.
They set the key and the iv on the cypher at the start and then do two blocks of  encryption (stream based).

Sadly can't dig in the the specifics but still trying to figure it out. But at least I have the same now both sides ;)  I'll close this now though.

**Comment by krzyzanowskim** [comment]
This is how OFB is defined. If IV is applied to every single block, I'd say it's not correct behaviour.

![screen shot 2016-08-27 at 12 27 14](https://cloud.githubusercontent.com/assets/758033/18026766/9d019fa8-6c51-11e6-86ec-1c74d9f85a52.png)

**Comment by AndyQ** [comment]
Thanks very much - that explains nicely how it should work!  I'll feed that back to the android guys!
