### ISSUE TITLE
CocoaPods uses legacy Swift version. SWIFT_VERSION.

### ISSUE THREAD

**Issue by cesarvarela** [krzyzanowskim/CryptoSwift#314]
Hi, I'm new in iOS development, and this is my first time using CocoaPods so maybe I'm doing something stupid.

This is how my pods file looks:

```
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'MessagesExtension' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MessagesExtension
  pod 'CryptoSwift', :git => "https://github.com/krzyzanowskim/CryptoSwift", :branch => "swift3"

end
```
And after installing and opening the workspace, I get lots of errors related to the new swift 3 syntax:
![screen shot 2016-08-28 at 3 21 07 am](https://cloud.githubusercontent.com/assets/1172479/18032009/821e9a1a-6cce-11e6-8f75-35065ef559a4.png)

Not sure if this is because the swift3 branch is behind latest beta or if I'm doing something wrong.

**Comment by krzyzanowskim** [comment]
maybe something cached locally, `swift3` branch is up to date with Xcode8 beta.

**Comment by krzyzanowskim** [comment]
anyway I'm testing Cococapods setup and one thing is kindof unexpected. Looks like Pod don't specify SWIFT_VERSION correctly, and that trigger Xcode code conversion 

![screen shot 2016-08-28 at 09 03 48](https://cloud.githubusercontent.com/assets/758033/18032205/8176e484-6cfe-11e6-876e-ab77236d3671.png)

**Comment by cesarvarela** [comment]
I see, if I set the swift mode to legacy, I still get lots of errors:

![screen shot 2016-08-28 at 4 13 30 am](https://cloud.githubusercontent.com/assets/1172479/18032236/d6909696-6cd5-11e6-85c9-88fe68a74376.png)

**Comment by krzyzanowskim** [comment]
you have to set the value to "No"

**Comment by krzyzanowskim** [comment]
looks like the issue is addressed in latest beta of Cocoapods

```
$ gem install cocoapods --pre
$ pod _1.1.0.beta.1_ install
```

**Comment by cesarvarela** [comment]
Thanks I also had trouble with this one https://github.com/CocoaPods/CocoaPods/issues/5594 

Seems to be working now.
