### ISSUE TITLE
Unable to build: Swift3 with Carthage and Xcode 8 beta 6

### ISSUE THREAD

**Issue by Andr3y-** [krzyzanowskim/CryptoSwift#316]
Unable to build CryptoSwift swift3 branch with Carthage and Xcode 8 beta 6 installed.

I am getting the following error, after running `Carthage update`

`The following build commands failed:
       	Ld /Users/username/Library/Developer/Xcode/DerivedData/CryptoSwift-aajricvhatmabjhhnfxnfhmmlknh/Build/Intermediates/CryptoSwift.build/Release-iphoneos/CryptoSwift\ iOS.build/Objects-normal/arm64/CryptoSwift normal arm64
(1 failure)`

Any idea when Xcode 8 beta 6 support would be added?

**Comment by krzyzanowskim** [comment]
Xcode8 beta 6 is supported. It's just that Xcode is broken. Closing as duplicate #240

**Comment by Andr3y-** [comment]
Thanks for linking #240.
Disabling Bitcode allowed to build with no issues
