### ISSUE TITLE
Compile error project level

### ISSUE THREAD

**Issue by nissaba** [krzyzanowskim/CryptoSwift#317]
Downloaded the project and tried to build it under xCode8 beta 6 getting the following

-- WARNINGS -- 
Target 'CryptoSwift OSX' of project 'CryptoSwift' was rejected as an implicit dependency for 'CryptoSwift.framework' because it doesn't contain platform 'iphoneos' in its supported platforms 'macosx'
Target 'CryptoSwift watchOS' of project 'CryptoSwift' was rejected as an implicit dependency for 'CryptoSwift.framework' because it doesn't contain platform 'iphoneos' in its supported platforms 'watchsimulator, watchos'
Target 'CryptoSwift tvOS' of project 'CryptoSwift' was rejected as an implicit dependency for 'CryptoSwift.framework' because it doesn't contain platform 'iphoneos' in its supported platforms 'appletvos, appletvsimulator'

Check dependencies

-- ERRORS --
Unable to run command 'Ld CryptoSwift' - this target might include its own product.
Unable to run command 'Ld CryptoSwift' - this target might include its own product.
Unable to run command 'CreateUniversalBinary CryptoSwift' - this target might include its own product.
Unable to run command 'GenerateDSYMFile CryptoSwift.framework.dSYM' - this target might include its own product.
Unable to run command 'Touch CryptoSwift.framework' - this target might include its own product.
Unable to run command 'CodeSign CryptoSwift.framework' - this target might include its own product.

**Comment by krzyzanowskim** [comment]
Clean cache. 
Today's change 82271abbf17409b1d26b0b1e862f9914b4443d0e replaced multiple targets with single target "CryptoSwift"
