### ISSUE TITLE
SHA512, SHA384 bug

### ISSUE THREAD

**Issue by chrisamanse** [krzyzanowskim/CryptoSwift#319]
Hi @krzyzanowskim! First of all, great work on implementing the standard crypto functions in Swift.

I'm also implementing crypto functions in Swift, and I've been comparing your digests' outputs to mine, `shasum`'s and other online generators. I came across this bug in CryptoSwift for SHA2 variants that have 64-bit words (i.e. SHA512), where they produce the wrong output for message lengths that are greater than 112 bytes (mod 128).

Ex.

**In CryptoSwift:**
`"abcdefghbcdefghicdefghijdefghijkefghijklfghijklmghijklmnhijklmnoijklmnopjklmnopqklmnopqrlmnopqrsmnopqrstnopqrstu".sha512()` produces `"feb885c0c56838413625ba4e15f3e6116fdb2ebe26f9c1d4b9ea8bea9a984702a61bbdbad784fa995d9ab8879befab0dd7d8566d26a5ad95cdf42fdddf088123"`

**In Terminal using `shasum`:**
`echo -n "abcdefghbcdefghicdefghijdefghijkefghijklfghijklmghijklmnhijklmnoijklmnopjklmnopqklmnopqrlmnopqrsmnopqrstnopqrstu" | shasum -a 512` produces `"8e959b75dae313da8cf4f72814fc143f8f7779c6eb9f7fa17299aeadb6889018501d289e4900f7e4331b99dec4b5433ac7d329eeb6dd26545e96e55b874be909"`

---

I've looked through your code and other implementations in other languages and found that the message "pre-processing" should be different from the other variants. Example implementation in Go can be found [here](https://golang.org/src/crypto/sha512/sha512.go#L210) line 210 wherein the message length representation should be a 128-bit or 16-byte integer (CryptoSwift uses 64-bit or 8-byte which is located [here](https://github.com/krzyzanowskim/CryptoSwift/blob/swift3/Sources/CryptoSwift/SHA2.swift#L199-L209)). This also makes the padding length equal to 112 (mod 128).

I could modify the code and create a pull request but I'm not sure where to put the custom implementation for `HashProtocol.prepare(_ len: Int) -> Array<UInt8>`.

**Comment by krzyzanowskim** [comment]
great, thank you!
please feel fee to prepare PR. Either put it in HashProtocol.prepare() if it can be distinguish there, if not, please move the proper implementations to SHA1 and SHA2 accordingly.

**Comment by krzyzanowskim** [comment]
thanks!
