### ISSUE TITLE
README: HMAC authentication need update - Swift 3.0 

### ISSUE THREAD

**Issue by sp8hmz** [krzyzanowskim/CryptoSwift#320]
There are no functions in Authenticator.swift file to authenticate with SHA256, SHA512 and so on. Because of this example code to authenticate doesn't work.

**Comment by krzyzanowskim** [comment]
#307 

Swift3 Readme is bot up to date.

**Comment by krzyzanowskim** [comment]
API has changed, for now please check tests https://github.com/krzyzanowskim/CryptoSwift/blob/swift3/Tests/CryptoSwiftTests/HMACTests.swift for usage.
