### ISSUE TITLE
HMAC implementation crashes/broken in Swift 3

### ISSUE THREAD

**Issue by danielrhodes** [krzyzanowskim/CryptoSwift#322]
I haven't been able to get this to work in my Swift 3 branch. Furthermore, when I run the following:

```swift
let key: Data = ...
let data: Data = ...
try! data.authenticate(with: HMAC(key: key.bytes, variant: .sha1))
```

I get a `fatal error: Index out of range` crash which points to [https://github.com/krzyzanowskim/CryptoSwift/blob/swift3/Sources/CryptoSwift/HMAC.swift#L79](https://github.com/krzyzanowskim/CryptoSwift/blob/swift3/Sources/CryptoSwift/HMAC.swift#L79)

When I tried an alternate way to get the HMAC:

```swift
try! HMAC(key: arrayOfBytes(value: key), variant: .sha1).authenticate(arrayOfBytes(value: data))
```

there was no crash, but the result did not match up with what an OpenSSL implementation was giving me.

I tried the [Crypto](https://github.com/soffes/Crypto/tree/swift3) library with the exact same key and data and it is giving me the expected result.

**Comment by krzyzanowskim** [comment]
thanks, can you share input data that caused the crash?

**Comment by krzyzanowskim** [comment]
when it comes to output, what you may observe (just guessing) is that OpenSSL produce truncated output while CryptoSwift don't. The size of the output of HMAC is the same as that of the underlying hash (10 bytes for sha1), although it can be truncated to 10 bytes.

It may be good point to add parameter to automatically truncate result as it may be expected more than not truncated output.

**Comment by krzyzanowskim** [comment]
@danielrhodes do you have any update for this?

**Comment by danielrhodes** [comment]
@krzyzanowskim  Sorry for the delay. This was on Swift 3 in XC8 Beta 6. I don't have the strings themselves anymore (the HMAC is part of signing a request, but it was happening consistently across requests). The key was a sha1 hash as a hex utf-8 string (also using Cryptoswift), and the data was a plain text utf-8 string. If you give me a few more days, I can have something more exact you could try as I am in the middle of something else.

**Comment by krzyzanowskim** [comment]
thanks! that would be great if you could show sample with unexpected output. For tests Ive made, it all good so far.

the only case for crash (I can think of) is when key len. dont match hash variant.

**Comment by krzyzanowskim** [comment]
@danielrhodes I found what cause the problem. It was regression as you mentioned. Fixed now.
