### ISSUE TITLE
How to decrypt encrypted string ?

### ISSUE THREAD

**Issue by MrLoveQD** [krzyzanowskim/CryptoSwift#323]
Hi.
I used encrypt:
`let aes = try AES(key: secretKey, iv:  vKey, blockMode: .CBC, padding: PKCS7());`
`let ciphertext = try aes.encrypt(input.utf8.map({$0}))`
`let encryptedData: String = ciphertext.toBase64()!`

How to decrypt **encryptedData** ?

**Comment by krzyzanowskim** [comment]
1. decode base64 encoded String back to bytes
2. decrypt it

Search for `String.decryptBase64ToString(..)` helper created for such case in particular.
