### ISSUE TITLE
Clarification on installation

### ISSUE THREAD

**Issue by ChMaxou** [krzyzanowskim/CryptoSwift#326]
Hi

I have been trying to install CryptoSwift for hours, but I still can't import it in my project. This is what I have done, the app is a message Extension:

![capture d ecran 2016-09-09 a 21 44 28](https://cloud.githubusercontent.com/assets/6448849/18402377/f7893a46-76d6-11e6-99b6-d94e291422ed.png)
![capture d ecran 2016-09-09 a 21 45 01](https://cloud.githubusercontent.com/assets/6448849/18402380/fafa0aac-76d6-11e6-8f9e-a7580a8b1ff4.png)

The documentation requires adding to an "Embed Frameworks" section, but I can't find any. Is it a feature that was deleted from Xcode 8?

**Comment by krzyzanowskim** [comment]
if you use cocoapods, just use cocoapods and dont try manual installation. Steps may wart between types of Xcode targets though

**Comment by krzyzanowskim** [comment]
@ChMaxou you have to add this step manually for this target
![Uploading Screen Shot 2016-09-11 at 08.21.09.png…]()

**Comment by krzyzanowskim** [comment]
![2016-09-12 14_21_25](https://cloud.githubusercontent.com/assets/758033/18435544/364d60c6-78f4-11e6-90e5-c2d9bf909c52.gif)
