### ISSUE TITLE
Problem with UITests

### ISSUE THREAD

**Issue by sembsa** [krzyzanowskim/CryptoSwift#327]
Hello, i have problem when run UITests:

dyld: Library not loaded: @rpath/CryptoSwift.framework/CryptoSwift
  Referenced from: /Users/sembsa/Library/Developer/CoreSimulator/Devices/CE958B0C-10E6-4D85-8C1F-3F9AC452A7C7/data/Containers/Bundle/Application/15098009-E530-417E-8D32-3370EDD892B4/testStream.app/testStream
  Reason: no suitable image found.  Did find:
	/Users/sembsa/Library/Developer/CoreSimulator/Devices/CE958B0C-10E6-4D85-8C1F-3F9AC452A7C7/data/Containers/Bundle/Application/15098009-E530-417E-8D32-3370EDD892B4/testStream.app/Frameworks/CryptoSwift.framework/CryptoSwift: no matching architecture in universal wrapper

Z tego co obczaiłem to jesteś Polakiem to opisze po Polsku będzie mi łatwiej.
Jak uruchamiam UITests w Xcode 8.0 GM to wywala mi ten błąd co wyżej. Może masz jakiś pomysł. Dzięki z góry za odpowiedź.
Świetna robotą 👍

**Comment by krzyzanowskim** [comment]
I'll try figure out, can you please attach sample project with the issue?

**Comment by krzyzanowskim** [comment]
see "That’s not it" paragraph about tests here: http://promisekit.org/news/2016/08/Multiplatform-Single-Scheme-Xcode-Projects/

**Comment by sembsa** [comment]
It's works, thanks 👍
