### ISSUE TITLE
Issue “Command /bin/sh failed with exit code 1” 

### ISSUE THREAD

**Issue by LimChihi** [krzyzanowskim/CryptoSwift#329]
When I add CryptoSwift by CocoaPods to my project, it will always Build failed with this error `Command /bin/sh failed with exit code 1`.
Then I try to fix this bug in this way [http://stackoverflow.com/questions/13006464/how-to-fix-the-issue-command-bin-sh-failed-with-exit-code-1-in-iphone](url). But I failed. 
Sorry for my poor English.

**Comment by krzyzanowskim** [comment]
it may be anything. try to create example project and attach to this issue

**Comment by LimChihi** [comment]
Hello 
I have build a new example project to catch this issue,but this demo  run very well.
Here I attach the message about `CryptoSwift` from the old project.
`Code Signing /Users/Lim/Library/Developer/Xcode/DerivedData/nokey_ios-gyqfhfuvywlbwjdznbzxvjllgmls/Build/Products/Debug-iphoneos/nokey_ios.app/Frameworks/CryptoSwift.framework with Identity iPhone Developer: ZHIYI LIN `
－－－－－－－
`/usr/bin/codesign --force --sign --  --preserve-metadata=identifier,entitlements "/Users/Lim/Library/Developer/Xcode/DerivedData/nokey_ios-gyqfhfuvywlbwjdznbzxvjllgmls/Build/Products/Debug-iphoneos/nokey_ios.app/Frameworks/CryptoSwift.framework"
`
－－－－－－－－
`/Users/Lim/Library/Developer/Xcode/DerivedData/nokey_ios-gyqfhfuvywlbwjdznbzxvjllgmls/Build/Products/Debug-iphoneos/nokey_ios.app/Frameworks/CryptoSwift.framework: bundle format unrecognized, invalid, or unsuitable
`

I thing the error may be in the last paragraph. Is this infomation helpful?

**Comment by krzyzanowskim** [comment]
Not really. It looks like Xcode issue more than CryptoSwift project itself. If you can't reproduce it with the new project, I can't reproduce it too. Deleting DerivedData may help if that's something with that.

1. Delete Derived data
2. Clean the project

**Comment by LimChihi** [comment]
Well
It is Xcode issue.I'm so sorry to intrude on you like this.
I have cleaned the project before.But I forgot to delete Derived data.
I am a student,I'm honor to learn thing from your code and the way you handler Xcode.
