### ISSUE TITLE
Show 203 errors after pod update

### ISSUE THREAD

**Issue by zahedul** [krzyzanowskim/CryptoSwift#330]
<img width="1280" alt="screen shot 2016-09-14 at 3 12 59 am" src="https://cloud.githubusercontent.com/assets/1929044/18491666/4555beac-7a29-11e6-9a8c-5b63135fabb5.png">

after pod update it show 203 errors. I don't add this package in my pod file. another package use this package.

thanks

**Comment by krzyzanowskim** [comment]
v0.6.0 is for Swift 3. If you use Swift 2.x you have to switch to `swift2` branch https://github.com/krzyzanowskim/CryptoSwift#older-swift

**Comment by krzyzanowskim** [comment]
You can either modify Podfile.lock and downgrade to version 0.5.2, or add CryptoSwift 0.5.2 to your Podfile - this way it will be used as dependency.

In any way, it looks like versions problem (Swift 2 vs Swift 3) and CryptoSwift 0.5.2 vs 0.6.0

```
pod 'CryptoSwift', '0.5.2' 
```
also... it can be addressed by the package that depends on CryptoSwift
```
spec.dependency 'CryptoSwift', '0.5.2'
```
