### ISSUE TITLE
Build for 9.3 with iPhone 4S

### ISSUE THREAD

**Issue by sembsa** [krzyzanowskim/CryptoSwift#331]
Hello, i have problem :(
When i use CryptoSwift (swift3) and build for iPhone 4S, XCode show me error:

`Value of type 'String' has no member 'sha1'`

This error is only on iPhone 4S when i build for >= 5S is not a problem.

I don't idea.

**Comment by sembsa** [comment]
@krzyzanowskim do you have idea ?

**Comment by krzyzanowskim** [comment]
I don't know, it's probably Xcode issue or project configuration issue.
iPhone 4s arch is armv7, x86_64 is for simulator, so it's simulator. Maybe it uses wrong binary, clear all the caches and derived data, this may help (as usually for Xcode).

**Comment by sembsa** [comment]
ok works, XCode 8 GM is many bug ehhh
