### ISSUE TITLE
No such module 'CryptoSwift' swift 3, Xcode 8 I use

### ISSUE THREAD

**Issue by NicoDevItalia** [krzyzanowskim/CryptoSwift#332]
Hello, I have a problem when I import the framework into project. I have try to import using cocoapod and carthage but nothing. What can I do to have nothing problem for 'No such module 'CryptoSwift'? 

Thanks

**Comment by krzyzanowskim** [comment]
Please follow the instructions from README or from Xcode documentation. If none of the method work for you you may have configuration problem with your project... it may be literally anything.

Looks like the issue is related to Xcode more than to CryptoSwift.

**Comment by NicoDevItalia** [comment]
Thanks @krzyzanowskim

**Comment by Goule** [comment]
@NicoDevItalia , got the same problem with my project, have you find any solution ?

**Comment by NicoDevItalia** [comment]
Yes @Goule, I have found a solution, I have rewrite entire project, I have recreated the project, after I have used carthage for my case, and the last thing I have import the framework, this work for me.
