### ISSUE TITLE
arrayOfBytes() xcode 8 swift 3

### ISSUE THREAD

**Issue by tindang** [krzyzanowskim/CryptoSwift#334]
i have install CryptoSwift 0.6.0. 

```swift
import Foundation
import CryptoSwift

extension String {
    func aesEncrypt(key: String, iv: String ) throws -> String{
        let data = self.data(using: String.Encoding.utf8, allowLossyConversion: true)
        let enc = try AES(key: key, iv: iv, blockMode:.CBC,padding: PKCS7()).encrypt(data!)
        let encData = NSData(bytes: enc, length: Int(enc.count))
        let base64String: String = encData.base64EncodedString(options: NSData.Base64EncodingOptions(rawValue: 0));
        let result = String(base64String)
        return result!
    }
    
    func aesDecrypt(key: String, iv: String) throws -> String {
        let data = NSData(base64Encoded: self, options: NSData.Base64DecodingOptions(rawValue: 0))
        let dec = try AES(key: key, iv: iv, blockMode: .CBC, padding: PKCS7 as! Padding).decrypt(data.arrayOfBytes())
        let decData = NSData(bytes: dec, length: Int(dec.count))
        let result = NSString(data: decData, encoding: NSUTF8StringEncoding)
        return String(result!)
    }
}
```
error arrayOfBytes() in func aesDecrypt

fix help me
thank you so much

**Comment by krzyzanowskim** [comment]
what is the error message?

**Comment by krzyzanowskim** [comment]
arrayOfBytes is no longer available. Use `data.bytes` in place.

**Comment by tindang** [comment]
i fix data.bytes but error 
[https://s15.postimg.org/sk213f7nv/Screen_Shot_2016_09_16_at_9_57_29_PM.png](url)

**Comment by krzyzanowskim** [comment]
@tindang because you pass Optional where you shouldn't, as error message show.

**Comment by tindang** [comment]
so you can fix help me. i want code func Decrypt . please help me.

**Comment by krzyzanowskim** [comment]
I'm not sure why you need this kind of function, given this example: [CryptoSwift.playground/Contents.swift](https://github.com/krzyzanowskim/CryptoSwift/blob/master/CryptoSwift.playground/Contents.swift#L92) and [README#basics](https://github.com/krzyzanowskim/CryptoSwift/blob/master/README.md#basics). Looks redundant and necessary to me. 

Seems you ask for Swift support more than CryptoSwift here.
