### ISSUE TITLE
Extra argument 'padding' in call(Swift 3)

### ISSUE THREAD

**Issue by malisanjay5433** [krzyzanowskim/CryptoSwift#340]
Migrating code to Swift 3.0 Kindly help me on this extension. 
```swift
extension String {
      func aesEncrypt(_ key: String, iv: String) throws -> String{
        let data = self.data(using: String.Encoding.utf8)
        **let enc = try AES(key: key, iv: iv, blockMode:.ECB).encrypt(data!.arrayOfBytes(), padding: PKCS7())**
        let encData = Data(bytes: UnsafePointer<UInt8>(enc), count: Int(enc.count))
        let base64String: String = encData.base64EncodedString(options: NSData.Base64EncodingOptions(rawValue: 0));
        let result = String(base64String)
        return result!
    }  

    func aesDecrypt(_ key: String, iv: String) throws -> String {
        let data = Data(base64Encoded: self, options:NSData.Base64DecodingOptions(rawValue: 0))
        **let dec = try AES(key: key, iv: iv, blockMode:.ECB).decrypt(data!.arrayOfBytes(), padding: PKCS7())**
        let decData = Data(bytes: UnsafePointer<UInt8>(dec), count: Int(dec.count))
        let result = NSString(data: decData, encoding: String.Encoding.utf8)
        return String(result!)
        
    }
}
```

**Comment by krzyzanowskim** [comment]
@malisanjay5433 what is the problem?

**Comment by malisanjay5433** [comment]
Swift 2.2: Its working below line
//      let enc = try AES(key: key, iv: iv, blockMode:.ECB).encrypt(data!.arrayOfBytes(), padding: PKCS7())

Swift 3: Giving error called Extra argument 'padding' in call. How can i solve this ?

**Comment by krzyzanowskim** [comment]
`padding` options is part of AES init now.

**Comment by malisanjay5433** [comment]
Now i'm not getting any error. Below code will work properly ?
 let enc = try AES(key: key, iv: iv, blockMode:.ECB).encrypt(data!)

**Comment by krzyzanowskim** [comment]
yes

**Comment by malisanjay5433** [comment]
Thanks lot

**Comment by sreechary** [comment]
I am getting 32 bytes after encrypting 16 data 
plz help me in finding the solution

**Comment by sreechary** [comment]
let bytes : [UInt8] =  [0x02,0x20,0x01,0x01,0x24,0x02,0x20,0x01,0x01,0x24,0x02,0x20,0x01,0x01,0x24,0x01]

do{


           let aes = try! AES(key: Key!, iv: "", blockMode: .ECB)


           let encrypt = try aes.encrypt(bytes)


           print("encrypted data size", encrypt.count)


           print("encrypt data is", encrypt)


            


        }catch


        {


           print(error)
        }

**Comment by sreechary** [comment]
my key is 16 chars
data is 16 bytes  and the encrypted data is 32 bytes 
If i decrypt the data i am getting the data correctly

**Comment by krzyzanowskim** [comment]
What you observes is additional block due to padding block at the end. This is expected.

**Comment by sreechary** [comment]
But I need only 16 bytes of data without padding values how to get it

**Comment by sreechary** [comment]
Is there any solution to display only encrypted data without padding data .
I need to display on 16 bytes

**Comment by krzyzanowskim** [comment]
Use no padding then. It works as long as your input is rounded to the size of a single block (16 bytes).

**Comment by sreechary** [comment]
Thanks you I am able to separate the encrypted data and padded value
One small query.How can I able to send more that 20 bytes of data to BLE in swift
