### ISSUE TITLE
Which branch is Swift 2.3 compatibility?

### ISSUE THREAD

**Issue by cikpis** [krzyzanowskim/CryptoSwift#341]
Hey guys, which branch is Swift 2.3 compatibility?

**Comment by krzyzanowskim** [comment]
https://github.com/krzyzanowskim/CryptoSwift#older-swift
![screen shot 2016-09-26 at 17 20 42](https://cloud.githubusercontent.com/assets/758033/18840044/94aedbb2-840d-11e6-9172-107b8ac7b3b2.png)

**Comment by cikpis** [comment]
I've read that. I thought was missed the 2.3 due to you specified the 2.1. Never mind, thanks.
