### ISSUE TITLE
XCode 7.3. Swift version 2.2  - 224 issues

### ISSUE THREAD

**Issue by MladenBekavac** [krzyzanowskim/CryptoSwift#343]
Hi, 
I have installed the framework via CocoaPods. 

> pod 'CryptoSwift'

Right after the installation I got 224 issues.  I also tried to download the files manually from older versions (Swift 2.X) and drag them to my project but it didn't work (added them in the "Link binary with libraries").

Here is a screenshot of the first error which appears. I could try to solve them one by one, but maybe there is a faster solution, or I am just doing something else wrong. 

Any advice is welcome :).

<img width="1440" alt="screen shot 2016-09-29 at 20 55 25" src="https://cloud.githubusercontent.com/assets/9347078/18968121/11adf054-8688-11e6-936c-2c7fd33167cd.png">

**Comment by krzyzanowskim** [comment]
tou need to use swift2 branch for Xcode 7

**Comment by MladenBekavac** [comment]
Ty for the help. Found it.

I changed: 

> pod 'CryptoSwift'

to:

> pod 'CryptoSwift', :git => "https://github.com/krzyzanowskim/CryptoSwift.git", :branch => "swift2"
