### ISSUE TITLE
Swift 2.3 compatible version in Cocoapods

### ISSUE THREAD

**Issue by victorg1991** [krzyzanowskim/CryptoSwift#344]
We are using this library in other library and we need to be compatible with swift 2.3, Can you please upload the latest changes of the swift2 branch to cocoapods? It would be a great help

Thank you!

Kind regards

**Comment by krzyzanowskim** [comment]
not really, but you may specify version < 0.6.0. should the job

**Comment by victorg1991** [comment]
I'll try, thank you! :)
