### ISSUE TITLE
AES-CCM (RFC 3610)

### ISSUE THREAD

**Issue by xslim** [krzyzanowskim/CryptoSwift#345]
Hi!
Great library!

Do you plan adding AES-CCM encryption?

Her's the RFC link 
https://github.com/xslim/TKCryptor/blob/master/rfc3610.txt

I once did implement it on Objective-C: 
https://github.com/xslim/TKCryptor/blob/master/TKCryptor/TKAESCCMCryptor.m

**Comment by binloan** [comment]
Bump. Needing this - Will this be scheduled any time soon? I can't find any other proper implementation and I am force to CCM through hardware.

**Comment by xslim** [comment]
@binloan Have you tried my library https://github.com/xslim/TKCryptor or you are searching for Swift-one?

**Comment by krzyzanowskim** [comment]
@xslim I'm happy to see PR with that if you have time. I'm quite busy with other project now and probably can't add this in short time.

**Comment by binloan** [comment]
@xslim I already found that one - however GitHub returns me a 404 on this link... (you made it private?) @krzyzanowskim I understand, thanks for the clarification though. Interestingly CommonCrypto has CCM built in, but somehow Apple doesn't expose it (looking to the c code). If they once would do I could also run with that...

**Comment by krzyzanowskim** [comment]
AES-CCM is merged.
https://github.com/krzyzanowskim/CryptoSwift#aes-ccm
