### ISSUE TITLE
CRC32 IEEE?

### ISSUE THREAD

**Issue by nullpixel** [krzyzanowskim/CryptoSwift#346]
I don't see any reference for me to use a IEEE with CRC32 :/

**Comment by krzyzanowskim** [comment]
Im not sure if I understand the qurestion

**Comment by nullpixel1** [comment]
It's a type of seed that can be used with CRC. https://golang.org/pkg/hash/crc32/

**Comment by nullpixel** [comment]
wow! ancient issue, but thanks for fixing nonetheless

**Comment by krzyzanowskim** [comment]
;) happened got PR in this area so I took a look in the issues :) https://github.com/krzyzanowskim/CryptoSwift/pull/609
