### ISSUE TITLE
xcode 8 + Swift 3 - getting error while building a project 

### ISSUE THREAD

**Issue by MayurKala0903** [krzyzanowskim/CryptoSwift#348]
1. Value of type 'Data' has no member 'arrayOfBytes'
2. Value of type 'Data' has no member 'base64EncodedStringWithOptions'

also getting other errors like -  Extra argument 'padding' in call, this i am getting in a String extension class within function aesEncrypt and aesDecrypt

**Comment by krzyzanowskim** [comment]
depend how you build it, its probably gow you setup your project. The code compile with Swift 3 without errors and warnings.
