### ISSUE TITLE
Problem with Random on Linux

### ISSUE THREAD

**Issue by jeffreybergier** [krzyzanowskim/CryptoSwift#352]
Hi,

I'm trying to write a simple piece of code that AES encrypts a passcode with a key and IV. The key and IV are generated randomly every time. This code works fine on macOS. But on Linux, the random keys are the same every time the program runs. I have had this problem before. The basic random functions on linux are Turnstile in nature. I found a solution with my own code. It was a basic class that opened /dev/random and read bits off of it on demand. I was wondering if you would be interested in a PR for Multiplatform.swift where the linux aspect of randomization was replaced with this randomizer I've been using on linux.

The code is originally from https://github.com/stormpath/Turnstile/blob/master/Sources/TurnstileCrypto/URandom.swift but I removed everything that wasn't needed in order to replicate the functionality of getting a certain number of random bytes.

``` swift
public class URandom {
    private let file = fopen("/dev/urandom", "r")
    
    /// Initialize URandom
    public init() {}
    
    deinit {
        fclose(file)
    }
    
    private func read(numBytes: Int) -> [Int8] {
        // Initialize an empty array with numBytes+1 for null terminated string
        var bytes = [Int8](repeating: 0, count: numBytes + 1)
        fgets(&bytes, numBytes + 1, file)
        
        bytes.removeLast()
        
        return bytes
    }
    
    /// Get a byte array of random UInt8s
    public func random(numBytes: Int) -> [UInt8] {
        return unsafeBitCast(read(numBytes: numBytes), to: [UInt8].self)
    }
}
```

**Comment by jeffreybergier** [comment]
Oops. I didn't realize that crypto swift doesn't actually use its own random function. That said, I forked and added the random class and adjusted the random function on Cryptor. I'm closing this issue and submitting a PR.

**Comment by colemancda** [comment]
@jeffreybergier Where can I find your PR? Was it merged?

**Comment by krzyzanowskim** [comment]
@colemancda not merged. This is what you're looking for:  https://github.com/krzyzanowskim/CryptoSwift/commit/d3f8c7234a2fa857502be3ba7f8f56a1f50f6b63 available on `develop` branch as of today.

**Comment by jeffreybergier** [comment]
@colemancda I ended up just including CryptoSwift and TurnstileCrypto in my project. TurnstileCrypto has the good random number generator for Linux. 

https://github.com/stormpath/Turnstile

I also formed cryptoswift and removed the dangerous random function it contains. 

https://github.com/jeffreybergier/CryptoSwift

**Comment by krzyzanowskim** [comment]
@jeffreybergier something wrong with RandomBytesSequence ?

**Comment by jeffreybergier** [comment]
@krzyzanowskim oh no. I didn't even know about that branch. I was working off of master. Is there a way to tell SPM to use a branch other than master?

**Comment by krzyzanowskim** [comment]
its part of 0.6.1 available now.

**Comment by jeffreybergier** [comment]
@krzyzanowskim that appears to have worked and my tests are all passing! thanks!!!
