### ISSUE TITLE
HMAC md5 authenticate invalid [UInt8] result

### ISSUE THREAD

**Issue by ianmoses** [krzyzanowskim/CryptoSwift#354]
In Swift 3 for ios 10, I am struggling to use the [UInt8] result from HMAC md5 authenticate function:
let hashedBytes: Array<UInt8> = try HMAC(key: concatonatedKey, variant: .md5).authenticate(bytes)

where: 
let bytes: Array<UInt8> = myString.utf8.map({$0})
and:
concatenatedKey is type String (i.e. "someStringUsedAsHashKey")

Trying to convert hashedBytes back to String to send to use in Web Service JSON request using:
let str = String(bytes: hashedBytes, encoding: .utf8)

After trying to debug, I am able to convert bytes variable (type is also Array<UInt8>) back to valid String. This is making me think there is a problem in the HMAC md5 authenticate function causing it to return an invalid [UInt8] result.

Please let me know if more information is required, any help is much appreciated.

**Comment by krzyzanowskim** [comment]
whatever tou want to send back, for sure it's not String formed out of hash bytes. You probably need it in form of hex OR Base64 encoded. Check Readme for hex notation.

**Comment by ianmoses** [comment]
@krzyzanowskim 

Thank you for the quick reply and you are correct, was incorrectly assuming the base64 string we got was also incorrect as it also wouldn't convert to a string. 

Real lapse in recognition that this is the exact point of a keyed hash, that the original string is not reproducible. 

However, the real reason for the incorrect (non-nil) base64 value was something we else. Escape characters in strings are not removed automatically when converting to [UInt8]. As a result, we were feeding an invalid JSON into the authenticate method. Example: 

Intended for using in method as [UInt8]:
"{\"User\":{\"DeviceType\":\"Apple\",\"DeviceModel\":\"iPhone 6 Plus\",\"DeviceDisplayMetrics\":\"screenWidth x screenHeight (points):414.0 x 736.0\",\"OSVersion\":\"10.0.2\"}}"

What was actually being used in method (solution was to create a different string for converting to [UInt8] for use by removing \\ throughout string )
"{\\\"User\\\":{\\\"DeviceType\\\":\\\"Apple\\\",\\\"DeviceModel\\\":\\\"iPhone 6 Plus\\\",\\\"DeviceDisplayMetrics\\\":\\\"screenWidth x screenHeight (points):414.0 x 736.0\\\",\\\"OSVersion\\\":\\\"10.0.2\\\"}}"

Wanted to provide in the event it was in any way informative, thank you again :)

**Comment by krzyzanowskim** [comment]
thanks, maybe somebody will have similar problem and your explanation will be helpfull.
