### ISSUE TITLE
Cannot compile via Pods (swift12)

### ISSUE THREAD

**Issue by eneko** [krzyzanowskim/CryptoSwift#36]
I added this to my Podfile, but the framework does not compile:

    pod 'CryptoSwift', :git => 'https://github.com/krzyzanowskim/CryptoSwift.git', :branch => 'swift12'

Here are some of the errors I'm getting:
```
.../Pods/CryptoSwift/CryptoSwift/Authenticator.swift:21:37: Use of undeclared type 'CryptoSwift'
.../Pods/CryptoSwift/CryptoSwift/Authenticator.swift:31:20: Use of unresolved identifier 'CryptoSwift'
.../Pods/CryptoSwift/CryptoSwift/Cipher.swift:42:30: Use of unresolved identifier 'CryptoSwift'
```

Any ideas?

**Comment by krzyzanowskim** [comment]
cocoapods 0.36 ?

**Comment by arctouch-ecilteodoro** [comment]
I installed it as a submodule. Not using cocoapods. Even though, i got this error.  
`Use of unresolved identifier: Cipher`  
`let ivData : NSData = Cipher.randomIV(keyData)`

**Comment by krzyzanowskim** [comment]
strange, can you send me over the sample project?

**Comment by krzyzanowskim** [comment]
New version available.
