### ISSUE TITLE
Getting EXC_BAD_ACCESS while using CryptoSwift

### ISSUE THREAD

**Issue by darshb** [krzyzanowskim/CryptoSwift#361]
Hi,
I am writing very simple code for encryption. I want to encrypt large pdf files. However, to start with I have taken very small file (12 KB). I am using CryptoSwift for encryption. Working with streams. I am getting mentioned error for this line from AES.Swift file "**# for idx in stride(from: expanded.startIndex, to: expanded.endIndex, by: 4) "** 

Please find my simple code below:

``` swift
import CryptoSwift
import UIKit
import Foundation


class ViewController: UIViewController {
    var outputStream:OutputStream? = OutputStream(toMemory: ())
    var ivArray: [UInt8] = [UInt8]()
    var keyArray: [UInt8] = [UInt8]()

override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.
         let pdfPath = Bundle.main.path(forResource: "Test5", ofType: "pdf")
        do{
            let myData:NSData = try NSData(contentsOfFile:pdfPath!)
            let count = (myData.length) / MemoryLayout<UInt8>.size
            // create an array of Uint8
            var array = [UInt8](repeating: 0, count: count)
             // copy bytes into array
            myData.getBytes(&array, length:count * MemoryLayout<UInt8>.size)
            outputStream?.open()
            //print(array)
             let ivSlice = array[0..<16]
             ivArray = Array<UInt8>(ivSlice)
             let keySlice = array[16..<32]
             keyArray = Array<UInt8>(keySlice)
            self.writeTo(stream: outputStream!, bytes: array)
            }catch{
            print("error")
        }
    }

    func writeTo(stream: OutputStream, bytes: Array<UInt8>) {
        var writtenCount = 0
      while stream.hasSpaceAvailable && writtenCount < bytes.count {
            let c = stream.write(bytes, maxLength: bytes.count)
            if c <= 0 {
                break;
            }
            writtenCount += stream.write(bytes, maxLength: bytes.count)
        }
        do{
            let aes = try AES(key: keyArray, iv: ivArray)
            var encryptor = aes.makeEncryptor()

            // prepare streams
            let data = Data(bytes: (0..<100).map { $0 })
            let inputStream = InputStream(data: data)
            let outputStream = OutputStream(toMemory: ())
            inputStream.open()
            outputStream.open()
            var buffer = Array<UInt8>(repeating: 0, count: 2)
            // encrypt input stream data and write encrypted result to output stream
            while (inputStream.hasBytesAvailable) {
                let readCount = inputStream.read(&buffer, maxLength: buffer.count)
                if (readCount > 0) {
                    try encryptor.update(withBytes: buffer[0..<readCount]) { (bytes) in
                        writeTo(stream: outputStream, bytes: bytes)
                    }
                }
            }
            // finalize encryption
            try encryptor.finish { (bytes) in
                writeTo(stream: outputStream, bytes: bytes)
            }
           // print result
            if let ciphertext = outputStream.property(forKey: Stream.PropertyKey(rawValue: Stream.PropertyKey.dataWrittenToMemoryStreamKey.rawValue)) as? Data {
                print("Encrypted stream data: \(ciphertext.toHexString())")
            }
         }catch{
     }
   }
  override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
}
```

**Comment by krzyzanowskim** [comment]
Can you please make a playground (or copy paste code ready to run) so I can possibly reproduce the issue? At this point you may get this crash out of anything.

**Comment by darshb** [comment]
Hi,

This is my working code which i have copied from ViewController.swift. You just need to replace pdf file which will reside in app bundle. For now, i just want to check ciphertext in console.
Please let me know if you need any aditional information.

**Comment by krzyzanowskim** [comment]
I cannot reproduce such issue. Please separate the problem if possible. With input values (key etc)
Have you looked at this example  https://github.com/krzyzanowskim/CryptoSwift/blob/master/CryptoSwift.playground/Contents.swift#L121 how stream is handled? it's available as a part of the Xcode project.

**Comment by darshb** [comment]
I have taken code from the example you mentioned for reference.

Please find key below:
key :  [243, 160, 208, 196, 198, 10, 52, 32, 48, 32, 111, 98, 106, 10, 60, 60]
iv :  [37, 80, 68, 70, 45, 49, 46, 51, 10, 37, 196, 229, 242, 229, 235, 167]

![screen shot 2016-10-21 at 6 08 58 pm](https://cloud.githubusercontent.com/assets/5258923/19598653/87a65a70-97b9-11e6-9cac-4aed7106570a.png)

**Comment by krzyzanowskim** [comment]
ok, are you able modify playground input that it will cause this issue? or send me a project to investigate. I have no clue what might me an issue.

**Comment by darshb** [comment]
Hi,
Apologies for delay in reverting back.
The project size is too big. Is it fine if I just upload ViewController.swift file. My code resides in that single file.

**Comment by krzyzanowskim** [comment]
@darshb simple Playground would work best. Can't confirm it's CryptoSwift issue for now.

**Comment by krzyzanowskim** [comment]
Any update? I can't reproduce issue with CryptoSwift
