### ISSUE TITLE
Trying with Large file size

### ISSUE THREAD

**Issue by sagarj3036** [krzyzanowskim/CryptoSwift#362]
Hi, I am trying with 20 mb large file in size. I am able to encrypt it and I have created encrypted file in documents folder. But the problem is encrypted file from documents directory is in double in size from the original one. Please let me know your inputs how to avoid this file size issue?
Original File 21 Mb
Encrypted File in documents directory: 42 MB

**Comment by krzyzanowskim** [comment]
depends what's in your code... hard to say why you get twice as big file. Maybe you append decrypted data twice somewhere?

**Comment by sagarj3036** [comment]
Thanks for the help. Please take a look at my code. and let me know if I need to make any correction
this is myViewcontroller class:


class ViewController: UIViewController, StreamDelegate {

    var inputStream: InputStream?

    let bufferSize = 10 * 1024

    var count = 0
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.
        
        let file = Bundle.main.path(forResource:"sample", ofType: "txt")
        let text = try? String(contentsOfFile: file!, encoding: .utf8)

        inputStream = InputStream(data: (text?.data(using: .utf8))!)
       // inputStream?.delegate = self

        inputStream?.schedule(in: RunLoop.current, forMode: RunLoopMode.defaultRunLoopMode)
        inputStream?.open()

        
        
        while (inputStream?.hasBytesAvailable)! {
            var buffer = Array<UInt8>(repeating: 0, count: bufferSize)
            let readCount = inputStream?.read(&buffer, maxLength: bufferSize)
            print("Read Count",readCount)
            if (readCount! > 0) {

                let output = NSString(bytes: &buffer, length: readCount!, encoding:String.Encoding.utf8.rawValue)
                self.doEncrypt(chunkdata: output as! String)
            }
        }
        
        
        
        
       // print("Text 1",text)
     //    let data = text?.data(using: String.Encoding.utf8)
        
        
    }

    
    
    
    
    
    func stream(_ stream: Stream, handle eventCode: Stream.Event) {
        switch eventCode {
        case Stream.Event.hasBytesAvailable:
           print("hasBytesAvailable")
           
           
           if let iStream = stream as? InputStream{
            var buffer = Array<UInt8>(repeating: 0, count: bufferSize)
            
            let bytesRead = iStream.read(&buffer, maxLength: bufferSize)
            if bytesRead >= 0 {
                let output = NSString(bytes: &buffer, length: bytesRead, encoding:String.Encoding.utf8.rawValue)
                self.doEncrypt(chunkdata: output as! String)
            } else {
                // Handle error
            }
            
           }

           
            break
            
        default:
            break
            
            
        }
        
    }
    
    func doEncrypt(chunkdata:String){
        do {
            
            print("doEncrypt",count)
            count = count+1
            print(NSDate())
            
            let aes = try AES(key: "passwordpassword", iv: "drowssapdrowssap") // aes128
            //  let ciphertext = try aes.encrypt(data?.map({$0}))
            let ciphertext = try aes.encrypt(chunkdata.utf8.map({$0}))
            
            
            
            
            
                writetoFile(text: ciphertext.toHexString())

           // print("Text 2", ciphertext.toHexString())
        } catch { }
        

    }

    
    func writetoFile(text:String){
        do {
            print("writetoFile 1")
            let documentDirectoryURL = try FileManager.default.url(for: .documentDirectory, in: .userDomainMask, appropriateFor: nil, create: true)
            // create the destination url for the text file to be saved
            let fileDestinationUrl = documentDirectoryURL.appendingPathComponent("file.txt")
            
            do {
                print("writetoFile 2")

                // writing to disk
                if let outputStream = OutputStream(url: fileDestinationUrl, append: true) {
                    outputStream.open()
                    print("writetoFile 3")

                    let bytesWritten = outputStream.write(text, maxLength: text.lengthOfBytes(using: .utf8))
                    if bytesWritten < 0 { print("write failure") }
                    outputStream.close()
                    print("writetoFile 4")

                } else {
                    print("Unable to open file")
                }
                
                
                
                
            } catch let error as NSError {
                print("error writing to url \(fileDestinationUrl)")
                print(error.localizedDescription)
            }
        }catch let error as NSError {
            print("error getting documentDirectoryURL")
            print(error.localizedDescription)
        }
    }

     override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }

}

**Comment by sagarj3036** [comment]
Ok...I w did  in the way which you suggested. But I have 500 mb file size.. I t takes approx 40 min to encrypt. Can you please suggest way to do the same please :)

**Comment by krzyzanowskim** [comment]
500mb is quite a lot of data to process indeed. Verify in Release configuration, or go with CommonCrypto.

**Comment by sagarj3036** [comment]
How to set mode AES 256 in CryptoSwift?

**Comment by krzyzanowskim** [comment]
use 32-bytes long key.

**Comment by sagarj3036** [comment]
Which key? and where to set?

**Comment by krzyzanowskim** [comment]
AES key
