### ISSUE TITLE
[0.6.2]sha1() isn't working correctly

### ISSUE THREAD

**Issue by CodeEagle** [krzyzanowskim/CryptoSwift#363]
As i checked, it works < release 0.6.2

**Comment by krzyzanowskim** [comment]
what exactly is the problem?

**Comment by CodeEagle** [comment]
![image](https://cloud.githubusercontent.com/assets/2311352/19644691/c39ec26c-9a23-11e6-8d0a-2fcbfe145428.png)

playground from project 0.6.2

**Comment by CodeEagle** [comment]
```
let target = "1477304791&1XpnGSRhOlZz2etXMeOdfNaHILTjW16U&8mpBBbzwsgs"
let expect = "0809bbf8489c594131c2030a84be364a0851a635"
let result = target.sha1()// "f6dec801275ac2be2e5ab72ae6838fe6c3011d66"
```
`0809bbf8489c594131c2030a84be364a0851a635` is what expected,
[sha1-online](http://www.sha1-online.com/)

**Comment by krzyzanowskim** [comment]
Thx. I broke it yesterday by changing bitPadding common function. Will prepare hotfix as soon as possible

**Comment by krzyzanowskim** [comment]
0.6.3 will be available in minutes. Should be ok with this change.

**Comment by krzyzanowskim** [comment]
Released https://github.com/krzyzanowskim/CryptoSwift/releases/tag/0.6.3
@CodeEagle pls verify and let me know if it's ok on your side.

**Comment by CodeEagle** [comment]
Ok, works again!
