### ISSUE TITLE
Encryption not working

### ISSUE THREAD

**Issue by sagarj3036** [krzyzanowskim/CryptoSwift#365]
while true{
                let inputData = inputFileHandle.readData(ofLength: bufferSize)
                
                if inputData.isEmpty {
                    print("data empty")
                    break
                }
                // perform action
                let outputData: NSData
                if willEncrypt{
                    outputData = encrypt(data: inputData) as NSData
                }
                else{
                    outputData = decrypt(data: inputData) as NSData
                }
                outputFileHandle.write(outputData as Data)
            }
 func encrypt(data: Data) -> Data {
        do {
            let aes = try AES(key: "passwordpassword", iv: "drowssapdrowssap") // aes128
            let ciphertext = try aes.encrypt(data)
            let data:Data? = Data(bytes: ciphertext,count: ciphertext.count)
            
            if let d = data{
                return d
            }
        }
        catch {
        
        }
        
        return Data()
    }

Hi,
If I use two different bufferSizes then encryption does not matches. Please let me know why the 2 encryptions with two different buffer sizes doesn't match?

**Comment by krzyzanowskim** [comment]
I dont know, does it use CryptoSwift at all?. Please dont make me analyse your code ang guess where is problem. Please make it strict and easy to reproduce f you believe its CryptoSwift fault, not your code/wrappers

**Comment by krzyzanowskim** [comment]
you should use incremental updates NOT encrypt each buffer separately, because its different operation and wont match by cipher design.

**Comment by sagarj3036** [comment]
Sorry. But What do you mean by incremental updates

**Comment by krzyzanowskim** [comment]
its described in README, with examples.
