### ISSUE TITLE
PKCS5 padding support

### ISSUE THREAD

**Issue by hfossli** [krzyzanowskim/CryptoSwift#367]
Thank you for open sourcing this library. <3 Seems very nice.

I see the implementation of PKCS5.swift is only a enum definition. 
```swift
public enum PKCS5 {
    //  PKCS#5 http://tools.ietf.org/html/rfc2898
}
```

And when trying to use it it fails
![skjermbilde 2016-10-28 kl 14 53 04](https://cloud.githubusercontent.com/assets/3652587/19807000/49139dc6-9d1e-11e6-8ae2-2f27d4daeaea.png)

Whereas PKCS7 compiles fine
![skjermbilde 2016-10-28 kl 14 53 34](https://cloud.githubusercontent.com/assets/3652587/19807019/58093174-9d1e-11e6-9e61-03b14d7491ee.png)

If I understand this correctly support for PKCS5 padding is missing.

**Comment by krzyzanowskim** [comment]
PKCS5 padding is a subset of PKCS7, just use PKCS7()
