### ISSUE TITLE
HMAC sha256 convert to string always nil

### ISSUE THREAD

**Issue by dbpfindexp** [krzyzanowskim/CryptoSwift#371]
Wondering if anyone has problems hmac sha256 variant?  Maybe I'm doing something wrong but I keep getting nil when i try to convert it to a string.

Here's my code
```
        let byteArray: Array<UInt8> = "Test".utf8.map({$0})
        let tokenBytes = try HMAC(key: "SECRET_KEY", variant: HMAC.Variant.sha256).authenticate(byteArray)
        let tokenString = String.init(data: Data.init(bytes:tokenBytes), encoding: String.Encoding.utf8)
```
tokenString is always null.

I'd like it to return `fe4887d1c4b769124e082d4665a51b674b0aa56833efe80400d2029a397f4e94`

**Comment by dbpfindexp** [comment]
Saw previous issue, closing.

**Comment by krzyzanowskim** [comment]
;-) `tokenBytes.toHexString()` is probably what you're looking for

**Comment by dbpfindexp** [comment]
Thanks @krzyzanowskim I did some additional googling and found the closed issue.  Great response time FYI. :)
