### ISSUE TITLE
Build fails on Xcode 8.2

### ISSUE THREAD

**Issue by cikpis** [krzyzanowskim/CryptoSwift#376]
Just set `yes` the `Use Legacy Swift Language Version` and then put it back to `no`.

This is gonna update your .xproject file and fix the error.

**Comment by krzyzanowskim** [comment]
Christ, Xcode is insane with this settings. I stop build with Xcode 8.1 - without good reason.

**Comment by cikpis** [comment]
Yep I know :) Image me that I have to report this to all my dependencies :)

**Comment by krzyzanowskim** [comment]
Fixed in 94f3e347e7bfaed24115d16b205ede4eb1a81633

**Comment by cikpis** [comment]
Cool! Can I find in the 0.6.6 version or I need to wait the 0.6.7?

**Comment by krzyzanowskim** [comment]
just get the master for now. There is not much to do next release right away. I'll think about it though.
