### ISSUE TITLE
Build Fail for CryptoSwift 0.6.6 with Carthage

### ISSUE THREAD

**Issue by sakura83102** [krzyzanowskim/CryptoSwift#379]
when I run command: carthage update --platform iOS, get fail with attached screenshot.

i tried the swift version 3.0, it's fail, then i updated xcode 8.2 with swift 3.0.2 but still fail

![fail](https://cloud.githubusercontent.com/assets/1661835/21223077/5235ca48-c300-11e6-9564-e6b54893212b.png)

**Comment by krzyzanowskim** [comment]
Duplicate #376 #378
