### ISSUE TITLE
Xcode 8.2 wants to code sign for simulator, fails

### ISSUE THREAD

**Issue by p2** [krzyzanowskim/CryptoSwift#380]
I have a setup where CryptoSwift is a submodule in my app repository, along with other Swift frameworks. They are a dependency and are linked and embedded into the app.

Since Xcode 8.2, whenever I try to run the app in the simulator, Xcode starts building CryptoSwift but fails with:

> Command /usr/bin/codesign failed with exit code 1
> Signing Identity:     "-"

This does **not** happen with the other frameworks. I have set Xcode to handle signing automatically. The issue also doesn't occur when running on device.

Even funnier, when I select the CryptoSwift target, hit CMD + B, then select the app target and hit run, it works. So, right now, to run the app I have to build CryptoSwift manually, then I can run the app.

I have no idea what's going on and have tried removing and re-adding CryptoSwift. The only difference I can see when looking at _Embed Frameworks_ is that CryptoSwift is listed as:

    CryptoSwift.framework  ...in build/Debug

while all other frameworks are listed as:

    Other.framework  ...in build/Debug-iphoneos

This is likely not the fault of CryptoSwift, putting it here in case others are hit by it and in the hopes somebody knows what's going on and has a fix. Thanks for an awesome framework!

**Comment by krzyzanowskim** [comment]
I wonder if single scheme setup is related: http://promisekit.org/news/2016/08/Multiplatform-Single-Scheme-Xcode-Projects/ 
Can you please, just for testing purpose check any of the dependency from the article?

**Comment by p2** [comment]
I tried, but I now have the “problem” that the issue does not occur on a fresh checkout on my one Mac, while it still does occur on a fresh checkout on the other Mac...

**Comment by krzyzanowskim** [comment]
I like that "problem". Will close this one, feel free to comment it in case you find out something new in that regard

**Comment by p2** [comment]
Sounds good, thanks.
