### ISSUE TITLE
Compile time

### ISSUE THREAD

**Issue by iwheelbuy** [krzyzanowskim/CryptoSwift#381]
Sometimes I check my code compile time to find out slow functions and fix them.
I've just started using you framework and accidentally found that there are some slow functions.
So, I've decided that you should know about it. Don't hesitate to close the issue

**935.0ms** _AES.swift final func expandKeyInv_
**1053.3ms** _SHA1.swift fileprivate final func process_

That is the way I check compile time:

_xcodebuild -workspace YOUR_WORKSPACE_NAME.xcworkspace -scheme YOUR_SCHEME_NAME -sdk iphonesimulator -arch x86_64 -configuration Debug clean build OTHER_SWIFT_FLAGS="-Xfrontend -debug-time-function-bodies" | grep '^[0-9]\{3,20\}.[0-9]\{1,20\}ms'_

**Comment by krzyzanowskim** [comment]
¯\_(ツ)_/¯ Swift compiler

**Comment by krzyzanowskim** [comment]
I'm closing for now. Couldn't figure out how to please swiftc without affecting runtime performance and without introducing code ugliness.
