### ISSUE TITLE
EXC_ARM_BREAKPOINT on iOS 8 - iPhone 5c

### ISSUE THREAD

**Issue by pietrocaselani** [krzyzanowskim/CryptoSwift#382]
I am facing a issue that I think its an overflow.
Running this code
```swift
let encrypted = try? Blowfish(key: key, blockMode: .CBC, padding: PKCS7()).encrypt(json.utf8.map({$0}))
```
the execution stops on this function:
```swift
private func F(x: UInt32) -> UInt32 {
        return ((self.S[0][Int(x >> 24) & 0xFF] &+ self.S[1][Int(x >> 16) & 0xFF]) ^ self.S[2][Int(x >> 8) & 0xFF]) &+ self.S[3][Int(x) & 0xFF]
    }
```
The message is: `Thread 1: EXC_BREAKPOINT (code=EXC_ARM_BREAKPOINT, subcode=0xe7ffdefe)`

The same code runs fine on iPhone SE, iPhone 6S, using iOS 10.2 and 10.1.
I tried to modify the code based on the answers on [Stackoverflow](http://stackoverflow.com/questions/29434253/xcode-exc-breakpoint-exc-arm-breakpoint-subcode-0xe7ffdefe), but I was not lucky.

**Comment by krzyzanowskim** [comment]
thanks!

eh Swift and machine based length of the Int: http://blog.krzyzanowskim.com/2014/09/09/swift-integer-overflow-issue/

I'll look at it.
