### ISSUE TITLE
precondition failed on Chacha20

### ISSUE THREAD

**Issue by abiaad** [krzyzanowskim/CryptoSwift#383]
On Ubuntu 14.04 when 
``` ChaCha20(key: key, iv: iv)```

I have a crash with : *precondition failed: file CryptoSwift-0.6.7/Sources/CryptoSwift/ChaCha20.swift, line 23*

**Comment by krzyzanowskim** [comment]
precondition(nonce.count == 12 || nonce.count == 8)

**Comment by abiaad** [comment]
Yes I read that.
**key** and **iv** are strings in my implementation. It was working like 1 month ago. Is there something to do on my side ?

**Comment by krzyzanowskim** [comment]
what is your iv? check that value

**Comment by krzyzanowskim** [comment]
I'm closing this one.
