### ISSUE TITLE
Swift compiler warnings

### ISSUE THREAD

**Issue by mikecorlett** [krzyzanowskim/CryptoSwift#384]
Using xcode 8.2 I get compiler warnings from the evaluateScript calls, e.g. 

cryptoJScontext?evaluateScript(cryptoJS)
the warning is: Expression of type JSValue? is unused

the fix seems to be to change the lines to

let _ = cryptoJScontext?evaluateScript(cryptoJS)

Any comments? 

Thanks

**Comment by krzyzanowskim** [comment]
This is not a CryptoSwift code

**Comment by mikecorlett** [comment]
I do apologise! I got my projects mixed up.

**Comment by krzyzanowskim** [comment]
No worries. Try CryptoSwift now :-)

**Comment by mikecorlett** [comment]
Yep :) Thanks.
