### ISSUE TITLE
no bug,help me! thank

### ISSUE THREAD

**Issue by isxiaohu** [krzyzanowskim/CryptoSwift#387]
older version code is  try! clearText.encrypt(AES(key: secret, iv: "", blockMode: .ECB)).toBase64()!    How about new version?

**Comment by krzyzanowskim** [comment]
This code should compile, what is the problem?

(It depends on what type of `clearText` is)

**Comment by isxiaohu** [comment]
String

**Comment by isxiaohu** [comment]
let encrptString:String = try! clearText.encrypt(cipher: cipher) is 16，I need Base64 string,Older version code is  
 // let encrptString: String = try! clearText.encrypt(cipher: AES(key: secret, iv: "", blockMode: .ECB)).toBase64()!
but new version toBase64 func not have.

**Comment by isxiaohu** [comment]
sorry，I m English is not good,thank you reply

**Comment by krzyzanowskim** [comment]
The result is already base64 string, see [String+Extension.swift#L50](https://github.com/krzyzanowskim/CryptoSwift/blob/master/Sources/CryptoSwift/String%2BExtension.swift#L50)

```swift
try "txt".encrypt(cipher: AES(key: "passwordpassword", iv: "drowssapdrowssap", blockMode: .ECB))
```

**Comment by krzyzanowskim** [comment]
if you want base64 you should use `Array(clearText.utf8).encrypt(...).toBase64()`

**Comment by isxiaohu** [comment]
let cipher = try! AES(key: secret, iv: "", blockMode: .ECB)
let encrptString:String = try! clearText.encrypt(cipher: cipher)
result is 3a7f9cb0e58645171345a0215f289d879fd7f52fdf4ab8179a3ab41190e6e4e6,
but older version code swift < 3.0
//        let encrptString: String = try! clearText.encrypt(cipher: AES(key: secret, iv: "", blockMode: .ECB)).toBase64()!
result is  On+csOWGRRcTRaAhXyidh5/X9S/fSrgXmjq0EZDm5OY=  (this is right)

**Comment by isxiaohu** [comment]
work out，good man,thank very very very mach~
