### ISSUE TITLE
Please Provide some Demo in case of File encryption and decryption.

### ISSUE THREAD

**Issue by shree007** [krzyzanowskim/CryptoSwift#388]
Please Provide some Demo in case of File encryption and decryption.

**Comment by krzyzanowskim** [comment]
Load file data and encrypt it.

```swift
do {
    let aes = try AES(key: "passwordpassword", iv: "drowssapdrowssap")
    let fdata = Data.init(contentsOf: URL.init(fileURLWithPath: "/path/file.dat")).encrypt(cipher: aes)
} catch {

}
```

**Comment by shree007** [comment]
Thank you Sir ,Actually  I want to make an iOS app,User will lock a file with password and open that file using same password. Can you give me some idea in swift? Previous one I tried but i had not helped.
