### ISSUE TITLE
Help translating this code from Swift 2.3 to 3.0

### ISSUE THREAD

**Issue by Dmaradan** [krzyzanowskim/CryptoSwift#391]
Hey all, I've been using this repo with great success up until changing to the 3.0 master branch.
Authenticator/HMAC/NSData seem to have undergone changes that break my code:

let key = user.secret
        let msg = message
        
        var keyBuff = [UInt8]()
        keyBuff += key.utf8
        
        var msgBuff = [UInt8]()
        msgBuff += msg.utf8
        
        let hmac = try! Authenticator.HMAC(key: keyBuff, variant: .sha256).authenticate(msgBuff)
        
        let ACCESS_SIGNATURE = NSData.withBytes(hmac).hexadecimalString

I tried doing this instead for the last two lines:

        let hmac = try! HMAC(key: keyBuff, variant: .sha256).authenticate(msgBuff)

        let ACCESS_SIGNATURE = Data(bytes: Digest.sha256(hmac)).base64EncodedString()

These lines compile but I'm not getting a matching value for my Access Sig as the one being generated in the server. The Swift 2 code works, but not this one. Any help is very, very appreciated.

**Comment by krzyzanowskim** [comment]
one remark: base64 != hex string

**Comment by Dmaradan** [comment]
Yes sorry, I've since changed it to

let ACCESS_SIGNATURE = Data(bytes: Digest.sha256(hmac)).hexadecimalString

But I'm still getting a wrong value. Do you think it's the initial part of the expression? Do these two expressions do the same thing?

"Data(bytes: Digest.sha256(hmac))" and "NSData.withBytes(hmac)"

**Comment by Dmaradan** [comment]
Sorry guys, I had a brainfart. It was just this:

let ACCESS_SIGNATURE = Data(bytes: hmac).hexadecimalString

**Comment by krzyzanowskim** [comment]
solved?
