### ISSUE TITLE
HMC256 from and to string (besides bytes)

### ISSUE THREAD

**Issue by SnitramDev** [krzyzanowskim/CryptoSwift#392]
HMC256 is only created using bytes. Could you please add support from and to strings?
It could be used as a string extension.

**Comment by krzyzanowskim** [comment]
string to byte conversion is as simple as this:
```swift
Array("string".utf8)
```

I can't be just bytes -> string because result bytes don't necessarly form valid string, hence that need further encoding (base64, or hex).
