### ISSUE TITLE
Cannot decrypt AES; "Bad magic number"

### ISSUE THREAD

**Issue by jimidobson** [krzyzanowskim/CryptoSwift#394]
I'm having issues decrypting a database file encrypted via AES.

I have a database that I am loading in as a Data object. I then pass this into the AES.encrypt():

```
let data = try Data(contentsOf: URL(fileURLWithPath: databasePath))
let aes = try AES(key: "password", iv: "1234567891234567") // aes128
let encryptedData = Data(data)
                
let encryptedFilename = file + ".aes"
                
savePath = self.fetchDocPath() + "/" + encryptedFilename
let finalFilePath = URL(fileURLWithPath: savePath)
try encryptedData.write(to: finalFilePath, options: .atomic)

```

This successfully creates the file, but nothing I do will allow me to decrypt it outside of Swift. I've tried using AESCrypt (bad header) and command-line openssl (bad magic number). I have also tried copying verbatim the example given in this project's playground:

```
let aes = try AES(key: "passwordpassword", iv: "drowssapdrowssap") // aes128
                let ciphertext = try aes.encrypt(Array("Nullam quis risus eget urna mollis ornare vel eu leo.".utf8))
let encryptedData = Data(ciphertext)
```

with the same file-writing logic.

I'm at a loss as to what I'm doing wrong; I'm not sure if I'm writing the data incorrectly or decrypting it incorrectly. If Id the entire process in reverse, i.e. I then immediately decrypt the encrypted data in Swift, I can write the resulting data to a .db file and I can open it just fine.

Can anyone suggest where I'm going wrong? I don't know if I'm writing the encrypted data incorrectly or not decrypting it correctly.

**Comment by krzyzanowskim** [comment]
Check this out https://github.com/krzyzanowskim/CryptoSwift/issues/249#issuecomment-217199078

**Comment by jimidobson** [comment]
I'm not sure I understand? I'm generating the AES file via this library, not openssl (although I am attempting to decrypt it via openssl). Also, I've tried encryption using the aes.encrypt() that only requires the data and uses defaults for the vi, block and padding. The same issue occurs.

If I'm not initialising the vi correctly from my code, could you please guide me? As far as I'm aware, the vi in my code above matches what AES.blocksize() returns anyway.

**Comment by jimidobson** [comment]
So I've looked further into this; I can save the data to a file as above, but this time, I've loaded the file back into Swift and run the decryption on the data. Once decrypted, I then save teh data back to disk as a new file, exactly the same way that I save the encrypted data.

The resulting decrypted file works fine and I can open it as a database.

This suggests that the library encryption/decryption process seems to work as long as only the library touches it, but the output is not being recognised by any other exterior AES decryption software or utility. Is this intentional or am I misunderstanding?

**Comment by krzyzanowskim** [comment]
No, it's not the case.
Can you attach project with the code with CryptoSwift and OpenSSL? I can take a look at this.

**Comment by krzyzanowskim** [comment]
is  `let encryptedData = Data(data)` a typo? because it's not encrypted `data` here.

**Comment by jimidobson** [comment]
Yep, sorry, that was a typo.

Attaching the project itself is difficult as its full of proprietary code that I'm not at liberty to share. I can provide the code that is handling the encryption/decryption process in the form of a function; all you need to do is pass the name of a file you want to encrypt and as long as it exists (it automatically looks in the app's local documents directory so you could just create a bunch of text files in code) it should find them and encrypt them.

I've commented out the stuff that isn't being used so it's as simple as possible:

```
public func encrypt(with files: [String]) throws {
        print("ENCRYPTING...")
        
        for (file) in files {
            do {
                //let password = genRandom(with: characterPool, numberOfCharacters: self.passwordLength)
                //let passwordFileName = file + ".txt"
                print("Generating password...")
                //generate a new password for this file
                
                //var savePath:String = fetchDocPath() + "/" + passwordFileName
                //try String(cString: password).write(toFile: savePath, atomically: false, encoding: String.Encoding.utf8)
                
                //encrypt the file using this password
                print("Encrypting database...")
                let databasePath = self.fetchDocPath() + "/" + file
                let data = try Data(contentsOf: URL(fileURLWithPath: databasePath))

                //let iv = genRandom(with: characterPool, numberOfCharacters: AES.blockSize)
                
                let aes = try AES(key: "password", iv: "passwordpassword", blockMode: .CBC) // aes128
                
                let encryptionOutput = try aes.encrypt(data.bytes)
                
                let encryptedData = Data(bytes: encryptionOutput)
                
                let encryptedFilename = file + ".aes"
                
                var savePath:String = self.fetchDocPath() + "/" + encryptedFilename
                let finalFilePath = URL(fileURLWithPath: savePath)
                try encryptedData.write(to: finalFilePath)
                
                let dataToDecrypt = try Data(contentsOf: finalFilePath)
                let decryptedBytes = try aes.decrypt(dataToDecrypt)
                let decryptedData = Data(decryptedBytes)
                
                let decryptedFilename = file + ".decrypted.db"
                
                savePath = self.fetchDocPath() + "/" + decryptedFilename
                let decryptedFilePath = URL(fileURLWithPath: savePath)
                try decryptedData.write(to: decryptedFilePath)

                
                print("Database encryption complete!")
            } catch {
                print(error)
            }
        }
    }
```

I appreciate the help!

**Comment by krzyzanowskim** [comment]
@jimidobson you can create empty project with the issue, though. I don't need the whole project. This and OpenSSL part.

**Comment by jimidobson** [comment]
No problem, will get back to you shortly

**Comment by jimidobson** [comment]
[test.zip](https://github.com/krzyzanowskim/CryptoSwift/files/735713/test.zip)

**Comment by krzyzanowskim** [comment]
Thanks. How do u decrypt with OpenSSL? I need to verify that.

**Comment by jimidobson** [comment]
via command-line on Mac, you can run this in the terminal:

openssl enc -d -aes-128-cbc -in encrypted.file -out decrypted.file

You can also download AESCrypt: https://www.aescrypt.com/download/

That runs with a GUI or command-line if you prefer.

**Comment by jimidobson** [comment]
Hello, any updates? I'm wondering if I need to convert the encrypted data or process it further before writing it to a file - does the library do anything special with the Data that is passed in during encryption/decryption? Maybe I'm missing a step?

**Comment by jimidobson** [comment]
@krzyzanowskim  I've performed another test, this time creating an identical copy of the aes object but using it to decrypt the data:

```
let aesDecrypt = try AES(key: "password", iv: "passwordpassword", blockMode: .CBC) // aes128
            
//load the same file back into the app and decrypt it
let dataToDecrypt = try Data(contentsOf: encryptedFilePath)
let decryptedBytes = try aesDecrypt.decrypt(dataToDecrypt)
let decryptedData = Data(decryptedBytes)
```

The resulting data written to the decrypted file is garbled - So for some reason, using the exact same encryptor to encrypt, read back in and decrypt the data works, but creating a new instance of the AES cryptor and using that to decrypt results in nonsense. 


[testfile.txt](https://github.com/krzyzanowskim/CryptoSwift/files/738766/testfile.txt)

[decrypted.txt](https://github.com/krzyzanowskim/CryptoSwift/files/738767/decrypted.txt)


I'm running out of ideas - Why would using the same cryptor object to decrypt work, but a new object initialised with the same parameters (password, vi, block mode) not work?

**Comment by krzyzanowskim** [comment]
I'll look at it in the evening or tomorrow.

**Comment by jimidobson** [comment]
Any news on this? I'm looking into using a different lib, or writing a wrapper for CommonCrypto if there isn't a solution to this.

**Comment by krzyzanowskim** [comment]
@jimidobson really, feel free to use whatever you want. I don't have any business in this project so I just can do as much as I can in my spare time and nothing more.

**Comment by krzyzanowskim** [comment]
To compare output with the OpenSSL first you should know how OpenSSL works
- salt is added
- IV is derived from the password if not given
- MD5 digest is used for key derivation by default

Let's build  CryptoSwift code and corresponding OpenSSL command:

```swift
let plaintext = Array("Nullam quis risus eget urna mollis ornare vel eu leo.".utf8)
let key = Array("passwordpassword".utf8).md5() // -md md5
let iv  = Array("drowssapdrowssap".utf8) // -iv 64726f777373617064726f7773736170
let aes = try AES(key: key, iv: iv) // -aes-128-cbc
let ciphertext = try aes.encrypt(plaintext) // enc
print(ciphertext.toHexString())
```

now you can compare the output with OpenSSL command:

> echo "Nullam quis risus eget urna mollis ornare vel eu leo." | openssl enc -aes-128-cbc -md md5 -nosalt -iv 64726f777373617064726f7773736170 -pass pass:passwordpassword -base64
cij+965z2Xqoj9tIHgtA72ZPfv5sxnt76vwkIt1CodYY313oa7mr0pSc5o++g0CX

expected output should match from the OpenSSL and CryptoSwift code
```
cij+965z2Xqoj9tIHgtA72ZPfv5sxnt76vwkIt1CodYY313oa7mr0pSc5o++g0CXYczxK2fGIa84xtwDtRMwBQ==
```

I hope that help you in your adventure. Good luck.

**Comment by krzyzanowskim** [comment]
To compare output with the OpenSSL first you should know how OpenSSL works
- salt is added
- IV is derived from the password if not given
- MD5 digest is used for key derivation by default

Let's build  CryptoSwift code and corresponding OpenSSL command:

```swift
let plaintext = Array("Nullam quis risus eget urna mollis ornare vel eu leo.".utf8)
let key = Array("passwordpassword".utf8).md5() // -md md5
let iv  = Array("drowssapdrowssap".utf8) // -iv 64726f777373617064726f7773736170
let aes = try! AES(key: key, iv: iv, blockMode: .CBC, padding: PKCS7()) // -aes-128-cbc
let ciphertext = try! aes.encrypt(plaintext) // enc
```

now you can compare the output with OpenSSL command:

> echo -n "Nullam quis risus eget urna mollis ornare vel eu leo." | openssl enc -aes-128-cbc -md md5 -nosalt -iv 64726f777373617064726f7773736170 -pass pass:passwordpassword -base64

expected output should match from the OpenSSL and CryptoSwift code
```
cij+965z2Xqoj9tIHgtA72ZPfv5sxnt76vwkIt1CodYY313oa7mr0pSc5o++g0CXYczxK2fGIa84xtwDtRMwBQ==
```

I hope that help you in your adventure. Good luck.

**Comment by jimidobson** [comment]
@krzyzanowskim That was the missing step I needed - I was lacking the MD5 digest, and I wasn't passing the correct parameters to openssl, specifically, the -nosalt and I wasn't providing the IV.

Thank you very much for you help, much appreciated 👍
