### ISSUE TITLE
Xcode 8.2 tries to convert to Swift 3.0

### ISSUE THREAD

**Issue by 2dvisio** [krzyzanowskim/CryptoSwift#395]
I have an issue with the latest version of CryptoSwift (Downloaded from Cocoapods, 0.6.7).

My (brand new) Xcode 8.2 complains that CryptoSwift is not compliant with Swift 3.0.

![screenshot_27_01_2017__17_22](https://cloud.githubusercontent.com/assets/925236/22380537/ba205200-e4b5-11e6-99e4-a3214485884a.png)

My Cocoapods repo seems to download the right version though.

![1__zsh](https://cloud.githubusercontent.com/assets/925236/22380593/e4234c6a-e4b5-11e6-9cfd-88acc9006822.png)

However I am welcomed by hundreds of errors once the process is completed (though the Converted tool says: No code update needed :///)

![treatgdm_xcodeproj](https://cloud.githubusercontent.com/assets/925236/22380652/11350536-e4b6-11e6-86e9-1b0d3ab655a9.png)

Here is a typical example from one of the errors:

![aes_swift](https://cloud.githubusercontent.com/assets/925236/22380681/2a8768b2-e4b6-11e6-8cf2-9564990cabfd.png)

Please advise if I am doing something dumb unintentionally.

My project also include some Objective-C code, and two Objective-C libraries.

Cheers.

**Comment by krzyzanowskim** [comment]
This is a known Cocoapods problem. search closed issues for possible solutions, and bump Cocoapods issue.

**Comment by 2dvisio** [comment]
Thanks!

**Comment by 2dvisio** [comment]
I have tried this:
https://github.com/krzyzanowskim/CryptoSwift/issues/342

But it actually seems not to work.

In addition I experience a new issue:

![pods_xcodeproj_and_xcode_8_2_tries_to_convert_to_swift_3_0_ _issue__395_ _krzyzanowskim_cryptoswift](https://cloud.githubusercontent.com/assets/925236/22381344/265f58d2-e4b9-11e6-8d01-d004013888ce.png)

And here:

![treatgdm_xcworkspace](https://cloud.githubusercontent.com/assets/925236/22381351/32421c48-e4b9-11e6-8577-5f6ebd6e7e8c.png)



When I try to set my own SWIFT_VERSION in the build settings of CryptoSwift I get this other error :///

![pods_xcodeproj](https://cloud.githubusercontent.com/assets/925236/22381439/85050d46-e4b9-11e6-9f01-dd1c6dd36767.png)

**Comment by 2dvisio** [comment]
Re-opened the issue by mistake. I am posting here just because you might have a solution or others might.
But it is correct not to open this issue as it is probably still caused by the bug of Cocoapods
