### ISSUE TITLE
How to do 1 byte en/decrypt for stream cipher

### ISSUE THREAD

**Issue by leaves615** [krzyzanowskim/CryptoSwift#397]
Hope help me.  
this is not issues.

**Comment by krzyzanowskim** [comment]
What have you tried already?
see https://github.com/krzyzanowskim/CryptoSwift#incremental-updates

**Comment by leaves615** [comment]
I've tested the incremental update method, which can only be encrypted once, and I want to use it to encrypt the persistent socket stream.

I refer to go language xorKeyStream implementation, and your update implementation, the preparation of the following code. It implements what I want.

[](https://github.com/leaves615/CryptoSwift/blob/dev/Sources/CryptoSwift/AES.swift)
line: 460-549.

**Comment by krzyzanowskim** [comment]
Have you checked the Playground code? there is a stream example coded.

**Comment by krzyzanowskim** [comment]
I think I don't follow, what is the problem you have. Why exactly you can't use incremental encryption as in Playground example? You should be able to use it. I want to understand to make a fix is there is a issue with Updatable implementation.

**Comment by leaves615** [comment]
Incremental encryption can be used, but can not be used in the socket stream, socket stream flow of bytes, not necessarily block size, sometimes only one byte, this time using the update method, it will not immediately get encrypt Text. But to wait until the accumulation of block size, will perform encryption.

**Comment by leaves615** [comment]
My English is not very good, so use google translation to get English

**Comment by krzyzanowskim** [comment]
I see your point now. Updatable shouldn't wait for the whole block for certain modes. agree.
thanks!

**Comment by krzyzanowskim** [comment]
Proper stream support for CTR mode landed in 0.11.0. Closing.
