### ISSUE TITLE
Decrypting AES128 imageData takes about 1minute and 10 seconds, am I doing something wrong?

### ISSUE THREAD

**Issue by 511430** [krzyzanowskim/CryptoSwift#40]
I am decrypting an image as NSData coming from a server.
I am using ECB mode, and the NSData length is 32592. 
The data is padded using PKCS#5.

This is the code I am using:
        
       var data:NSData =  // The data from the server
        let keyData = self.constants.blob_encryption_key.dataUsingEncoding(NSUTF8StringEncoding,    allowLossyConversion: false)!
        let ivData:NSData = Cipher.randomIV(keyData)
        
        var cipher = Cipher.AES(key: keyData, iv: ivData, blockMode: CipherBlockMode.ECB)
        var decryptedData = cipher.decrypt(data)
        
        println(decryptedData)

When running this code, the simulator uses 100% CPU and the memory usage is about 21,5mb.
I am getting the image back is at was, it only takes a long long time.
What am I doing wrong?

Thanks in advance!

**Comment by giacgbj** [comment]
Hi, I think it's the same question asked in #30.

Same behavior calculating "simpler" hashes: my tests showed that a SHA-256 hash was 300/400 times slower than using CommonCrypto.

**Comment by 511430** [comment]
Hi, thanks for your answer.
Could you or someone else provide me with an example on how to do this in commoncrypto?

Thanks in advance!

**Comment by krzyzanowskim** [comment]
First, go with branch swift12 in Release build. Its still underperforment, but should be better than master branch. I test it against 1Mb of data.

And better go with ChaCha20 cipher, this algorithm is much performent than AES.

Any ideas how to speed up swift codebase, are appreciated.

**Comment by 511430** [comment]
Thanks for the help, but I am not the one who encrypts the data, so I had to use AES/ECB.
I appreciate the work you've put in this library, but for my specific purpose using CommonCrypto was the best solution.
Using CommonCrypto the data was decrypted within 0,5-1 second, which is really fast.

Thanks again, great library!
