### ISSUE TITLE
Can't able to decrypt the data

### ISSUE THREAD

**Issue by Gantaios** [krzyzanowskim/CryptoSwift#400]
Hi Everyone i am unable to decrypt the data coming the server 
 here are my key and iv

let key = "9876a5p4a3a2z1q0"
let iv = "0q1z2a3a4p5a6789"

The string i need to decrypt is this "5ca9b162fe2936c0fd7f5a834d3d874a8ae39a5d482509a82b50e8ea5248cc2ce8acce5ae4c6ac1677918ffea9e3454b894fd06d1a0baae59384aa456b3eb90b"    
i am unable to do it any help it's a json string and need to decode and parse it

**Comment by krzyzanowskim** [comment]
it's a hex (string) encoded bytes, you can use [this](https://github.com/krzyzanowskim/CryptoSwift#data-types-conversion):
```swift
let bytes = Array<UInt8>(hex: "0x010203")
```
to convert it to the array of bytes.

**Comment by Gantaios** [comment]
Do i need to convert it to nsdata again sorry am new to this stuff want help

**Comment by krzyzanowskim** [comment]
It depends what you need, if you need Data you convert to Data, it's up to you.

> CryptoSwift uses array of bytes aka Array<UInt8> as a base type for all operations. Every data may be converted to a stream of bytes. You will find convenience functions that accept String or NSData, and it will be internally converted to the array of bytes.

**Comment by Gantaios** [comment]
Thank you so much i god it hurray thank you. one last one can i use it in objective -c if so how to
