### ISSUE TITLE
Conversion from bytes to [UInt32] is very slow

### ISSUE THREAD

**Issue by Joannis** [krzyzanowskim/CryptoSwift#401]
I'm trying to hash a file with MD5 which requires the file to be converted to an UInt32 array. This process takes 1.3 seconds where the rest of the hashing takes 70ms.

EDIT: The line in question: https://github.com/OpenKitten/MongoKitten/blob/mongokitten31/Sources/MongoKitten/Querying/GridFS.swift#L159

**Comment by Joannis** [comment]
One more this: Thanks Marcin for your continuous work on CryptoSwift. You're a friendly dev that's nice to work with :+1: I'm happy to contribute my idea of how this could be approached in a PR if you'd like.

**Comment by krzyzanowskim** [comment]
@Joannis feel free to prepare PR, I'm happy to merge it.

**Comment by bkostjens** [comment]
@Joannis Did you find any solution to the performance problem? Thanks a lot for looking into it.

**Comment by Joannis** [comment]
@bkostjens I did not. I'm giving it another shot in an hour. Otherwise I'll need to use LibreSSL for MD5, which we already depend on.

**Comment by krzyzanowskim** [comment]
I did some improvement, significantly faster in my test. @Joannis pls test if you can.
