### ISSUE TITLE
Cross Platform?

### ISSUE THREAD

**Issue by izotx** [krzyzanowskim/CryptoSwift#402]
I have a bizzare problem. 
I am running the same code on my laptop, iMac, and iPad.
The Data encrypted on iMac can't be decrypted on iPad.
Same thing with data encrypted on iPad, it can't be decrypted on by laptop  nor iMac.

I am using following code to decrypt and encrypt. Any help will be very appreciated:

```

public class SecuritySuite
{   static func getAESP()->String{
        return "xxxxxx" //32 characters
    }
    
    static let iv = "xxxxx" //12 characters
    
    public static  func encryptData(data:Data)->(Data?){
        let bytes = data.bytes
        let encrypted = try! ChaCha20(key: SecuritySuite.getAESP(), iv: SecuritySuite.iv ).encrypt(bytes)
        let d = Data(bytes: encrypted)
    return d
    }

//Decrypt data
    public static func decryptData(data:Data)->Data{
        let bytes = data.bytes
    
        let decrypted = try! ChaCha20(key: SecuritySuite.getAESP(), iv: SecuritySuite.iv).decrypt(bytes)
        return Data(bytes: decrypted)
    }
}

```

**Comment by krzyzanowskim** [comment]
... that shouldn't happen. I'm looking at encrypted data on my iPhone6 and my Macbook but can't spot any difference. Maybe you can build test project I can give a try?

**Comment by izotx** [comment]
Hi, I changed the encryption to AES, and I am specifying manually padding, blockMode and etc.
`AES(key: key, iv: iv, blockMode: .CBC, padding: PKCS7()).encrypt(inputBytes)`
 and the problem seems to went away. 

I had problems with ChaCha, I don't exclude option though that that was something in my code. I don't have time to investigate it further.  I hope to get back to it in the future.
Thanks for a great library.
