### ISSUE TITLE
Do PKCS7() Padding is included in this code?

### ISSUE THREAD

**Issue by htarwara6245** [krzyzanowskim/CryptoSwift#404]
let input: [UInt8] = [0,1,2,3,4,5,6,7,8,9]
let encrypted: [UInt8] = try! AES(key: "secret0key000000", iv:"0123456789012345", blockMode: .CBC).encrypt(input)

Any Ideas?

**Comment by krzyzanowskim** [comment]
Yes it is. It is the default value to the `padding` parameter here: https://github.com/krzyzanowskim/CryptoSwift/blob/master/Sources/CryptoSwift/AES.swift#L111
