### ISSUE TITLE
How to decrypt data

### ISSUE THREAD

**Issue by wata-vientran** [krzyzanowskim/CryptoSwift#407]
I has a text
let message = "Test Mess"

// This code for encrypt right ?
let dataEncryp = message.sha256()

How to decrypt data from dataEncryp ?
Thank you so much.

**Comment by Joannis** [comment]
SHA256 is a one-way encryption (hashing) function, you cannot decrypt this unless you brute-force the message.

**Comment by wata-vientran** [comment]
(Y)
Thank you so much @Joannis 
You save my day. hahaa.
