### ISSUE TITLE
Strange behvaviour of AES-128 encryption!

### ISSUE THREAD

**Issue by kmno** [krzyzanowskim/CryptoSwift#408]
Here's my code : 
`let initKey = responseData["payload"]["data"]["initialKey"].stringValue
let decodedData = NSData(base64EncodedString: initKey, options: NSDataBase64DecodingOptions(rawValue: 0))`

the initKey is a base64 value retrieved from server. then i create an AES-128 key as follow : 
`let key = try! AES(key: (decodedData?.arrayOfBytes())!)`

i use this method to encrypt some strings : 
` func encrypt(_p: String, _key: Cipher) -> String{
        let encrypted = try! _p.encrypt(_key).toBase64()!
        return encrypted
    }`

**it works fine on short length strings. but when i test it with longer string (like : 12345678901234567890) it seems to encrypt it some first characters but the rest are totally incorrect! 
(i compare the result with similar android AES encryption code, so the first characters are equal but the rest not ... )**

i'm using swift 2.2

thanks for help

**Comment by krzyzanowskim** [comment]
Swift 2 branch is not maintained. Try to replicate issue with the master branch

**Comment by kmno** [comment]
ow! so what can should i do? my project is in an urgent condition.. i need help about it

**Comment by krzyzanowskim** [comment]
you can ask for the consulting work if you need. you'll find my email.
