### ISSUE TITLE
Can't submit tvOS app when integrating with Carthage and --no-build option due to bitcode problems

### ISSUE THREAD

**Issue by emaloney** [krzyzanowskim/CryptoSwift#410]
I am attempting to integrate CryptoSwift into a tvOS app that uses Carthage to manage dependencies but not build them. To do this, I pass `--no-build` to Carthage, drag `CryptoSwift.xcodeproj` into my workspace, and set up CryptoSwift as one of the app's embedded frameworks.

Building and even running on my device works fine without any bitcode settings at all, but when I attempt to submit the app to Apple, the App Store rejects it because the project does not contain bitcode. (tvOS projects require full bitcode for app submission.) In order to fix this issue, tvOS developers need to add the appropriate bitcode settings to their projects.

Unfortunately, when CryptoSwift is integrated as described above, adding the appropriate bitcode settings to the application target causes the build to fail altogether because CryptoSwift builds without bitcode by default. The error displayed is:

```
ld: bitcode bundle could not be generated because '<redacted>/CryptoSwift.framework/CryptoSwift' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I was able to resolve the issue by adding a `BITCODE_GENERATION_MODE` build setting with a value of `bitcode` for the Release configuration of CryptoSwift. Once I do this, I am able to build and submit.

I've submitted PR #409 with this one-line change that fixes the issue.

If you would like to see the problem for yourself, here are the steps to reproduce:

1. Create a new tvOS application project in Xcode
2. Add the necessary `ENABLE_BITCODE=YES` and `BITCODE_GENERATION_MODE=bitcode` to the Release configuration of the project. These settings are needed for building an Apple TV app that will be accepted by the App Store.
3. Create a `Cartfile` in the root dir with the line: `github "krzyzanowskim/CryptoSwift" ~> 0.6.7`
4. Run the command `carthage update --no-build`
5. When the checkout is complete, drag `Carthage/Checkouts/CryptoSwift/CryptoSwift.xcodeproj` into the Xcode project window for the new tvOS project created in Step 1
6. Xcode will ask if you would like to create a workspace & save a new workspace. Do so.
7. Within Xcode, select the application target, and add `CryptoSwift.framework` to the Embedded Binaries list in the General tab
8. Build

Upon performing Step 8, you should see the error described above. If you instead build against my fork instead, the build succeeds.

**Comment by krzyzanowskim** [comment]
thanks! just one question. Does it breaks any other platform? there were an issues in the past with the bitcode

**Comment by emaloney** [comment]
It shouldn't cause a problem, because the `BITCODE_GENERATION_MODE` setting only comes into play when `ENABLE_BITCODE` is set to `YES` in the first place. So if a given platform (such as macOS) doesn't use bitcode, it won't have any effect.
