### ISSUE TITLE
Error in decryption OpenSSL encrypted file

### ISSUE THREAD

**Issue by froimer** [krzyzanowskim/CryptoSwift#411]
Hi @jimidobson @krzyzanowskim ,
I'm trying to decrypt with CryptoSwift an OpenSSL encrypted text file with the text "Test", following your excellent response at this post: https://github.com/krzyzanowskim/CryptoSwift/issues/394

This is what I have:

OpenSSL encryption: 

`openssl enc -aes-128-cbc -md md5 -nosalt -iv 64726f777373617064726f7773736170 -pass pass:passwordpassword -base64 -in Test.txt -out Test.enc
`

Swift code:
```
var text: String?
       if let path = Bundle.main.path(forResource: "Test", ofType: "enc") {
            do {
                text = try String(contentsOfFile: path, encoding: String.Encoding.utf8)
                print(text!)
            } catch {
                print("Failed to read text from \(error)")
            }
        } else {
            print("Failed to load file from app bundle")
        }
var ciphertext : Array<UInt8>
let plaintext = Array(text!.utf8)
let key = Array("passwordpassword".utf8).md5() // -md md5
let iv  = Array("drowssapdrowssap".utf8) // -iv 64726f777373617064726f7773736170
do {
            let aes = try! AES(key: key, iv: iv, blockMode: .CBC, padding: PKCS7()) // -aes-128-cbc
            ciphertext = try! aes.decrypt(plaintext) // decrypt
} catch {
            print(error)
}

```

But I found this error en the decrypt line:

`fatal error: 'try!' expression unexpectedly raised an error: CryptoSwift.AES.Error.dataPaddingRequired: file /Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-800.0.63/src/swift/stdlib/public/core/ErrorType.swift, line 178
`

Many thanks for your help in advance.

**Comment by krzyzanowskim** [comment]
What is inside the `Test.txt` file?

**Comment by froimer** [comment]
Hi Martin,

It contains "test".

Many thanks.

**Comment by krzyzanowskim** [comment]
looks good here. Cannot reproduce the issue on my side:

```swift
    func testIssue411() {
        let ciphertext: Array<UInt8> = [0x2A,0x3A,0x80,0x05,0xAF,0x46,0x58,0x2D,0x66,0x52,0x10,0xAE,0x86,0xD3,0x8E,0x8F] // test
        let key = Array("passwordpassword".utf8).md5() // -md md5
        let iv  = Array("drowssapdrowssap".utf8) // -iv 64726f777373617064726f7773736170
        let aes = try! AES(key: key, iv: iv, blockMode: .CBC, padding: PKCS7()) // -aes-128-cbc
        let plaintext = try! ciphertext.decrypt(cipher: aes)
        XCTAssertEqual("74657374", plaintext.toHexString())
    }
```

What is wrong with your code:
Converting encrypted bytes to String - your Test.enc contains base64 encoded data. You should decode base64 first. Then you can't form String out of that because ther are just some bytes (not a string bytes)
