### ISSUE TITLE
decrypting a encrypted string with blowfish returns nil when trying to convert it back

### ISSUE THREAD

**Issue by fabrijp** [krzyzanowskim/CryptoSwift#415]
How can i get the string back in this situation ?

**Encrypting**
`let message = "secret"`
`let encrypted = try! Blowfish(key: "passwordpassword", iv: "12345678", blockMode: .CFB, padding: NoPadding()).encrypt(Array(message.utf8))`

**Decrypting**
`let decrypted = try! Blowfish(key: "passwordpassword", iv: "12345678", blockMode: .CFB, padding: NoPadding()).decrypt(encrypted)`
**Here it fails**
`if let decryptedString  = String(data: Data(bytes: decrypted), encoding: .utf8) {
                print (decryptedString)
            } else {
                print ("Failed")
            }`

Thank you !

**Comment by krzyzanowskim** [comment]
Fixed (develop branch).

**Comment by fabrijp** [comment]
Thank you. But convert the string back still getting nil..

**Comment by krzyzanowskim** [comment]
cannot reproduce the issue, here's the test:
```
        do {
            let plaintext = Array("secret12".utf8)
            let encrypted = try Blowfish(key: "passwordpassword", iv: "12345678", blockMode: .CFB, padding: NoPadding()).encrypt(plaintext)
            let decrypted = try Blowfish(key: "passwordpassword", iv: "12345678", blockMode: .CFB, padding: NoPadding()).decrypt(encrypted)
            XCTAssertEqual(plaintext, decrypted)
            if let decryptedString = String(data: Data(bytes: decrypted), encoding: .utf8) {
                print (decryptedString)
            } else {
                print ("Failed")
            }
        } catch {
        }
```

**Comment by fabrijp** [comment]
Thank you!
I’ve created a default iOS project, copied the CryptoSwift folder into it. It works on playground but not when i compile for iOS.

The encryption is working fine, i got the encrypted bytes [115, 101, 99, 114, 101, 116] of a string “secret" and i can decrypt it back on Java or Vapor. The issue is when it’s decrypted on iOS project, i got bytes results [223, 218, 60, 237, 231, 233] instead of [169, 5, 96, 20, 35, 37] and maybe that’s the reason i cannot get the string back. I’m running the test on iPad simulator, Xcode Version 8.2.1 (8C1002) on MacOS Sierra 10.12.3

Maybe I’m missing something..
