### ISSUE TITLE
HMAC.authenticate crashing intermittently

### ISSUE THREAD

**Issue by AndrewSelvia** [krzyzanowskim/CryptoSwift#416]
HMAC. authenticate is crashing intermittently for me.

I am running a Vapor app in a Heroku environment (Linux). HMAC.authenticate crashes my app intermittently (maybe at 50% of requests). The error is very vague to me, so I'm hoping to find some help. Perhaps I am doing something unexpected or erroneous?

The error in my Heroku logs is:
`*** Error in 'App': corrupted double-linked list: 0x00007fe6d001f7f0 ***`

The code looks like this:
```
let key = "key"
let keyBytes = Array(key.utf8)
let messageBytes = Array("message".utf8)
let hmac = HMAC(key: keyBytes, variant: .sha256)
guard let signatureBytes = try? hmac.authenticate(messageBytes)
    else { ... }
let data = Data(bytes: signatureBytes)
let signature = data.base64EncodedString(options: .lineLength64Characters)
```

Notably, when I comment out the line containing `hmac.authenticate` (and use `let signatureBytes: [UInt8] = []` instead), I do not see the crash.

**Comment by krzyzanowskim** [comment]
The `corrupted double-linked list` is a C error message. It may come from everywhere in Vapor stack, I believe. The reason why your app stop crash after comment that line may not be related to that line, but to the code that is executed after that line and parses the `signatureBytes`.
Are you able to debug the code with the crash?

**Comment by AndrewSelvia** [comment]
Sadly, I am not able to debug it effectively. It is only happening in my hosted environment, not locally. The logs contain the only error message I can trace & they aren't exceptionally informative.

Are you saying the issue could be with the `Data` initializer? Do you have reason to believe that the initializer may fail when supplied the output of `hmac.authenticate`? Have you seen an error like this before?

**Comment by krzyzanowskim** [comment]
I can be anwyehere. Try to log the `signatureBytes` to the console and see if you can catch the output that cause the crash, of if there is no output.

**Comment by AndrewSelvia** [comment]
Looks like it's actually this line:
`let signature = data.base64EncodedString(options: .lineLength64Characters)`

Have you seen problems with `Data.base64EncodedString` before? How do you normally fix it on Linux? Is there a preferred way to base64 encode data with CryptoSwift?

I have tried every option combination for that method & they all fail with varying degrees of regularity.

When it works, I see two lines when I `print` `signatureBytes`. For example,
```
[11, 185, 106, 93, 124, 251, 130, 32, 110, 163, 105, 117, 62, 130, 181, 156, 237, 111, 127, 90, 60, 144, 111, 66, 165, 70, 180, 12, 5, 174, 16, 189]
[120, 50, 89, 22, 47, 229, 165, 158, 15, 70, 105, 61, 93, 182, 193, 169, 30, 217, 151, 120, 187, 26, 190, 167, 216, 64, 208, 135, 252, 4, 49, 92]
```

When it fails, I only see one:
`[198, 43, 236, 70, 85, 218, 197, 205, 120, 62, 87, 175, 215, 186, 187, 9, 34, 190, 36, 160, 189, 236, 3, 101, 174, 133, 70, 242, 218, 146, 142, 175]`

**Comment by krzyzanowskim** [comment]
If you can reproduce that, it's worth to report it to https://bugs.swift.org/ as it looks like the swift foundation problem.

**Comment by krzyzanowskim** [comment]
I can't reproduce the issue on Ubuntu 16.4 with Swift 3.0.2. Can you make sample project (not web, just executable) where you can reproduce the issue? I'd like to exclude CryptoSwift for sure.

**Comment by AndrewSelvia** [comment]
@krzyzanowskim I went on a debugging deep-dive yesterday. It seems the issue lied with the fact that I was building my project with a pre-release version of Swift 3.1. This led to errors at runtime that were co-located but not directly related to CryptoSwift. I apologize for the false alarm.

Thanks for making this great project! Do you have financial supporters?

**Comment by krzyzanowskim** [comment]
That's great. It may be worth to report to Swift though, anyway, so it wont get in to the next stable release.

I don't have financial supporters. If you willing to make a donation to support me with the work on this project, you can use my paypal https://www.paypal.me/krzyzanowskim I'd be gratefull. Thanks!
