### ISSUE TITLE
issue while running it in xcode 7.3.1

### ISSUE THREAD

**Issue by raghubb4444** [krzyzanowskim/CryptoSwift#419]
![screen shot 2017-04-04 at 12 52 40 pm](https://cloud.githubusercontent.com/assets/13926905/24645448/c750b2a8-1935-11e7-8139-d23ff4be4d09.png)
 
I did pod update. But it shows 294 errors from that cryptoswift files.Whats the issue?Am using swift 2.2.

**Comment by krzyzanowskim** [comment]
Xcode 7.3.1 is Swift 2.x and it's not compatible with the latest relase (Swift 3.x)

> Swift 2.2, 2.3: branch `swift2` version <= 0.5.2

https://github.com/krzyzanowskim/CryptoSwift#older-swift-versions

**Comment by raghubb4444** [comment]
How to do pod install for swift version 2.2?

**Comment by krzyzanowskim** [comment]
https://guides.cocoapods.org/using/the-podfile.html

pod 'CryptoSwift', '0.5.2'
