### ISSUE TITLE
Warning on ChaCha20.swift

### ISSUE THREAD

**Issue by xandros6** [krzyzanowskim/CryptoSwift#422]
ChaCha20.swift:16:21: 
Property should not be declared fileprivate because its type uses a private type

**Comment by krzyzanowskim** [comment]
what generates this warning?

**Comment by xandros6** [comment]
on ChaCha20.swift Context structure is private so "context" member can't be fileprivate but private

**Comment by krzyzanowskim** [comment]
You're using some old code, don't you? There is no Context in ChaCha20.swift

**Comment by xandros6** [comment]
I'm on 0.6.8 tag

**Comment by krzyzanowskim** [comment]
That's not possible https://github.com/krzyzanowskim/CryptoSwift/blob/0.6.8/Sources/CryptoSwift/ChaCha20.swift

**Comment by xandros6** [comment]
I use Carthae and on log:
*** Checking out CryptoSwift at "0.6.8"

I run another update and check.

Thanks.

**Comment by krzyzanowskim** [comment]
delete carthage caches. afaik it's common carthage has issue with using outdated versions (you can find it in closed issues here too)

**Comment by xandros6** [comment]
You are the best! Thanks.

**Comment by krzyzanowskim** [comment]
have a good day ;)
