### ISSUE TITLE
Decrypt function crashes when try to decrypt an empty string ""

### ISSUE THREAD

**Issue by FranMartinRomero** [krzyzanowskim/CryptoSwift#423]
When I try to decrypt an empty string the code crashes in the extension "AES: Cipher" in the line 

> chunks.indices.formIndex(&lastIdx, offsetBy: chunks.count - 1)

The encryption of an empty string return now "QqTYcbUglZ66POuPLRNo8w==" instead of "" as in previous versions. Is this the expected behaviour now?

**Comment by yarodevuci** [comment]
@FranMartinRomero got the same problem with an Empty string.. My error is BidirectionalCollections can be advanced by a negative amount

Any research on that?

**Comment by FranMartinRomero** [comment]
No at the moment @yarodevuci I set 0.6.7 as the release to use on my app at the moment. I just need to understand if this is a bug, to solve it in a fork, or if it's the expected behaviour (don't accept empty strings) and I should check if my string to decrypt is empty or not. Anyway I consider this as a bug because it crashes with a string.

**Comment by krzyzanowskim** [comment]
@FranMartinRomero what input (parameters) cause the crash? can you post it here please?

**Comment by krzyzanowskim** [comment]
The encrypted empty string should not result in an empty string. This is expected behavior (a change for better).

**Comment by krzyzanowskim** [comment]
I assume the problem is with this call

```swift
let decrypted = try "".decryptBase64(cipher: cipher)
```

**Comment by krzyzanowskim** [comment]
In general, the empty string is an invalid input data and can't be decrypted to anything reasonable (to answer @FranMartinRomero question).

In this case, the error should be thrown (better error than the one from the Collection).

**Comment by FranMartinRomero** [comment]
Yes, that is the problem. In the previous Crypto versions when I tried to encrypt an empty string I was getting "" as result. So if I try now to decrypt "" I'm getting the crash. I'm agree we should not try to encrypt an empty string but I highlighted this crash because it was not happening before and I didn't see any comment about this.

**Comment by krzyzanowskim** [comment]
Sure, thank you for the report. I'll address this scenario it in the better way.

**Comment by FranMartinRomero** [comment]
Thank you Marcin!
