### ISSUE TITLE
dyld: Library not loaded

### ISSUE THREAD

**Issue by Krisyean** [krzyzanowskim/CryptoSwift#427]
dyld: Library not loaded: @rpath/CryptoSwift.framework/CryptoSwift
  Referenced from: /var/containers/Bundle/Application/F00DFC23-B7B9-46D9-89AD-A2C8E16DDA04/NOW.app/NOW
  Reason: image not found

Xcode 8.2.1
Using multiple targets for same Project
working good with iOS project
Unable to push build for tvOS

Dragged n dropped cryptoswift to project
Created separate targets in crypto iOS and tvOS
added target dependencies for both iOS and tvOS project respectively.

**Comment by krzyzanowskim** [comment]
Did you Embedded Framework https://github.com/krzyzanowskim/CryptoSwift#embedded-framework ?

**Comment by Krisyean** [comment]
yes i did that

**Comment by krzyzanowskim** [comment]
It's not exactly "Embed frameworks" with the "Frameworks" destination.

**Comment by Krisyean** [comment]
thanks for correcting me!
