### ISSUE TITLE
Decrypted string displays unknown characters

### ISSUE THREAD

**Issue by rjjohnpatrickcruz** [krzyzanowskim/CryptoSwift#428]
Hi,

Any help I'm new to encryption in swift.

Im using this code:

        do {

            let aes = try AES(key:"key" iv: "iv") // aes128
            let ciphertext = try aes.encrypt(Array(password.utf8))
            ecrypted_password = ciphertext.toHexString()
            
        } catch {}

But when decrypting it in the backend using PHP, I get this string with extra unknown characters 
- Qwerty1234\u0006\u0006\u0006\u0006\u0006\u0006 - 

Hope anyone could help me.

Thank you!

**Comment by krzyzanowskim** [comment]
\u0006 char is a 0x6 byte repeated six times. It's padding (PKCS7 in this case) to 16 bytes (block size). Padding should be removed while decrypting during the decryption. Usually, padding can be specified as a parameter - looks like you're missing that on the PHP side.

**Comment by rjjohnpatrickcruz** [comment]
How can I do that? Do you have samples there? Thank you!

**Comment by krzyzanowskim** [comment]
It depends on what you're using on the PHP side. You should look there for this.
