### ISSUE TITLE
If my key string contains 44 char?

### ISSUE THREAD

**Issue by reza-khalafi** [krzyzanowskim/CryptoSwift#429]
I am trying to use CryptoSwift for larval encryption, and in laravel encryption key contains 44 char. and AES-256-CBC in CryptoSwift just accept [16,24,32] char count. How to fix this?

**Comment by krzyzanowskim** [comment]
what is larval encryption?
you cant "fix" what is not broken. You probably need to transform key to the appropriate lenght for the cipher

**Comment by reza-khalafi** [comment]
`let key : String = "u6KuXJLIUwEUl7noY8J8H1ffDRwLC/5gjaWW1qTQ3hE="`
and IV something like this:   
` let iv : String = "wbtMIynAc//F9Q=="`    
 and my message   
` let message : String = "s:6:"123456";"   `  
So  how to transform to appropriate length ?

**Comment by krzyzanowskim** [comment]
One option is to use PBKDF. It really depends on what you want to do
