### ISSUE TITLE
Help with code swift 3

### ISSUE THREAD

**Issue by josmanperez** [krzyzanowskim/CryptoSwift#431]
Hello everyone!, first of all thank you for this awesome library, really :1st_place_medal: 

I have a piece of code that was working flawless back on swift 1.2 and PHP on the backend, I use this piece of code to send a encrypted string and decrypt that string on the server side (using php) and everything was working fine. 
After update everything to Swift 3 now my function is working but the result of decrypt on the server side gives me a really weird string nothing like the original one whatsoever. 

This is the piece of code (on the client side) 

`let key = json[AppConstant.COD_STRING_KEY_PASS.rawValue].stringValue`
  `let iv = json[AppConstant.COD_STRING_IV_PASS.rawValue].stringValue`
   `do {
          let encoded:String = try! pass.encrypt(cipher: AES(key: key, iv: iv, blockMode: .CBC))                      
          if let encodedHex = self.base64ToByteArray(encoded) {
            let parameters:[String:String]  = 
 ["access_token":access_token,"encrypted_string":"1","stringencrypted":self.bytesToString(encodedHex)]}`

And that are the parameters attached to the request. I have not change anything on the server side (in fact if I use the previous swift 1.2 version it works with no problem)  

Is there something that am I doing wrong? any help will be very appreciated :)

Thank you so much

**Comment by josmanperez** [comment]
I will answer this question for someone that might be facing the same issue. 
Using swift 3. there is no need for doing the `encodedHex = self.base64ToByteArray(encoded)`

If you use directly `encoded:String = try! pass.encrypt(cipher: AES(key: key, iv: iv, blockMode: .CBC))` it will give you the correct encoded string

**Comment by RajkumarThyadi** [comment]
@josmanperez   Can you please help me with integrating CryptoSwift with Swift3.0 update.

**Comment by josmanperez** [comment]
Sure @RajkumarThyadi what problems are you facing?
