### ISSUE TITLE
Need update with Swift 3.0

### ISSUE THREAD

**Issue by RajkumarThyadi** [krzyzanowskim/CryptoSwift#432]
I included CryptoSwift in y project through pods , it showing errors with Swift 3.0 . Its working fine with Swift 2.3. We need update of this framework with Swift3.0

**Comment by krzyzanowskim** [comment]
it's a CocoaPods issue. The current latest version of CryptoSwift is Swift 3.0. You have to set SWIFT_VERSION manually somewhere in your project or Pods project. You'll find more in closed issues.
