### ISSUE TITLE
Submit app to AppStore which have aes encryption

### ISSUE THREAD

**Issue by imanuelpardosi** [krzyzanowskim/CryptoSwift#434]
I develop IOS app, using swift 3. I use CryptoSwift (https://github.com/krzyzanowskim/CryptoSwift) in my project to decrypt files from server. Is any problems when submit my app to AppStore? Or what should I prepare before submit app which is have encryption code.

**Comment by krzyzanowskim** [comment]
You should not have problems. Here is already thread that cover this topic https://github.com/krzyzanowskim/CryptoSwift/issues/76
