### ISSUE TITLE
AES Problem

### ISSUE THREAD

**Issue by AzAli71** [krzyzanowskim/CryptoSwift#435]
I want to encrypt withAES without iv for one text
I have used this : 
  do {
            let aes = try AES(key: "12345", iv: "") 
            let ciphertext = try aes.encrypt(Array("AlirezaAli".utf8))
            print(ciphertext.toHexString())
        } catch {
            print(error)
        }

but it crashes in line 55  preconditionFailure("Unknown AES variant for given key.")

**Comment by krzyzanowskim** [comment]
your key need to be 16/32 bytes long

**Comment by AzAli71** [comment]
could you please assist me what is wrong in below ?  
let keyString = "12345"
       let myData = keyString.data(using: String.Encoding.utf8)?.sha256()
      let key =  myData!.toHexString()
      let aes =  try? AES.init(key: key, iv: "")
         let ciphertext = try? aes?.encrypt(Array("this is test ".utf8))

**Comment by AzAli71** [comment]
my problem fixed , thanks for your grate library
