### ISSUE TITLE
AES Encryption to strange characters

### ISSUE THREAD

**Issue by imanuelpardosi** [krzyzanowskim/CryptoSwift#436]
This is my code to encrypt a string and the result is readable string: /QOEtrf3o8buv2wA9FeAyg==. How can I get the strange character (non readable) like this: Ί�^��h��y^ғ.

var input = "CryptoSwift"
var key = "passwordpassword"
var iv = "drowssapdrowssap"

func aesEncrypt(input: String, key: String, iv: String) throws -> String {
    let data = input.utf8
    let encrypted = try! AES(key: key, iv: iv, blockMode: .CBC, padding: PKCS7()).encrypt([UInt8](data))
    let encryptedData = Data(encrypted)
    return encryptedData.base64EncodedString()
}

let encrypted = try! aesEncrypt(input: input, key: key, iv: iv)
print("encrypted: \(encrypted)")

**Comment by krzyzanowskim** [comment]
`/QOEtrf3o8buv2wA9FeAyg==` looks like Base64 encoded data. Don't use `base64EncodedString()` so you won't get base64 encoded data. Does that answer your question?
