### ISSUE TITLE
Native support for hmac sha512 for swift 3.1?

### ISSUE THREAD

**Issue by nabtron** [krzyzanowskim/CryptoSwift#439]
Hi, sorry if it's a stupid question. But if i simply need to encrypt a string before sending it to api server with hmac sha512, do I need this library? Can't it be done in some way using native swift 3.1 only?

Thanks

**Comment by krzyzanowskim** [comment]
You can use whatever library you want, as log as it provides HMAC-SHA512. CryptoSwift does provide that.

**Comment by nabtron** [comment]
no, my query is, can't we do it without including any library? by some mini code / class only?
