### ISSUE TITLE
@_specialize not supported by Swift 4

### ISSUE THREAD

**Issue by freak4pc** [krzyzanowskim/CryptoSwift#440]
It seems you heavily use the `@_specialized` attribute, but it seems to:

1. [Not officially guaranteed to be supported by Apple](https://github.com/apple/swift/commit/df6e927147dfe95568d7cb3d159152f9bf9b1d3e#diff-6551cd688c812cb4fdebcdb5b196a314R549)
2. [Only work with generics](https://github.com/apple/swift/pull/10095/files)

CryptoSwift currently doesn't build under Xcode 9 developer preview due to these reasons so I would assume a better specialized build solution should be employed here

Would love your thoughts

Thanks,
Shai

**Comment by krzyzanowskim** [comment]
It changed the syntax. I'll update it in the morning.

**Comment by freak4pc** [comment]
Thanks @krzyzanowskim , I appreciate it. 
Was sure this is more than a syntax change so relieved to know its more straightforward then that :)

**Comment by krzyzanowskim** [comment]
So the syntax changed for Swift 3 and 4. I updated it on the `develop` branch. There's still compilation regression https://bugs.swift.org/browse/SR-5140

**Comment by ldrr** [comment]
Maybe you will take a look at https://github.com/krzyzanowskim/CryptoSwift/pull/445 for a compile bug fix
