### ISSUE TITLE
what time will support swift4?

### ISSUE THREAD

**Issue by Mosaics** [krzyzanowskim/CryptoSwift#443]
what time will support swift4?

**Comment by krzyzanowskim** [comment]
as soon as possible https://twitter.com/krzyzanowskim/status/872296134844137472

**Comment by freak4pc** [comment]
@Mosaics Please see #440 . You could probably close this one.

**Comment by tzm41** [comment]
Compiler error in `encrypt()` on latest dev branch. `AES.swift:214:11: Expression was too complex to be solved in reasonable time; consider breaking up the expression into distinct sub-expressions`.

**Comment by krzyzanowskim** [comment]
please report to Apple. It compiles here on MacBookAir. This factor depends on the machine resources that compiles the code

**Comment by tzm41** [comment]
Okay. I am running on RMBP 2015.

**Comment by krzyzanowskim** [comment]
Add this to the OTHER_SWIFT_FLAGS and let me know if that help in your case
```
-solver-memory-threshold 999999999
```

**Comment by genedelisa** [comment]
fwiw, I'm motivated by the new MusicKit, which requires a developer token (jwt) sent with requests. I want to use JSONWebToken which has CryptoSwift as a dependency to generate this "on the fly".
(most of the compile issues are about @_specialize)

Just informational, not complaining etc. I know you'll get to the update when you can.
Thanks

**Comment by krzyzanowskim** [comment]
@genedelisa it's addressed on the `develop` branch and should compile just fine.

**Comment by krzyzanowskim** [comment]
ups. looks like I forgot to push the fix. It's pushed now. Sorry for the mistake.

**Comment by Mosaics** [comment]
@freak4pc thanks!
