### ISSUE TITLE
Support compiling under Xcode 9 (Swift 3.2)

### ISSUE THREAD

**Issue by serieuxchat** [krzyzanowskim/CryptoSwift#444]
I know that it's a bit early now, but being able to compile with Xcode 9 (and Swift 3.2) would be really cool (since code completion and the editor in general is SO much nicer in the new Xcode).

**Comment by gonghao** [comment]
👍 Hope to support Swift 3.2 ASAP.

**Comment by krzyzanowskim** [comment]
available from `develop` branch now.

**Comment by X-my** [comment]
I installed the latest version with cocoapods,and there is a compiler error in Xcode9 beta:

> .../Pods/CryptoSwift/Sources/CryptoSwift/AES.swift:214:11: Expression was too complex to be solved in reasonable time; consider breaking up the expression into distinct sub-expressions

here is written in my  Podfile:
> pod 'CryptoSwift', :git => "https://github.com/krzyzanowskim/CryptoSwift", :branch => 'develop'

Could you tell me how to solve this problem, please?

**Comment by gonghao** [comment]
Yes, the same problem with @X-my 
Maybe it should be written like this:
```
      let encrypted: Array<UInt8> = [
            UInt8(b0 & 0xFF),UInt8((b0 >> 8) & 0xFF),UInt8((b0 >> 16) & 0xFF),UInt8((b0 >> 24) & 0xFF),
            UInt8(b1 & 0xFF),UInt8((b1 >> 8) & 0xFF),UInt8((b1 >> 16) & 0xFF),UInt8((b1 >> 24) & 0xFF),
            UInt8(b2 & 0xFF),UInt8((b2 >> 8) & 0xFF),UInt8((b2 >> 16) & 0xFF),UInt8((b2 >> 24) & 0xFF),
            UInt8(b3 & 0xFF),UInt8((b3 >> 8) & 0xFF),UInt8((b3 >> 16) & 0xFF),UInt8((b3 >> 24) & 0xFF)
        ]

        return encrypted
```

**Comment by X-my** [comment]
@gonghao 
It worked for me, thks!

**Comment by krzyzanowskim** [comment]
I'm sorry, I forgot to push changes yesterday, it's all in place now from the `develop` branch.

**Comment by leoniralves** [comment]
When you will merge solution to a new pod version?
I'm using pod in podspec.

**Comment by krzyzanowskim** [comment]
When Xcode will out of beta, as always. Use develop branch in your Podfile

```
pod 'CryptoSwift', :git => "https://github.com/krzyzanowskim/CryptoSwift", :branch => "develop"
```

**Comment by nicolettemanas** [comment]
Hi, the workaround doesn't seem to work on simulators but it compiles to devices just fine. Just want to confirm whether it is the expected behavior?

**Comment by krzyzanowskim** [comment]
can't simplify it enough to the slowest possible machine ever. Please report Swift bug. http://bugs.swift.org/

**Comment by saltyskip** [comment]
```
  w = rk2[r][0]
            rk2[r][0] = U1[Int(B0(w))] ^ U2[Int(B1(w))] ^ U3[Int(B2(w))] ^ U4[Int(B3(w))]

            w = rk2[r][1]
            rk2[r][1] = U1[Int(B0(w))] ^ U2[Int(B1(w))] ^ U3[Int(B2(w))] ^ U4[Int(B3(w))]

            w = rk2[r][2]
            rk2[r][2] = U1[Int(B0(w))] ^ U2[Int(B1(w))] ^ U3[Int(B2(w))] ^ U4[Int(B3(w))]

            w = rk2[r][3]
            rk2[r][3] = U1[Int(B0(w))] ^ U2[Int(B1(w))] ^ U3[Int(B2(w))] ^ U4[Int(B3(w))]
```

same complexity issue on this code block line 312 AES.swift

**Comment by leed881010** [comment]
I had same issue either..
After using xcode 9 beta. complier error 'Expression was too complex to be solved in reasonable time; consider breaking up the expression into distinct sub-expressions' was appeared. on AES 

w = rk2[r][0]
            rk2[r][0] = U1[Int(B0(w))] ^ U2[Int(B1(w))] ^ U3[Int(B2(w))] ^ U4[Int(B3(w))]

            w = rk2[r][1]
            rk2[r][1] = U1[Int(B0(w))] ^ U2[Int(B1(w))] ^ U3[Int(B2(w))] ^ U4[Int(B3(w))]

            w = rk2[r][2]
            rk2[r][2] = U1[Int(B0(w))] ^ U2[Int(B1(w))] ^ U3[Int(B2(w))] ^ U4[Int(B3(w))]

            w = rk2[r][3]
            rk2[r][3] = U1[Int(B0(w))] ^ U2[Int(B1(w))] ^ U3[Int(B2(w))] ^ U4[Int(B3(w))]

here is my pod file
pod 'CryptoSwift', :git => 'https://github.com/krzyzanowskim/CryptoSwift.git', :branch => 'develop'

**Comment by krzyzanowskim** [comment]
Please file a Swift bug, like this https://bugs.swift.org/browse/SR-5140

**Comment by Ramki115** [comment]
I have issues with Xcode 9 using swift3. here are the errors

PKCS7' cannot be constructed because it has no accessible initializers
Cannot convert value of type 'Data' to expected argument type 'ArraySlice<UInt8>'

I am using  pod 'CryptoSwift', :git => 'https://github.com/krzyzanowskim/CryptoSwift.git', :branch => 'develop'

**Comment by krzyzanowskim** [comment]
@Ramki115 For swift 3 you need version 0.7.1 (or branch `swift32`) https://github.com/krzyzanowskim/CryptoSwift#swift-versions-support

**Comment by Ramki115** [comment]
Yup. it is working. Thanks @krzyzanowskim

**Comment by kurotsukikaitou** [comment]
For those who still on swift 3.1, who should use CryptoSwift 0.6.9 using `pod 'CryptoSwift', '0.6.9'`, the workaround still not implemented. I've use XCode 8.0 (since there are old project which still stuck at swift 2.3 and might be months before the higher ups give approval to migrate to latest swift).

The codes on 0.6.9 still using:
```swift
        var b0 = UInt32(block[block.startIndex + 0 + (0 << 2)]) << 0 | UInt32(block[block.startIndex + 1 + (0 << 2)]) << 8 | UInt32(block[block.startIndex + 2 + (0 << 2)]) << 16
            b0 = b0 | UInt32(block[block.startIndex + 3 + (0 << 2)]) << 24
        var b1 = UInt32(block[block.startIndex + 0 + (1 << 2)]) << 0 | UInt32(block[block.startIndex + 1 + (1 << 2)]) << 8 | UInt32(block[block.startIndex + 2 + (1 << 2)]) << 16
            b1 = b1 | UInt32(block[block.startIndex + 3 + (1 << 2)]) << 24
        var b2 = UInt32(block[block.startIndex + 0 + (2 << 2)]) << 0 | UInt32(block[block.startIndex + 1 + (2 << 2)]) << 8 | UInt32(block[block.startIndex + 2 + (2 << 2)]) << 16
            b2 = b2 | UInt32(block[block.startIndex + 3 + (2 << 2)]) << 24
        var b3 = UInt32(block[block.startIndex + 0 + (3 << 2)]) << 0 | UInt32(block[block.startIndex + 1 + (3 << 2)]) << 8 | UInt32(block[block.startIndex + 2 + (3 << 2)]) << 16
            b3 = b3 | UInt32(block[block.startIndex + 3 + (3 << 2)]) << 24
```
Instead of this code I found in the develop branch:
```swift
        let b00 = UInt32(block[block.startIndex.advanced(by: 0)])
        let b01 = UInt32(block[block.startIndex.advanced(by: 1)]) << 8
        let b02 = UInt32(block[block.startIndex.advanced(by: 2)]) << 16
        let b03 = UInt32(block[block.startIndex.advanced(by: 3)]) << 24
        var b0 = b00 | b01 | b02 | b03
        
        let b10 = UInt32(block[block.startIndex.advanced(by: 4)])
        let b11 = UInt32(block[block.startIndex.advanced(by: 5)]) << 8
        let b12 = UInt32(block[block.startIndex.advanced(by: 6)]) << 16
        let b13 = UInt32(block[block.startIndex.advanced(by: 7)]) << 24
        var b1 = b10 | b11 | b12 | b13
        
        let b20 = UInt32(block[block.startIndex.advanced(by: 8)])
        let b21 = UInt32(block[block.startIndex.advanced(by: 9)]) << 8
        let b22 = UInt32(block[block.startIndex.advanced(by: 10)]) << 16
        let b23 = UInt32(block[block.startIndex.advanced(by: 11)]) << 24
        var b2 = b20 | b21 | b22 | b23
        
        let b30 = UInt32(block[block.startIndex.advanced(by: 12)])
        let b31 = UInt32(block[block.startIndex.advanced(by: 13)]) << 8
        let b32 = UInt32(block[block.startIndex.advanced(by: 14)]) << 16
        let b33 = UInt32(block[block.startIndex.advanced(by: 15)]) << 24
        var b3 = b30 | b31 | b32 | b33
```

The develop branch you proposed to use was for latest swift, I presume. Any chance that would be fixed?

**Comment by krzyzanowskim** [comment]
@kurotsukikaitou the wsift versions and branches are listed in README

**Comment by kurotsukikaitou** [comment]
Yes. I know, which is why I use `pod 'CryptoSwift', '0.6.9'` because the project I worked on is in swift 3.1. When I compile the project, the 'too complex' error was shown on those codes. If I change the code according to my comment above, it works on simulator, but failed to compile for device because of signing error.

**Comment by coryhymel** [comment]
@kurotsukikaitou a signing error wouldn't have anything to do with the pod itself. Make sure to check your signing certificates and settings.
