### ISSUE TITLE
Problem in Swift 4

### ISSUE THREAD

**Issue by RajChanchal** [krzyzanowskim/CryptoSwift#446]
Kindly update the lib to Swift 4.

**Comment by krzyzanowskim** [comment]
current code does compile with swift 3 mode, you can use it with swift 4.

**Comment by Joannis** [comment]
Actually, it doesn't seem to compile with the Swift 3.2 mode for me. The only way for me to use CryptoSwift with Xcode 9 is to manually download and install a different Swift compiler from swift.org and use that instead of the bundled version.

**Comment by RajChanchal** [comment]
@Joannis I didn't know the way you have mentioned. Trying it, have downloaded a 352 MB file from [here](https://swift.org/download/#snapshots) for Swift 4.0. Should I run this package directly or I need to do something else prior to running the package?

**Comment by Joannis** [comment]
Not Swift 4.0, you'll need Swift 3.1 sadly. But that way you are able to run an older version of Swift with the newer Xcode. That's the only way I know. Alternatively you can install an older version of Swift 4.0 without the removed `@_specialized` attribute. But other features might not have been implemented at that point, either.

The only way to be able to run Swift 4.0, Xcode 9 *and* CryptoSwift is by putting CryptoSwift into editable mode in SPM, thus using the `develop` branch.

`swift package edit CryptoSwift --revision develop`

**Comment by krzyzanowskim** [comment]
yes. so the thing is that the 4.0 compiler (bundled with Xcode 9) support is available on develop branch. As usually, I keep master compatible with the latest stable release, that is 3.1. I'll add that to the Readme


Marcin,

**Comment by krzyzanowskim** [comment]
There is `swift4`.

**Comment by krzyzanowskim** [comment]
@IshwaryaRaja choose the right version from the README https://github.com/krzyzanowskim/CryptoSwift#swift-versions-support

**Comment by IshwaryaRaja** [comment]
But there is no version that supports Xcode 9.2 swift 3.2.3

**Comment by krzyzanowskim** [comment]
How it's different than 3.2 ? Checkout the branch `swift32`

**Comment by IshwaryaRaja** [comment]
It shows the error "Module compiled with Swift 4.0 cannot be imported in Swift 3.2.3"

**Comment by krzyzanowskim** [comment]
@IshwaryaRaja not a Sources problem. You have to build CryptoSwift with the 3.2 Swift. Check your project setup for that.

**Comment by IshwaryaRaja** [comment]
The swift language version in build settings is set to 3.2 only.
