### ISSUE TITLE
CryptoSwift not compiling due to a complex line of code

### ISSUE THREAD

**Issue by Joannis** [krzyzanowskim/CryptoSwift#447]
[This line of code in MD5](https://github.com/krzyzanowskim/CryptoSwift/blob/develop/Sources/CryptoSwift/MD5.swift#L104) is not compiling on my server. It's a 32-core nehalem CPU, and although it's powerful, one single core compiling the MD5.swift file is having trouble with Line 104. I see you already simplified the complex statement a little bit, because you split off one byte from the 32-bit unsigned integer. But I don't see why the others aren't split off, too.

**Comment by krzyzanowskim** [comment]
"to complex in reasonable time" factor is machine dependent. The best you can do is give it more time to compile https://github.com/krzyzanowskim/CryptoSwift/blob/master/scripts/CI.sh#L26

**Comment by krzyzanowskim** [comment]
see https://github.com/krzyzanowskim/CryptoSwift/issues/418#issuecomment-291589701

**Comment by Joannis** [comment]
I'm aware, thanks for the reminder of the workaround :)
But I don't see the added value of keeping them on a single line of code there. It prevents compilation on older machines (such as any Nehalem CPU), which is a downside I can see.

I'll use the workaround for now anyways :)
