### ISSUE TITLE
Support sequential encrypt() calls

### ISSUE THREAD

**Issue by richkzad** [krzyzanowskim/CryptoSwift#449]
aes = AES(..., .CBC...)
first = aes.encrypt(Array("hello".utf8))
second = aes.encrypt(Array("hello".utf8))

I expected the first & second to be different, since they're being encrypted with the same instance of AES, using the same instance of CBCModeWorker.

Instead, AES's encrypt() creates a new CBCModeWorker every time.

I had to solve this in my app by calling makeEncryptor() and using that throughout the life of the communication channel instead.

**Comment by krzyzanowskim** [comment]
For that, you should use encryptor, just as you used it. AES instance is stateless.
https://github.com/krzyzanowskim/CryptoSwift#incremental-updates

**Comment by richkzad** [comment]
I think the docs should be updated to say this. Given you can create an AES instance, it seems more intuitive to me that it wouldn't be stateless.
