### ISSUE TITLE
AES documentation problem with `Crypto.randomIV`

### ISSUE THREAD

**Issue by danyalaytekin** [krzyzanowskim/CryptoSwift#45]
Trying to compile the code snippet in the following part of the documentation:

```
// 2. Encrypt with key and random IV
let keyData = NSData.withBytes([0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00])
let ivData:NSData = Cipher.randomIV(keyData)
```

Leads to the error:

`Cannot invoke 'randomIV' with an argument list of type '(NSData)'`

Branch `swift12`, Xcode 6.3 beta 3.

**Comment by krzyzanowskim** [comment]
there is a change on develop branch (please use this one from now on) and README is not updated to this changes. In short NSData is replaced with [UInt8] and this is easily convertible between NSData and [UInt8].

There is extension to NSData to do conversion

````swift
extension NSData {
func bytes() -> [UInt8] { .. }
class public func withBytes(bytes: [UInt8]) -> NSData { .. }
}
````

**Comment by danyalaytekin** [comment]
Thanks @krzyzanowskim. :+1:

**Comment by krzyzanowskim** [comment]
Documentation updates with new version 0.0.9
