### ISSUE TITLE
Finding problems in Swift 3 syntax

### ISSUE THREAD

**Issue by Anjali-R21** [krzyzanowskim/CryptoSwift#452]
Hello,

I have included this repository in my podfile, and after converting this code to Swift 3 syntax I have faced following issues:
![screen shot 2017-06-27 at 3 39 48 pm](https://user-images.githubusercontent.com/23051999/27582753-b9300154-5b4f-11e7-984d-e7953f535dc9.png)

How do I make the syntax swift 3 compatible

**Comment by krzyzanowskim** [comment]
Go to Pods target and set Swift version in Builds Settings. This is CocoaPods issue and I can't do anything about it.

**Comment by Anjali-R21** [comment]
Ok

**Comment by krzyzanowskim** [comment]
https://github.com/CocoaPods/CocoaPods/pull/5530

**Comment by Anjali-R21** [comment]
Thanks a ton!
