### ISSUE TITLE
AES-256-CBC Decryption Problem

### ISSUE THREAD

**Issue by mrrashidi** [krzyzanowskim/CryptoSwift#453]
I want to decrypt a AES-256-CBC hash which it's IV is used as prefix (appended to it's first) and base64 encoded.
I've tested everything I found on the web but nothing useful.

Here is my Swift code: if you tale a look, you see that I took the first 16 bytes of it for IV, and the rest for the data, and I did the very same thing in C# and works perfectly fine! 

(By the way I'm new to Swift)

```
let cipher = response.data.toHexString();
let cipherData = try! cipher.aesDecrypt(key: "myKey")
print("Decrypted: \(cipherData)")

func aesDecrypt(key: String) throws -> String {
        let cipher: Data = Data(base64Encoded: self, options: 
NSData.Base64DecodingOptions(rawValue: 0))!;
        let data = cipher.subdata(in: 16..<cipher.endIndex)
        let iv = cipher.subdata(in: 0..<16).toHexString()
        let dec = try AES(key: key, iv: iv, blockMode:.CBC).decrypt(data)
        let decData = NSData(bytes: dec, length: Int(dec.count))
        let result = NSString(data: decData as Data, encoding: String.Encoding.utf8.rawValue)
        return String(result!)
    }
```
              
Here is my php code for encrypting and decrypting:

```
function encrypt_aes($string)
{
    $key = env('MC_KEY');
    $method = 'AES-256-CBC';
    $iv = openssl_random_pseudo_bytes(openssl_cipher_iv_length('aes-256-cbc'));
    $ciphertext =  openssl_encrypt($string, $method, $key, OPENSSL_RAW_DATA, $iv);
    return base64_encode($iv.$ciphertext);
}

function decrypt_aes($string)
{
    $key = env('MC_KEY');
    $method = 'AES-256-CBC';
    $cipher = base64_decode($string);
    $iv_size = openssl_cipher_iv_length('aes-256-cbc');

    $iv = substr($cipher, 0, $iv_size);
    return openssl_decrypt(substr($cipher, $iv_size), $method, $key, OPENSSL_RAW_DATA, $iv);
}
```
I'd really appreciate if you help me, Thanks

**Comment by krzyzanowskim** [comment]
Can I assume that the key you're using is 32 bytes long?

I don't fully understand what is going on in the Swift code. Looks like `aesDecrypt` is called on hex encoded data, but it's treated as base64 encoded data.

you're doing this
```swift
let cipher = response.data.toHexString();
```

then this, where `self` is (I assume) result of `response.data.toHexString()`:
```swift
let cipher: Data = Data(base64Encoded: self, options: NSData.Base64DecodingOptions(rawValue: 0))!;
```

you can't do that. Try this:
```swift
let cipher = response.data.toBase64();
```

**Comment by mrrashidi** [comment]
Thank you for answering me sir, my data is base64encoded and the key is 16bytes, by the way I've tested`let cipher = response.data.toString();` by converting it to ascii string but no luck! i've tested unicode and utf8 too.

```
func toString() -> String {
        return (NSString(data: self, encoding: String.Encoding.asciii.rawValue) as String?)!
    }
```

When I convert the Data to string and check my IV, it will be some random count like between 16 and 32.. not the 16 as I wanted! I thinks this is about encoding but I couldn't find any way!

and here is the given error:

`Block size and Initialization Vector must be the same length!`

**Comment by gunnartorfis** [comment]
Try this mate. I'd recommend using some Obfuscator to store your password. 

```
static func decrypt(value: String) -> String {
    let decoded: Data = Data(base64Encoded: value)!
        
    let iv = [UInt8](decoded.subdata(in: 0..<16))
    let encrypted = [UInt8](decoded.subdata(in: iv.count..<decoded.count))
        
    let key = [UInt8]("YourPassword".data(using: .ascii)!)
        
    do {
        let aes: AES = try AES(key: key, iv: iv, blockMode: .CBC)
        let text = try aes.decrypt(encrypted)
            
        if let string = String(bytes: text, encoding: .utf8) {
            return string
        } 
    } 
    catch {}
}
```
