### ISSUE TITLE
Error on compilation with Xcode 9 and Swift 3.2

### ISSUE THREAD

**Issue by cikpis** [krzyzanowskim/CryptoSwift#459]
Hey guys, I wanted to check my app if it's working with new Xcode 9 and Swift 3.2 but seems that I cannot because your library is not updated yet.

```
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/carmelo.gallo/Desktop/Projects/aegon-james-ios/Carthage/Checkouts/CryptoSwift/CryptoSwift.xcworkspace -scheme CryptoSwift -configuration Release -derivedDataPath /Users/carmelo.gallo/Library/Caches/org.carthage.CarthageKit/DerivedData/CryptoSwift/0.6.9 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build (launched in /Users/carmelo.gallo/Desktop/Projects/aegon-james-ios/Carthage/Checkouts/CryptoSwift)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/r3/pgb_5y4j5f9897vqr684k9g40000gp/T/carthage-xcodebuild.zjJcdp.log
```

Could you please fix that? Thanks in advance, cheers!

**Comment by krzyzanowskim** [comment]
See https://github.com/krzyzanowskim/CryptoSwift#swift-versions-support

branch `develop`

**Comment by cikpis** [comment]
👍

**Comment by sonaNSP** [comment]
Hi,
Im unable to compile in Xcode 9.0.
Please can you guide me on this

**Comment by krzyzanowskim** [comment]
@sonaNSP use the right version https://github.com/krzyzanowskim/CryptoSwift#swift-versions-support and verify the setup to use the right Swift version.

**Comment by sonaNSP** [comment]
I'm using
 pod 'CryptoSwift', :git => "https://github.com/krzyzanowskim/CryptoSwift", :branch => "master"
still facing errors.
Please can you specify the path.

**Comment by krzyzanowskim** [comment]
It really depends on what you need, for swift 3.2 you should use CryptoSwift version 0.7.0, master branch is for Swift 4

**Comment by sonaNSP** [comment]
Thanks.. its working now

**Comment by SushmithaRaja** [comment]
Hi, I get this error for Xcode 9.2 
Module compiled with Swift 4.0 cannot be imported in Swift 3.2.3
can you please suggest the version I should use in pods

**Comment by krzyzanowskim** [comment]
@SushmithaRaja choose the version that works for you https://github.com/krzyzanowskim/CryptoSwift#swift-versions-support

**Comment by SushmithaRaja** [comment]
can you please suggest me the right version coz I have tried most of them and nothing clicked

**Comment by SushmithaRaja** [comment]
I tried installing version 0.7.0 but I am unable to do it .
it redirects to version 0.7.2 can you help me with this please.

**Comment by krzyzanowskim** [comment]
v 0.7.0 was published to the CocoaPods, you can download it manually too https://github.com/krzyzanowskim/CryptoSwift/releases/tag/0.7.0

If you need help with CocoaPods, please ask on the CocoaPods.

**Comment by SushmithaRaja** [comment]
I downloaded it manually and it worked sorry for the late reply. Thank you so much.
