### ISSUE TITLE
Support Carthage Cache

### ISSUE THREAD

**Issue by beseder42** [krzyzanowskim/CryptoSwift#460]
Like this caching is supported easily:

https://github.com/typelift/SwiftCheck/pull/227

**Comment by krzyzanowskim** [comment]
What is needed to support that?

**Comment by beseder42** [comment]
A `CryptoSwift-Swift.h#´ header file is needed by carthage to read the version of Swift in the built framework.

According to the mentioned pull request it is achieved by deleting these settings in the project file:
SWIFT_INSTALL_OBJC_HEADER = NO;		
SWIFT_OBJC_INTERFACE_HEADER_NAME = "";

**Comment by krzyzanowskim** [comment]
would you mind to create PR and test it? I'm happy to merge it.

**Comment by krzyzanowskim** [comment]
any progress on this ?

**Comment by beseder42** [comment]
Sorry, I was busy ... will do it tomorrow!

**Comment by beseder42** [comment]
#463
