### ISSUE TITLE
Leak Blowfish 

### ISSUE THREAD

**Issue by MrCirdo** [krzyzanowskim/CryptoSwift#461]
There is leak in BlowFish algorithm

This exemple of Code (Repeat twice for Intruments)
``` swift
import CryptoSwift

do{
    let blowfish = try Blowfish(key: "12345678", iv: "", blockMode: .CBC, padding:  NoPadding())
    let data = try blowfish.encrypt(Array("1234567812345678".utf8))
}catch _{
    print("Error")
}

do{
    let blowfish = try Blowfish(key: "1234567812345678", iv: "", blockMode: .CBC, padding:  NoPadding())
    let data = try blowfish.encrypt(Array("1234567812345678".utf8)) 
}catch _{
    print("Error")
}
```
Here is Intruments Trace :
[Leak BlowFish.trace.zip](https://github.com/krzyzanowskim/CryptoSwift/files/1160075/Leak.BlowFish.trace.zip)

**Comment by samynu** [comment]
I've the same issue with the latest release version.

**Comment by SunnyGit** [comment]
I get a leak identified in BlowFish as well. Is there a fix for it ?

**Comment by Frizlab** [comment]
I am able to reproduce the issue. Found some ideas; will try and find the definitive source of the problem later.

**Comment by fabrijp** [comment]
Any fix for this issue ? I'm experiencing the same problem on a project.

**Comment by fabrijp** [comment]
@Frizlab Any of your ideas worked ? Could you please share  it ?  Thanks

**Comment by Frizlab** [comment]
I tried looking at it at some point in time, but I’ve been busy… 🤷‍♂️ I’ll probably try again at some point! But for now, if you want to have a go, be my guest. I could provide an Instrument trace I think if you want.

**Comment by fabrijp** [comment]
Thanks @Frizlab I end up using another framework.

**Comment by pranav1605** [comment]
@Frizlab which framework did you end up using, kindly let me know.

**Comment by fabrijp** [comment]
@pranav1605 here it is: 
https://github.com/iosdevzone/IDZSwiftCommonCrypto
I have stripped out only blowfish part that I needed and included in my project. Works nicely.
