### ISSUE TITLE
No such module 'CryptoSwift'

### ISSUE THREAD

**Issue by HariniHamsa** [krzyzanowskim/CryptoSwift#462]
I am using drag and drop to have cryptoswift in my Xcode9 project and added taget dependencies for both iOS and tvOS, however when i build the tvOS target, I am getting "No such module 'CryptoSwift'". Using the branch develop as I am on swift 3.2

**Comment by krzyzanowskim** [comment]
Please attache the project. Can't help with the Xcode setup without looking at it.

**Comment by archilo20** [comment]
I'm having the same issue :/ 
[DoctorCel.zip](https://github.com/krzyzanowskim/CryptoSwift/files/1354384/DoctorCel.zip)
