### ISSUE TITLE
CryptoSwift.AES.Error.dataPaddingRequired:

### ISSUE THREAD

**Issue by Ketan-Wadyalkar** [krzyzanowskim/CryptoSwift#465]
I am using CryptoSwift for encryption in my app. Below is the code
 
let str = "1234567890"

 let input: Array<UInt8> = Array(str.utf8)

 let encrypted: Array<UInt8> = try! AES(key: "secret0key000000", iv: "0123456789012345", blockMode: .CBC, padding: NoPadding()).encrypt(input)

 let output = encrypted.toHexString()

I am getting below error when this method is getting executed.

fatal error: 'try!' expression unexpectedly raised an error: CryptoSwift.AES.Error.dataPaddingRequired: file /Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-802.0.53/src/swift/stdlib/public/core/ErrorType.swift, line 182

What am i doing wrong here ??...
If i use  PKCS7() padding, then it's working fine.
Is it a bug or i have missed something ??

**Comment by Ketan-Wadyalkar** [comment]
Sorry
My bad, as the string length was < 16, thats why i was getting this error

**Comment by shadyk** [comment]
@Ketan-Wadyalkar I have the same problem and I didnt get the above. 
The string length should be > 16 in order to encrypt? 
Usually the string length is entered by the user!

**Comment by krzyzanowskim** [comment]
@shadyk it depends, but for cbc yes, and that why u need padding. Padding is the solution to that limitation
