### ISSUE TITLE
can't even import CryptoSwift using cocoapods

### ISSUE THREAD

**Issue by jonavuka** [krzyzanowskim/CryptoSwift#474]
I tried multiple ways but for some reason I can't get CryptoSwift to import into my project. I add into my podfile "pod 'CryptoSwift'" and do a pod install. I reload xcode and check the pods and see it's there, but then when I try to import it into one of my swift files, xcode can't find it. I originally had a min of ios 10 so i lowered it to 8.0 to test and it still didnt work. I'm no cocoapod expert but I notice that when I see my Podfile I see two target memberships: CryptoSwift and Pods-Project. I have two other cocoapods: admob and googlemaps, I think they both were but in the Pods-Project target membership.

**Comment by krzyzanowskim** [comment]
try ask https://github.com/CocoaPods/CocoaPods I'd try to deintegrate Pods and install it again. Looks like some setup issue.

**Comment by jonavuka** [comment]
It's weird I moved the pod declaration for cryptoswift in my podfile and now I can import! For all other who may run into this issue declare cryptoswift pod above all others

**Comment by krzyzanowskim** [comment]
sounds like worth to report to cocoapods.
