### ISSUE TITLE
Please help AES Encryption 

### ISSUE THREAD

**Issue by iOSDevAkshay** [krzyzanowskim/CryptoSwift#476]
I need to encrypt a string in swift , I have a JAVA code as below 
public static String encrypt(String strToEncrypt)
	{
		try
		{
			Cipher cipher = Cipher.getInstance("AES/ECB/PKCS5Padding");
			cipher.init(Cipher.ENCRYPT_MODE, secretKey);        
			setEncryptedString(Base64.encodeBase64String(cipher.doFinal(strToEncrypt.getBytes("UTF-8"))));
		}
		catch (Exception e)
		{	           
			System.out.println("Error while encrypting: "+e.toString());
		}
		return null;
	}

Please help me how to achieve in swift ?

**Comment by iOSDevAkshay** [comment]
"AES/ECB/PKCS5Padding" How to implement this using cryptoswift ?

**Comment by krzyzanowskim** [comment]
Read this: https://github.com/krzyzanowskim/CryptoSwift#aes-advanced-usage
and this: https://github.com/krzyzanowskim/CryptoSwift/issues/367#issuecomment-256919320

--
Yours Java to Swift Translation Service sincerely.
