### ISSUE TITLE
What's the encoding format to convert encrypted bytes array to string?

### ISSUE THREAD

**Issue by SnitramDev** [krzyzanowskim/CryptoSwift#478]
let key = [UInt8]("B999D8EDF17767AE8CF8A14FA6A36BD2".data(using: .utf8)!)

        let input: Array<UInt8> = [UInt8]("NEW TEST XXXYYYZZZ".data(using: .utf8)!)
        
        do {
            let encrypted = try AES(key: key, blockMode: .CBC, padding: PKCS7()).encrypt(input)
            let decrypted = try AES(key: key, blockMode: .CBC, padding: PKCS7()).decrypt(encrypted)
            print("**********************")
            print(String(bytes: encrypted, encoding: String.Encoding.utf8) ?? "No string.")
            print(String(bytes: decrypted, encoding: String.Encoding.utf8) ?? "No string.")
            print("**********************")
        } catch {
            print(error)
        }

I'm able to get a string for the decrypted bytes array, but I'm not able to get a string for the encrypted bytes array. So, I guess the problem must be on the encoding format? What's the encoding format to convert an encrypted bytes array to a string?

Thanks!

**Comment by krzyzanowskim** [comment]
`encrypted` is an array of bytes, it is not a string. You may want to encode it with base64 if you want. (helper is available)
