### ISSUE TITLE
0.7.0-alpha.1 iTunes Connect Error ITMS-90060

### ISSUE THREAD

**Issue by zirinisp** [krzyzanowskim/CryptoSwift#479]
Using Carthage with the above version I get the following error when I try to upload to the App Store.

[Transporter Error Output]: ERROR ITMS-90060: "This bundle is invalid. The value for key CFBundleShortVersionString '0.7.0-alpha.1' in the Info.plist file must be a period-separated list of at most three non-negative integers."

The error is self explanatory and I have seen it before. Please remove -alpha.1 from the target version and it should then upload to the App Store without any problems.

**Comment by zirinisp** [comment]
Could not create a pull request as it is just a renamed tag and GitHub, sees everything else identical.

I also could not include my fork on my project, as it is a dependency of another dependency.

Hope this issue gets fixed soon.

**Comment by krzyzanowskim** [comment]
oh crap. Feel free to prepare PR for the correct branch. thanks.

**Comment by zirinisp** [comment]
Apparently this issue has already been solved on 0.7.1 and carthage was using a cached version. Had to delete carthage cache and get the new one to make it work.

So no PR, the problem has already been solved.
