### ISSUE TITLE
Cipher.randomIV

### ISSUE THREAD

**Issue by mdclark01** [krzyzanowskim/CryptoSwift#48]
When encrypting and decrypting is Cipher.randomIV based off the key? Im having issues when I encrypted text then go back to decrypted the text using a different Cipher.randomIV value but the same key I get nil.

**Comment by mdclark01** [comment]
Actually my problem sometimes is not resolved by using the same randomIV I have started to encounter 

*** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[_NSInlineData subdataWithRange:]: range {0, 18446744073709551453} exceeds data length 16'

when trying to decrypt. This references PKCS7.swift :

```
public func removePadding() -> NSData {
    var padding:Byte = 0
    data.subdataWithRange(NSRange(location: data.length - 1, length: 1)).getBytes(&padding, length: 1)
    
    if padding >= 1 {
        return data.subdataWithRange(NSRange(location: 0, length: data.length - Int(padding)))
    }
    return data
}
```
any idea's what I might be doing wrong?

Here is how i'm decrypting 
```
let keyDataNSData = NSData(base64EncodedString: keyData, options: NSDataBase64DecodingOptions.IgnoreUnknownCharacters)

let aesEncryptedMessage = NSData(base64EncodedString: theMessage.text, options: NSDataBase64DecodingOptions.IgnoreUnknownCharacters)

let ivData:NSData = Cipher.randomIV(keyDataNSData!)

let decryptedData = Cipher.AES(key: keyDataNSData!, iv: ivData, blockMode: .CBC).decrypt(aesEncryptedMessage!)
```

**Comment by krzyzanowskim** [comment]
I believe this is fixed on develop branch

**Comment by mdclark01** [comment]
Is it possible to use cocopods to install the development branch?

**Comment by krzyzanowskim** [comment]
yes sure

pod 'CryptoSwift', :git => "https://github.com/krzyzanowskim/CryptoSwift", :branch => "develop"

**Comment by mdclark01** [comment]
Thanks!
