### ISSUE TITLE
cocoapods install resulting in issues

### ISSUE THREAD

**Issue by bj97301** [krzyzanowskim/CryptoSwift#480]
pod 'CryptoSwift' 
results in these errors:
Swift Compiler Error Group
.../CryptoSwift/Sources/CryptoSwift/Generics.swift:31:14: Expected identifier for type name
.../CryptoSwift/Sources/CryptoSwift/Generics.swift:31:30: Expected declaration
.../CryptoSwift/Sources/CryptoSwift/UInt16+Extension.swift:20:18: Expected identifier for type name
.../CryptoSwift/Sources/CryptoSwift/UInt16+Extension.swift:20:46: Expected declaration
.../CryptoSwift/Sources/CryptoSwift/UInt16+Extension.swift:18:1: In extension of 'UInt16'
.../CryptoSwift/Sources/CryptoSwift/UInt16+Extension.swift:25:18: Expected identifier for type name
.../CryptoSwift/Sources/CryptoSwift/UInt16+Extension.swift:25:46: Expected declaration
.../CryptoSwift/Sources/CryptoSwift/UInt16+Extension.swift:18:1: In extension of 'UInt16'
.../CryptoSwift/Sources/CryptoSwift/UInt32+Extension.swift:29:18: Expected identifier for type name
.../CryptoSwift/Sources/CryptoSwift/UInt32+Extension.swift:29:46: Expected declaration
.../CryptoSwift/Sources/CryptoSwift/UInt32+Extension.swift:27:1: In extension of 'UInt32'
.../CryptoSwift/Sources/CryptoSwift/UInt32+Extension.swift:34:18: Expected identifier for type name
.../CryptoSwift/Sources/CryptoSwift/UInt32+Extension.swift:34:46: Expected declaration
.../CryptoSwift/Sources/CryptoSwift/UInt32+Extension.swift:27:1: In extension of 'UInt32'
.../CryptoSwift/Sources/CryptoSwift/UInt64+Extension.swift:24:18: Expected identifier for type name
.../CryptoSwift/Sources/CryptoSwift/UInt64+Extension.swift:24:46: Expected declaration
.../CryptoSwift/Sources/CryptoSwift/UInt64+Extension.swift:18:1: In extension of 'UInt64'
.../CryptoSwift/Sources/CryptoSwift/UInt64+Extension.swift:29:46: Expected declaration
.../CryptoSwift/Sources/CryptoSwift/UInt64+Extension.swift:18:1: In extension of 'UInt64'
.../CryptoSwift/Sources/CryptoSwift/UInt64+Extension.swift:29:18: Expected identifier for type name
.../CryptoSwift/Sources/CryptoSwift/AES.swift:555:83: 'C' does not have a member type named 'Element'; did you mean '_Element'?
.../CryptoSwift/Sources/CryptoSwift/AES.swift:574:83: 'C' does not have a member type named 'Element'; did you mean '_Element'?
.../CryptoSwift/Sources/CryptoSwift/Cipher.swift:27:76: 'C' does not have a member type named 'Element'; did you mean '_Element'?
.../CryptoSwift/Sources/CryptoSwift/Cipher.swift:33:76: 'C' does not have a member type named 'Element'; did you mean '_Element'?
.../CryptoSwift/Sources/CryptoSwift/AES.swift:562:39: Generic parameter 'T' could not be inferred
.../CryptoSwift/Sources/CryptoSwift/AES.swift:594:63: Ambiguous reference to member 'subscript'
.../CryptoSwift/Sources/CryptoSwift/BatchedCollection.swift:51:5: Found this candidate
.../Swift.Collection:27:12: Found this candidate
.../Swift._Indexable:23:12: Found this candidate
.../Swift._Indexable:23:12: Found this candidate
.../Swift._Indexable:45:12: Found this candidate

**Comment by bj97301** [comment]
any help is much appreciated :)

**Comment by mohpor** [comment]
Can confirm this, I have the same issues.

**Comment by crystalztl** [comment]
same issue when building the framework from the proj. it is the proj itself issue rather than the cocoapods integration.

**Comment by hardikdevios** [comment]
For now, use this because `master` code is **SWIFT 4** 

`pod 'CryptoSwift', '~> 0.6.9'
`

RIP **SWIFT 3** in short time 👍

**Comment by wasa1234** [comment]
Swift versions support

    Swift 1.2: branch swift12 version <= 0.0.13
    Swift 2.1: branch swift21 version <= 0.2.3
    Swift 2.2, 2.3: branch swift2 version <= 0.5.2
    Swift 3.0, 3.1, branch swift3 version <= 0.6.9
    Swift 3.2, branch swift32 version <= 0.7.0
    Swift 4.0, branch master

**Comment by krzyzanowskim** [comment]
The transition from Swift 3.1 (Xcode8) to Swift 3.2 (Xcode9) is hard. For now, please use the 0.6.9 for Xcode8.

Current master is Swift 3.2 code (that differs from Swift 3.1 a lot). It's a temporary inconvenience.

**Comment by bj97301** [comment]
Good to know.  May I suggest bumping down the default version for the cocoapods install?

**Comment by krzyzanowskim** [comment]
That's not something I can do, cocoapods decide what is default version

**Comment by bj97301** [comment]
I see.

**Comment by bj97301** [comment]
Thanks for the quick reply and all of the help btw.  I really appreciate it.
