### ISSUE TITLE
Exclude extra sources if I need only one type of encryption?

### ISSUE THREAD

**Issue by gerchicov-bp** [krzyzanowskim/CryptoSwift#482]
For example I need AES encryption only? Could you describe which files are extra and could be removed.

**Comment by krzyzanowskim** [comment]
nope, sorry. Too busy with life. Why would you extract that code? The module is so small anyway.

**Comment by gerchicov-bp** [comment]
@krzyzanowskim 

Maybe the project is small but there are a lot of files in it.

for example from readme:
```
Cipher

AES-128, AES-192, AES-256
ChaCha20
Rabbit
Blowfish
```

most of programmers doesn't need more than one kind of encryption in one project. In such cases even sources are not needed.
So at least if there is any way to import these sources manually, exclude files I will never use and edit `import` directives? Of course if it doesn't involve the whole project rewriting

**Comment by krzyzanowskim** [comment]
I'm not supporting that kind of work, sorry. It's too hard to maintain. For the same reason most of the libraries don't offer it too (look at OpenSSL, CommonCrypto etc.). I'd just use the sub project and doesn't care what file is in it.

**Comment by gerchicov-bp** [comment]
Ok thanks for explanation. Anyways you could mark it as "enhancement"

**Comment by krzyzanowskim** [comment]
Thanks for the report anyway. I'm have no plans to work on that anytime soon though.
