### ISSUE TITLE
Error while compiling in XCode 9

### ISSUE THREAD

**Issue by SnitramDev** [krzyzanowskim/CryptoSwift#485]
When compiling in XCode 9, I get the following errors:

<img width="315" alt="screen shot 2017-09-13 at 17 24 46" src="https://user-images.githubusercontent.com/8367143/30391353-92412f00-98a8-11e7-8331-b1b026141b35.png">

Thanks! :)

**Comment by krzyzanowskim** [comment]
check the README and choose the right. version to your Swift

**Comment by gyzerocc** [comment]
I think the branch should be "swift4" and not the "master" in README
```
Swift versions support
   Swift 1.2: branch swift12 version <= 0.0.13
   Swift 2.1: branch swift21 version <= 0.2.3
   Swift 2.2, 2.3: branch swift2 version <= 0.5.2
   Swift 3.0, 3.1, branch swift3 version <= 0.6.9
   Swift 3.2, branch swift32 version <= 0.7.0
   Swift 4.0, branch master
```
@krzyzanowskim

**Comment by krzyzanowskim** [comment]
actually it should be "master" at the end of the day, it's just not yet released. Synch all the README's from all the branches is hard ;)

**Comment by Samyro** [comment]
Hi, I checkout branch swift4, but it still cannot compile. Mainly because of the issue "Argument labels '(trancatingIfNeeded:)' do not match any available overloads. Thanks

**Comment by krzyzanowskim** [comment]
means you don't use swift4 compiler for some reason. verify your setup. this is a change I. Swift standard library introduced by xcode9

**Comment by Samyro** [comment]
It turns out that I was compiling with swift4 Xcode 9 beta version. After updated to Xcode 9 GM Seed, problem solved. Thank you for your reply.

**Comment by SnitramDev** [comment]
Got it! Thanks.

**Comment by IshwaryaRaja** [comment]
My app runs on the simulator but does not run when connected to the device. It shows the error 
Use of unresolved identifier "AES". I am adding that the import statement is getting compiled and does not show any error.

**Comment by mohdimran3pg** [comment]
Hi Team,
I am getting Cryptoswift lib compile time errors when running it on **XCode 9.4.1**, i updated my pod file with **"https://github.com/krzyzanowskim/CryptoSwift", :branch => "master"** version of Cryptoswift but still getting same.

<img width="1440" alt="compile time error" src="https://user-images.githubusercontent.com/29884011/42160445-d5c4b600-7e14-11e8-9b99-7ab942211335.png">
