### ISSUE TITLE
SHA1 calculation really take great long time

### ISSUE THREAD

**Issue by Mioke** [krzyzanowskim/CryptoSwift#487]
```swift
let temp = CFAbsoluteTimeGetCurrent()  * 1000
let sha1 = data.sha1() // data's size is 256k
                        
inblock = CFAbsoluteTimeGetCurrent()  * 1000
print("[sha1] sha1: \(inblock - temp)")
```
Duration is floating between 20~30ms. But the lib `CommonCrypto` cost less than 1ms. I'm already turn on -WMO

---
version 0.6.9

**Comment by krzyzanowskim** [comment]
Make sure it's in release mode. Now you know everything about Swift Performance. holds my, that will speed up, I have no time to sit on it recently though.

**Comment by krzyzanowskim** [comment]
It's more a language thing, it's like comparing C memory management and Swift memory management. Swift approach is way slower.

I'm closing this one as duplicate #30

**Comment by aahung** [comment]
Release mode is way faster than debug mode
