### ISSUE TITLE
Not compatible with Swift 1.2 and Xcode 6.3 (6D570)

### ISSUE THREAD

**Issue by prefect42** [krzyzanowskim/CryptoSwift#49]
A lot of syntax changes, errors and warnings must be fixed to make CryptoSwift work on Xcode 6.3

**Comment by ashchan** [comment]
FYI: there's a `swift12` branch.

**Comment by krzyzanowskim** [comment]
check banch "develop" - its ready dor Swift 1.2. Will be merged to master very soon

**Comment by prefect42** [comment]
Very good! Thanks!

**Comment by zeusent** [comment]
I'm really new to this CocoaPods thing. Can you tell me how my Podfile entry should look like so that I use the develop branch? Also, should it be `develop` or `swift12`? Thanks!

**Comment by krzyzanowskim** [comment]
new version is available on master branch. check README for details.
