### ISSUE TITLE
I am not able to comile CryptoSwift in my xcode version 8.3.3

### ISSUE THREAD

**Issue by RVERM05** [krzyzanowskim/CryptoSwift#490]
Hello,
I am not able to comile CryptoSwift in my xcode version 8.3.3. I can not also set no manually because I did not find Legacy Swift_version.

Please have a look attached screenshot.
<img width="1252" alt="screen shot 2017-09-18 at 1 20 44 pm" src="https://user-images.githubusercontent.com/28747877/30532764-a10aaa6a-9c73-11e7-9735-9912b60a7664.png">
<img width="1245" alt="screen shot 2017-09-18 at 1 20 38 pm" src="https://user-images.githubusercontent.com/28747877/30532765-a10e4c42-9c73-11e7-83dc-70896581ba17.png">
<img width="1250" alt="screen shot 2017-09-18 at 1 19 57 pm" src="https://user-images.githubusercontent.com/28747877/30532766-a11d7f28-9c73-11e7-8189-d8dfe07bbd3e.png">

**Comment by krzyzanowskim** [comment]
What version you're trying to build https://github.com/krzyzanowskim/CryptoSwift#swift-versions-support ?
