### ISSUE TITLE
Install CryptoSwift 0.6.9 through SPM

### ISSUE THREAD

**Issue by tpvslics** [krzyzanowskim/CryptoSwift#493]
Hi Krzyzanowskim:

I am trying to install CryptoSwift according to:
https://github.com/krzyzanowskim/CryptoSwift#swift-versions-support

I need package version 0.6.9 according to this (Swift 3.1), since the latest version in swift 3.1 generates many errors ...

I'm trying to install it through SPM but I can not get that version down ... the question is, what is the correct line that I should put to indicate dependency with that version ?.

In advance I thank you.

**Comment by krzyzanowskim** [comment]
this should work

```swift
Package(url: "https://github.com/krzyzanowskim/CryptoSwift.git", version: "0.7.2")
```
