### ISSUE TITLE
SIGABRT: malloc: *** error for object 0x1702459a0: Invalid pointer dequeued from free list 

### ISSUE THREAD

**Issue by AccentSystems** [krzyzanowskim/CryptoSwift#494]
Hi. FIrst of all thank you for this lib. It helps a lot.

I am having some troubles to succeed with a simple AES256ECB encrypt.
The error (described on the issue title) is triggered every second time I call the encrypt function. Seems like a memory leak but I am not able to debug it properly.

Here is the code I call:

    challenge = self.unlockChallengeChar.value!
                
    print("challenge: \(challenge.hexString!)") // prints f7a4ec66629e5fe371c3f973fbae4675
                
    //Encrypt pass
    var pass = ""
    var key = "f3a5863d037dd832da483cc15dbf6421"
    let index = key.index(key.startIndex, offsetBy: 32)
    do{
        pass = try challenge.aesEncrypt(key.dataValue()!.bytes).hexString!.substring(to: index)
                    
        let test1 = try challenge.aesEncrypt(key.dataValue()!.bytes).hexString!.substring(to: index)
        let test2 = try challenge.aesEncrypt(key.dataValue()!.bytes).hexString!.substring(to: index)
    }catch{
        print("error encrypting password: \(error)")
    }

    print("pass: \(pass)") //pass prints ok if I comment the test1 and test2 lines

Where the aesEncrypt method is an extension of Data:

    extension Data {
      func aesEncrypt(_ key: Array<UInt8>) throws -> Data{
        
          let toEncrypt: Array<UInt8> = self.getByteArray()
        
          let iv: Array<UInt8> = []
        
          var encrypted: Array<UInt8>? = nil
        
          do {
              encrypted = try AES(key: key, iv: iv, blockMode: .ECB, padding: PKCS7()).encrypt(toEncrypt)
          } catch {
              print("error: \(error.localizedDescription)")
          }
        
          let passEncrypted = Data(bytes: encrypted!)
        
          return passEncrypted
      }
    }

The catch is never triggered :S

Note that the IV key is empty. If I call the aesEncrypt on pass only once... MOST of times it goes well and the result is the expected one. But if I call the test1 and test2 lines it will crash every time in one of them (as a starting point) but in any random function inside de CryptoSwift lib.

Sometimes, it also triggers a different but similar issue like:

SIGABRT: malloc: *** error for object 0x1702459a0: Mismatched size for pointer dequeued from free list.

Any idea what am I doing wrong? May the IV empty value be the problem? Anything I could try to fix this.

Thanks a lot in advance.

**Comment by krzyzanowskim** [comment]
Is this a Linux? Can you make a simple project to reproduce that? I'd say it's Swift fault but who knows

**Comment by AccentSystems** [comment]
Hi Marcin, thanks for the reply.

I am working on a iMAC, with Xcode 8.3.3. CryptoSwift library is 0.6.9 (if I try to pod the 0.7.0 it jumps to the 0.7.1 and it does not work as it is Swift4)

I created a new project with only one view controller. The error is still there. I also tried with an IV of 16 bytes of 0x00.

Many times the error is different and it triggers on different functions of the CryptoSwift lib.

This is my pod file:

    source 'https://github.com/CocoaPods/Specs.git'
    platform :ios, '8.0'
    use_frameworks!

    target 'CryptoTest' do

        pod 'CryptoSwift', '~> 0.6.9'

    end

Here is the code of the main view controller:

    import UIKit
    import CryptoSwift

    class ViewController: UIViewController {

    override func viewDidLoad() {
        super.viewDidLoad()
        
        doCrypto()
    }
    
    func doCrypto(){
        
        let challenge = "f7a4ec66629e5fe371c3f973fbae4675".uppercased().dataValue()!
        
        //Encrypt pass
        var pass = ""
        var test1 = ""
        var test2 = ""
        let key = "f3a5863d037dd832da483cc15dbf6421".uppercased()
        let index = key.index(key.startIndex, offsetBy: 32)
        do{
            pass = try challenge.aesEncrypt(key.dataValue()!.bytes).hexString!.substring(to: index)
            
            test1 = try challenge.aesEncrypt(key.dataValue()!.bytes).hexString!.substring(to: index)
            test2 = try challenge.aesEncrypt(key.dataValue()!.bytes).hexString!.substring(to: index)
        }catch{
            print("error encrypting password: \(error)")
        }
        
        
        print("pass: \(pass)")
        print("test1: \(test1)")
        print("test2: \(test2)")
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
    }

    extension String {
    func dataValue() -> Data? {
        var data = Data(capacity: characters.count / 2)
        
        let regex = try! NSRegularExpression(pattern: "[0-9a-f]{1,2}", options: .caseInsensitive)
        regex.enumerateMatches(in: self, options: [], range: NSMakeRange(0, characters.count)) { match, flags, stop in
            let byteString = (self as NSString).substring(with: match!.range)
            var num = UInt8(byteString, radix: 16)!
            data.append(&num, count: 1)
        }
        
        guard data.count > 0 else {
            return nil
        }
        
        return data
    }
    
    }

    extension Data {
    var hexString: String? {
        return map { String(format: "%02x", $0) }.joined(separator: "")
    }
    
    func getByteArray() -> Array<UInt8> {
        let count = self.count / MemoryLayout<Int8>.size
        var array = [UInt8](repeating: 0, count: count)
        self.copyBytes(to: &array, count:count * MemoryLayout<UInt32>.size)
        return array
    }
    
    func aesEncrypt(_ key: Array<UInt8>) throws -> Data{
        
        let toEncrypt: Array<UInt8> = self.getByteArray()
        
        let iv: Array<UInt8> = []
        //let iv: Array<UInt8> = "00000000000000000000000000000000".dataValue()!.getByteArray()
        
        var encrypted: Array<UInt8>? = nil
        
        do {
            encrypted = try AES(key: key, iv: iv, blockMode: .ECB , padding: PKCS7()).encrypt(toEncrypt)
        } catch {
            print("errorooror: \(error.localizedDescription)")
        }
        
        let passEncrypted = Data(bytes: encrypted!)
        
        return passEncrypted
        
    }
    
    }

The following error is triggered:

![c1](https://user-images.githubusercontent.com/18568521/30633296-6bf19568-9deb-11e7-9cc3-dcf1ebffe63c.png)

![c2](https://user-images.githubusercontent.com/18568521/30633348-a4c15ba8-9deb-11e7-8758-0215867eddb6.png)

    CryptoTest(836,0x1b237cb40) malloc: *** error for object 0x17000dfe0: Mismatched size for pointer dequeued from free list
    *** set a breakpoint in malloc_error_break to debug

Attached you will find the full project.

Thank you!

[CryptoTest.zip](https://github.com/krzyzanowskim/CryptoSwift/files/1317014/CryptoTest.zip)

**Comment by krzyzanowskim** [comment]
It doesn't seem the CryptoSwift issue, it looks like the way you manipulate data is broken, below working code

```swift
class ViewController: UIViewController {

    override func viewDidLoad() {
        super.viewDidLoad()
        
        doCrypto()
    }
    
    func doCrypto(){
        
        let challenge = Data(Array("f7a4ec66629e5fe371c3f973fbae4675".uppercased().utf8))
        
        //Encrypt pass
        var pass = ""
        var test1 = ""
        var test2 = ""
        let keyString = "f3a5863d037dd832da483cc15dbf6421"
        let key = Array(keyString.uppercased().utf8)
        let index = keyString.index(keyString.startIndex, offsetBy: 32)
        do{
            pass = try challenge.aesEncrypt(key).toHexString().substring(to: index)

            test1 = try challenge.aesEncrypt(key).toHexString().substring(to: index)
            test2 = try challenge.aesEncrypt(key).toHexString().substring(to: index)
        }catch{
            print("error encrypting password: \(error)")
        }
        
        
        print("pass: \(pass)")
        print("test1: \(test1)")
        print("test2: \(test2)")
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }


}

extension String {
//    func dataValue() -> Data? {
//        var data = Data(capacity: characters.count / 2)
//        
//        let regex = try! NSRegularExpression(pattern: "[0-9a-f]{1,2}", options: .caseInsensitive)
//        regex.enumerateMatches(in: self, options: [], range: NSMakeRange(0, characters.count)) { match, flags, stop in
//            let byteString = (self as NSString).substring(with: match!.range)
//            var num = UInt8(byteString, radix: 16)!
//            data.append(&num, count: 1)
//        }
//        
//        guard data.count > 0 else {
//            return nil
//        }
//        
//        return data
//    }

}

extension Data {
//    var hexString: String? {
//        return map { String(format: "%02x", $0) }.joined(separator: "")
//    }

//    func getByteArray() -> Array<UInt8> {
//        let count = self.count / MemoryLayout<Int8>.size
//        var array = [UInt8](repeating: 0, count: count)
//        self.copyBytes(to: &array, count:count * MemoryLayout<UInt32>.size)
//        return array
//    }

    func aesEncrypt(_ key: Array<UInt8>) throws -> Data{
        
        let toEncrypt: Array<UInt8> = self.bytes
        
        let iv: Array<UInt8> = []
        //let iv: Array<UInt8> = "00000000000000000000000000000000".dataValue()!.getByteArray()
        
        var encrypted: Array<UInt8>? = nil
        
        do {
            encrypted = try AES(key: key, iv: iv, blockMode: .ECB , padding: PKCS7()).encrypt(toEncrypt)
        } catch {
            print("errorooror: \(error.localizedDescription)")
        }
        
        let passEncrypted = Data(bytes: encrypted!)
        
        return passEncrypted
        
    }
    
}

```

**Comment by AccentSystems** [comment]
Oh man... so many thanks for your help... and so sorry to have bothered you when it's not a lib issue. Really appreciate it. BR.
