### ISSUE TITLE
Blowfish minimum key size is 5

### ISSUE THREAD

**Issue by brightsider** [krzyzanowskim/CryptoSwift#496]

**Comment by krzyzanowskim** [comment]
usually, you should elaborate a little more

**Comment by brightsider** [comment]
https://legrandin.github.io/pycryptodome/Doc/3.4.6/Crypto.Cipher.Blowfish-module.html

> key (byte string) - The secret key to use in the symmetric cipher. Its length can vary from 5 to 56 bytes.

In your code:
`precondition(key.count >= 8 && key.count <= 56)`
