### ISSUE TITLE
Viewcontroller deinit method is not called when using AES.init

### ISSUE THREAD

**Issue by lokeshkumarpedda** [krzyzanowskim/CryptoSwift#497]
I am using cryptoswift in my application,i am decrypting my encrypted data using cryptoswift library i am doing like this
```
DispatchQueue.global(qos: .userInteractive).async { [weak self] in
            guard let strongSelf = self else{return}
           let decryptBytes = try AES.init(key: hashByteArray, iv: iv, blockMode: .ECB, padding: PKCS7()).decrypt(encrytedData)

}
```
Until the decryption finished the view controller is not deallocating.

**Comment by krzyzanowskim** [comment]
I don't think any issue related to CryptoSwift here. Swift keep the strong reference to self because that's how Swift and closures works.
