### ISSUE TITLE
Cannot fetch this repo with SPM v4

### ISSUE THREAD

**Issue by CocoaPriest** [krzyzanowskim/CryptoSwift#498]
SPM freezes while doing `swift package update`:

     Fetching https://github.com/krzyzanowskim/CryptoSwift.git
     error: reachedTimeLimit

Apple Swift version 4.0 (swiftlang-900.0.65 clang-900.0.37)
Target: x86_64-apple-macosx10.9
Apple Swift Package Manager - Swift 4.0.0-dev (swiftpm-13126)

**Comment by krzyzanowskim** [comment]
no idea what's this, worth to report to https://bugs.swift.org there's not much I can do about that. You can try to delete all caches and install as a new package, it's something with resolving dependency tree. https://github.com/apple/swift-package-manager/blob/master/Sources/PackageGraph/DependencyResolver.swift#L1307

also https://twitter.com/krzyzanowskim/status/910923859070738433
