### ISSUE TITLE
Deprecated method integerWithBytes

### ISSUE THREAD

**Issue by zeusent** [krzyzanowskim/CryptoSwift#50]
Using the latest version (**0.0.9**) I get the following warning when compiling.

> 'integerWithBytes' was deprecated in * version 0.8

Is there a way to suppress this?

**Comment by krzyzanowskim** [comment]
this behave as intended. This method will be removed in next version and I marked is as deprecated to remember.

**Comment by krzyzanowskim** [comment]
you can use `inhibit_all_warnings!` in Podfile to suppress warnings (is CococaPods setup)

**Comment by joaodmj** [comment]
Hi Marcin,

I couldn't suppress this warning. Is there anything we can do to change the method? If I submit the App with this warning Apple will reject it. Thanks!

**Comment by krzyzanowskim** [comment]
@joaodmj Actually, I don't think that Apple will reject the app because of such warnings. Haven't heard about such case.

integerWithBytes is deprecated because it not fast enough, so it have to be re-writen.

**Comment by joaodmj** [comment]
Ok Marcin. Thanks for your reply.


2015-04-21 13:53 GMT+01:00 Marcin Krzyzanowski <notifications@github.com>:
