### ISSUE TITLE
SHA 384 returns different values

### ISSUE THREAD

**Issue by ciminuv** [krzyzanowskim/CryptoSwift#502]
Hi guys,

First, I would say that you guys did a great work on this library!

I am planing to use this library in my project. However, when I try following code:
```swift
"1".sha3(.sha384) // returns: f39de487a8aed2d19069ed7a7bcfc274e9f026bba97c8f059be6a2e5eed051d7ee437b93d80aa6163bf8039543b612dd
"1".sha384() // returns: 47f05d367b0c32e438fb63e6cf4a5f35c2aa2f90dc7543f8a41a0f95ce8a40a313ab5cf36134a2068c4c969cb50db776
```

It returns different values and both different with the one returns by `digest/sha3` in ruby:
```ruby
require 'digest/sha3'
Digest::SHA3.hexdigest("1", 384) // returns: 8147a2689f508cc03278c313290588b44607b5c0ccc07df5b0a80baf7d25812f0928c018c81381ef1dc76b25dbf6bafc
```

Maybe I missed something?

P/s: `8147a2689f508cc03278c313290588b44607b5c0ccc07df5b0a80baf7d25812f0928c018c81381ef1dc76b25dbf6bafc` is my expected value.

**Comment by krzyzanowskim** [comment]
SHA-384 is a variant of SHA-2, while SHA3(.sha384) is SHA3.
The value 8147a2689f508cc03278c313290588b44607b5c0cc... doesn't seem correct for a string "1". Maybe "1" is interpreted as a number... I don't know.
