### ISSUE TITLE
CryptoSwift: Many Swift compiler error

### ISSUE THREAD

**Issue by nem95** [krzyzanowskim/CryptoSwift#504]
Hi there!

I'm trying to build and run swift code but I got many error form CryptoSwift.
Last week I was able to build and run the swift code, but now its impossible! 

Xcode was updated to version 9 this weekend and now the build no more works

If someone can help me, please do it :) 

Thanks,

**Comment by krzyzanowskim** [comment]
Use the correct version for your project https://github.com/krzyzanowskim/CryptoSwift#swift-versions-support

**Comment by nem95** [comment]
@krzyzanowskim how please ? It's not my code, I'm just trying to test it, I never opened Xcode before :/, I added this: "  pod 'CryptoSwift', :git => "https://github.com/krzyzanowskim/CryptoSwift", :branch => "master" " on the Pods => Podfile but it doesn't change anything
