### ISSUE TITLE
Unreadable file when decrypting plist file

### ISSUE THREAD

**Issue by jjjjaren** [krzyzanowskim/CryptoSwift#505]
Hello!

I am trying to decrypt a plist file I have encrypted with OpenSSL but am having a problem.

If I encrypt using aes-128 and a 16 byte key (passwordpassword), I can decrypt the file just fine. However, if I switch to aes-256 and a 32 byte key (passwordpasswordpasswordpassword), the decrypted file becomes unreadable.

I have attached a sample project. Please see encrypt.sh, a run script that encrypts my test.plist as test.enc, and ViewController.swift where I am decrypting test.enc with CryptoSwift.

[Example.zip](https://github.com/krzyzanowskim/CryptoSwift/files/1342770/Example.zip)

**Comment by krzyzanowskim** [comment]
OpenSSL format explained: https://github.com/krzyzanowskim/CryptoSwift/issues/249#issuecomment-217199078
