### ISSUE TITLE
CryptoSwift does not compile in Xcode 8.3.3

### ISSUE THREAD

**Issue by satyres** [krzyzanowskim/CryptoSwift#507]
Hi , thank you for this awesome library !
please need your help when i try to compile my project with cryptoswift i got this error.

**Expected ')' in '_specialize' attribute** 

please help me

**Comment by meacreatio** [comment]
Same here. +1

**Comment by meacreatio** [comment]
Probably common knowledge, but if using Cocoapods you can go back.  Within your Podfile: `pod 'CryptoSwift', '0.6.9'`

**Comment by satyres** [comment]
Hi thank you for the answer 
is there any solution with the current version ?

**Comment by krzyzanowskim** [comment]
Please use the right version for the Swift version you're using https://github.com/krzyzanowskim/CryptoSwift#swift-versions-support
Xcode 8.3.3 it's Swift 3.1

> Swift 3.1, branch swift3 version <= 0.6.9

**Comment by satyres** [comment]
Hi , thank you for your comment.
can i use CocoaPods to choose the right version ,if so how to write the correct Podfile ?

**Comment by satyres** [comment]
this is how to it 
 pod 'CryptoSwift', '~> 0.6.9'
Thank you so krzyzanowskim  it is working.
