### ISSUE TITLE
compile issue

### ISSUE THREAD

**Issue by Nathan187** [krzyzanowskim/CryptoSwift#509]
trying to use RNCryptor

/Project Work/Source Code/Work Related/<withheld>/Carthage/Build/iOS/CryptoSwift.framework/CryptoSwift compiled with older version of Swift language (3.0) than previous files (4.0) file '/Project Work/Source Code/Work Related/<withheld>/Carthage/Build/iOS/CryptoSwift.framework/CryptoSwift' for architecture x86_64

**Comment by krzyzanowskim** [comment]
Delete DerivedData, delete Carthage cache and you're good. Most likely Carthage + Xcode issue.

**Comment by nboyd-sportdx** [comment]
that did not work

ld: /Project Work/Source Code/Work Related//Carthage/Build/iOS/CryptoSwift.framework/CryptoSwift compiled with older version of Swift language (3.0) than previous files (4.0) file '/Project Work/Source Code/Work Related//Carthage/Build/iOS/CryptoSwift.framework/CryptoSwift' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by krzyzanowskim** [comment]
It Carthage issue, try ask there.
