### ISSUE TITLE
Compiler errors with new Xcode release

### ISSUE THREAD

**Issue by e-jam** [krzyzanowskim/CryptoSwift#511]
I just upgraded Xcode to version 9.0 and it seems that CryptoSwift is not working with this version of code I get countless compiler error. 
![screen shot 2017-10-03 at 2 54 29 am](https://user-images.githubusercontent.com/25905259/31120047-f27a162c-a7e7-11e7-98dd-870e7600d4fc.png)

Any help in solving this issue would be much appreciated.

**Comment by krzyzanowskim** [comment]
You need to update CryptoSwift to match the Swift your using. Check README for details.

**Comment by e-jam** [comment]
Thank you for getting back so quickly. :)
