### ISSUE TITLE
Create 32 bytes base64 encoded key for AES256

### ISSUE THREAD

**Issue by trondkr** [krzyzanowskim/CryptoSwift#512]
Hi. First, thanks for a great library!

I understand this is not an issue but rather my lack of properly understanding how to do this. I want to create a base64 binary encoded key for AES256 based on a random length password, but I am unable to get it right. I need the base64 encoded key for uploading files to S3 with server side encryption using AWS SDK for iOS. I want to use CryptoSwift for handling the password (and later the client side encryption of files).

I tried this to create a PBKDF2 (which, to my understanding, would generate a 32 bytes key based on the provided password):

     func calculatePBKDF2(pass: String) ->  Array<UInt8> {
        
        let password: Array<UInt8> = Array(pass.utf8)
        let salt: Array<UInt8> = Array("test".utf8)
       
        do {
            let pb = try PKCS5.PBKDF2(password: password, salt: salt, iterations: 4096, variant: .sha256).calculate()
            return pb
        }catch{
            print("error")
        }
        return Array<UInt8>()
    }

However, this returns an Array<UInt8> and I was not sure how to convert that to a proper base64 encoded string for key I could use. I would really appreciate any comments, links or suggestions for how to do this. Thanks! Cheers, Trond

**Comment by krzyzanowskim** [comment]
see https://github.com/krzyzanowskim/CryptoSwift#data-types-conversion

array.toBase64()
