### ISSUE TITLE
When creating multiple targets only primary is working

### ISSUE THREAD

**Issue by Krisyean** [krzyzanowskim/CryptoSwift#513]
When creating multiple targets for ios and tvos by duplicating primary target, only primary target is working fine and secondary target project trows an error saying "no such module Cryptoswift" in classes that use  Cryptoswift.h

Using swift 3.2 compatible(swift32)
environment  XCode

**Comment by krzyzanowskim** [comment]
it may be due to http://promisekit.org/news/2016/08/Multiplatform-Single-Scheme-Xcode-Projects/

**Comment by iosdeveloper** [comment]
Ran into the same thing adding a WatchKit extension to an iOS app, both embedding the framework. I'm using manual installation. Any fix? Perhaps there could be multiple targets  CryptoSwift iOS, CryptoSwift watchOS and so on.

**Comment by iosdeveloper** [comment]
Maybe there is a different reason for it. I can't even embed it in a new project (WatchKit App) in the WatchKit extension only now.

**Comment by krzyzanowskim** [comment]
The advantages of single scheme configuration are bigger than the drawbacks to me.

You can set up a sample project and attach here so we can take a look at the Xcode project configuration.

**Comment by iosdeveloper** [comment]
It‘s literally just a new project from the WatchKit app template, dropping the CryptoSwift.xcodeproj, and adding CryptoSwift.framework to Embedded Binaries for the WatchKit extension target.

**Comment by krzyzanowskim** [comment]
You need to handle that manually by adding the targets per arch by yourself.

Or use Cocoapods if you can that will do it for you:

```
use_frameworks!

target "test" do
    pod "CryptoSwift"
end

target "test WatchKit Extension" do
    pod "CryptoSwift"
end
```

<img width="294" alt="screen shot 2017-10-09 at 00 53 37" src="https://user-images.githubusercontent.com/758033/31321838-4f63b32c-ac8c-11e7-8a8e-b455aaa007de.png">

**Comment by maxbaeumle** [comment]
If you can‘t use Pods (like me), you could use my fork: https://github.com/maxbaeumle/CryptoSwift/compare/master...multi-scheme

@krzyzanowskim Does this look right?

**Comment by krzyzanowskim** [comment]
Starting [0.8.0](https://github.com/krzyzanowskim/CryptoSwift/releases/tag/0.8.0) release you will find precompiled binaries for all platforms.
