### ISSUE TITLE
Export Compliance?

### ISSUE THREAD

**Issue by murphman300** [krzyzanowskim/CryptoSwift#516]
Hello,

I'm facing the export compliance question for an app i'm using which is using the JWT.io Swift library, which has CryptoSwift as a dependency. Can you confirm that CryptoSwift only uses CommonCrypto and Security encryption APIs?

If not, as in it uses custom encryption software, do you know is CryptoSwift can be considered safe to submit under export compliance laws without the massive amount of paperwork needed to become compliant?

Much appreciated!

**Comment by krzyzanowskim** [comment]
Closing as duplicate https://github.com/krzyzanowskim/CryptoSwift/issues/76
