### ISSUE TITLE
AES encryption and decrypt 

### ISSUE THREAD

**Issue by khancom1988** [krzyzanowskim/CryptoSwift#517]
Hello i was using the below initializer for decryption 

               try AES(key: secretKeyByteArray).decrypt([UInt8](data))

Now the initializer takes blockMode please tell me how to use this blockMode in my current initializer i am using it like 

                let iv: Array<UInt8> = []
                let decrypted = try AES(key: secretKeyByteArray, blockMode: .CBC(iv: iv)).decrypt([UInt8](data))

but result is always nil

**Comment by krzyzanowskim** [comment]
Isn't the error thrown, that the iv is not valid? you have empty IV

**Comment by khancom1988** [comment]
@krzyzanowskim 

I was't using any iv previously what should be the default iv in that case

**Comment by krzyzanowskim** [comment]
In that case, I assume all zeros that was the default previously (not the best default, hence removed)

```swift
Array<UInt8>(repeating: 0, count: AES.blockSize)
```
