### ISSUE TITLE
bytes function not found

### ISSUE THREAD

**Issue by LightD** [krzyzanowskim/CryptoSwift#52]
I have a swift project.. I imported CryptoSwift using Cocoapods.. when I try to use `bytes()` function, the compiler is only detecting the original `var bytes: UnsafePointer<Void> { get }` that exists in the class itself, and not detecting your NSData extension.. I had to copy the segment that had your extension implemented to the top of my `SecurityHelper` class, to get it to work.. and of course I did `import CryptoSwift` at the top of the class.. 
Not really sure what's up.. but.. this is the situation I'm having right now :(

**Comment by LightD** [comment]
Since I'm at it.. how do I deal with all of this if all I have is strings? encode string to NSData and then use the bytes conversion function?

**Comment by krzyzanowskim** [comment]
It has been changed in latest version (0.0.10) due to ambiguity issue. From now on please use `arrayOfBytes()`

**Comment by krzyzanowskim** [comment]
Regarding Strings, yes, String->NSData->[UInt8], or you can build String->[UInt8] conversion by your own of course.
