### ISSUE TITLE
Problem when compile with carthage

### ISSUE THREAD

**Issue by prsolucoes** [krzyzanowskim/CryptoSwift#520]
Hi,

I have the following error:

```
*** Skipped installing CryptoSwift.framework binary due to the error:
	"Incompatible Swift version - framework was built with 4.0 (swiftlang-900.0.65 clang-900.0.37) and the local version is 4.0 (swiftlang-900.0.65.2 clang-900.0.37)."
*** Checking out CryptoSwift at "0.8.0"
```

Can you help me with it?

Im using latest xcode9 version.

Thanks.

**Comment by krzyzanowskim** [comment]
dont know, the error message doesnt make sense. Try ask on Carthage repo

**Comment by krzyzanowskim** [comment]
The frameworks were built with the Xcode 9, I assume you're using 9.0.1 and swift version is different? that's PITA. I'm not sure how to handle this case with the carthage tbh.

**Comment by krzyzanowskim** [comment]
I replaced precompiled build attached to the release with the one built with Xcode 9.0.1. That should help.
