### ISSUE TITLE
XCode 9.0.1 (9A1004) '...' is inaccessible du to `private` protection level

### ISSUE THREAD

**Issue by kuzdu** [krzyzanowskim/CryptoSwift#521]
With the newest XCode Verison (XCode 9.0.1 (9A1004)) I got a lot of errors with protection level (see attachment).

For a quick and dirty fix I changed every variable to public. That works but... it isn't best practise.  :)

![aes swift 2017-10-23 15-56-26](https://user-images.githubusercontent.com/7271766/31893043-c5d85218-b80a-11e7-94d6-143314756f5a.png)

**Comment by krzyzanowskim** [comment]
wait, what? it's expected to be private. Any way to reproduce it? Can you attach the sample project here?

**Comment by daconghz** [comment]
I have the same problem. swift version is 3.0.2, xcode 8.0. Maybe can't use version 0.8.0. but when I change to version 0.6.9, some "expression too complex" appeared. what can I do now?

**Comment by krzyzanowskim** [comment]
Setting 
```
-solver-memory-threshold 300000
```
would probably help

**Comment by krzyzanowskim** [comment]
anyway, I can't re-relase the versions but I can accept PR on the branches, so if you have a backport PR I'm happy to look at it.

**Comment by kuzdu** [comment]
So I downgrade the pod to `0.7.1`. Now everything works. I'm sorry I can't share my project with you because of sensitiv data. I hope you can understand that.  

I tried to reproduce the issue with a new project but in the new project everything works perfectly. 

I was searching for different configs or linking in my projects but I didn't find anything.

**Comment by krzyzanowskim** [comment]
That's suggest that you're not using Swift 4 maybe, where the "private" meaning has changed. That's the only explanation I can find.

**Comment by krzyzanowskim** [comment]
see comment above https://github.com/krzyzanowskim/CryptoSwift/issues/521#issuecomment-338726898

**Comment by Fyb3roptik** [comment]
This is not fixed. I am using xcode 9.4.1 and Swift 4 and still receiving these errors

**Comment by krzyzanowskim** [comment]
It's a setup issue. The codebase is swift 4 for a long time already.
