### ISSUE TITLE
ChaCha20 implementation changed, old encrypted data lost forever?

### ISSUE THREAD

**Issue by DaveWoodCom** [krzyzanowskim/CryptoSwift#522]
I'm updating an old app that used CryptoSwift 0.1.1 to Swift 4 with the current version of CryptoSwift. It seems that CryptoSwift's ChaCha20 implementation changed at some point (see: #179 & f73a162 )

The old app has data encrypted using the old ChaCha20 cipher. Is there any way with the current CryptoSwift to decrypt that data?

Thanks

**Comment by krzyzanowskim** [comment]
yea, it changed. bummer. my fault but I had to fix it. All you can try it revert  (or make in on side) and see if that works. The current impl. has unrolled loops and it's not very obvious how to change it. I'd rather try to back to the version of ChaCha20.swift from that time and update it to the Swift 4
