### ISSUE TITLE
Private Access level Issue 

### ISSUE THREAD

**Issue by AfrozZaheer** [krzyzanowskim/CryptoSwift#523]
Hi I update Crypto to latest version and I'm getting these issues. 

I'm using

Xcode 9 
Swift 3.2 
Crypto 0.8.0

![screen shot 2017-10-25 at 12 15 33 pm](https://user-images.githubusercontent.com/25176835/31985482-b459ee28-b97e-11e7-8d41-b336d6a64359.png)

**Comment by krzyzanowskim** [comment]
latest version is for Swift4. Check the README for appropriate version for Swift 3.2

**Comment by danielfeelfine** [comment]
Only set Swift version to 4.0 for solve that.
