### ISSUE TITLE
SHA256 with key

### ISSUE THREAD

**Issue by huaqixue** [krzyzanowskim/CryptoSwift#525]
Thank you for you see my issue,  I have to use CryptoSwift in my project.
And I don't found the way to use CryptoSwift how to make a SHA256 with a key. 
Such as, `hash_hmac( 'sha256' , string $data , string $key) `in PHP. Please help me.

**Comment by krzyzanowskim** [comment]
See readme for HMAC https://github.com/krzyzanowskim/CryptoSwift#message-authenticators-1
