### ISSUE TITLE
problems with CryptoSwift migration to Xcode 9

### ISSUE THREAD

**Issue by Marcelrama** [krzyzanowskim/CryptoSwift#526]
hello, I have problems with CryptoSwift before making the migration to Xcode 9 I can not Build and run to verify that all the libraries are working in xcode 9 Swift 3.2, so then be able to perform the migration with the assistant.

in the image I can leave the errors I get when build and run xcode.
![captura de pantalla 2017-11-02 a la s 09 14 05](https://user-images.githubusercontent.com/22013703/32328266-cc311044-bfaf-11e7-9f36-dcfdc03bcc09.png)

```
target 'Loupper' do
    
use_frameworks!

pod 'Alamofire’, '~> 4.0'
pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
#pod 'AlamofireImage'
pod 'Firebase'
pod 'JSQMessagesViewController'
#pod 'IQAudioRecorderController'
#pod 'JSQSystemSoundPlayer'
#pod 'IDMPhotoBrowserConstants'
pod 'MBProgressHUD'
pod 'GoogleMaps'
#pod 'HanekeSwift'
pod 'HanekeSwift', :git => 'https://github.com/Haneke/HanekeSwift.git', :branch => 'feature/swift-3'
pod 'ActionSheetPicker-3.0'
pod 'CryptoSwift'

   target 'LoupperTests' do
     inherit! :search_paths
     # Pods for testing
   end

   target 'LoupperUITests' do
      inherit! :search_paths
      # Pods for testing

   end

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.2'
        end
    end
end

```

**Comment by FrankieLWChen** [comment]
We have the same issue for version 0.8.0, but 0.7.2 is prefer work on Xcode 9

**Comment by Marcelrama** [comment]
I finished solving it by installing with cartage

**Comment by krzyzanowskim** [comment]
For CocoaPods, don't do manual migration to new Swift, delete Pods and reinstall choosing right version https://github.com/krzyzanowskim/CryptoSwift#swift-versions-support
