### ISSUE TITLE
Cant Compile Private error

### ISSUE THREAD

**Issue by frozts91** [krzyzanowskim/CryptoSwift#527]
Hi, after update to swift 4 and xcode 9.1, it give error while compile

private lazy var expandedKey: Array<Array<UInt32>> = self.expandKey(self.key, variant: self.variant) <<  'expandKeyInv' is inaccessible due to 'private' protection level

**Comment by krzyzanowskim** [comment]
If you're seeing this error means the code is built with Swift 3.2. Please verify your setup.

**Comment by migue19** [comment]
change of 3.2 to 4 and return 

open override func openLeft() {.  (Declarations from extensions cannot be overridden yet)

**Comment by krzyzanowskim** [comment]
wait, there is something to change on 3.2 branch? mind to make PR?
