### ISSUE TITLE
Version 0.8 errors on Xcode 9.1

### ISSUE THREAD

**Issue by SS-HU** [krzyzanowskim/CryptoSwift#528]
Hi!

When podding CryptoSwift for Xcode 9.1 projects, it throws a bunch of errors due to being set to swift 3.2, but compiles when set to swift 4.0 for swift language.

**Comment by krzyzanowskim** [comment]
Blame CocoaPods. I don't know why it's set to Swift 3.2. Change it to Swift 4.0 and report issue to CocoaPods maybe.
https://github.com/krzyzanowskim/CryptoSwift/blob/0.8.0/CryptoSwift.podspec#L17
