### ISSUE TITLE
AES (dataPaddingRequired) Need help

### ISSUE THREAD

**Issue by SouSame** [krzyzanowskim/CryptoSwift#529]
#### this's code i used. Thank you.
       let key="12345678900987654321564738290123".bytes; //32
        let iv="passwordpasswordwordpasswordpass".bytes; //32
        let message="Hello text for encrypt HelloHello text for encrypt";
        print(message.count) //50
        let data = Padding.pkcs7.add(to: message.bytes, blockSize: AES.blockSize)
        do {
            let aes = try AES(key: key, blockMode: .CBC(iv: iv), padding: .pkcs7)
            let ciphertext = try aes.encrypt(data)
            print(ciphertext.toHexString())
        } catch {
            print(error)//dataPaddingRequired   
        }

**Comment by smkdoss73** [comment]
try this 

         ```let  aes = try AES(key: key, blockMode: CBC(iv: iv), padding: .pkcs7).encrypt(data) ```
