### ISSUE TITLE
AES - Get the encryptext in String

### ISSUE THREAD

**Issue by Persilos** [krzyzanowskim/CryptoSwift#53]
Hi ! 
You will find here my method to crypt a password... Before the update of CryptoSwift and Swift in 1.2, my method worked perfectly, but now i can't find the equivalent. In comment, you have my first method which worked before updates. 
Below this is my new code. The problem with this is "pwdEncrypted" equals nil...

Regards and thanks for your help

```swift   
 class func encryptAES(password : String) -> String{
        
        /*let keyData = (ApplicationProperties.CRYPT_KEY as NSString).dataUsingEncoding(NSUTF8StringEncoding)
        let ivData : [UInt8]  = Cipher.randomIV(keyData)
        let aes = Cipher.AES(key: keyData!, iv: ivData, blockMode: .ECB)
        let nsDataPassword : NSData = (password as NSString).dataUsingEncoding(NSUTF8StringEncoding)!
        return aes.encrypt(nsDataPassword)!.base64EncodedStringWithOptions(nil)*/
        
        var byteArrayKey = [Bytef]()
        for char in ApplicationProperties.CRYPT_KEY.utf8{
            byteArrayKey += [char]
        }
        let iv = Cipher.randomIV(AES.blockSize)
        
        var byteArrayPwd = [Bytef]()
        for char in password.utf8{
            byteArrayPwd += [char]
        }
        let encrypted = Cipher.AES(key: byteArrayKey, iv: iv, blockMode: .CBC).encrypt(byteArrayPwd)
        let pwdEncrypted =  NSString(bytes: encrypted!, length: encrypted!.count, encoding: NSUTF8StringEncoding)
        return pwdEncrypted as! String
    }
```

**Comment by krzyzanowskim** [comment]
Cipher.AES().encrypt() -> **[UInt8]**? You can't pass [UInt8] as NSData to NSString. I know that compiler would allow that because of ambiguity issue (this is a bug I believe rdar://20517897) between array and nsdata, but this is not right type here.

`let pwdEncrypted:[UInt8]`

so first you have to convert it to NSData with `NSData.withBytes(pwdEncrypted)`
