### ISSUE TITLE
Facing Issue in AES.swift

### ISSUE THREAD

**Issue by rathodmayur93** [krzyzanowskim/CryptoSwift#533]
<img width="955" alt="screen shot 2017-11-14 at 2 54 30 pm" src="https://user-images.githubusercontent.com/15011486/32772399-bf2b4a90-c94b-11e7-9167-2fd7cad6a261.png">

Facing error while compiling AES.swift like inaccessible due to 'private' protection level.
Please help

**Comment by krzyzanowskim** [comment]
Closing as duplicate of #521 #523 #527 #531
