### ISSUE TITLE
XCode 9.1 compiles with 37 errors

### ISSUE THREAD

**Issue by Pacana78** [krzyzanowskim/CryptoSwift#534]
Hi,

I added CryptoSwift with the podfile, and when I try to compile the project I got a bunch of errors, just to mention some:
'expandKey' is inaccessible due to 'private' protection level 
 'variantNr' is inaccessible due to 'private' protection level
'calculateSBox' is inaccessible due to 'private' protection level
all in AES.swift

Thanks for your help

**Comment by krzyzanowskim** [comment]
U have to use Swift 4 compiler.

Closing as duplicate of #521 #523 #527 #531 #533

**Comment by Pacana78** [comment]
Thanks

**Comment by cilvet** [comment]
I changed to Swift 4.0 compiler and I'm still getting these same results. Any Idea what I might be doing wrong?

**Comment by krzyzanowskim** [comment]
The CryptoSwift target must use Swift 3.2 mode.

**Comment by zhouhao27** [comment]
@krzyzanowskim I do the reverse. The main project no change still swift 3.2. But cryptorSwift target 4.0.
