### ISSUE TITLE
AES ECB pkcs7 question

### ISSUE THREAD

**Issue by ETmanwenhan** [krzyzanowskim/CryptoSwift#535]
AES ECB pkcs7 

Why am I wrong to encrypt this? The error is as follows:

> Cannot convert value of type '[UInt8]' to expected argument type 'String'

```swift
 do {
            
            let iv: [UInt8]  = Array("".utf8) as [UInt8]
            let aes = try AES(key: AES_KEY, iv: iv) // aes128
            let ciphertext = try aes.encrypt(Array("666666".utf8))
             print(ciphertext.toHexString())
        } catch {
            print(error)
        }
```

**Comment by krzyzanowskim** [comment]
What line? isn't it about AES constructor and you're using String as one of the parameters ?

**Comment by ETmanwenhan** [comment]
![5c302dc7-9eea-4135-a7b0-227a92decf3c](https://user-images.githubusercontent.com/5837888/32887996-ce47a094-cb00-11e7-8c68-af912d82fc4f.png)
@krzyzanowskim  help me ,thanks!

**Comment by krzyzanowskim** [comment]
so, you're AES_KEY is String probably, and yout iv is not, and there is no initializer that accept that set of parameters. Look at the types.

**Comment by ETmanwenhan** [comment]
@krzyzanowskim 
My question is: how does the decrypted transform into a String

> result = String(data: Data(decrypted), encoding: .utf8) ?? ""
I transform is blank.Why? Can you help me ?

```swift
/// AES解密 转换格式：AES128 .ECB pkcs7
    func aes_Decrypt() -> String {
        
        var result = ""
        do {
            
            let key: [UInt8] = Array(AES_KEY.utf8) as [UInt8]
            
            let aes = try! AES(key: key, blockMode: .ECB, padding: .pkcs7) //AES128 .ECB pkcs7
            let decrypted = try aes.decrypt(Array(self.utf8))
            
            result = String(data: Data(decrypted), encoding: .utf8) ?? ""
            Loger.log(msg: "AES 解密后: \(result)")
            
        } catch {
            print(error)
        }
        
        return result
    }
```

**Comment by ETmanwenhan** [comment]
@krzyzanowskim 
With your help, I have successfully implemented the encryption and decryption of AES (AES128. ECB pkcs7). Thank you!
Here's my solution:

```swift
//
//  AESutil.swift
//  yiyue
//
//  Created by ChenWenHan on 2017/11/17.
//  Copyright © 2017年 YiBan. All rights reserved.
//

import Foundation
import CryptoSwift

extension String {
    
    /// AES加密 转换格式：AES128 .ECB pkcs7
    func aes_Encrypt() -> String {
        
        var result = ""
        do {
            
            let key: [UInt8] = Array(AES_KEY.utf8) as [UInt8]
            
            let aes = try! AES(key: key, blockMode: .ECB, padding: .pkcs7) //AES128 .ECB pkcs7
            let encrypted = try aes.encrypt(Array(self.utf8))
            
            result = encrypted.toHexString()
            Loger.log(msg: "AES 加密后: \(result)")
            
            
            /*
            //还原
            let decrypted = try aes.decrypt(encrypted)
            let a = String(data: Data(decrypted), encoding: .utf8) ?? ""
            Loger.log(msg: "AES 加密还原: \(a)")
             */
            
            
        } catch {
            print(error)
        }
        
        return result
    }
    
    /// AES解密 转换格式：AES128 .ECB pkcs7
    func aes_Decrypt() -> String {
        
        var result = ""
        do {
            
            let hexString = self
            let key: [UInt8] = Array(AES_KEY.utf8) as [UInt8]
            
            let aes = try! AES(key: key, blockMode: .ECB, padding: .pkcs7) //AES128 .ECB pkcs7
            let decrypted = try aes.decrypt(Array(hex: hexString))
            
            result = String(data: Data(decrypted), encoding: .utf8) ?? ""
            Loger.log(msg: "AES 解密后: \(result)")
            
        } catch {
            print(error)
        }
        
        return result
    }
    
}

```

**Comment by KDLNiranjan** [comment]
let base = URL(string:"http://*******?" + defaults.string(forKey: "token")!)

        let request = NSMutableURLRequest(url:base!)

        request.httpMethod = "POST"

        request.addValue("*****", forHTTPHeaderField:"api-key")

        request.addValue("application/json", forHTTPHeaderField:"Content-Type")

        let parameter = ["user_id": defaults.string(forKey: "user_id")!]

        guard let httpbody = try? JSONSerialization.data(withJSONObject: parameter, options: []) else { return }

        request.httpBody = httpbody

        let task = URLSession.shared.dataTask(with: request as URLRequest) { (data, response, error) in

            let json = (try? JSONSerialization.jsonObject(with: data!, options: JSONSerialization.ReadingOptions.mutableContainers)) as? NSDictionary

          print(json)

            let jsonValue = json!["response_str"] as! String

            print(jsonValue)

            let dataToDecrypt : Data = jsonValue.data(using: String.Encoding.utf8) as! Data

          print(dataToDecrypt)

            let password =  "*****"

Here they used a password for encryption , i need to decrypt the data with password. Above mentioned suits for me perfectly except the password. Can you please tell me how to decrypt the value using password? 

type : AES(key: key, blockMode: .ECB, padding: .pkcs7) . Where I should pass the password, where i should give the key length(128) ??

**Comment by krzyzanowskim** [comment]
> how to decrypt the value using password?
I don't know the answer to that question. It depends on how the password was transformed during encryption.
