### ISSUE TITLE
update to swift4.0 error

### ISSUE THREAD

**Issue by linkjd** [krzyzanowskim/CryptoSwift#537]
I`m already update to swift4.0, then get some error, like “'expandKey' is inaccessible due to 'private' protection level”, "'calculateSBox' is inaccessible due to 'private' protection level", "Cannot call value of non-function type 'Int32'"

**Comment by krzyzanowskim** [comment]
It looks like you're not using Swift4 compiler to build CryptoSwift

Closing as duplicate of #521 #523 #527 #531 #533

**Comment by linkjd** [comment]
OK, Thank you very much
