### ISSUE TITLE
AES encrytpion issue after updating to >= 0.7.0

### ISSUE THREAD

**Issue by TomaszWlodarczyk** [krzyzanowskim/CryptoSwift#538]
Hello

Why version >= 0.7.0 encrypts strings in a different way than 0.6.9?
It turned out that after updating the library my app cannot decrypt strings which were decrypted with 0.6.9 version.

**Comment by krzyzanowskim** [comment]
No, unless you encode it differently maybe? Hard to say

**Comment by TomaszWlodarczyk** [comment]
Nope. I used the same AES key and iv. 
 0.6.9 on ios10 gives me -   **ZUI7BJCSi7EQnat2jybyMg==**
 0.7.0 on ios11 gives me -    **ZH9iHDKAe6E3deJtpbzQvg== **

**Comment by krzyzanowskim** [comment]
No, but its tested against the same expected values, and I don't recall to change test vectors.

**Comment by TomaszWlodarczyk** [comment]
Please find more details about that issue.

I prepared a test 

```
let key = "074d4c5cc5a98a6b9f80161471a3c21f25504dadd197c70c9a138038df9fa4f8" //: Array<UInt8> = [0x2b, 0x7e, 0x15, 0x16, 0x28, 0xae, 0xd2, 0xa6, 0xab, 0xf7, 0x15, 0x88, 0x09, 0xcf, 0x4f, 0x3c]
let iv = "b2a1a4aa025f23ab"// Array<UInt8> = [0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f]
let input: Array<UInt8> = [0x6b, 0xc1, 0xbe, 0xe2, 0x2e, 0x40, 0x9f, 0x96, 0xe9, 0x3d, 0x7e, 0x11, 0x73, 0x93, 0x17, 0x2a]
        
        do {
        let aes = try AES(key: key, iv: iv)
        let encrypted1 = try aes.encrypt(input)
        let encrypted2 = try Data(bytes: input).encrypt(cipher: aes)
     }
```

On iOS 10 the values **encrypted1** and **encrypted2** are equal and its value is

```
    - 0 : 175
    - 1 : 38
    - 2 : 23
    - 3 : 82
    - 4 : 209
    - 5 : 219
    - 6 : 79
    - 7 : 31
    - 8 : 59
    - 9 : 108
    - 10 : 14
    - 11 : 210
    - 12 : 178
    - 13 : 255
    - 14 : 150
    - 15 : 242
    - 16 : 223
    - 17 : 241
    - 18 : 27
    - 19 : 125
    - 20 : 122
    - 21 : 230
    - 22 : 76
    - 23 : 136
    - 24 : 209
    - 25 : 42
    - 26 : 75
    - 27 : 207
    - 28 : 89
    - 29 : 42
    - 30 : 26
    - 31 : 136
```

On iOS11 both values are the same but are different than those ones computed on iOS10

```
  - 0 : 143
  - 1 : 187
  - 2 : 167
  - 3 : 176
  - 4 : 104
  - 5 : 51
  - 6 : 119
  - 7 : 225
  - 8 : 141
  - 9 : 215
  - 10 : 235
  - 11 : 53
  - 12 : 37
  - 13 : 217
  - 14 : 75
  - 15 : 220
  - 16 : 4
  - 17 : 115
  - 18 : 121
  - 19 : 171
  - 20 : 145
  - 21 : 27
  - 22 : 194
  - 23 : 1
  - 24 : 127
  - 25 : 236
  - 26 : 94
  - 27 : 54
  - 28 : 125
  - 29 : 64
  - 30 : 249
  - 31 : 243
```

What is interesting when I was trying to use the key and iv as an Array<UInt8> (the exact values are in the code above), computed values are **the same for both** iOS versions.

**Comment by TomaszWlodarczyk** [comment]
It turned out that may key is twice too long. It worked on iOS10 somehow but on iOS11 it did not. After cutting the key in a half and took the first part it started working again.
