### ISSUE TITLE
CMAC Support

### ISSUE THREAD

**Issue by beribas** [krzyzanowskim/CryptoSwift#539]
Hi Martin,

thank you for the library, we are successfully using it in our project. There is only one thing where we have to switch to openssl: CMAC generation.

Are there any plans to support it in the future?

**Comment by TictoDev** [comment]
I am taking a stab at this.
https://tools.ietf.org/html/rfc4493

**Comment by krzyzanowskim** [comment]
The future will be available with the next release.

**Comment by beribas** [comment]
That's great, thank you!
