### ISSUE TITLE
HMAC usage

### ISSUE THREAD

**Issue by hamchapman** [krzyzanowskim/CryptoSwift#54]
In Ruby if you load up IRB ($ `irb`) and then `require openssl` then you can run the following code:

```ruby
OpenSSL::HMAC.hexdigest('sha256', "mySecret", "toBeSigned")
```

and get the following output: `"e3fbbc3295f9228593f251b24b910179417846f495b67e00d239a956a9338de8"`

In CryptoSwift if I run:

```swift
var key = "mySecret"
var msg = "toBeSigned"

var keyBuff = [UInt8]()
keyBuff += key.utf8

var msgBuff = [UInt8]()
msgBuff += msg.utf8

let hmac = Authenticator.HMAC(key: keyBuff, variant: .sha256).authenticate(msgBuff)
println(hmac)

println(NSString(bytes: hmac!, length: hmac!.count, encoding: NSUTF8StringEncoding))
```

Then the output of `println(hmac)` is:

 `Optional([227, 251, 188, 50, 149, 249, 34, 133, 147, 242, 81, 178, 75, 145, 1, 121, 65, 120, 70, 244, 149, 182, 126, 0, 210, 57, 169, 86, 169, 51, 141, 232])`

and `println(NSString(bytes: hmac!, length: hmac!.count, encoding: NSUTF8StringEncoding))` returns nil.

I can't seem to get from starting with two strings (a secret and a message), to a resulting string.

Any ideas what I'm getting wrong? 

Thanks

**Comment by krzyzanowskim** [comment]
that's fine, everything is in order:
0xE3 = 227
0xFB = 251
etc...

**Comment by hamchapman** [comment]
Yeah, the digest itself seems to be correct, but how do I convert `hmac` into a `String`?

**Comment by krzyzanowskim** [comment]
I see, to make hexadecimal representation of numbers, printed as a string you can write a function for that, or you can try `hexString` property defined as a extension to the NSData.
In your case you need to convert array of bytes to NSData first:

`NSData.withBytes(hmac).hexString`

**Comment by hamchapman** [comment]
That's awesome! Thank you :+1:
