### ISSUE TITLE
Decrypt error "dataPaddingRequired"

### ISSUE THREAD

**Issue by sreenath2406** [krzyzanowskim/CryptoSwift#540]
When I try to decrypt, I got this error "dataPaddingRequired"
Here is my code,
do {
            let aesDecryption = try AES.init(key: keyBytes, iv: ivBytes, blockMode: .ECB, padding: .noPadding).decrypt(Array(data.utf8))
        } catch {
            print("Error.... \(error)")
        }
Please let me know what is wrong with my code

**Comment by krzyzanowskim** [comment]
You need to use padding, but you use `.noPadding`
