### ISSUE TITLE
When I run "git submodule add https://github.com/krzyzanowskim/CryptoSwift.git" to install CryptoSwift , get this error message

### ISSUE THREAD

**Issue by dongpinyun** [krzyzanowskim/CryptoSwift#541]
![image](https://user-images.githubusercontent.com/26698885/33307711-0f499c50-d407-11e7-93fc-1dadf48362d4.png)

**Comment by krzyzanowskim** [comment]
clone the repo again. Either you had local changes or something and git need to force fetch the repo.

**Comment by dongpinyun** [comment]
Thanks
