### ISSUE TITLE
Import problem

### ISSUE THREAD

**Issue by Rufik134** [krzyzanowskim/CryptoSwift#542]
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!
target 'project' do
  
  
  pod 'Alamofire', '~> 4.5'
  pod 'Kingfisher', '~> 3.0’
  pod 'SwiftyJSON'
  pod 'CryptoSwift'

end

As you see, I've installed library via CocoaPods. 
But can't import in my project

**Comment by krzyzanowskim** [comment]
Hard to say, try to ask the CocoaPods team what's going on. It may be a project setup issue. Feel free to re-open if it turn out to be CryptoSwift issue.
