### ISSUE TITLE
PKCS7 S/Mime support

### ISSUE THREAD

**Issue by zkrige** [krzyzanowskim/CryptoSwift#543]
What are your requirements around this package? 

I built a S/MIME PKCS7 container decrypter/encrypter, but it relies on your openSSL module

Would this be something you would want to add to this library?

If you're happy to add something with an OpenSSL dependency, then I will add it and PR

**Comment by krzyzanowskim** [comment]
not really, unless you can drop the OpenSSL dependency. feel free to re-open the issue.
