### ISSUE TITLE
ChaCha20 Fatal error: Not enough bits to represent a signed value

### ISSUE THREAD

**Issue by Paraphraser** [krzyzanowskim/CryptoSwift#544]
File:  ChaCha20.swift
Function: func process(bytes: Array<UInt8>, counter: inout Array<UInt8>, key: Array<UInt8>) -> Array<UInt8>

Within the body of this function, lines 225 & 226 are:

                u += UInt32(counter[i])
                counter[i] = UInt8(u)

u is a UInt32 and is initialised to 1.

Counter is an array of UInt8. Assume counter[i] == 255.

After line 225, u will be equal to 256. This will cause line 226 to fail with the message "Fatal error: Not enough bits to represent a signed value".

The intention seems to be to constrain values of u to the lower 8 bits so this should probably be made explicit in line 226 with:

                counter[i] = UInt8(u & 0xFF)

**Comment by krzyzanowskim** [comment]
Do you have a failing test case for that by any chance?

**Comment by Paraphraser** [comment]
I have attached a playground (ChaCha20.playground.zip) and a file that produces the problem (Example.pdf.zip).

Obviously, the playground should be unzipped but the zipped PDF should be placed on your desktop before running the playground.

There isn't anything special about the attached zipped PDF. I've hit the problem on many different files and file types.
[ChaCha20.playground.zip](https://github.com/krzyzanowskim/CryptoSwift/files/1529263/ChaCha20.playground.zip)
[Example.pdf.zip](https://github.com/krzyzanowskim/CryptoSwift/files/1529264/Example.pdf.zip)

**Comment by krzyzanowskim** [comment]
thanks, I asked it to create test along the fix

**Comment by krzyzanowskim** [comment]
Fixed in 0.8.1
