### ISSUE TITLE
Deprecation issue

### ISSUE THREAD

**Issue by hamada147** [krzyzanowskim/CryptoSwift#545]
Dear @krzyzanowskim,
Kindly notice the following. In the "CSArrayType+Extensions.swift" inside the public extension CSArrayType where Iterator.Element == UInt8 in method toHexString

You are using characters which has been deprecated as of Swift 4
You should replace the following line
```swift
if s.characters.count == 1
```
with
```swift
if s.count == 1
```

**Comment by krzyzanowskim** [comment]
There is no`CSArrayType`, you should probably update to the current version.

**Comment by hamada147** [comment]
@krzyzanowskim You were correct I had an outdated version.
