### ISSUE TITLE
HexString to Data

### ISSUE THREAD

**Issue by trimaximus** [krzyzanowskim/CryptoSwift#546]
Step 1. Encrypt string with AES;
Step 2. Convert encrypted data to hex string;
Step 3. Send hex string to server and get another hex string from server; 
Step 4. Decode hex string to data and decrypt data with AES.

I used function `toHexString()` and wrote my own function to decode hex string. Is that possible to add this function in your next version?

**Comment by krzyzanowskim** [comment]
is rhere something wrong with Data(hex:) ?

**Comment by trimaximus** [comment]
I can not find `Data(hex:)`, here follows my code: 
`extension Data {

    init?(hexString: String) {
        let length = hexString.count / 2
        var data = Data(capacity: length)
        for i in 0 ..< length {
            let j = hexString.index(hexString.startIndex, offsetBy: i * 2)
            let k = hexString.index(j, offsetBy: 2)
            let bytes = hexString[j..<k]
            if var byte = UInt8(bytes, radix: 16) {
                data.append(&byte, count: 1)
            } else {
                return nil
            }
        }
        self = data
    }
} `

**Comment by krzyzanowskim** [comment]
I'm sorry, actually it's on Array
```swift
Array<UInt8>(hex: "hex")
```

for Data it would be
```swift
extension Data {
    public init(hex: String) {
        self.init(bytes: Array<UInt8>(hex: hex))
    }
}
```
