### ISSUE TITLE
AES CBC Encryption & Decryption Code

### ISSUE THREAD

**Issue by hamada147** [krzyzanowskim/CryptoSwift#547]
Dear @krzyzanowskim 
I'm trying to implement both AES ECB and AES CBC as a string extension and here is my code so far.
```swift
import CryptoSwift

extension String {
 
    // encrypt the string
    func aes_Encrypt(AES_KEY: String) -> String {
        var result = ""
        do {
            let key: [UInt8] = Array(AES_KEY.utf8) as [UInt8]
            let aes = try! AES(key: key, blockMode: .ECB, padding: .pkcs7) // AES128 .ECB pkcs7
            let encrypted = try aes.encrypt(Array(self.utf8))
            result = encrypted.toHexString()
            print("AES Encryption Result: \(result)")
        } catch {
            print("Error: \(error)")
        }
        return result
    }
    
    // decrypt the string
    func aes_Decrypt(AES_KEY: String) -> String {
        var result = ""
        do {
            let encrypted = self
            let key: [UInt8] = Array(AES_KEY.utf8) as [UInt8]
            let aes = try! AES(key: key, blockMode: .ECB, padding: .pkcs7) // AES128 .ECB pkcs7
            let decrypted = try aes.decrypt(Array(hex: encrypted))
            result = String(data: Data(decrypted), encoding: .utf8) ?? ""
            print("AES Decryption Result: \(result)")
        } catch {
            print("Error: \(error)")
        }
        return result
    }
    
    // encrypt the string in AES CBC
    func aesCBC_Encrypt(AES_KEY: String) -> String {
        var result = ""
        do {
            let key: [UInt8] = Array(AES_KEY.utf8) as [UInt8]
            let iv = AES.randomIV(AES.blockSize)
            let aes = try! AES(key: key, blockMode: .CBC(iv: iv), padding: .pkcs5)
            let encrypted = try aes.encrypt(Array(self.utf8))
            result = encrypted.toHexString()
            print("AES Encryption Result: \(result)")
        } catch {
            print("Error: \(error)")
        }
        return result
    }
    
    // decrypt the string in AES CBC
    func aesCBC_Decrypt(AES_KEY: String) -> String {
        var result = ""
        do {
            let encrypted = self
            let key: [UInt8] = Array(AES_KEY.utf8) as [UInt8]
            let iv = AES.randomIV(AES.blockSize)
            let aes = try! AES(key: key, blockMode: .CBC(iv: iv), padding: .pkcs5)
            let decrypted = try aes.decrypt(Array(hex: encrypted))
            result = String(data: Data(decrypted), encoding: .utf8) ?? ""
            print("AES Decryption Result: \(result)")
        } catch {
            print("Error: \(error)")
        }
        return result
    }
   
}

```
AES ECB is working fine with no issues
But AES CBC is not doing so well. It dose the encryption with no issues but I'm unable to decrypt the same generated string. 
I know that I'm suppose to know the iv (randomly generated) during the encryption but I'm not suppose to know the iv during the decryption (do please correct me if I'm wrong). I always get an empty string and the Array of UInt8 that is the result of decryption is always wrong. What am I doing wrong here?

**Comment by rondinellimorais** [comment]
You can try use ```iv = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]```

I did have same problema, take a look: https://github.com/krzyzanowskim/CryptoSwift/issues/562

**Comment by hamada147** [comment]
I will test that

**Comment by krzyzanowskim** [comment]
the `[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]` itself is not the best advice, but yes, to decrypt you need the IV used while encrypted. Since you generate random on encrypt and another random on decrypt... it doesn't match.

**Comment by hamada147** [comment]
Unfortunately that didn't work.
@krzyzanowskim I thought so. Is there any plans for having random IV each time but during the decryption we don't need to provide the IV.

**Comment by ml1375** [comment]
how to fix it??
please Help me 
@krzyzanowskim

**Comment by ml1375** [comment]
in this line i have error
    let decrypted = try aes.decrypt(Array(hex: encrypted))

**Comment by krzyzanowskim** [comment]
@ml1375 can't help you. Check the README and update your code.

**Comment by xuaninbox** [comment]
This is what I use, hope it can help someone.

`class func encryptPayload(_ payload: String, withKey key: String) -> String? {
        do {
            let key = key.md5().bytes
            let bytes = payload.bytes
            let iv = AES.randomIV(AES.blockSize)
            let aes = try AES(key: key, blockMode: BlockMode.CBC(iv: iv))
            let encrypted = try aes.encrypt(bytes)
            let encryptedK = Data(bytes: encrypted)
            var encryptedKIV = Data(bytes: iv)
            encryptedKIV.append(encryptedK)
            return encryptedKIV.base64EncodedString()
        } catch {
            return nil
        }
    }

    class func decryptPayload(_ payload: String, withKey key: String) -> String? {
        do {
            guard let data = Data(base64Encoded: payload) else {
                return nil
            }
            let count = [UInt8](data).count
            guard count > AES.blockSize else {
                return nil
            }
            let key = key.md5().bytes
            let iv = Array([UInt8](data)[0 ..< AES.blockSize])
            let bytes = Array([UInt8](data)[AES.blockSize ..< count])
            let aes = try AES(key: key, blockMode: BlockMode.CBC(iv: iv))
            let decrypted = try aes.decrypt(bytes)
            return String(bytes: decrypted, encoding: .utf8)
        } catch {
            return nil
        }
    }`

**Comment by iosPayal** [comment]
Hi,

I'm unable to convert [UInt8] to string afetr decryption, please do help working on same issue for a long time still dont have any solution for it.
let decrypted = try aes.decrypt(bytes)
 String(bytes: decrypted, encoding: .utf8)
I'm getting value for '**decrypted**' in the form of [UInt8] but second line doesnt work for me
I'm using Xcode 9.4
encrypted string is base64encoded


this is the code i'm using:
 class func decryptPayload(_ payload: String, withKey key: String) -> String? {
        do {
            guard let data = Data(base64Encoded: payload, options: Data.Base64DecodingOptions.ignoreUnknownCharacters) else {
                return nil
            }
            let count = [UInt8](data).count
            guard count > AES.blockSize else {
                return nil
            }
            let key = key.md5().bytes
            let iv = Array([UInt8](data)[0 ..< AES.blockSize])
            let bytes = Array([UInt8](data)[AES.blockSize ..< count])
            let aes = try AES(key: key, blockMode: CBC(iv: iv))
            let decrypted = try aes.decrypt(bytes)
            print(decrypted)
            return String(bytes: decrypted, encoding: .utf8)
        } catch {
            return nil
        }
    }

the key used for encryption is:
 key = "EE99C7A159003D36"
  iv = "693AE52C9E6DF3E0"

But unable to decrypt the encrypted string:
the key used for decryption is:
key = "EE99C7A159003D36"

and iv generated like this:
iv - : Array([UInt8](data)[0 ..< AES.blockSize])

**Comment by iosPayal** [comment]
My mistake , I resolved the issue
I removed the iv from encrypted string and send the remaining string for decryption

**Comment by Pratik-Sodha** [comment]
Below Code for me. 

Using base64 string instead of hex string.
And change padding mode to .pkcs7

`extension String {
    
    // encrypt the string
    func aes_Encrypt(AES_KEY: String) -> String {
        var result = ""
        do {
            let key: [UInt8] = Array(AES_KEY.utf8) as [UInt8]
            let aes = try! AES(key: key, blockMode: ECB() as BlockMode, padding: .pkcs7)
            let encrypted = try aes.encrypt(Array(self.utf8))
            result = encrypted.toBase64()!
            print("AES Encryption Result: \(result)")
        } catch {
            print("Error: \(error)")
        }
        return result
    }
    
    // decrypt the string
    func aes_Decrypt(AES_KEY: String) -> String {
        var result = ""
        do {
            let encrypted = self
            let key: [UInt8] = Array(AES_KEY.utf8) as [UInt8]
            let aes = try! AES(key: key, blockMode: ECB() as BlockMode, padding: .pkcs7) // AES128 .ECB pkcs7
            let decrypted = try aes.decrypt(Array(base64: encrypted))
            result = String(data: Data(decrypted), encoding: .utf8) ?? ""
            print("AES Decryption Result: \(result)")
        } catch {
            print("Error: \(error)")
        }
        return result
    }
    
}`
