### ISSUE TITLE
Expression was too complex to be solved in reasonable time; consider breaking up the expression into distinct sub-expressions

### ISSUE THREAD

**Issue by jhonyourangel** [krzyzanowskim/CryptoSwift#549]
i get the error:
`Expression was too complex to be solved in reasonable time; consider breaking up the expression into distinct sub-expressions`

for this line 
```
[
            UInt8(b0 & 0xFF),
            UInt8((b0 >> 8) & 0xFF),
            UInt8((b0 >> 16) & 0xFF),
            UInt8((b0 >> 24) & 0xFF),
            UInt8(b1 & 0xFF),
               UInt8((b1 >> 8) & 0xFF),
               UInt8((b1 >> 16) & 0xFF),
               UInt8((b1 >> 24) & 0xFF),
               UInt8(b2 & 0xFF),
               UInt8((b2 >> 8) & 0xFF),
               UInt8((b2 >> 16) & 0xFF),
               UInt8((b2 >> 24) & 0xFF),
               UInt8(b3 & 0xFF),
               UInt8((b3 >> 8) & 0xFF),
               UInt8((b3 >> 16) & 0xFF),
               UInt8((b3 >> 24) & 0xFF) ] as Array<UInt8>
```

**Comment by jhonyourangel** [comment]
to fix it i just split the code in more exec code:
`
var ret = [
            UInt8(b0 & 0xFF),
            UInt8((b0 >> 8) & 0xFF),
            UInt8((b0 >> 16) & 0xFF),
            UInt8((b0 >> 24) & 0xFF) ] as Array<UInt8>
        //newline
        ret += [ UInt8(b1 & 0xFF),
               UInt8((b1 >> 8) & 0xFF),
               UInt8((b1 >> 16) & 0xFF),
               UInt8((b1 >> 24) & 0xFF) ] as Array<UInt8>
        //newline
        ret += [ UInt8(b2 & 0xFF),
               UInt8((b2 >> 8) & 0xFF),
               UInt8((b2 >> 16) & 0xFF),
               UInt8((b2 >> 24) & 0xFF) ] as Array<UInt8>
// new line
        ret += [ UInt8(b3 & 0xFF),
               UInt8((b3 >> 8) & 0xFF),
               UInt8((b3 >> 16) & 0xFF),
               UInt8((b3 >> 24) & 0xFF) ] as Array<UInt8>
`

**Comment by krzyzanowskim** [comment]
what machine/swift version ?

**Comment by jhonyourangel** [comment]
I believe I was wrong.
I had those issues from the pod ( cocoa pod ), and before testing it from the GitHub, I added the issues.
The version from the GitHub is working with no issue 
Sorry man 

Anyway I have swift 4, iOS 11 and machine is MBP 13” 2017 base model

**Comment by krzyzanowskim** [comment]
The cocoapod release should be fine, v 0.8.0

**Comment by adnanafzal565** [comment]
In my case, it was due to mistype variables. I was concatenating NSInt type variable with String type. Hope this solves someone's problem having the same case.
