### ISSUE TITLE
AES with CFB-8 support for encryption and decryption

### ISSUE THREAD

**Issue by joshnaNalla** [krzyzanowskim/CryptoSwift#550]
hi. i want to encrypt a text with CFB-8 bits how can i do this as it has only CFB in library? this is the code how iam using
        let message: Array<UInt8> = "Hello World".bytes
        let vector: Array<UInt8> = "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0".bytes
        let key: Array<UInt8> = "secretkey".bytes

let aes = try? AES(key: key, blockMode: .CFB(iv: vector), padding: .noPadding).encrypt(messages)
        let hexs   = aes?.toBase64() 
        print(hexs ?? "hjj")

**Comment by krzyzanowskim** [comment]
Just regular CFB is available (operates on the block size). You can easily add new block mode though.
