### ISSUE TITLE
How to decrypt a Base64 data?

### ISSUE THREAD

**Issue by nzhuda** [krzyzanowskim/CryptoSwift#555]
Hi
Need help on following code snippet...

let encryptedData = try aes.encrypt(Array(strData.utf8))
 
Now I have converted the "encryptedData" to Base64() as:
let base64data = tokenCipherData.toBase64()!

So, if thr original data is "abc" the base64 will be "0qoqJMrTvU1xue+W57DGlw==",

Now I want to get back the original string "abc" from this base64data...How can I do that?

TIA

**Comment by krzyzanowskim** [comment]
decode base64, decrypt decoded data. there is helper for that. example is in README afair

**Comment by nzhuda** [comment]
Thank you so much, Got it!

**Comment by krzyzanowskim** [comment]
Base64 is not a cipher
