### ISSUE TITLE
[Java] SHA3 Java Porting

### ISSUE THREAD

**Issue by pascalbros** [krzyzanowskim/CryptoSwift#559]
Hi, thanks so much for the library.

I want to convert this Java code:
```
byte[] bytes = ....
Keccak.Digest384 keccak = new .....
keccak.update(bytes);
byte[] byte_state = this.keccak.digest();
```
But in the library there is just the `update()` function.
I'm not an expert of hasing algorithm, how can I achieve the same result?

Thanks so much.

**Comment by krzyzanowskim** [comment]
```swift
data.sha3(.keccak384)
```
