### ISSUE TITLE
Update to swift 1.2

### ISSUE THREAD

**Issue by luxis** [krzyzanowskim/CryptoSwift#56]
When is this gonna happen? I get this error when I try to compile my project.

"Module file was created by an older version of the compiler"

**Comment by krzyzanowskim** [comment]
Im not sure how this warning is related to swift1.2. transition to swift1.2 has been done a while ago.

**Comment by luxis** [comment]
Sorry, I had to clean my build to get this to work, however, I get this error now.

 'integerWithBytes' was deprecated in * version 0.8

**Comment by luxis** [comment]
line 39 in IntExtension.swift

**Comment by krzyzanowskim** [comment]
Duplicates https://github.com/krzyzanowskim/CryptoSwift/issues/50
