### ISSUE TITLE
Unable to decrypt if string contains '_' symbol?

### ISSUE THREAD

**Issue by rbmedpalli** [krzyzanowskim/CryptoSwift#561]
Unable to decrypt if string contains '_' symbol. getting exception

**Comment by krzyzanowskim** [comment]
It sounds like a misuse. Can't say more from the description. 

> CryptoSwift uses array of bytes aka Array<UInt8> as a base type for all operations. Every data may be converted to a stream of bytes. You will find convenience functions that accept String or Data, and it will be internally converted to the array of bytes.
