### ISSUE TITLE
BlockMode.Error.invalidInitializationVector when iv is string empty

### ISSUE THREAD

**Issue by rondinellimorais** [krzyzanowskim/CryptoSwift#562]
Hello, nice job!

When I use the tag **0.7.2** version of **CryptoSwift**, I can encrypt text using the code below:

```
let text = "rondinelli morais"
let key = "FpjqJ6QBT3yyWQaU"

if let data = text.data(using: .utf8) {
    do {
        
        let aes = try AES(key: key, iv: "", blockMode: .CBC, padding: .pkcs7)
        let encrypted = try aes.encrypt([UInt8](data))
        let encryptedData = Data(encrypted)
        
        print(encryptedData.base64EncodedString())
    }
    catch let error {
        print(error.localizedDescription)
    }
}
```
I can pass the empty string in parameter iv, and it's working!
The output is: **X3mJIQ7UE2fDDAZAXxbAA/AHPM4URikvwyxAeluJxLQ=**

Now, I upgraded to tag **0.8.1** version of **CryptoSwift**, the iv parameter was removed on **0.8.0**.

In this version, I use this code:

```
let text = "rondinelli morais"
let key = "FpjqJ6QBT3yyWQaU".bytes
let iv = "".bytes

if let data = text.data(using: .utf8) {
    do {
        
        let aes = try AES(key: key, blockMode: BlockMode.CBC(iv: iv), padding: Padding.pkcs7)

        let encrypted = try aes.encrypt([UInt8](data))

        let encryptedData = Data(encrypted)

        print(encryptedData.base64EncodedString())
    }
    catch let error {
        print(error.localizedDescription)
    }
}
```

But I cannot use iv empty because I receive **The operation couldn’t be completed. (CryptoSwift.BlockMode.Error error 1.)** in debug I can see the value of error **invalidInitializationVector**

and any other method I did try (randomIV, same value of key on iv, another BlockMode methods), generated a different output encrypt.

Can you help me?

**Comment by krzyzanowskim** [comment]
The IV is required for CBC mode. Previously I used all zeros IV when IV value was not specifically provided. This is in line with eg. CommonCrypto behavior, but it's not a good practice. I decided to remove this implicit value. The answer here is use `iv = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0] as [UInt8]` but remember that you shouldn't reuse IV twice for the same message, instead u should use different IV for each encrypt.



https://github.com/krzyzanowskim/CryptoSwift/blob/77074e12885bc036038e288a0507750d853d1f48/CHANGELOG#L12

> - Removes Ciphers "iv" parameter (value moved to BlockMode)
> - BlockMode uses associated value for IV value where apply e.g. .CBC(iv: ivbytes)

**Comment by rondinellimorais** [comment]
it worked! thank you.

Yes, I know this is not a best practices, but my app contains a long history 😔, thank you for this.

**Comment by Chhuon** [comment]
Hello and thank your for your awesome library.  
I have similar problem to @rondinellimorais. When I run the code, I ran into crash. I did move the iv parameter to BlockMode, yet problem is there. Please kindly help me correct and guide me on this. Thank you! 

This is Encryption Function
```
    func aesEncrypt(key: String, iv: String) throws -> String {
        let text = "Hello"
        let data = text.data(using: .utf8)!
        let encrypted = try! AES(key: key.bytes, blockMode: .CBC(iv: iv.bytes), padding: .pkcs5).encrypt([UInt8](data))
        let encryptedData = Data(encrypted)
        return encryptedData.base64EncodedString()  
    }
```
Then I tried to call the function in viewDidLoad()
```
    override func viewDidLoad() {
        super.viewDidLoad()
        
        do {
            let encrypted = try! aesEncrypt(key: "AIzaSyBBumM7UYChWQagm", iv: "123")
            print("result:", encrypted)
        }catch let error {
            print("Error:", error)
        }
    }
```
Here it is. It ran into crash with the message: 

Thread 1: Fatal error: 'try!' expression unexpectedly raised an error: CryptoSwift.BlockMode.Error.invalidInitializationVector

**Comment by rondinellimorais** [comment]
https://github.com/krzyzanowskim/CryptoSwift/issues/563

**Comment by mihailsalari** [comment]
mother fu@###@ with your f### encryption, anything doesn't work correctly!!!

**Comment by jvvinoth** [comment]
Hi @krzyzanowskim  Always am getting this error -> CryptoSwift.CTR.Error.invalidInitializationVector

I have to decrypt from server value in this format -> (AES-256/CTR/NoPadding) and below is my coide to decrypt.

Key = 0ezTRoStYRJBWfoNYs20180712065316
IV = 0b0f89dbba8748205cfb2f41364d15bb

===========
    func aesDecrypt(key: String, iv: String) throws -> String {
        let decrypted = try! AES(key: key.bytes, blockMode: CTR(iv: iv.bytes), padding: .noPadding).decrypt(self.bytes)
        let decryptedData = Data(decrypted)
        return String(bytes: decryptedData.bytes, encoding: .utf8) ?? "Could not decrypt"
    }
===========

Appreciate if you can help on this ! Thanks:-)
