### ISSUE TITLE
not encrypt correctly in swift 4 xcode 9

### ISSUE THREAD

**Issue by Mor4eza** [krzyzanowskim/CryptoSwift#568]
# Details

- CryptoSwift version: 0.8.1
- Swift version: swift 4
- Platform version: 
	- [x] iOS/tvOS/watchOS
	- [ ] macOS
	- [ ] Linux
- Installation: 
	- [x] CocoaPods
	- [ ] Carthage
	- [ ] Swift Package Manager
	- [ ] Manual
- [ ] [I'm a supporter](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=92Z6U3LBHF9J4).

# Description
not encrypt correctly in swift 4 xcode 9

# Steps to reproduce
after updating to xcode 9 and lib to version 0.8.1

Sample code:

```swift
func aesEncrypt() throws -> String {
        
        if let data = self.data(using: .utf8) {
            do {
                let aes = try AES(key: KeyPassword.bytes, blockMode: BlockMode.CBC(iv: KeyIv), padding: Padding.pkcs5)
                
                let encrypted = try aes.encrypt(data.bytes)
                
                let encryptedData = Data(encrypted)
                
                print(encryptedData.base64EncodedString())
                return encryptedData.base64EncodedString()
            }
            catch let error {
                print(error.localizedDescription)
            }
        }
        return ""
    }
```

> my data:

{"confirmType":"STATIC_PIN","osVersion":"11.0","clientVersion":"2.0.1","phoneNumber":"","password":"ali12$&@","udId":"DE19AF28-AC44-4C18-AE2A-08BC1D90C4C9","nickname":"payam22960211","deviceModel":"iphone"}

> encryped String:

oQofYl7ea1Z+ETykVpUvGyMt9LvTVHop051Ntyx/D9fHCNT+1NoROSnoYXNEnR3JRS8/VuC6LEpiCsmlHNJMydco20Kha2FPYvqS2z6lIS5Fmvj7vxZzFS5Z+8Q6myUdWrCRYUCX2FuxmYW2n1R89Qn8uureJ+7uuPyXs7pkls6toErlp0xtDT8DHowjUs3fP1EBx2OYfxVXRUwnV3zD/HIZ2s7NlRqAtyAsZbDV5O4dSJT8qlGGNFfsdNgz5FM9RAMWLjycA94wKRpD573kBQ==

> Decrypted result:

���w���6(��`STATIC_PIN","osVersion":"11.0","clientVersion":"2.0.1","phoneNumber":"","password":"ali12$&@","udId":"DE19AF28-AC44-4C18-AE2A-08BC1D90C4C9","nickname":"payam22960211","deviceModel":"iphone"}

why unknown Characters added to my Data?!

**Comment by krzyzanowskim** [comment]
I don't see the decryption part, how it is decrypted?

**Comment by Mor4eza** [comment]
i decrypt that with my own key in https://aesencryption.net/

**Comment by krzyzanowskim** [comment]
Please post the sample key and IV you use.

**Comment by Mor4eza** [comment]
KeyPassword = "GatePasswords123"
KeyIv  = "1234567890123456"
in above sample code i used a random Iv
this is result with this iv

> pzMnZ31vheTxZ86/nM1vtuSEAaMYoK6nA407upTes3ATys+I9PaRSNYfbO/kWgsfqNU2DYIyJZoIG5ssSinhY2BPEdrDHezJYRdXGVcTP676qtiX/cXxgjkBqISJzCDwiUXNw0USMZdeU1SgieOB8cGzDmZ+rzD9C9h4AgCNcU1nR5zFeui+cmgZYLrXUBeXb2l9KAZY4yt9ClDqB7GK/43XoycPy77DAfXYkIJutJpaMGLC98uYBGuCt/JrWnN5/2XyjbIPEor270gA2chtOw==

> and result is 
{"confir6T2pe":zSTATIC_PIN","osVersion":"11.0","clientVersion":"2.0.1","phoneNumber":"","password":"ali12$&@","udId":"DE19AF28-AC44-4C18-AE2A-08BC1D90C4C9","nickname":"payam22960211","deviceModel":"iphone"}



confirmType Is changed

**Comment by krzyzanowskim** [comment]
> error: value of type 'Data' has no member 'data'

Would you mind attaching the code that can be compiled to replicate? That'd really help and save a lot of time

**Comment by Mor4eza** [comment]
```swift


import UIKit
import CryptoSwift
class ViewController: UIViewController {
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        let body = ["clientVersion": "2.0.1",
                    "deviceModel": "iphone",
                    "nickname": "payam22960211",
                    "osVersion": "11.0",
                    "password": "ali12$&@",
                    "phoneNumber":"",
                    "udId": "DE19AF28-AC44-4C18-AE2A-08BC1D90C4C9",
                    "confirmType": "STATIC_PIN",
                    ]
        
        print("Enc Data: \(try! body.convertToJson().aesEncrypt())")
        
        // Do any additional setup after loading the view, typically from a nib.
    }
    
    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
    
    
}
extension String {
    
    func aesEncrypt() throws -> String {
        let KeyPassword = "GatePasswords123"
        let KeyIv  = "1234567890123456"
        if let data = self.data(using: .utf8) {
            do {
                
                let aes = try AES(key: KeyPassword.bytes, blockMode: BlockMode.CBC(iv: KeyIv.bytes), padding: Padding.pkcs5)
                
                let encrypted = try aes.encrypt(data.bytes)
                
                let encryptedData = Data(encrypted)
                
                print(encryptedData.base64EncodedString())
                return encryptedData.base64EncodedString()
            }
            catch let error {
                print(error.localizedDescription)
            }
        }
        return ""
    }
}

extension Dictionary {
    
    func convertToJson() -> String{
        
        var Json : String!
        let dictionary = self
        if let theJSONData = try? JSONSerialization.data(
            withJSONObject: dictionary,
            options: []) {
            let theJSONText = String(data: theJSONData,encoding: .utf8)
            Json = theJSONText
        }
        return Json
        
    }
    
}


```

**Comment by Mor4eza** [comment]
Did you find the Problem?! @krzyzanowskim

**Comment by krzyzanowskim** [comment]
I can't verify what's going on at https://aesencryption.net/ It's not a good test. I wouldn't trust it too much. The example code on that site has errors (eg. confuses key size with block size).

Anyways, I fixed the PHP example found at that site and verified it returns value equals to CryptoSwift value: https://gist.github.com/krzyzanowskim/078298b2d59808cc281dae2bb6f9e7a3

It doesn't look like a CryptoSwift bug. I'm closing this one. Feel free to re-open if you can provide the code that suggests it's a bug anyways.

**Comment by tkhabbab** [comment]
public class EncryptionDecryption {
    String strResult;

    public  String Encrypt(String text, String key) throws Exception {
        Cipher cipher = Cipher.getInstance("AES/CBC/PKCS5Padding");
        byte[] keyBytes = new byte[16];
        byte[] b = key.getBytes("UTF-8");
        int len = b.length;
        if (len > keyBytes.length)
            len = keyBytes.length;
        System.arraycopy(b, 0, keyBytes, 0, len);
        SecretKeySpec keySpec = new SecretKeySpec(keyBytes, "AES");
        IvParameterSpec ivSpec = new IvParameterSpec(keyBytes);
        cipher.init(Cipher.ENCRYPT_MODE, keySpec, ivSpec);

        byte[] results = cipher.doFinal(text.getBytes("UTF-8"));
        Log.v("GET Result from  final:", results.toString());
        strResult = Base64.encodeToString(results, 1);

        Log.v("Encrypt01:", strResult);
        Log.v("Encrypt02:", results.toString());
        return strResult;
    }


    public String Decrypt(String text, String key) throws Exception {
        Cipher cipher = Cipher.getInstance("AES/CBC/PKCS5Padding"); //this parameters should not be changed
        byte[] keyBytes = new byte[16];
        byte[] b = key.getBytes("UTF-8");
        int len = b.length;
        if (len > keyBytes.length)
            len = keyBytes.length;
        System.arraycopy(b, 0, keyBytes, 0, len);
        SecretKeySpec keySpec = new SecretKeySpec(keyBytes, "AES");
        IvParameterSpec ivSpec = new IvParameterSpec(keyBytes);
        cipher.init(Cipher.DECRYPT_MODE, keySpec, ivSpec);
        byte[] results = new byte[text.length()];
        //BASE64Decoder decoder = new BASE64Decoder();
        try {
            results = cipher.doFinal(Base64.decode(text, Base64.DEFAULT));
        } catch (Exception e) {
            Log.i("Error in Decryption", e.toString());
        }
        Log.i("Data", new String(results, "UTF-8"));
        //return new String(results, "UTF-8"); // it returns the result as a String
        return new String(results, "UTF-8");
    }


}





How can i use this method in CryptoSwift

**Comment by danielnakamashi** [comment]
See if this helps https://stackoverflow.com/questions/25480250/encryption-for-ios-3des-not-same-as-android-and-net/26400365
