### ISSUE TITLE
[help wanted] Decrypt result is different from what I get in Python

### ISSUE THREAD

**Issue by tulssinep** [krzyzanowskim/CryptoSwift#569]
# Details

- CryptoSwift version:  0.8.1
- Swift version: 4
- Platform version: 
	- [x] iOS/tvOS/watchOS
	- [ ] macOS
	- [ ] Linux
- Installation: 
	- [ ] CocoaPods
	- [x] Carthage
	- [ ] Swift Package Manager
	- [ ] Manual

Hello, thank you for this repo. I've been spending the last 2 hours trying to get decrypting to work. My key (32B), my iv (16B) as well as my encrypted data are Base64. However, as I have no control over the incoming data and its encoding, I am unable to convert it to String. This is a problem as your AES() constructor seems to take only Strings (except for the data) which would make my code very unsafe. Is there a way to use something like byte-arrays?

Decrypting my data in Python using `Crypto.Cipher`'s `AES` implementation works perfectly fine, I am passing `bytes` objects to the `AES.new(key, mode, IV)` constructor and would love to do the same in Swift.

I have found a solution on StackOverflow which does allow me to parse bytes but unfortunately it gives me another result.

In Python I do `AES.new(key=key, mode=AES.MODE_CBC, IV=iv)`
The solution at stackoverflow is taken from the following post and can be found under the `Swift 3 & 4 with Data type` section https://stackoverflow.com/a/37681510/2330482
Whilst I get the desired output in Python (base64-encoded image), doing the same like the person on StackOverflow gives me an entirely different result. I've read that CBC is default so this shouldn't be the issue I guess. Any ideas?

Thanks so much.

**Comment by tulssinep** [comment]
Took me 14 hours + a night of well-deserved sleep til I got it; was using the wrong key size. Thanks so much for this, will defo donate a few bucks.

However, I still think a data-compatible constructor would be nice

**Comment by krzyzanowskim** [comment]
There is a `[UInt8]` constructor (easily to convert from Data: https://github.com/krzyzanowskim/CryptoSwift#basics). The String based is just a sugar.
