### ISSUE TITLE
AES decryption with PKCS7 padding seems to read last byte incorrectly

### ISSUE THREAD

**Issue by gyamana** [krzyzanowskim/CryptoSwift#57]
Hello,

A newbie iOS developer here, but please hear me out.

I have been scratching my head over the last couple of hours around trailing characters after decryption.

I am using CryptoSwift 0.0.10, and it seems that the PKCS7.remove() function is removing one byte of padding only, despite the bytes value being larger than 1.

The following is the byte array before padding removal:

    [84, 104, 105, 115, 32, 105, 115, 32, 109, 121, 32, 111, 114, 105, 103, 105, 110, 97, 108, 32, 116, 101, 120, 116, 8, 8, 8, 8, 8, 8, 8, 8]

The following is the output I see after padding removal has been executed:

    This is my original text

As you can see, there are 7 special characters trailing the decrypted text (the characters show up as 'backspace', which corresponds to U+0008) 

I have managed to work out that I can actually change the CryptoSwift's code under the Pods directory and recompile to see the results.

Initially I put in a series of println statements to grab the above.

The code seems to be correct, and it actually works if I cut and paste the first line like so:

    var padding = Int(bytes.last!) // last byte
    padding = Int(bytes.last!) // last byte

However without re-initializing the padding variable, it remains as a value of 1 no matter what the value of the last byte is.

Would you be able to look at whether this is an issue, or a misuse of the library?

Regards,

George

**Comment by krzyzanowskim** [comment]
I don't see issue here. eight 8 at the end says that remove() should remove eight bytes, so it remove them.

```swift
public func remove(bytes: [UInt8], blockSize:Int? = nil) -> [UInt8] {
    var padding = Int(bytes.last!) // last byte

    if padding >= 1 {
        return Array(bytes[0..<(bytes.count - padding)])
    }
    return bytes
}


let bytes = remove([84, 104, 105, 115, 32, 105, 115, 32, 109, 121, 32, 111, 114, 105, 103, 105, 110, 97, 108, 32, 116, 101, 120, 116, 8, 8, 8, 8, 8, 8, 8, 8], blockSize: 16)

bytes.last // = 116
```

**Comment by gyamana** [comment]
Hmm, that is puzzling..

This only occurs when I grab the version of the library from CocoaPods.

I hadn't picked this issue up initially since the trailing characters weren't visible with println, but my colleague raised the issue and I am able to produce the same.

I am calling the library like so:

            let decrypted = AES(key: keyBytes, iv: ivBytes, blockMode: CipherBlockMode.CBC)?.decrypt(encryptedBytes, padding: PKCS7())

I can post up the variables that I can see cause the issue if you would like

**Comment by krzyzanowskim** [comment]
Can you please setup sample project to reproduce the issue?

**Comment by gyamana** [comment]
Hi,

I have pushed my sample implementation at the following repository:

https://github.com/gyamana/Playground

**Comment by NilsLattek** [comment]
I am having a similar issue where the last byte is incorrect. However this only occurs when using the library on the device (iPhone 5S). In the simulator everything works fine.

**Comment by krzyzanowskim** [comment]
@gyamana can you please provide testcase() to demonstrate this issue? the one I can run and verify on my side.

**Comment by gyamana** [comment]
Hi @krzyzanowskim, I've added a unit test case as you suggested. The issue will not be apparent on the simulator, but similar to @NilsLattek, when I run the test on an actual device, the test fails.

I have tested on an iPhone 6 with iOS 8.3 (12F70):

![image](https://cloud.githubusercontent.com/assets/10286008/8270008/ec487174-1809-11e5-8739-d4c0a42ab63c.png)

**Comment by gyamana** [comment]
Hey thanks :)

**Comment by krzyzanowskim** [comment]
Comment for future: It is a [Swift optimizer bug](http://blog.krzyzanowskim.com/2015/06/21/optimizer-considered-harmful/), observed on device for non-optimised builds only. I've made a workaround for that.

**Comment by gyamana** [comment]
Wow, thanks for that update.. I hope Apple will look to fix this issue with Swift.

Also, thanks for the mention :)
