### ISSUE TITLE
Is Apple allow Cryptoswift?

### ISSUE THREAD

**Issue by alaindixon** [krzyzanowskim/CryptoSwift#572]
Hi,

Very simple question, when you try to deploy an App on Itunes connect.
They ask you if you use an encryption method. I wonder if I have to declare that I use Cryptoswift ??? (In fact, SwiftDDP use Cryptoswift, I don't know what it does exactly).

Cheers

Alain

**Comment by krzyzanowskim** [comment]
It is allowed.
also see https://github.com/krzyzanowskim/CryptoSwift/issues/76
