### ISSUE TITLE
Generate sha256 from file. 

### ISSUE THREAD

**Issue by danilke** [krzyzanowskim/CryptoSwift#573]
# Details

- CryptoSwift version: 
- Swift version: 
- Platform version: 
	- [ ] iOS/tvOS/watchOS
	- [x] macOS
	- [ ] Linux
- Installation: 
	- [x] CocoaPods
	- [ ] Carthage
	- [ ] Swift Package Manager
	- [ ] Manual
- [ ] [I'm a supporter](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=92Z6U3LBHF9J4).

# Description
 Hello, it is possible to generate sha256 from file using `CryptoSwift`? in OSX terminal similar comand is `shasum -a 256 /path/to/my/file`. I'm new in swift and sorry if my question is to noob.

**Comment by krzyzanowskim** [comment]
yes it is. Use `Data` and calculate hash is the easiest way. See README for sample how to calculate sha.

**Comment by danilke** [comment]
Thank you!  How can init instance of `Data` with a path of file? I only found NSData:
 `let data: NSData? = NSData(contentsOfFile: "/path/of/file")`.
