### ISSUE TITLE
Signatures like in Sodium?

### ISSUE THREAD

**Issue by kuyawa** [krzyzanowskim/CryptoSwift#574]
Hi Marcin, amazing job you've done with this library. This is just a question not an issue, feel free to remove it if inappropriate. I'd like to use your library instead of Sodium because it's full native but can't find the `sign` method anywhere, I am not well versed in cryptography so any pointer would be highly appreciated. Thanks.

**Comment by kuyawa** [comment]
So the answer is to use `HMAC(key: key, variant: .sha256).authenticate(message)`

But unfortunately it looks like Sodium uses ed25519 for detached signatures so can't use CryptoSwift for now. Will wait for the ed25519 enhancement in future releases. Thanks anyway.

**Comment by kuyawa** [comment]
Ok, found this nice implementation using CryptoSwift:

https://gitlab.com/katalysis/Ed25519/blob/master/Sources/ed25519.swift

**Comment by krzyzanowskim** [comment]
Sorry for the lack of response. I should add some Curves finally. Have it on my desk for a long time, just lack of time.
