### ISSUE TITLE
AES128 encryption without iv

### ISSUE THREAD

**Issue by dinesh547** [krzyzanowskim/CryptoSwift#575]
Hi Sir,
I am trying to use cryptoswift in my code.
My requirement is to use AES128 encryption without a iv.
Can you please share a example where AES128 is used without an initialisation vector.
I know It will decrease the security of encryption. But its a requirement,

Thanks in advance for any help.

**Comment by krzyzanowskim** [comment]
You need to use ECB block mode.

**Comment by dinesh547** [comment]
Thanks @krzyzanowskim
