### ISSUE TITLE
Release 0.8.2 is broken (Carthage + manual archives)

### ISSUE THREAD

**Issue by johnhammerlund** [krzyzanowskim/CryptoSwift#577]
# Details

- CryptoSwift version: 0.8.2
- Swift version: 4.0
- Platform version: 
	- [x] iOS/tvOS/watchOS
	- [x] macOS
	- [ ] Linux
- Installation: 
	- [ ] CocoaPods
	- [x] Carthage
	- [ ] Swift Package Manager
	- [x] Manual
- [ ] [I'm a supporter](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=92Z6U3LBHF9J4).

# Description
Two issues have been introduced in the latest patch version:
1. The Release configuration now requires an optimization profile, which does not exist
1. The test target is now built for almost all build actions, which causes archives to fail due to lack of XCTest in watchOS

# Steps to reproduce
For Carthage:
1. Checkout tag `0.8.2`
1. Run `carthage build --no-skip-current`

For manual archive:
1. Checkout tag `0.8.2`
1. Product > Archive

**Comment by johnhammerlund** [comment]
Might also be a good call for some additional CI testing for building via `xcodebuild`, auxiliary to SPM

**Comment by krzyzanowskim** [comment]
Thanks, missed that. It's disabled for archive though
![screen shot 2018-02-16 at 10 11 08](https://user-images.githubusercontent.com/758033/36300467-b8c9bcb8-1301-11e8-8a7e-e18e7e14024b.png)

The CI help is a good idea, mind to work on it? I'm happy to merge.

**Comment by johnhammerlund** [comment]
Sure thing @krzyanowskim. Might not get around to it until early next week, but I’d be happy to jump on it.

As for the build actions, Carthage was failing unless all but the “Test” action was enabled. Since the latest 0.8.x is broken on Carthage  (which breaks consuming dependencies that depend on semantic versioning), I figured this could be temporary / actions could be re-enabled in a follow-up along with CI updates.

**Comment by shinma** [comment]
Any chance for fix in near future?

**Comment by krzyzanowskim** [comment]
Fixed: https://github.com/krzyzanowskim/CryptoSwift/pull/578

**Comment by johnhammerlund** [comment]
Thanks @krzyzanowskim 

Been another busy week, but I'll try to get some more work into CI updates tonight
