### ISSUE TITLE
How can I compile in swift 3.2 and xcode 9.2?

### ISSUE THREAD

**Issue by popularizan** [krzyzanowskim/CryptoSwift#582]
# Details

- CryptoSwift version: 
- Swift version: 
- Platform version: 
	- [x ] iOS/tvOS/watchOS
	- [ ] macOS
	- [ ] Linux
- Installation: 
	- [ x] CocoaPods
	- [ ] Carthage
	- [ ] Swift Package Manager
	- [ ] Manual
- [ ] [I'm a supporter](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=92Z6U3LBHF9J4).

# Description

No compile in Swift 3.2 and Xcode 9.2
I can not swift 4. How can I compile in swift 3.2 and xcode 9.2?

![screen shot 2018-02-27 at 09 41 46](https://user-images.githubusercontent.com/23721500/36718559-897ed02a-1ba2-11e8-8212-df06ab2b7f6c.png)

# Steps to reproduce

Sample code:

```swift
import CryptoSwift


```

**Comment by krzyzanowskim** [comment]
You have to choose right branch. The most recent version is not compatible with Swift 3.2:
https://github.com/krzyzanowskim/CryptoSwift#swift-versions-support
