### ISSUE TITLE
Could not decrypt AES 256 encrypted from PHP

### ISSUE THREAD

**Issue by mrunalthanki** [krzyzanowskim/CryptoSwift#584]
I am using [PHP_AES.zip](https://github.com/krzyzanowskim/CryptoSwift/files/1789173/PHP_AES.zip) for encryption in AES_256 and Decrypting it with CryptoSwift AES() Cipher. But I won't be able to get decrypted data. Below is my result with example.

**Note :** PHP is using `openssl_encrypt()` function for encrypt data.

**PHP Encryption :**
data = My text to encrypt.
key = 12345678123456781234567812345678 // 32Bytes 
blockSize = 256

**Encrypted String** : `CHlP5Wqz5TUn839wGEs5QR1s8cauhX3m6pvaeHkWaQI=`

**iOS (Swift 4) Decryption :**

```
do {
            let aes = try AES(key: "12345678123456781234567812345678", iv: "1234567890123456")
            // DECRYPTION
            let dt = try "CHlP5Wqz5TUn839wGEs5QR1s8cauhX3m6pvaeHkWaQI=".decryptBase64(cipher: aes)
            let dciphertext = String(data: Data(bytes: dt), encoding: .utf8)

            print("Decrypted Crypto : \(String(describing: dciphertext))")
} catch {
            print("error : \(error.localizedDescription)")
        }
```

**Decrypted String :** `|K\u{13}@PNC\u{18}M_\u{11}W]WGOpt.`

Can anyone please help me?

**Comment by krzyzanowskim** [comment]
Did you search for the closed php and openssl related tickets already?

**Comment by krzyzanowskim** [comment]
You problem is IV. U're not using explicit IV to encrypt, but does use it to decrypt.
This is PHP warning:
```
Warning: openssl_encrypt(): Using an empty Initialization Vector (iv) is potentially insecure and not recommended
```

**Comment by mrunalthanki** [comment]
Okay thank you. I got it.
