### ISSUE TITLE
No such module on CryptoSwift

### ISSUE THREAD

**Issue by carlosguedes** [krzyzanowskim/CryptoSwift#589]
# Details

- CryptoSwift version: (0.8.1)
- Swift version: 4
- Platform version: 
	- [ ] iOS/tvOS/watchOS
	- [x ] macOS
	- [ ] Linux
- Installation: 
	- [x ] CocoaPods
	- [ ] Carthage
	- [ ] Swift Package Manager
	- [ ] Manual
- [ ] [I'm a supporter](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=92Z6U3LBHF9J4).

# Description
When I install it using pods it keeps saying:

No such module 'CryptoSwift'

And there is nothing I can do to make it get recognised.

Any suggestion?

# Steps to reproduce

Sample code:

```swift
import CryptoSwift


```

**Comment by krzyzanowskim** [comment]
Looks like it's an integration issue. Try re-setup the project or ask CocoaPods guys

**Comment by carlosguedes** [comment]
Thanks for the answer but re-setup didn't worked... well, very strange...

The pod works, installs but can't get recognised.

Also when I tried

pod 'CryptoSwift', :git => "https://github.com/krzyzanowskim/CryptoSwift", :branch => "master"

I got this error:

Pre-downloading: `CryptoSwift` from `https://github.com/krzyzanowskim/CryptoSwift`, branch `master`
[!] Failed to load 'CryptoSwift' podspec: 
[!] Invalid `CryptoSwift.podspec` file: undefined method `swift_version=' for #<Pod::Specification name="CryptoSwift">.

 #  from /var/folders/_1/fsh6qv1x2dsgv67z5z5nr6fm0000gn/T/d20180326-12333-k5wsof/CryptoSwift.podspec:11
 #  -------------------------------------------
 #    s.social_media_url   = "https://twitter.com/krzyzanowskim"
 >    s.swift_version = "4.0"
 #    s.ios.deployment_target = "8.0"
 #  -------------------------------------------

**Comment by krzyzanowskim** [comment]
Upgrade cocoapods
