### ISSUE TITLE
Blowfish ECB can not encrypt

### ISSUE THREAD

**Issue by marcelosantoro** [krzyzanowskim/CryptoSwift#591]
# i am trying to encrypt with the follow code:
```swift
import CryptoSwift

let message = "my sentence to be encrypted."
let base64String = try! Blowfish(key: "passwordpassword", iv: "", blockMode: .ECB, padding: .noPadding).encrypt(Array(message.utf8)).toBase64()
```
Installed with CocoaPods
 - pod 'CryptoSwift'

![captura de tela 2018-03-28 as 03 44 34](https://user-images.githubusercontent.com/2624618/38013781-c6360f5a-323c-11e8-8637-823c54e16c2e.png)

**Comment by krzyzanowskim** [comment]
Your message has to be padded to the cipher block size, but isn't, is it?

**Comment by marcelosantoro** [comment]
Please, can you give me an example ???

**Comment by krzyzanowskim** [comment]
Example of a message that is padded to 8 bytes? "12345678" this is 8 bytes.

 U decided to not use padding `padding: .noPadding` but you need padding apparently

**Comment by marcelosantoro** [comment]
I am asking... because... i have the same functions using blowfish.js (http://sladex.org/blowfish.js/ext/blowfish.js) in a HTML/jQuery application... and the "padding" option is not necessary.

Please can you say to me, what is the real difference using the padding option ?

Why i can't use the "noPadding" option ?

Thank you very much to take your time with me.

**Comment by krzyzanowskim** [comment]
because you need padding for "my sentence to be encrypted." message.

> To whom may be concerned: I offer professional support to all my open source projects.

I'm closing this one, as I don't see the problem with a CryptoSwift here. Feel free to contact me for a crypto consultancy.
