### ISSUE TITLE
Fix Swift 4.1 Compiler Warnings

### ISSUE THREAD

**Issue by ilendemli** [krzyzanowskim/CryptoSwift#592]
- CryptoSwift version: 0.8.3
- Swift version: 4.1
- Platform (iOS/macOS/Linux/...): iOS
- Installation method (CocoaPods/Carthage/SPM/...): CocoaPods
- Project name: -

# Description

Updating Xcode to 9.3 updates Swift compiler to Version 4.1. Changes have been introduced and used some functions are deprecated.

# Steps to reproduce

Try compiling any project using Xcode 9.3

**Comment by krzyzanowskim** [comment]
It's ready on the master branch, waiting for release later today
https://twitter.com/krzyzanowskim/status/979490180171292672

**Comment by krzyzanowskim** [comment]
0.9.0
https://github.com/krzyzanowskim/CryptoSwift/releases/tag/0.9.0
