### ISSUE TITLE
No 'index' candidates produce the expected contextual result type '_?'

### ISSUE THREAD

**Issue by LanWor** [krzyzanowskim/CryptoSwift#594]
- CryptoSwift version: 0.9.0
- Swift version: 4.0
- Platform (iOS/macOS/Linux/...): iOS 9.3
- Installation method (CocoaPods/Carthage/SPM/...): CocoaPods 1.4.0
- Project name:trust

# Description

> To whom may be concerned: I offer professional support to all my open source projects.
when I import CryptoSwift use CocoaPods,it tell these errors 

<img width="872" alt="2018-04-02 3 09 47" src="https://user-images.githubusercontent.com/16620492/38187174-1ac000bc-3689-11e8-9c80-3f4da64d8f2a.png">

i did not do anything before that......but it dose not work

**Comment by krzyzanowskim** [comment]
Cannot reproduce with Xcode 9.3

1. Download CryptoSwift sources
1. Build

For the CococaPods, try:
```
pod cache clean CryptoSwift
pod deintegrate
pod install
```

**Comment by tengyifei** [comment]
This happens on Xcode 9.2 and Swift 4.0. Any way for it to be backwards-compatible?

**Comment by krzyzanowskim** [comment]
For 4.0 you should not update to 0.9.0
https://github.com/krzyzanowskim/CryptoSwift#swift-versions-support
