### ISSUE TITLE
CryptoSwift not found for architecture arm64

### ISSUE THREAD

**Issue by felipevaladares** [krzyzanowskim/CryptoSwift#595]
- CryptoSwift version: 0.8.3
- Swift version: 4.0
- Platform: iOS
- Installation method: CocoaPods

Hi, i'm using CryptoSwift in my project and every time that try to run a sample app i got the following error:
ld: framework not found CryptoSwift for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

the lib really doesn't have arm64 support? or is some kind of bug here? any idea for how i can solve?

**Comment by krzyzanowskim** [comment]
It does have. Looks like https://github.com/CocoaPods/CocoaPods integration issue. Try ask there.. Check linking etc.
