### ISSUE TITLE
Compatibility with Cryptojs for AES encryption

### ISSUE THREAD

**Issue by rezakhmf** [krzyzanowskim/CryptoSwift#596]
- CryptoSwift version: **0.8.1**
- Swift version: **4**
- Platform (iOS/macOS/Linux/...): ios
- Installation method (CocoaPods/Carthage/SPM/...): **CocoaPods**
- Project name:

# Description

I've encrypted a string with Cryptojs by AES but I can't decrypt in crypto swift

# Steps to reproduce
please referet to these following stackoverflow:

Sample code to reproduce the issue:

**crypto js**
```js
var encrypted = CryptoJS.AES.encrypt("mystringforencryption", "secret");

console.log(encrypted);
console.log("encrypted.ciphertext");
console.log(encrypted.ciphertext);
console.log(encrypted.ciphertext.toString(CryptoJS.enc.Base64));
console.log("encrypted.key");
console.log(encrypted.key);
console.log(encrypted.key.toString(CryptoJS.enc.Base64));
console.log("encrypted.iv");
console.log(encrypted.iv);
console.log(encrypted.iv.toString(CryptoJS.enc.Base64));
console.log("encrypted.salt");
console.log(encrypted.salt);
console.log(encrypted.salt.toString(CryptoJS.enc.Base64));
console.log("encrypted.padding.pad");
console.log(encrypted.padding);
```
**swift part:**

```swift
import CryptoSwift

let mdata = Data(base64Encoded: "U2FsdGVkX19zC/z0w6myZ74GbapfAywMvb3Al2aD4v8=")!
let count = [UInt8](mdata).count
let mbytes = Array([UInt8](mdata)[AES.blockSize ..< count])
let mkey = "secret".md5().bytes
let miv = Array([UInt8](mdata)[0 ..< AES.blockSize])
let aes = try AES(key: mkey, blockMode: BlockMode.CBC(iv: miv))
let decrypted = try aes.decrypt(mbytes)
let mresult =  String(bytes: decrypted, encoding: .utf8)
print(mresult)
```

**Comment by krzyzanowskim** [comment]
I can spot two issues here:

1. String to bytes conversion. `String.md5()` return hex represented string that you make bytes from.


```swift
let mkey = "secret".md5().bytes
```
should be
```swift
let mkey = [UInt8](hex: "secret".md5())
```

2. "secret" string can't be used as a AES key (is too short), so CryptoJS derive the key from "secret" string password using one of the KBF function. Reading CryptoJS sources shows It uses: www.openssl.org/docs/crypto/EVP_BytesToKey.html

It's better to use [PBKDF2](https://github.com/krzyzanowskim/CryptoSwift#password-based-key-derivation-functions) on both to derive the same key.

```swift
import Foundation 
import CryptoSwift 

let mdata = Data(base64Encoded: "U2FsdGVkX19zC/z0w6myZ74GbapfAywMvb3Al2aD4v8=")!
let count = [UInt8](mdata).count
let mbytes = Array([UInt8](mdata)[AES.blockSize ..< count])
let miv = Array([UInt8](mdata)[0 ..< AES.blockSize])
let mkey = try! PKCS5.PBKDF2(password: "secret".bytes, salt: miv, iterations: 4096, keyLength: 16, variant: .md5).calculate()
let aes = try AES(key: mkey, blockMode: BlockMode.CBC(iv: miv))
let decrypted = try aes.decrypt(mbytes)
```


I don't see the issue on the CryptoSwift side. Closing this one.

**Comment by astrokin** [comment]
if someone decided to use default CryptoJS functionality - i've finally[ make it work on iOS and Android ](https://medium.com/@alex.strok/cross-platform-encrypt-decrypt-ios-android-web-5f4ec26c2cef ):)
