### ISSUE TITLE
Am getting this swift compiler error

### ISSUE THREAD

**Issue by bbincybbaby** [krzyzanowskim/CryptoSwift#599]
- CryptoSwift version: master branch version
- Swift version: Swift 4
- Platform (iOS/macOS/Linux/...):  macOS
- Installation method (CocoaPods/Carthage/SPM/...): CocoaPods
- Project name: Test

# Description

Am getting swift compiler error on installing CryptoSwift

![image](https://user-images.githubusercontent.com/7812984/38348956-77b0df18-38c2-11e8-95e6-933ce3017f82.png)

**Comment by krzyzanowskim** [comment]
You need Swift 4.1 for the most recent version. See readme.
