### ISSUE TITLE
Update XCode 9.3 issue solved here

### ISSUE THREAD

**Issue by matheusbloebaum** [krzyzanowskim/CryptoSwift#600]
Just for you to know, that the issues #533 and all the others related to this one, just appeared again after updating xCode to 9.3, my apps were Swift 4.1 selected, and the simplest solution is the following: 
1- update your Podfile to the original set, as: 
    pod 'CryptoSwift'

2- open the "CryptoSwift Framework": Target -> Build Settings -> Swift Language and change to 4.1 (mine was 3.3 pre-selected)

Thanks.

**Comment by krzyzanowskim** [comment]
I don't know if I can do anything more to make the CocoaPods set the right Swift version. If you have any idea, I'm all ears here.

**Comment by DenHeadless** [comment]
CocoaPods uses Swift version of your project settings(not target settings). Anything that could be set on open-source project's level is discarded as far as i know.

**Comment by krzyzanowskim** [comment]
The https://github.com/krzyzanowskim/CryptoSwift/blob/master/CryptoSwift.podspec#L12 already pointing it should use Swift 4 setup, I don't understand why it's not respected.

Did you try report the issue to CocoaPods maybe?
