### ISSUE TITLE
unknown argument: '-remove-runtime-asserts' with XCode 9.3

### ISSUE THREAD

**Issue by chawax** [krzyzanowskim/CryptoSwift#601]
- CryptoSwift version: 0.9.0
- Swift version: 4.0.3 (Toolchain)
- Platform (iOS/macOS/Linux/...): iOS
- Installation method (CocoaPods/Carthage/SPM/...): CocoaPods

# Description

I use CryptoSwift in my project but since XCode 9.3 compilation fails with this error :

```
<unknown>:0: error: unknown argument: '-remove-runtime-asserts'
Command /Library/Developer/Toolchains/swift-4.0.3-RELEASE.xctoolchain/usr/bin/swiftc failed with exit code 1
```

I have the same problem with CryptoSwift 0.8.3.
I can't upgrade to Swift 4.1 because I have dependencies on Swift 4.0.x.

Any idea how I could solve this problem ?

**Comment by krzyzanowskim** [comment]
don't upgrade, set the version to 0.8.3 - that's the last version for Swift 4.0

I'm afraid I can't help with that. Did you report to Apple / CocoaPods already? It looks like a swift toolchain issue to me.

**Comment by krzyzanowskim** [comment]
[rdar://39239995](https://openradar.appspot.com/39239995)

**Comment by chawax** [comment]
OK, thanks for your help. I hope Apple will solve the problem quickly !

**Comment by krzyzanowskim** [comment]
Apple won't fix that.

> Apple Developer Relations, April 11 2018, 5:22 PM:
> There are no plans to address this based on the following:
> Please use Swift 4.1 toolchains and/or the one provided with Xcode.
> We are now closing this report.
