### ISSUE TITLE
how to combine md5 and aes?

### ISSUE THREAD

**Issue by ferdinandharmaputra** [krzyzanowskim/CryptoSwift#605]
Hello,

Please help me, this is my android team code:

           String password = "password"
           String dkey = "blablablabla";
            dkey = Md5.hashMd5(dkey);
            Cipher cipher = Cipher.getInstance("AES");
            cipher.init(Cipher.ENCRYPT_MODE, generateMySQLAESKey(dkey,"UTF-8"));

            byte[] cleartext = password.getBytes("UTF-8");
            byte[] ciphertextBytes = cipher.doFinal(cleartext);
            String _aes = new String(Hex.encodeHex(ciphertextBytes));

            return _aes;

How to create code like this using this pod?

Im developing application using swift 3. and this is my code =

        var password = "password"
        var key = "blablabla"
        var encryptedKey = key.md5()
        
        let data = password.data(using: .utf8)!
        
        print("encrypt Key : \(encryptedKey)")
        print("encrypt Password : \(data)")
        do {
            let aes = try AES(key: encryptedKey, iv: "AES") // aes128
            let ciphertext = try aes.encrypt(Array(data!))
            
            print ("ciphertext : \(ciphertext)")
        } catch { }

but it crash

Thank you before

**Comment by krzyzanowskim** [comment]
it crash? most likely it throws error that your `iv` parameter is invalid.

the line
```
try AES(key: encryptedKey, iv: "AES")
```
uses default value for blockMode = .CBC, this mode needs IV. Please check what IV and block mode is used on Android side and use the same.

https://developer.android.com/reference/javax/crypto/Cipher.html#getIV()

> If you find CryptoSwift useful, please [donate](https://www.paypal.com/donate/?token=yvl3LYX46jFvJZNNDAYfquxJowf5iK1t-9jvdw4tL5jlSuuUBfP35JnRDt17eRS_W2uBVW&country.x=US&locale.x=US) to keep the project running

**Comment by ferdinandharmaputra** [comment]
oh i see, thank you for the response.

in my case I should convert the key using MD5 and then encrypt the key using AES CBC.

then combine with the password where the password already converted to be utf8

and return the string.

hopefully you can help me sir :)

Thank you before
