### ISSUE TITLE
why Unexpected platform condition (expected 'os', 'arch', or 'swift')

### ISSUE THREAD

**Issue by onunix** [krzyzanowskim/CryptoSwift#606]
When i download the zip and compile on MacBook  ,it shows
 #if canImport(Darwin)
import Darwin
#else
import Glibc
#endif

error:  Unexpected platform condition (expected 'os', 'arch', or 'swift')
No such module 'Glibc'

What 's wrong with me ? may you help me ?
![Uploading 2018-04-19.png…]()

**Comment by krzyzanowskim** [comment]
This is Swift 4.1 feature, you're probably usign Swift 4.0

**Comment by onunix** [comment]
It's true, thank you!

**Comment by onunix** [comment]
then Which branch is recommended for swift 4.0 ?
