### ISSUE TITLE
AES trying to encrypt arabic numbers (١٢٣٤٥) crashes (returns nil)

### ISSUE THREAD

**Issue by alshcompiler** [krzyzanowskim/CryptoSwift#607]
AES trying to encrypt arabic numbers (١٢٣٤٥) crashes (returns nil), and i am using 

.encrypt(Array(padString(source: data).**utf8**))

It works perfect with English strings, so i am sure my code is fine but in arabic numbers case please advise

**Comment by krzyzanowskim** [comment]
Can't reproduce, looks good here.

```swift
import Foundation 
import CryptoSwift 

let aes = try AES(key: "passwordpassword", iv: "drowssapdrowssap")
let ciphertext = try aes.encrypt(Array("١٢٣٤٥".utf8))
print(ciphertext.toHexString()) // 9da29d524a4a910ebab3bbbad8b73916
```

**Comment by alshcompiler** [comment]
i think the problem that caused all of this is the following extra parameter : 
let aes = try AES(key:key, iv:iv,blockMode: .CBC, padding: NoPadding())

the padding parameter ... i hope this is something new for you, and it works now fine after i removed it , thanks!

**Comment by krzyzanowskim** [comment]
padding is not new, and you rather need padding for CBC, unless you add padding manually before.

**Comment by krzyzanowskim** [comment]
NoPadding means no padding will be added by CryptoSwift

**Comment by krzyzanowskim** [comment]
As I said, I dont see a problem, it encrypt just fine with default padding
