### ISSUE TITLE
Crash when trying to encrypt a string

### ISSUE THREAD

**Issue by zarghol** [krzyzanowskim/CryptoSwift#610]
- CryptoSwift version: 0.9.0 (we used 0.7.2 with iOS 4.0)
- Swift version: 4.1
- Platform (iOS/macOS/Linux/...): iOS (Simulator)
- Installation method (CocoaPods/Carthage/SPM/...):  Carthage

# Description

The encrypt method throw an exception when called (`Thread 1: EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)`)

# Steps to reproduce
just call the encrypt method of AES

Sample code to reproduce the issue:

```swift
import CryptoSwift

let bytes = Array("testString".utf8)
do {
    let encrypter = try AES(key: bytes, blockMode: .ECB)
    let aesId = try encrypter.encrypt(bytes)
    // crash on the encrypt method
} catch {
    print("Crypting failed")
}
```

**Comment by zarghol** [comment]
it appears to be the key length : I have a 64 characters key, so It crash, but using a 32 works (with `String(key64Chars[0..<32]`)

**Comment by zarghol** [comment]
Could you at least send a Swift Error instead of raw Bad Instruction Exception ? Thanks !!!! :)

**Comment by krzyzanowskim** [comment]
it shouldn't crash for this parameters, I'll check it

**Comment by zarghol** [comment]
It's causes by Variant : 
```
swift

public var variant: Variant {
        switch keySize * 8 {
        case 128:
            return .aes128
        case 192:
            return .aes192
        case 256:
            return .aes256
        default:
            preconditionFailure("Unknown AES variant for given key.")
        }
    }
```

since my key doesn't have a length of 16, 24, or 32 characters, preconditionFailure is called

**Comment by zarghol** [comment]
I don't know if this is part of this bug, but I try to have the same result between version 0.7.2 and 0.9.0, but I can't :

In 0.7.2, I can have a 64-bit key, with an aes128 variant, `key.size` is 64
In 0.9.0, I can't, due to variant (calling encryptor.variant, crash the same way the encrypt method do). If I try to put a substring of my key ([0..<16], to get the aes128 variant), the result is obviously not the same...

**Comment by zarghol** [comment]
pull request submitted : https://github.com/krzyzanowskim/CryptoSwift/pull/612

**Comment by edopelawi** [comment]
Folks, any update in this issue?

**Comment by zarghol** [comment]
the pull request is still pending : the unit tests crash on the CI, but not on my computer : it's hard to debug it...

**Comment by krzyzanowskim** [comment]
@zarghol PR #612 can't be merged in current form as it's not valid. The crash is not random, it's due the input values are not handled properly.

**Comment by zarghol** [comment]
I don't understand why it is working on my computer then...

**Comment by krzyzanowskim** [comment]
Closing as duplicate: https://github.com/krzyzanowskim/CryptoSwift/issues/611

**Comment by edopelawi** [comment]
Dear all, I'm not sure whether this is a good idea, but I want to add further info.

I'm currently working on an app for a client, and they asked me to implement a certain encryption process, which I can't share due to confidentiality issues. Their encryption process uses AES, and it works up to Xcode 9.2. It somehow crashes when I tried to run it in Xcode 9.3... I decided to wait for Xcode 9.4, which turns out still have the same issue.

Based on Xcode 9.3's [release notes](https://developer.apple.com/library/archive/releasenotes/DeveloperTools/RN-Xcode/Chapters/Introduction.html), the issue might have something to do with the new 64-bit mode.

I hope this info helps, just in case any of you want to revisit this issue in the future.

**Comment by krzyzanowskim** [comment]
The exact shouldn't matter (unless it's something with string conversion). The invalid length thould throw error in the latest version too. If that's anythring else I'm very curious how's the stacktrace

**Comment by edopelawi** [comment]
Dear @krzyzanowskim, I got clearance from my client to share the config, but with different keys. 😉 

You can find the sample code [in this repo](https://github.com/edopelawi/CryptoSwiftAESIssue). The master branch uses 0.9.0, and the code crashes on run. I also added `master-0.10.0` to use version 0.10.0, and the AES creation throws an exception.

There might be an issue in my configuration... but I can't really put a finger on it. It would be great if you could take a look at it. Thanks man!

**Comment by edopelawi** [comment]
@krzyzanowskim, have tried to check the sample?
