### ISSUE TITLE
Make variant injectable

### ISSUE THREAD

**Issue by zarghol** [krzyzanowskim/CryptoSwift#611]
# Description

Since old version (0.7.2) could work with a 64-length key, with an aes128 variant,
It could be great to let the user decide which variant to use, for compatibility purpose and for convenience.
We could put as a default the current choice based on the key length.

**Comment by zarghol** [comment]
pull request submitted : https://github.com/krzyzanowskim/CryptoSwift/pull/612

**Comment by krzyzanowskim** [comment]
64 bytes long key is not valid AES key and shouldn't work nor be used ever. As pointed https://github.com/krzyzanowskim/CryptoSwift/pull/612#discussion_r189444431 so far I was not able to reproduce flawless use of 64 bytes long key with 0.7.2
