### ISSUE TITLE
Password-Based Key Derivation Functions  PKCS5.PBKDF2  and  Rfc2898DeriveBytes(C#) produce diffrent result

### ISSUE THREAD

**Issue by kimseak-dev** [krzyzanowskim/CryptoSwift#614]
- CryptoSwift version:  Lastest
- Swift version: 4.00
- Platform (iOS/macOS/Linux/...): iOs 
- Installation method : Cocopod
- Project name: TestEncryptDescript

# Description

> To whom may be concerned: I offer professional support to all my open source projects.
> I got issue  Password-Based Key Derivation Functions produces  different result from C#

I used PKCS5.PBKDF2 (swift) and Rfc2898DeriveBytes (c#) to generate key 32 bit but get  different values

C#
```C#
string password = "s33krit"
string salt = "nacllcan"
Rfc2898DeriveBytes rfc2898 = new Rfc2898DeriveBytes(System.Text.Encoding.UTF8.GetBytes(password), System.Text.Encoding.UTF8.GetBytes(salt),100);
byte[] key =  rfc2898.GetBytes(256 / 8);
```

Swift
```swift
import CryptoSwift

let password: Array<UInt8> = Array("s33krit".utf8)
let salt: Array<UInt8> = Array("nacllcan".utf8)
let key =try! PKCS5.PBKDF2(password: password, salt: salt, iterations:100, variant: .sha256).calculate()
```
so result **key** in C# and Swift are diffrent

please help to give any solution thanks you

**Comment by krzyzanowskim** [comment]
Let me google it for you.

https://msdn.microsoft.com/en-us/library/system.security.cryptography.rfc2898derivebytes(v=vs.110).aspx

**Rfc2898DeriveBytes Class**
> Implements password-based key derivation functionality, PBKDF2, by using a pseudo-random number generator based on HMACSHA1.

compare with

https://github.com/krzyzanowskim/CryptoSwift#password-based-key-derivation-functions

You get 100 Internet points for finding one difference, I get nothing ;-(

**Comment by smkdoss73** [comment]
Hi Team,

Am new for encryption and decrypt concept . please guide me how to decrypt web service response.
**Now am using swift 4**
 **My code** 
   ` var encryptedString = "Test Encrypted String" `
  `  let adminpassword = "1234" `
  `  let adminsalt = "usersalt" `
    ` let adminiv = "user" `

please guide me , Thanks advance
