### ISSUE TITLE
Frame work file is missing in Can you please upload it. 

### ISSUE THREAD

**Issue by jainMadhur42** [krzyzanowskim/CryptoSwift#616]
- CryptoSwift version: 
- Swift version: 
- Platform (iOS/macOS/Linux/...): 
- Installation method (CocoaPods/Carthage/SPM/...): 
- Project name:

# Description

> To whom may be concerned: I offer professional support to all my open source projects.

# Steps to reproduce

Sample code to reproduce the issue:

```swift
import CryptoSwift

// Code goes here

```

**Comment by krzyzanowskim** [comment]
?
