### ISSUE TITLE
Swift 4 File/image to SHA1 wrong 

### ISSUE THREAD

**Issue by Timothybas** [krzyzanowskim/CryptoSwift#619]
let hashData = fileData.sha1()
                    
let calculatedHash = hashData.map { String(format: "%02hhx", $0) }.joined()
here is my code written in Swift 4 and it give me wrong SHA1 hash value.
Need help...
Thanks

**Comment by krzyzanowskim** [comment]
why SHA1 wrong?

**Comment by Timothybas** [comment]
I am using B2 cloud storage for file upload and i have to send sha1 has of image/ file while upload it says sha1 hash not matched with file and i also checked with online site its giving me wrong hash

Thanks

**Comment by Timothybas** [comment]
im getting this issue  ["status": 400, "code": bad_request, "message": Sha1 did not match data received]

**Comment by krzyzanowskim** [comment]
Unfortunately I can't verify what are you doing with the informations you provided

**Comment by Timothybas** [comment]
in android i have used the following code and its working fine 
    private static String getFileHash(File file) throws NoSuchAlgorithmException, IOException {
        MessageDigest md = MessageDigest.getInstance("SHA1");
        FileInputStream fis = new FileInputStream(file);
        byte[] dataBytes = new byte[ (int) 1024 * 5];
        int nread = 0;

        while ((nread = fis.read(dataBytes)) != -1) md.update(dataBytes, 0, nread);

        byte[] mdBytes = md.digest();
        StringBuffer sb = new StringBuffer("");
        for (int i = 0; i < mdBytes.length; i++)
            sb.append(Integer.toString((mdBytes[i] & 0xff) + 0x100, 16).substring(1));

        return sb.toString();
    }

**Comment by krzyzanowskim** [comment]
This is. Not helpful. Please attach the file and hash for the file you claim is not valid.

**Comment by Timothybas** [comment]
​
 WhatsApp Image 2018-05-17 at 10.49.05 PM.jpeg
<https://drive.google.com/file/d/1SAW4lLW0ZzToYfPmgmkARNwI8PkP2cOI/view?usp=drive_web>
​Hi,

SHA1 for the attached image  : 917eff1fc1dfaa01c70a22c39b1b5b663af2ada6 -
CryptoSwift
Actual SHA1 for this image      : 9695653474F3F7D45DC11749EE6CAC7F - online
website
Actual SHA1 for this image      : 9695653474F3F7D45DC11749EE6CAC7F - Android
Actual SHA1 for this image      : 9695653474F3F7D45DC11749EE6CAC7F - py

Thanks in Advice,

**Comment by Timothybas** [comment]
Hi,

SHA1 for the attached image  : 917eff1fc1dfaa01c70a22c39b1b5b663af2ada6 - CryptoSwift
Actual SHA1 for this image      : 9695653474F3F7D45DC11749EE6CAC7F - online website
Actual SHA1 for this image      : 9695653474F3F7D45DC11749EE6CAC7F - Android
Actual SHA1 for this image      : 9695653474F3F7D45DC11749EE6CAC7F - py
[https://drive.google.com/file/d/1SAW4lLW0ZzToYfPmgmkARNwI8PkP2cOI/view](url)
Thanks in Advice,

**Comment by Timothybas** [comment]
Here you can check http://onlinemd5.com/

**Comment by krzyzanowskim** [comment]
You must be doing something wrong,
I get `510ea5477d465f804dde2ec65d65fc043e7738eb` value for a given file.
 
![screen shot 2018-05-19 at 21 56 44](https://user-images.githubusercontent.com/758033/40272564-8a49622a-5baf-11e8-8baa-05faa5bfba70.png)
