### ISSUE TITLE
Need better docs

### ISSUE THREAD

**Issue by grosch** [krzyzanowskim/CryptoSwift#621]
Would you please consider some extra documentation?  What's currently there is really just a reference to the methods for people who already know what they all mean.  For someone not familiar with security and all the different types, who is just coming from a standpoint of "I need to encrypt my data on this side and decrypt it over there" I really have no idea where to start with your library.

**Comment by krzyzanowskim** [comment]
It's a tricky request as (as far as I understand) you ask for: "how to use cryptography to..." and I believe there are books out there that cover the subject. With the knowledge what you need, you can use the library like this. It doesn't solve the universal problem "how to encrypt" as out there are plenty of ways to build a secure protocol that consists the cryptography primitives (from a library like CryptoSwift).

I think it's not the of the library. It's more a request for a tutorial... but that the whole different story.

For now I can recommend a book [Serious Cryptography](https://nostarch.com/seriouscrypto) by Jean-Philippe Aumasson.
