### ISSUE TITLE
AES 256 to string

### ISSUE THREAD

**Issue by ronysteel** [krzyzanowskim/CryptoSwift#623]
Hi, but how to encrypted string like:  
ghJuUa7lt+pgYZ3vc3JPQZp8+KO/hBZsBa9vNscBFMChPOWquLGOZPqwkK6t/yU44Ez/oZoOlPX3OP5YyuPA/0jSnjmD8z5GEepclwTEJ8c=
from AES256 encryption?

**Comment by krzyzanowskim** [comment]
Via [README](https://github.com/krzyzanowskim/CryptoSwift#usage)

![screen shot 2018-05-22 at 17 48 06](https://user-images.githubusercontent.com/758033/40373952-51442678-5de8-11e8-84cd-0f2425c689c9.png)

**Comment by ronysteel** [comment]
@krzyzanowskim I have this code:
```
    let key = "6k?.df$H>sK6;;69}7*u<86.s$P#zJ%a"
    let textToEncrypt = "1234567890123456"
    
    let aes = try? AES(key: Array(key.utf8),
                       blockMode: CBC(iv: Array(textToEncrypt.utf8)),
                       padding: .pkcs7)
    
    let chipherText = try? aes?.encrypt(Array(textToEncrypt.utf8))
```

How to get a string like this:
ghJuUa7lt+pgYZ3vc3JPQZp8+KO/hBZsBa9vNscBFMChPOWquLGOZPqwkK6t/yU44Ez/oZoOlPX3OP5YyuPA/0jSnjmD8z5GEepclwTEJ8c=

I need AES 256 encryption

**Comment by krzyzanowskim** [comment]
@ronysteel I'll leave your comment for future example how to not show up in the OpenSource community. This project adopted [CODE_OF_CONDUCT](https://github.com/krzyzanowskim/CryptoSwift/blob/master/CODE_OF_CONDUCT.md) for a reason.
