### ISSUE TITLE
Unresolved identifier 'GCM'

### ISSUE THREAD

**Issue by YongxianTan** [krzyzanowskim/CryptoSwift#624]
CryptoSwift version: 9.3.1 (9E145)
Swift version: 4.1
Platform: macOS
Installation method: CocoaPods

I have just downloaded the latest master copy and installed CryptoSwift using CocoaPods. Using the example given on the README:

```
do {
    // In combined mode, the authentication tag is directly appended to the encrypted message. This is usually what you want.
    let gcm = GCM(iv: iv, mode: .combined)
    let aes = try AES(key: key, blockMode: gcm, padding: .noPadding)
    let encrypted = try aes.encrypt(plaintext)
    let tag = gcm.authenticationTag
catch {
    // failed
}
```

I get the error of "Use of unresolved identifier 'GCM'". I have tried other functions like aes.encrypt and aes.decrypt and they all work fine

**Comment by krzyzanowskim** [comment]
GCM is not released to Cocoapods yet. it's available from master branch

**Comment by YongxianTan** [comment]
Are you able to give a date as to when you will release it to Cocoapods?

Much thanks and appreciation

**Comment by krzyzanowskim** [comment]
this or next week at latest
