### ISSUE TITLE
Obj-C support from Block Modes.

### ISSUE THREAD

**Issue by TheHmmka** [krzyzanowskim/CryptoSwift#627]
- CryptoSwift version: 0.10.0
- Swift version: -
- Platform (iOS/macOS/Linux/...): iOS
- Installation method (CocoaPods/Carthage/SPM/...): CocoaPods
- Project name: -

# Description

CBC() is not working from Obj-C/Swift mixed project. Please, add support for Obj-C.

# Steps to reproduce

Just use framework from Obj-C code.

Sample code to reproduce the issue:

```swift
import CryptoSwift

let aes = try? AES(key: Array(configuration.apiSecret.utf8), blockMode: ECB())

```

**Comment by krzyzanowskim** [comment]
Wait, can't access Swift class from Swift? That'd be unlikely.

**Comment by TheHmmka** [comment]
So, let me describe deeper.
I have created my own CocoaPod with dependency from CryptoSwift (for many internal projects in my company).
My own CocoaPod is using in Obj-C/Swift project.
That's the reason of the problem.
With enum there was no error but now...
May be this is a problem of CocoaPods, but what's the reason to move away from enum?

**Comment by albertbori** [comment]
I can confirm this issue in a Swift project that uses CryptoSwift with Cocoapods. I do have some objective-c and a bridging header in the project, but it's 98% swift code throughout. (Not sure if that info is helpful)

Podfile reference line:

    pod 'CryptoSwift'

Podfile.lock:

     - CryptoSwift (0.9.0)

![screen shot 2018-06-13 at 4 24 06 pm](https://user-images.githubusercontent.com/1742709/41381754-6de24c52-6f26-11e8-9161-ac8d85bb4671.png)

It detects the AES class just fine, but not CBC. 🤷‍♂️

**Comment by TheHmmka** [comment]
I am glad to be not alone! :-)

**Comment by krzyzanowskim** [comment]
I hear you,'z I must admit the ObjC interoperability has a pretty low priority for a pure swift library like this. I'll take a look, though I'd rather not change API again for that sole reason. Maybe there is an easy "fix" for that.

**Comment by albertbori** [comment]
Looks like `CBC(iv: iv)` was refactored to `BlockMode.CBC(iv: iv)`. The docs need to be updated.

**Comment by krzyzanowskim** [comment]
@albertbori it wasn't. `CBC` is a top level struct. Full name is `CryptoSwift.CBC` Would u mind to share the Xcode project to reproduce the issue?

**Comment by krzyzanowskim** [comment]
`struct CBC: BlockMode` is not an enum. There is no `BlockMode.CBC` in the sources.
