### ISSUE TITLE
some characters are dropped after decrypting 

### ISSUE THREAD

**Issue by zj9205** [krzyzanowskim/CryptoSwift#628]
- CryptoSwift version: 0.10.0
- Swift version: 4.1
- Platform (iOS/macOS/Linux/...): iOS
- Installation method (CocoaPods/Carthage/SPM/...): CocoaPods
- Project name:

# Description
Ex. 
Input: the count of encrypted string is 9120
Output: the count of decrypted data array is only 9110
last 10 characters are dropped.
I was using AES-CBC-256, pkcs7

> To whom may be concerned: I offer professional support to all my open source projects.

# Steps to reproduce

Sample code to reproduce the issue:

```swift
import CryptoSwift

// Code goes here

```

**Comment by krzyzanowskim** [comment]
Show me the code

**Comment by toothpiggystudio** [comment]
Thanks for your reply, @krzyzanowskim , I already have that on the top of my file.  I also tried to clean the project and still the same. 

![screen shot 2018-05-31 at 12 15 21 pm](https://user-images.githubusercontent.com/28891494/40770639-554607a6-64cc-11e8-98ab-20f3aa1765ff.png)

**Comment by krzyzanowskim** [comment]
padding is an enum, use `.pkcs7`

**Comment by toothpiggystudio** [comment]
Got another error when i changed it on .pkcs7, before the comment out line was working when i used the previous lib. I tried to update this morning and i got this error. i also tried to use

pod 'CryptoSwift', :git => "https://github.com/krzyzanowskim/CryptoSwift", :branch => "master"

but still the same. thanks

![screen shot 2018-05-31 at 12 18 25 pm](https://user-images.githubusercontent.com/28891494/40770900-fe9e7ffe-64cc-11e8-9f74-f127933e353f.png)

**Comment by krzyzanowskim** [comment]
```
try AES(key: key.bytes, blockMode: CBC(iv: iv.bytes), padding: .pkcs7)
```

**Comment by toothpiggystudio** [comment]
Hi!

Thank you for your help. its now working. :)
