### ISSUE TITLE
PKCS7' cannot be constructed 

### ISSUE THREAD

**Issue by toothpiggystudio** [krzyzanowskim/CryptoSwift#629]
- CryptoSwift version: 
![screen shot 2018-05-31 at 11 47 23 am](https://user-images.githubusercontent.com/28891494/40769418-fd23c368-64c8-11e8-8371-e995b80688a2.png)

- Swift version: 4.1
- Platform (iOS/macOS/Linux/...): iOS
- Installation method (CocoaPods/Carthage/SPM/...): CocoaPods
- Project name:

Hi I update my CryptoSwift using CocoaPods and i got this error.
"'PKCS7' cannot be constructed because it has no accessible initializers"

please see attached screenshot.  

Thanks.

**Comment by krzyzanowskim** [comment]
> 0.7.2
> - Adds Padding enum (.pkcs5, .pkcs7, .noPadding, .zeroPadding)

It's an enum since 0.7.2

**Comment by toothpiggystudio** [comment]
Thank you! It's working. :)

**Comment by sreechary** [comment]
How it worked I am also getting the same issue

**Comment by krzyzanowskim** [comment]
@sreechary relevant sample can be found in README

**Comment by sreechary** [comment]
sorry i didn't understood that could you please help me in that

**Comment by Rakshitha-M-Rodrigo** [comment]
`let encrypted = try! AES(key: key, iv: iv, padding: .pkcs7).encrypt([UInt8](data))`

Check on the repo.. it's all there... Thanks ! @krzyzanowskim krzyzanowskim

**Comment by amit6061** [comment]
E dataPaddingRequired
