### ISSUE TITLE
Module file's minimum deployment target is ios9.0 

### ISSUE THREAD

**Issue by GG526** [krzyzanowskim/CryptoSwift#630]
Module file's minimum deployment target is ios9.0 v9.0:

**Comment by GG526** [comment]
My App is iOS 8.0.

**Comment by Vinzius** [comment]
Yes. It seems something changed since v0.10. I had to force v0.9 for the Pusher lib via Carthage.

But podspecs say `s.ios.deployment_target = "8.0"`.

Could it be the Xcode proj?

**Comment by GG526** [comment]
I integrate with Carthage and cannot support iOS8 after I update to v0.10.
I have to return a version.

**Comment by GG526** [comment]
Xcode 9.4.
swift 4.1.
Minimum supported version iOS 8.0.
The use of Carthage.

**Comment by krzyzanowskim** [comment]
I don't remember this change. Maybe an overlook. Can you confirm it works with ios 8?

**Comment by GG526** [comment]
The previous version was available in iOS 8.0.

**Comment by GG526** [comment]
thanks

**Comment by guilhermearaujo** [comment]
I believe a new release must be created for Carthage be able to build a framework targeting 8.0
Otherwise we must import like this: `github "krzyzanowskim/CryptoSwift" "master"`

**Comment by krzyzanowskim** [comment]
yes. I have to finish one feature first, hopefully, will have it ready today, so stay tuned.

**Comment by krzyzanowskim** [comment]
Released 0.11.0 should fix the issue.
