### ISSUE TITLE
I am currently use AES in Swift and my friend did in java but encryption time we are not getting same answer.

### ISSUE THREAD

**Issue by Sravan525** [krzyzanowskim/CryptoSwift#633]
- CryptoSwift version: 
- Swift version: 
- Platform (iOS/macOS/Linux/...): 
- Installation method (CocoaPods/Carthage/SPM/...): 
- Project name:

# Description

> To whom may be concerned: I offer professional support to all my open source projects.

# Steps to reproduce

Sample code to reproduce the issue:

Java code

```java
private String encrypt(String text,String password) throws UnsupportedEncodingException, NoSuchAlgorithmException, NoSuchPaddingException, InvalidKeyException, BadPaddingException, IllegalBlockSizeException {
    Key key = generateKey(password);
    String keyChange = key.toString();
 //   String encodedKey = Base64.getEncoder().encodeToString(keyChange.getEncoded());
    Log.v("AES","Value Of key :"+keyChange);
    Cipher c = Cipher.getInstance(AES);
    c.init(Cipher.ENCRYPT_MODE,key);
    byte[] encval = c.doFinal(text.getBytes());
    String encryptedVal = Base64.encodeToString(encval,Base64.DEFAULT);
    Log.v("AES","enc key :"+encryptedVal);
    return encryptedVal;
}
private SecretKeySpec generateKey(String password) throws NoSuchAlgorithmException, UnsupportedEncodingException {
   
    byte[] bytes = password.getBytes("UTF-8");
   
    SecretKeySpec secKey = new SecretKeySpec(bytes,"AES");
    return secKey;
}
public String decrypt(String cipher, String password) throws UnsupportedEncodingException, NoSuchAlgorithmException, NoSuchPaddingException, InvalidKeyException, BadPaddingException, IllegalBlockSizeException {
    SecretKeySpec key = generateKey(password);
    Cipher c = Cipher.getInstance(AES);
    c.init(Cipher.DECRYPT_MODE,key);
    byte[] decodeval = Base64.decode(cipher,Base64.DEFAULT);
    byte[] decval = c.doFinal(decodeval);
    String decryptedValue = new String(decval);
    Log.v("AES","Dec key :"+decryptedValue);
    return decryptedValue;
}
```

Swift code:
```swift
let key = "raviraviraviraviraviraviraviravi" // length == 32
        let iv = "0000000000000000" // length == 16
        let s = "hai"
        let enc = try! s.aesEncrypt(key: key, iv: iv)
        print("ENCRYPT",enc)
//        let encc = "Kw3/2fVvzam7RoKn44/Hqg==\n"
        let dec = try! enc.aesDecrypt(key: key, iv: iv)
        print("DECRYPT",dec)



  func aesEncrypt(key: String, iv: String) throws -> String {
        let data = self.data(using: String.Encoding.utf8)
        //self.dataUsingEncoding(NSUTF8StringEncoding)
        let encrypted = try AES(key: key, iv: iv, padding: .pkcs7).encrypt((data?.bytes)!)
        let encData = Data(bytes: encrypted, count: encrypted.count)
        let base64str = encData.base64EncodedString(options: .init(rawValue: 0))
        let result = String(base64str)
        return result
    }
    func aesDecrypt(key: String, iv: String) throws -> String {
        let data = Data(base64Encoded: self)!
        let decrypted = try! AES(key: key, iv: iv, padding: .pkcs7).decrypt([UInt8](data))
        let decryptedData = Data(decrypted)
        return String(bytes: decryptedData.bytes, encoding: .utf8) ?? "Could not decrypt"
    }
```
plese tell me what is the problem?

**Comment by krzyzanowskim** [comment]
The problem is that you either use different keys, or u misuse string encodings. Most likely u use different key though.

**Comment by Sravan525** [comment]
Thank you sir,I used both sides same key that is "raviraviraviraviraviraviraviravi" and message hai.
but encrypt format was not matching.

**Comment by krzyzanowskim** [comment]
looks like Java is transforming the password to a key with a function

**Comment by tktdw** [comment]
i want implement AES ECB encription in Java and Swift, but why in swift get different value ?

Java code

public static void setKey(String myKey){
    MessageDigest sha = null;
    try {
        key = myKey.getBytes("UTF-8");
        sha = MessageDigest.getInstance("SHA-1");
        key = sha.digest(key);
        key = Arrays.copyOf(key, 16);
        secretKey = new SecretKeySpec(key, "AES");
    }
    catch (NoSuchAlgorithmException e) {
        e.printStackTrace();
    }
    catch (UnsupportedEncodingException e) {
        e.printStackTrace();
    }
}

public static String encrypt(String strToEncrypt, String secret){
    try {
        setKey(secret);
        Cipher cipher = Cipher.getInstance("AES/ECB/PKCS5Padding");
        cipher.init(Cipher.ENCRYPT_MODE, secretKey);

        byte[] encrypted = cipher.doFinal(strToEncrypt.getBytes());
        String encoded = Base64.encodeToString(encrypted, Base64.NO_WRAP);
        Log.d("haha", encoded);
        return encoded;
    } catch (Exception ex) {
        ex.printStackTrace();
    }
   return null;
}


Swift code:

func encrypt(key: String, value: String) -> String {
    let byteKey = [UInt8](key.utf8)
    let sha = byteKey.sha1()
    let secretKey = Array(sha [0..<16])
    let data = value.data(using: String.Encoding.utf8)!
    let encrypted = try! AES(key: secretKey, blockMode: .ECB, padding: .pkcs5).encrypt([UInt8](data))
    let encryptedData = Data(encrypted)
    let base64str = encryptedData.base64EncodedString()
    let result = String(base64str)
    Log("before enkrip " + value);
    Log("after enkrip " + base64str);
    return result!
}

plese tell me what is my wrong?

**Comment by superRFstrat** [comment]
I'm having a similar issue, the password and salt are exactly the same.  I believe the issue lies within the Base64 encoding cipher that Java uses.  I get a datapaddingrequired error when calling the function without using the decryptBase64 method on the input string.  When I pass the aes cipher into the cipher argument I get an output that can't be converted into a string.  I'm looking through the source code for the Java Base64 encoder right now but it's hard to make sense of.  I'll let you know if I find a solution.
