### ISSUE TITLE
Unable to compile Xcode9.2

### ISSUE THREAD

**Issue by singhdavinder** [krzyzanowskim/CryptoSwift#634]
![screen shot 2018-07-04 at 3 53 53 pm](https://user-images.githubusercontent.com/24710356/42273365-937df3fe-7fa6-11e8-9e5c-4d4e38ca0b2c.png)

**Comment by krzyzanowskim** [comment]
`canImport` is Swift 4.1 feature. You need Swift 4.1 for that version of CryptoSwift.
