### ISSUE TITLE
The compiler gets confused

### ISSUE THREAD

**Issue by sgbasaraner** [krzyzanowskim/CryptoSwift#636]
- CryptoSwift version: 0.10.0
- Swift version: 4.1
- Platform (iOS/macOS/Linux/...): iOS 10
- Installation method (CocoaPods/Carthage/SPM/...): CocoaPods
- Project name: Carla

# Description

The compiler is confused about the type of CBC. When build target is set as a device (say, iPhone X, for example), it identifies CBC as a struct and compiles. However, when build target is Generic iOS Device, the same code does not compile as the compiler now identifies it as a case in an enum called BlockMode. This inevitably breaks the codebase, as the same code does not compile in all cases.

# Steps to reproduce

The code below compiles for iPhone X (simulator) target, but does not compile for Generic iOS Device target:

```swift
import CryptoSwift

@objc func aesEncrypt(_ key: String, iv: String) throws -> String {
        let data = self.data(using: String.Encoding.utf8.rawValue)

        // This only compiles for simulator target
        let cbc = CBC(iv: Array(iv.utf8))

        let enc  = try AES(key: Array(key.utf8), blockMode: cbc).encrypt((data?.bytes)!)
        let encData = NSData(bytes: enc, length: Int(enc.count))
        let base64String: String = encData.base64EncodedString(options: NSData.Base64EncodingOptions(rawValue: 0))
        let result = String(base64String)
        return result
    }

```

The code below compiles for Generic iOS Device target, but does not compile for iPhone X (simulator) target:

```swift
import CryptoSwift

@objc func aesEncrypt(_ key: String, iv: String) throws -> String {
        let data = self.data(using: String.Encoding.utf8.rawValue)

        // This only compiles for non-simulator targets
        let cbc = BlockMode.CBC(iv: Array(iv.utf8))

        let enc  = try AES(key: Array(key.utf8), blockMode: cbc).encrypt((data?.bytes)!)
        let encData = NSData(bytes: enc, length: Int(enc.count))
        let base64String: String = encData.base64EncodedString(options: NSData.Base64EncodingOptions(rawValue: 0))
        let result = String(base64String)
        return result
    }

```

Any idea why this would be the case?

**Comment by krzyzanowskim** [comment]
The fullname is `BlockMode.CBC`. Don't know why swift compiler can/can't interfere type properly. To me it looks like both link different versions of CryptoSwift

**Comment by sgbasaraner** [comment]
I tried to open a fresh new project and was able to recreate the issue. Can you please try to run call this code:

```
import CryptoSwift

extension NSString {
    @objc func aesEncrypt(_ key: String, iv: String) throws -> String {
        let data = self.data(using: String.Encoding.utf8.rawValue)
        
        // This only compiles for non-simulator targets
        let cbc = CBC(iv: Array(iv.utf8))
        
        let enc  = try AES(key: Array(key.utf8), blockMode: cbc).encrypt((data?.bytes)!)
        let encData = NSData(bytes: enc, length: Int(enc.count))
        let base64String: String = encData.base64EncodedString(options: NSData.Base64EncodingOptions(rawValue: 0))
        let result = String(base64String)
        return result
    }
}

print(try! "swift".aesEncrypt("asd", iv: "asd"))
```

**Comment by krzyzanowskim** [comment]
It's `CBC`. BlockMode is a protocol. Use just `CBC`. Full name is CryptoSwift.CBC

http://online.swiftplayground.run/
![screen shot 2018-07-11 at 21 40 49](https://user-images.githubusercontent.com/758033/42595608-1d31a9fe-8553-11e8-9b47-cbc7c2c81b6e.png)

Can't reproduce. You can attach here a sample Xcode project where the problem occurs and reopen the issue.

**Comment by krzyzanowskim** [comment]
but there is no `enum BlockMode` in the repository. Maybe you need to clean the sources or something.

**Comment by sgbasaraner** [comment]
> but there is no enum BlockMode in the repository. Maybe you need to clean the sources or something.

@krzyzanowskim  I know, that's why I wrote 'the compiler gets confused' in the title. Have you tried to run the project I attached in my last comment?
