### ISSUE TITLE
Debug / Release speeds

### ISSUE THREAD

**Issue by sarahjstacey15** [krzyzanowskim/CryptoSwift#638]
- CryptoSwift version: 0.10.0 
- Swift version: 4.1
- Platform (iOS/macOS/Linux/...): iOS
- Installation method (CocoaPods/Carthage/SPM/...): CocoaPods
- Project name: N/A

# Description
I have a project that reads in an encrypted JSON file of data I want to decrypt each time the app is run, this all works well however when the app is in debug mode the decryption takes around 30 seconds, on release build it takes 3 seconds. Would be great to have a feature where you could turn of the debugging. 

> To whom may be concerned: I offer professional support to all my open source projects.

# Steps to reproduce
N/A

Sample code to reproduce the issue:

```swift
import CryptoSwift

// Code goes here

```

**Comment by krzyzanowskim** [comment]
That's the nature of Swift compiler. Depends on the integration, you can modify settings to build CryptoSwift in release mode always.

**Comment by sarahjstacey15** [comment]
I've integrated using cocoa pods and enabled whole module optimisation, any other tips?
