### ISSUE TITLE
AES 128-bit block exceeded!

### ISSUE THREAD

**Issue by jamesmartins** [krzyzanowskim/CryptoSwift#64]
Hi. Your library is awesome!. I love pure swift.
I using AES algoritmo + ECB/PKCS5 Padding. But I getting error: "AES 128-bit block exceeded".
Can I help-me? I've a webservice rest java that generate and send my iOS App an encrypted data:

data = "4PVOJpuZ9rEPgiMHr7EWI+jgDAA0/AusBeGRdNH7EkePRHURixwwah1JnqnZCudxhKeK9CdhA2A+85nymSnI2OVEu/YT8ImVWEkluRPwEtvwcBCVOe/+jc5BJgBxYevqxRhxc5SI3MPuN/JRt6CHeMMYxjvvrFBvLzfVaBp5wbS/TF81ZtKVJggZZRig/i9lcOmOon60foRGK6lm3bUf09RLBL/G91w2Bt9ZNdFoFQpaahSXc9cYyvip1NiRDhVReNgPzLeaoV5tnxOR758AJWh+ClW3krAhF9ASpfmVxpKqDyvmcwN0tmQXpAfyVX++M/AyWWKbuQ+tjmxpKkArj3SzpoFUX6tI+dSeY44mfftQwMcNXXSmtn1vqJAuV0d6FP4wkm8fmNj3EghcflgGZkSR9Vn1HN4d/wJQnFfitsGTWVWtchQ4JEOLQkrPsN7CYHuGAsvlybegV5IrtIy77Q==" 

My Private key is: 
"20204789552049DKRPV072008T6E9M4T456979087ASDWEBNBUYI7Y820204789552049DKRPV072008T6E9M4T456979087ASDWEBNBUYI7Y820204789552049DKRPV072008T6E9M4T456979087ASDWEBNBUYI7Y820204789552049DKRPV072008T6E9M4T456979087ASDWEBNBUYI7Y82010425245204958020072008T6E9A5MRSAC"

So, I imported your library and I did this way:
I declared a class and transforming my private key to [UInt8]: 

class KeyPair {
    static func getPrivateKey()->[UInt8]{
        var str = "20204789552049DKRPV072008T6E9M4T456979087ASDWEBNBUYI7Y820204789552049DKRPV072008T6E9M4T456979087ASDWEBNBUYI7Y820204789552049DKRPV072008T6E9M4T456979087ASDWEBNBUYI7Y820204789552049DKRPV072008T6E9M4T456979087ASDWEBNBUYI7Y82010425245204958020072008T6E9A5MRSAC"
        return [UInt8](str.utf8)
    }
}

After this I did a func:
func decript(encryptedData : [UInt8]) -> String{
        let iv = Cipher.randomIV(AES.blockSize)
        var data = NSData()
        if let aes = AES(key: KeyPair.getPrivateKey(), iv: iv, blockMode: CipherBlockMode.ECB){
            let decripted  = aes.decrypt(encryptedData, padding: PKCS7())
            data = NSData(bytes: decripted!, length: KeyPair.getPrivateKey().count)
        }
        return  NSString(data: data, encoding: NSUTF8StringEncoding) as! String 
}

There is something that I'm not understand!! 
Can I help-me?

ps:  my encripted data is encripted with length 1024 bits.

**Comment by krzyzanowskim** [comment]
I think you misuse AES, may it be the thing?
- Your data looks like Base64 encoded string, you should decode it first.
- if you key is 1024 bits it's probably not the AES-128 key, you may confuse keys here.

"AES 128-bit block exceeded" error message is not accurate, it's not only about AES-128, it should be "AES block size exceeded!"

**Comment by jamesmartins** [comment]
Thanks. I'll try. But I think that you is correct!!
