### ISSUE TITLE
GCM.Error.fail when decrypting String

### ISSUE THREAD

**Issue by SylvanM** [krzyzanowskim/CryptoSwift#643]
- CryptoSwift version: 0.10.0
- Swift version: 4.2
- Platform (iOS/macOS/Linux/...): macOS
- Installation method (CocoaPods/Carthage/SPM/...): git submodule I think
- Project name: AES-GCM

# Description

> To whom may be concerned: I offer professional support to all my open source projects.

Ok so basically I have encrypted a string using AES-GCM, and when I try decrypting it, I get the error GCM.Error.fail. I looked in the GCM class and apparently this error is thrown then the 'expectedTag' is not equal to the 'computedTag'. I don't even know what that means or if it has anything to do with how I am using the decrypt function, but I've tried changing the padding (if that does anything) to see if that changes it, and it doesn't.

Believe it or not I'm actually pretty unexperienced in cryptography or computer science.

# Steps to reproduce

Initialize a new AES class with a blockmode of gcm with the iv and key, and then try decrypting a string.

Sample code to reproduce the issue:

```swift
import CryptoSwift

// Code goes here

// This is an extension to the String class, so that I can just do string.encrypt(key, iv)

func decrypt(key: String, iv: String) throws -> String {
        do {
            let gcm = GCM(iv: iv.bytes)
            let aes = try AES(key: key.bytes, blockMode: gcm, padding: .pkcs7)

            let decipherbytes = try aes.decrypt(self.bytes)
            let deciphertext = decipherbytes.toHexString()

            return deciphertext
        } catch {
            throw error // Error is: GCM.Error.fail and it has something to do with the expected tag not being the computed tag or something
        }
    }
}

```

**Comment by krzyzanowskim** [comment]
> apparently this error is thrown then the 'expectedTag' is not equal to the 'computedTag'.

that means that the data cannot be verified after decryption. Most likely key is invalid, or any other parameter used during encryption.

**Comment by sam-moshenko** [comment]
Did you manage to solve the issue? I have the same error
