### ISSUE TITLE
AES 256 key generation and save

### ISSUE THREAD

**Issue by taglia3** [krzyzanowskim/CryptoSwift#644]
- CryptoSwift version: 0.9.0
- Swift version: 4.1
- Platform (iOS/macOS/Linux/...):  iOS
- Installation method (CocoaPods/Carthage/SPM/...):  CocoaPods
- Project name: Enterprise project

# Description

Hi,
for a customer's app I've to use AES 256 for storing personal infos.
I've created two utilities for encrypt and decrypt (see code below).

Now I want to generate the 32bytes key. What is the best approach for doing this task?

In my mind I think that the steps will be:

1. check if there is an existing key (**in UserDefaults? I Don't think it's the best approach...**)
2. if exist use it
3. if not exist, generate it (**how can I generate it?**) 
4. save it (**in UserDefaults? I Don't think it's the best approach...**)

I think that the key is unique, so how can I store it after it has been generated? If I don't store it, I will unable to decrypt the saved items.

Could you help me, please?

Matteo

```swift
import CryptoSwift

extension Data {
    
    func aesEncrypt(withKey key: String) -> Data? {
        do {
            let aes = try AES(key: key.bytes, blockMode: .ECB, padding: .pkcs7)
            let bytes = try aes.encrypt(self.bytes)
            return Data(bytes: bytes)
        }
        catch {
            return nil
        }
    }
    
    func aesDecrypt(withKey key: String) -> Data? {
        do {
            let aes = try AES(key: key.bytes, blockMode: .ECB, padding: .pkcs7)
            let bytes = try aes.decrypt(self.bytes)
            return Data(bytes: bytes)
        }
        catch {
            return nil
        }
    }
    
}

```

**Comment by pprraasshhaanntthh** [comment]
@taglia3 how you achieved generating the key ?
