### ISSUE TITLE
Decrypt response always coming nil

### ISSUE THREAD

**Issue by smkdoss73** [krzyzanowskim/CryptoSwift#646]
**Describe the bug**
How to create key. Some time  I got this error like "padding require"
I tried two different way but I am failure 

**My Sample code**

```swift 4.1

import CryptoSwift

 let password: Array<UInt8> = Array("1234".utf8)
        let salt: Array<UInt8> = Array("mysalt".utf8)
        let iv: Array<UInt8> = Array("myiv".utf8)
        let encmsg: Array<UInt8> = Array("encrypted string".utf8)

//        let key = try? PKCS5.PBKDF2(password: password, salt: salt, iterations: 1000, keyLength: 1000, variant: .md5).calculate()
        
        let key = try? HKDF(password: password, salt: salt, variant: .sha256).calculate()
        
        let finaloutput = try? AES(key: key!, blockMode: CBC(iv: iv), padding: .pkcs7).decrypt(encmsg)
        
        print("Final Output", finaloutput)
```

**Expected behavior**

am getting nil response only , Please guide me where am doing wrong 

**Environment (please complete the following information):**
- Swift version: 4.1
- Platform (iOS/macOS/Linux/...): Mac OS
- Installation method (CocoaPods/Carthage/SPM/...): CocoaPods

**Additional context**

Please share me sample code also please... because am new for encryption and decryption

**Comment by krzyzanowskim** [comment]
> Some time I got this error like "padding require"

this comes from the decrypt(), this is because "encmsg" is not a ciphertext at all.
