### ISSUE TITLE
Carthage for Swift 4.2?

### ISSUE THREAD

**Issue by BassApps** [krzyzanowskim/CryptoSwift#650]
Hey I've just opened the Xcode 10.0 beta (10L176w) which gave me the following
`Module compiled with Swift 4.1.2 cannot be imported in Swift 3.4`
I've then set Swift version to 4 and 4.2 which gives
`Module compiled with Swift 4.1.2 cannot be imported in Swift 4.2: `

To be honest I don't know much about all this module and dependency stuff - what can I do to get Carthage build to 4.2? Or is it maybe possible to set my own project to 4.1.2? I'm not in need for any feature in particular, I just want to be able to use the beta

Thanks

**Comment by krzyzanowskim** [comment]
Carthage uses precompiled binary that is build with Xcode 9. Unfortunately there's onway to provide binaries for different Swift version for carthage. You have to skip it and force carthage to build the module from the sources
