### ISSUE TITLE
Problem to compile in Xcode with swift 3.3

### ISSUE THREAD

**Issue by zhouhao27** [krzyzanowskim/CryptoSwift#652]
Got errors when compiling the CryptoSwift in Swift 3.3.

> /Users/myname/Projects/myprofject/Mobile/Pods/CryptoSwift/Sources/CryptoSwift/Generics.swift:23:14: Unknown parameter UInt8 in '_specialize attribute'

My pod file:

`pod 'CryptoSwift', '~> 0.6.9'`

Any idea?

**Comment by krzyzanowskim** [comment]
Use the specific version for Swift 3, see https://github.com/krzyzanowskim/CryptoSwift#swift-versions-support. Remove `~>` from the version specifier.
