### ISSUE TITLE
CryptoSwift with CryptoJS

### ISSUE THREAD

**Issue by craig42** [krzyzanowskim/CryptoSwift#654]
Hi everyone,

**Describe the bug**
I've encrypted a string with Cryptojs in AES but I can't decrypt in CryptoSwift
I have already seen "Compatibility with Cryptojs for AES encryption #596" but it doesn't work for me.
I can't change Cryptojs code because this code is in production.
 
**To Reproduce**
1. Execute javascript code below
2. Copy encryptedText from javascript
3. Try to decrypt text with CryptoSwift 

**Sample code**

```javascript
var CryptoJS = require("crypto-js");
message="hello";
var key = "@!abcdef@";
var result = CryptoJS.AES.encrypt(message, key);
var encryptedText = result.toString();
console.log(encryptedText);
```
```swift
let mdata = Data(base64Encoded: "U2FsdGVkX183L9KMplOrdQv4gxqPQayV+hAbc3vwO5M=
")!
let count = [UInt8](mdata).count
let mbytes = Array([UInt8](mdata)[AES.blockSize ..< count])
let miv = Array([UInt8](mdata)[0 ..< AES.blockSize])
let mkey = try! PKCS5.PBKDF2(password: "@!abcdef@".bytes, salt: miv, iterations: 4096, keyLength: 16, variant: .md5).calculate()
            
let aes = try AES(key: mkey, blockMode: BlockMode.CBC(iv: miv))
let decrypted = try aes.decrypt(mbytes)

```

**Expected behavior**
I have an swift compilation error : "Type 'BlockMode' has no member 'CBC'"

**Environment (please complete the following information):**
- Swift version:  4.1.2
- Platform (iOS/macOS/Linux/...): iOS
- Installation method (CocoaPods/Carthage/SPM/...): Carthage

Regards.

**Comment by krzyzanowskim** [comment]
> Expected behavior
> I have an swift compilation error : "Type 'BlockMode' has no member 'CBC'"

check README for the API. Remove `BlockMode`

**Comment by krzyzanowskim** [comment]
If any default changed since https://github.com/krzyzanowskim/CryptoSwift/issues/596#issuecomment-381341586 somebody needs to re-read CryptoJS sources to get the reason what it does now by default. The most likely key is derived uses different parameters by default (or different function)

**Comment by astrokin** [comment]
if someone decided to use default CryptoJS functionality - i've finally[ make it work on iOS and Android ](https://medium.com/@alex.strok/cross-platform-encrypt-decrypt-ios-android-web-5f4ec26c2cef):)
