### ISSUE TITLE
Swift 4.2/xcode 10 Compatability

### ISSUE THREAD

**Issue by justinkumpe** [krzyzanowskim/CryptoSwift#656]
**Is your feature request related to a problem? Please describe.**
When trying to compile in Xcode 10 I get error: Module compiled with Swift 4.1.2 cannot be imported by the Swift 4.2 compiler. With this compatibility error I can not even compile the app in Xcode 10 (even without updating my app to Swift 4.2

**Describe the solution you'd like**
Would be nice if CryptoSwift was compatible with Swift 4.2.

**Comment by krzyzanowskim** [comment]
I guess this is about Carthage. I'll remove precompiled binary so your Carthage setup can build it with the different version of Xcode

**Comment by krzyzanowskim** [comment]
> Module compiled with Swift 4.1.2 cannot be imported by the Swift 4.2 compiler
actually. 0.11.0 release doesn't have the pre-build binaries. What's the problem then? It looks like you have cached framework somewhere build with a 4.1
