### ISSUE TITLE
if AES-256-CFB update a small size block can'nt return result

### ISSUE THREAD

**Issue by SouHanaQiao** [krzyzanowskim/CryptoSwift#657]
**To Reproduce**
1. 

**Sample code**

```swift

var d: [UInt8] = [3, 12, 104, 109, 46, 98, 97, 105, 100, 117, 46, 99, 111, 109, 0, 80, 99]
    let aes = try AES(key: ShadowSocksEncryptionMethod.Stream.AES_256_CFB.key(password: "12345678"), blockMode: .CFB(iv: cipher.iv), padding: Padding.noPadding)
    var decryptor = try aes.makeDecryptor()
    let de3 = try decryptor.update(withBytes: d[0..<5])
    let de4 = try decryptor.update(withBytes: d[5..<10])

```

**Expected behavior**
Like openssl, the AES-256-CFB mode update less than block size can return the result!
It must give a falg "isLast" for true, or call finish function! But openssl shouldn't be!
In socket bytes stream encryp, sometime get less than a block size data!

**Environment (please complete the following information):**
- Swift version: 
- Platform (macOS): 
- Installation method (SPM): 
- Project name:

**Additional context**

**Comment by krzyzanowskim** [comment]
There was some more work in that area, especially with GCM. I'll close this issue.
