### ISSUE TITLE
Same encryption with android, ios and php

### ISSUE THREAD

**Issue by sinanerkan86** [krzyzanowskim/CryptoSwift#66]
Hi. 
I have a code on Android and it encrypt string with secret key and iv. 
For example asd@asd.com encrypted state is= 975eff7ef2b882bb9b37014ccd10bb0e
I sent this to php and it decrypt it and make sql query as asd@asd.com.
I have to do this on ios. But I can't get the same result with this library. Where can I make mistakes.
Android Code is: 
cipher.init(Cipher.ENCRYPT_MODE, secretkeySpec, ivParameterSpec);
byte[] encrypted = cipher.doFinal(padString(textToBeEncrypted).getBytes());

and i convert in to string.

I have to do same on ios. 
thanks

**Comment by krzyzanowskim** [comment]
Are you sure you pass the same key and IV values to the function ? To reproduce issue you have to pass key and IV here with the code you use it.

**Comment by sinanerkan86** [comment]
Yes I use the same key and iv which is on android and php.

**Comment by krzyzanowskim** [comment]
I'm pretty sure you pass wrong data to the function, however there is no way to check it you without more  details.

It may be
1. wrong input data
2. invalid "convert to string" function

**Comment by sinanerkan86** [comment]
on android: 
String iv = "some_secret_iv";
String secretKey = "some_secret_key";

ivParameterSpec = new IvParameterSpec(iv.getBytes());
secretKeySpec = new IvParameterSpec(secretKey.getBytes(), "AES");

cipher = Cipher.getInstance("AES/CBC/NoPadding");

and i give these ivParameterSpec and secretKeySpec to cipher init function. this encrypt the string.

**Comment by krzyzanowskim** [comment]
how do you use it with CryptoSwift ? Please, can you prepare full working sample, where you think encryption result is invalid? I can't confirm the issue.

**Comment by sinanerkan86** [comment]
let key: [UInt8] = [UInt8]("some_secret_key".utf8)
let iv: [UInt8] = [UInt8]("some_secret_iv".utf8)
let emailUnicode: [UInt8] = [UInt8](userEmail.utf8)
let encryptedEmail = Cipher.AES(key: key, iv: iv, blockMode: .CBC).encrypt(emailUnicode)

let dataEncrypted  = NSData.withBytes(encryptedEmail!)
println(dataEncrypted)

dataEncrypted is not the same on android encrypted string

**Comment by sinanerkan86** [comment]
let key: [UInt8] = [UInt8]("some_secret_key".utf8)

            let iv: [UInt8] = [UInt8]("some_secret_iv".utf8)
            
            let emailUnicode: [UInt8] = [UInt8](userEmail.utf8)

**Comment by krzyzanowskim** [comment]
So you cast String (I assume) to [Uint8]... it won't work as you think it is.

**Comment by sinanerkan86** [comment]
how could i pass secret key and iv to your function?

**Comment by krzyzanowskim** [comment]
https://github.com/krzyzanowskim/CryptoSwift#conversion-between-nsdata-and-uint8

**Comment by sinanerkan86** [comment]
so where can i write "some_secret_iv" or "some_secret_key" on this code as string.

**Comment by sinanerkan86** [comment]
???

**Comment by krzyzanowskim** [comment]
I can't help you. Not enough information to verify this ticket.

To verify such request, please provide working sample code, present what is result and what is expected result. "some_secret_key" is nothing I can verify, it's not even valid key (to short). I'm not able to guess what is your problem here.
