### ISSUE TITLE
Scrypt supported?

### ISSUE THREAD

**Issue by Sajjon** [krzyzanowskim/CryptoSwift#662]
Hey! I was wondering if [Scrypt](https://crypto.stackexchange.com/questions/8159/what-is-the-difference-between-scrypt-and-pbkdf2) is supported? Does not seem to be right?

Three years ago @galinyonchev asked about it in [issue 145](https://github.com/krzyzanowskim/CryptoSwift/issues/145). I will implement this now myself and might do a PR later.

**Comment by krzyzanowskim** [comment]
Looking forward

**Comment by Sajjon** [comment]
@krzyzanowskim regarding Scrypt, I ended up using Trust Wallet Scrypt. It works quite well! It is under MIT license, so we might want to integrate that into CryptoSwift someday, [you can find the implementation here](https://github.com/TrustWallet/trust-keystore/blob/master/Sources/Scrypt.swift). For parameters, however, I prefer the more Swifty naming I use [here](https://github.com/OpenZesame/Zesame/blob/master/Source/Cryptography/Scrypt.swift#L40-L56)

**Comment by krzyzanowskim** [comment]
merged ;)
