### ISSUE TITLE
Should HMAC calculateHash return Optional<[UInt8]> ?

### ISSUE THREAD

**Issue by MainasuK** [krzyzanowskim/CryptoSwift#664]
https://github.com/krzyzanowskim/CryptoSwift/blob/9284485ecd681b04d17e71383d903b5de33516db/Sources/CryptoSwift/HMAC.swift#L40-L53

Due to Digest.*(bytes) always return [UInt8].
Maybe we could remove ? mark of  #`calculateHash` function return  type.

**Comment by krzyzanowskim** [comment]
Makes sense
