### ISSUE TITLE
decrypting json file that was encrypted using openSSL with key and iv returns error "CryptoSwift.AES.Error.dataPaddingRequired"

### ISSUE THREAD

**Issue by 8bitramen** [krzyzanowskim/CryptoSwift#665]
**Describe the bug**
Seemingly correct encrypted file fails to decrypt. 

**To Reproduce**
1. encrypted json file in terminal using openSSL
2. add file to project
3. decryption fails using mentioned parameters. 

**Sample code**

command for terminal openSSL encryption was:

openssl enc -aes-256-cbc -a -K 1234123412341234 -iv 1234123412341234 -in commonKeys.json -out commonKeys2.json 

```
if let url = Bundle.main.url(forResource: "commonKeys2", withExtension: "json") {
            do {
                let data = try Data(contentsOf: url)
                let enc = try data.aesDecrypt(key: "1234123412341234", iv: "1234123412341234")
                let object = try JSONSerialization.jsonObject(with: enc!, options: .allowFragments)
                if let commonKeysDict = object as? [String : Any] {
                    let env = EnvironmentConfigurator(json: commonKeysDict, bundleID: bundleID)
                    environment = Environment(config: env!)
                }
            } catch {
                print("Error!! Unable to parse commonKeys json")
                environment = nil
            }
        }

extension Data {
    func aesDecrypt(key: String, iv: String) throws -> Data? {
        let decrypted = try AES(key: key, iv: iv).decrypt(self.bytes)
        return Data(decrypted)
    }
}


```

**Expected behavior*
even when i try every type of padding, it still gets the dataPassingRequired issue. I haven't been able to find an answer online.

**Environment (please complete the following information):**
- Swift version: xCode 9.4.1, swift 4.2
- Platform (iOS/macOS/Linux/...): macOS
- Installation method (CocoaPods/Carthage/SPM/...): CocoaPods
- Project name: N/A

**Additional context**
data fails due to error "

**Comment by krzyzanowskim** [comment]
> -K/-iv         key/iv in **hex** is the next argument

your value passed to CryptoSwift doesn't look HEX - that may be the issue.

**Comment by amit6061** [comment]
E dataPaddingRequired
