### ISSUE TITLE
Overlapping accesses to 'result', but modification requires exclusive access; consider copying to a local variable

### ISSUE THREAD

**Issue by mohdimran3pg** [krzyzanowskim/CryptoSwift#666]
Hi Team,

I recently build my app code with **Xcode 10.0** version and i got build errors into **SwCrypt.swift** file, Have you guys fixed this error or you are working on it.

**Comment by krzyzanowskim** [comment]
`SwCrypt.swift` ? What is that file

**Comment by mohdimran3pg** [comment]
Hi krzyzanowskim,

I think i added wrong issue here.
