### ISSUE TITLE
Blowfish: Decrypted String always nil

### ISSUE THREAD

**Issue by c1812841** [krzyzanowskim/CryptoSwift#670]
**Describe the bug**
I have only salt and encrypted text from server.
Server uses [https://metacpan.org/pod/Crypt::Blowfish](url) for encrypt text.

My salt jeVNgsSsV9BHtBT3
My encrypted text 41729ce849cce3f0

**Sample code**

```swift
do {
let dec = try Blowfish(key: "jeVNgsSsV9BHtBT3".bytes, padding: .noPadding).decrypt("4fb5f3f8b346d8da".bytes)

            print(String(data: Data(bytes: dec), encoding: .utf8)) // here always nil
            print(String(bytes: dec, encoding: .utf8)) // here always nil
} catch {
}
```

**Expected behavior**
Decrypted string will not nil

**Environment (please complete the following information):**
- Swift version: **4.2**
- Platform (iOS/macOS/Linux/...):  **iOS**
- Installation method (CocoaPods/Carthage/SPM/...): **CocoaPods**
- Project name: noname pet-project

**Comment by krzyzanowskim** [comment]
You can't form a proper UTF-8 string from the ciphertext, this is expected. Ciphertext data != UTF String. You want to convert data to/from string representation, see https://github.com/krzyzanowskim/CryptoSwift#basics

**Comment by c1812841** [comment]
I'm sorry, but I can't figure out how to get the decrypted string?

**Comment by krzyzanowskim** [comment]
There is no single answer, it depends on what you need. I don't know what is expected the "dec". I guess there are some bytes there. Normally, salt != key. You should use exactly the same key as is used on the server side.

**Comment by c1812841** [comment]
...salt != key...
Tell me please, in constructor Blowfish(**key**: String, padding: PaddingProtocol)
**key** - what is it?

**Comment by krzyzanowskim** [comment]
A key is a piece of information (a parameter) that determines the functional output of a cipher. To encrypt and decrypt message, you need use the same key to encrypt and decrypt.

https://en.wikipedia.org/wiki/Key_(cryptography)

**Comment by c1812841** [comment]
Of course, I'm wrong, in my case, **jeVNgsSsV9BHtBT3** is just the **key**, which was used to encrypt the string
