### ISSUE TITLE
GCM tagLength support

### ISSUE THREAD

**Issue by Justin-Jeon** [krzyzanowskim/CryptoSwift#672]
First of all, thanks for your project.

**Is your feature request related to a problem? Please describe.**
I using AES-GCM encryption. 
I would like to change tagLength on encryption time.

The value are fixed to 16 now.
    fileprivate static let tagLength = 16

**Describe the solution you'd like**
Could you make a additional parameter during init GCM or set function to set the value?

**Comment by krzyzanowskim** [comment]
This should be easy, wanna prepare PR?

**Comment by Justin-Jeon** [comment]
Sure, if you make PR, I will get and test. :)
Thanks a lot.

**Comment by krzyzanowskim** [comment]
I've meant if you want to prepare PR :)

**Comment by krzyzanowskim** [comment]
released
