### ISSUE TITLE
Error dataPaddingRequired when AES128 Encrypt

### ISSUE THREAD

**Issue by CoderMaurice** [krzyzanowskim/CryptoSwift#674]
Error dataPaddingRequired when AES128 Encrypt
Is pkcs7padding not the default? Why do I get this error?
I don’t know what the reason is, please help me.

**Sample code**

```swift
let aes = try AES(key: "keykeykeykeykeyk", iv: "drowssapdrowssap") // aes128
let ciphertext = try aes.encrypt(Array("Nullam quis risus eget urna mollis ornare vel eu leo.".utf8)).toBase64()
// ciphertext = h3bFtfONHu1QyC7pvgHUwjNjrIsJrDUnLwnNEeKrmlo1nKbJYc+BNc4Sb+3GnTsa01E1/boaaBt4dEasVx13fg==

let decryptText = try aes.decrypt(ciphertext.bytes).toBase64()?.decryptBase64ToString(cipher: aes)
// Error: dataPaddingRequired

```

- Swift version: 4.2
- Platform (iOS/macOS/Linux/...): iOS
- Installation method (CocoaPods/Carthage/SPM/...): CocoaPods

**Comment by krzyzanowskim** [comment]
> try aes.decrypt(ciphertext.bytes).toBase64()?.decryptBase64ToString(cipher: aes)

why there is another decrypt ```decryptBase64ToString(cipher: aes)``` ? looks like you're trying to  decrypt decrypted data.
