### ISSUE TITLE
about -aes-128-gcm,our gcm caculate the "128" by keysize*8 and if it can be set as prameter?

### ISSUE THREAD

**Issue by skytodmoon** [krzyzanowskim/CryptoSwift#676]
**Is your feature request related to a problem? Please describe.**
I want to use this GCM function, but my key need to be 32 length and also use the 128 aes encrypt.
but in default this AES auto caculate as keysize*8 = 256, any parameter ? or any other method?

**Describe the solution you'd like**
some parameter can be set.

**Comment by krzyzanowskim** [comment]
Key cannot be 32 bytes long and 16 bytes long at the same time. The key is used by AES, hence AES-128-GCM means 16 bytes long key used as a parameter for AES instance. Whatever is 32 bytes long in your question, it's not an AES key.
