### ISSUE TITLE
HOW TO ADD CRYPTOSWIFT TO AN ANDROID PROJECT

### ISSUE THREAD

**Issue by rayflex84** [krzyzanowskim/CryptoSwift#679]
Hello,
please I'm struggling to add cyptoswift in an android project with no success, and there is NO guide what so ever on how to do anywhere
Please help me out.

IOS, it's okay but Android don't know how to do it.
Thanks to all.

**Comment by krzyzanowskim** [comment]
Ref https://github.com/krzyzanowskim/CryptoSwift/pulls

**Comment by krzyzanowskim** [comment]
If you use SwiftPM on Android, the setup should be the same everywhere.

**Comment by rayflex84** [comment]
Hi,
Thanks for your reply,
could you please detail how to do it.
never used swift package manager on android projects unfortunately.
Thanks again

**Comment by krzyzanowskim** [comment]
> never used swift package manager on android projects unfortunately.
me neither. You can look at links here https://github.com/krzyzanowskim/CryptoSwift/pull/651 maybe it will be helpful
