### ISSUE TITLE
iOS 7 compatability

### ISSUE THREAD

**Issue by pieisgood** [krzyzanowskim/CryptoSwift#68]
It would be great if this worked out of the box with iOS 7. As it stands I have a copy of your code inside a project and have changed it to work properly with iOS 7. When incorporating it into a project, without it being a submodule, CryptoSwift namespacing is lost and needs to be accounted for. Also HMAC and P1305 switch cases can't have the same name as your classes HMAC and P1305... a quick fix that could help some folks looking to suport iOS7.

**Comment by krzyzanowskim** [comment]
#16

**Comment by pieisgood** [comment]
right, but copying the files into the project produces build errors. The small changes I outlined fix these compile time errors.

**Comment by krzyzanowskim** [comment]
What do you propose? pull request is welcome to discuss on it.

**Comment by pieisgood** [comment]
I just propose a small ios7 folder that contains the necessary changes to the files that produce build errors for CryptoSwift. So a use can still pull from github but have the option to replace the files with the ios7 compatible ones. I'll put in a pull request later today, thanks!

**Comment by alvinpb** [comment]
@pieisgood any progress on the PR - would like to use it? Otherwise if you could outline the changes?

**Comment by krzyzanowskim** [comment]
https://github.com/krzyzanowskim/CryptoSwift/pull/69
