### ISSUE TITLE
CMS Enveloped Data (RSA + AES 256 CBC)

### ISSUE THREAD

**Issue by LukasPutala** [krzyzanowskim/CryptoSwift#684]
Hi,

I would like to use swiftCrypto to encrypt the message using the rfc5652 standard. I want to use the rsa public key to encrypt it with which I will encrypt the symmetrically key that has previously encrypted the message. I think it's the rfc5652 standard. Final encrypted data should be in the EnvelopedData structure. 

It should be RSA + AES256 CBC encryption.

Can you please help me?

**Comment by krzyzanowskim** [comment]
CryptoSwift doesn't provide RSA
