### ISSUE TITLE
DES/ECB/PKCS5 Padding

### ISSUE THREAD

**Issue by vaibhavjhaveri** [krzyzanowskim/CryptoSwift#686]
- CryptoSwift version: Latest
- Swift version: 4.2
- Platform (iOS/macOS/Linux/...): iOS
- Installation method (CocoaPods/Carthage/SPM/...): Cocoapods

# Description

```
private static const type:String='simple-des-ecb';

public static function encrypt(txt:String, salt:String):String
{
    var key:ByteArray = Hex.toArray(Hex.fromString(salt));
    var data:ByteArray = Hex.toArray(Hex.fromString(txt));
    var pad:IPad = new PKCS5;
    var mode:ICipher = Crypto.getCipher(type, key, pad);
    pad.setBlockSize(mode.getBlockSize());
    mode.encrypt(data);
    data.position = 0;
    //trace("encrypted: " + Base64.encodeByteArray(data));
    return Base64.encodeByteArray(data);
}
```

Above is my code for encryption in ActionScript. I want to reproduce it in Swift. Please help me !!!

**Comment by vaibhavjhaveri** [comment]
@krzyzanowskim Why did you close the issue? 
Atleast you should have commented with some kind of solution or reference

**Comment by krzyzanowskim** [comment]
@vaibhavjhaveri it's not an issue, nor a bug report. You ask me to rewrite code from another language to Swift - this is not the place for this kind of service, hence closed.
