### ISSUE TITLE
Decrypt file non-linearly in streaming mode

### ISSUE THREAD

**Issue by AdamNSmith** [krzyzanowskim/CryptoSwift#687]
- CryptoSwift version: latest
- Swift version: 4
- Platform (iOS/macOS/Linux/...): iOS
- Installation method (CocoaPods/Carthage/SPM/...): CocoaPods
- Project name:

# Description

Hello,
I'm trying to use CryptoSwift to encrypt and decrypt a local mp4 file using stream mode for playback with AVPlayer in iOS. I have implemented the `AVAssetResourceLoaderDelegate` protocol so that AVPlayer will inform me of what block it needs next so that I can then decrypt that block of the mp4 and return it to AVPlayer.

The issue is that AVPlayer doesn't request blocks linearly. When first starting up, it might request bytes 65,536->131,072 and then get 0->65535 and then get 262,144
->327,680, etc. Even if AVPlayer requested all of the chunks linearly starting from the beginning of the file, if the user seeked the video I will run into a similar situation. The issue is that given a CryptoSwift decrypter, if you don't decrypt the blocks in-order then the decryption gets fowled up and the first 16 bytes (which is the IV I'm assuming) of every additional block is incorrect.

I'm aware that streaming decryption works (at least with AES) by using a key and an IV for the first block, and then calculates the following blocks IV based off the previous blocks IV. Given this, is there any way to decrypt a file in a non-linear fashion that's still efficient? 

Thanks, I appreciate the help.

**Comment by krzyzanowskim** [comment]
For that kind of encryption, you need stream cipher, or stream mode of AES (that is a block cipher by itself). AES-CTR would do the job I guess.

With AES-CTR, it is possible to encrypt each part of data independently. You can use seek() method to set the counter value u need to use for a chunk. see: https://github.com/krzyzanowskim/CryptoSwift/blob/288692d159d1babc245a031dc59be759efd531bc/Sources/CryptoSwift/BlockMode/CTR.swift#L94 - still you'd need to know what block number it is, but this is fairly easy, isn't it? (if you know the total lenth, position, and block size = 16 bytes)

**Comment by AdamNSmith** [comment]
Okay, thanks for the info. Out of curiosity, why doesn't the CBC implementing have a seek function? Theoretically, CBC decryption can be parallelized and can decrypt portions of a file, right?
