### ISSUE TITLE
Encrypt decrypt a String 

### ISSUE THREAD

**Issue by guns28** [krzyzanowskim/CryptoSwift#691]
Hi , i'm trying to encrypt and decrypt a String but i'm always getting 
encrypt error : invalidKeyOrInitializationVector

what is the simple way to do it ? thx
here is my code : 

 let password: Array<UInt8> = Array("password".utf8)

        do {
            let encrypted = try ChaCha20(key: Array("key".utf8), iv: Array("iv".utf8)).encrypt(password)
            print(encrypted)
            do {
                let decrypted = try ChaCha20(key: Array("key".utf8), iv: Array("iv".utf8)).decrypt(encrypted)
                print(decrypted)
            } catch {
                //handle error
                print("decrypt error : \(error)")
            }
        } catch {
            //handle error
            print("encrypt error : \(error)")
        }

**Comment by krzyzanowskim** [comment]
Each cipher has a requirement for parameters. `iv` should be 8 or 12 bytes long for chacha, and `key` should be 32 bytes long in this case.

**Comment by guns28** [comment]
thank you now i have this : 
encrypted : [134, 7, 197, 216, 45, 239, 33, 240]
decrypted : [112, 97, 115, 115, 119, 111, 114, 100]

Sorry but how do i get my first value  let password: Array = Array("password".utf8)

thx

**Comment by guns28** [comment]
it's done thx.
