### ISSUE TITLE
How do you generate a SecretKeySpec or SecretKey (as used in java) with CryptoSwift

### ISSUE THREAD

**Issue by VinceBezzina** [krzyzanowskim/CryptoSwift#692]
**Describe the bug**

**To Reproduce**
1. 

**Sample code**

```swift



```

**Expected behavior**

**Environment (please complete the following information):**
- Swift version: 
- Platform (iOS/macOS/Linux/...): 
- Installation method (CocoaPods/Carthage/SPM/...): 
- Project name:

**Additional context**

**Comment by VinceBezzina** [comment]
Trying to port some code to Swift

**Comment by krzyzanowskim** [comment]
> How do you generate a SecretKeySpec or SecretKey (as used in java) with CryptoSwift

I don't
