### ISSUE TITLE
AES 256 ECB  not work with 64 character key

### ISSUE THREAD

**Issue by krutitrivedi** [krzyzanowskim/CryptoSwift#693]
**Describe the bug**
hi!, i'm trying to encrypt string using AES 256 with ECB mode with pkcs5 padding 
can you please provide me sample code for that my key length is 64 character and i receive error of invalidKeySize
**To Reproduce**
1. 

**Sample code**

```swift
extension String {
    
    // encrypt the string
    func aes_Encrypt(AES_KEY: String) -> String {
        var result = ""
        do {
            let key: [UInt8] = Array(AES_KEY.utf8) as [UInt8]
            let aes = try! AES(key: key, blockMode: ECB() as BlockMode, padding: .pkcs5)
            let encrypted = try aes.encrypt(Array(self.utf8))
            result = encrypted.toHexString()
            print("AES Encryption Result: \(result)")
        } catch {
            print("Error: \(error)")
        }
        return result
    }
    
    // decrypt the string
    func aes_Decrypt(AES_KEY: String) -> String {
        var result = ""
        do {
            let encrypted = self
            let key: [UInt8] = Array(AES_KEY.utf8) as [UInt8]
            let aes = try! AES(key: key, blockMode: ECB() as BlockMode, padding: .pkcs5) // AES128 .ECB pkcs7
            let decrypted = try aes.decrypt(Array(hex: encrypted))
            result = String(data: Data(decrypted), encoding: .utf8) ?? ""
            print("AES Decryption Result: \(result)")
        } catch {
            print("Error: \(error)")
        }
        return result
    }
    
}


```

**Expected behavior**
2019-01-23 12:11:47.814392+0530 Saccess Scanner[5753:1478399] Fatal error: 'try!' expression unexpectedly raised an error: CryptoSwift.AES.Error.invalidKeySize: file /BuildRoot/Library/Caches/com.apple.xbs/Sources/swiftlang_Fall2018/swiftlang_Fall2018-1000.11.42/src/swift/stdlib/public/core/ErrorType.swift, line 184

**Environment (please complete the following information):**
- Swift version: 4.1
- Platform (iOS/macOS/Linux/...): 
- Installation method (CocoaPods/Carthage/SPM/...): 
- Project name:

**Additional context**

**Comment by krzyzanowskim** [comment]
AES 256 requires 32bytes (256 bits) long key, therefore you can't use 64bytes long key.
