### ISSUE TITLE
Please help converting 2 lines of Java hashing method to swift.

### ISSUE THREAD

**Issue by junweimah** [krzyzanowskim/CryptoSwift#696]
My android developer has this in a function which I need to have the exact output. But I cant get it right after trying for hours using this library.

Java code: 

```
md.update(salt);
return md.digest(input);
```
`md` is using the `SHA-512` algorithm 
`salt` and `input` is type of `byte[]`, which I can get it as `salt.bytes` in swift.

But what is the 2 lines is swift? 

I have been trying with these codes from the doc but still cant get the right output as Android: 

```
let bytes:Array<UInt8> = [0x01, 0x02, 0x03]
let digest = input.md5()
let digest = Digest.md5(bytes)
let data = Data(bytes: [0x01, 0x02, 0x03])

let hash = data.sha512()    
do {
  var digest = MD5()
  let partial1 = try digest.update(withBytes: [0x31, 0x32])
  let partial2 = try digest.update(withBytes: [0x33])
  let result = try digest.finish()
} catch { }
```

So far I have this: 

```
var digest = MD5()
let updatedSalt = try digest.update(withBytes: byteOfSalt)
let result = try digest.finish(withBytes: updatedSalt)
```

but by printing the base64 of `result`, it is not the same as the one from Android

Please help
Thanks in advance

**Comment by krzyzanowskim** [comment]
The code looks good. I don't know the input values to compare. Especially I don't see full Java code to make any comparition.

**Comment by junweimah** [comment]
Hi thanks for the reply. I'll try to provide more Java code and the input string.

```
String password  = "12345678"
String salt  = "12345"

saltByte = salt.getBytes(StandardCharsets.UTF_8);
passwordByte = password.getBytes(StandardCharsets.UTF_8);

md = MessageDigest.getInstance("SHA-512", "SC");

md.update(saltByte);
String digest = md.digest(passwordByte);

String base64HashOfDigest = org.spongycastle.util.encoders.Base64.toBase64String(digest) 
//bnhO4jFWKBnxwBlowI2zlaF0cLRFlDFIBLI1jvRI94Ohq6KkvhZSm+HoC6bzEPaIFzjBzGx3kOZlLdnNlNJaVg==
```

This is the Java code, spongycastle is a library for android, but basically that line is just to get the base64, just like our `.toBase64()`

I cant get the string like above. Can you help?

Thanks

**Comment by krzyzanowskim** [comment]
> var digest = MD5()

u need `SHA2(variant: .sha256)` here, not `MD5`

**Comment by junweimah** [comment]
Thanks but I am still not getting the same string.

This is my swift code: 

let password = "12345678"
let salt = "12345"

let byteOfPassword = password.bytes
let byteOfSalt = salt.bytes

var sha512 = SHA2(variant: .sha512)
let updatedSalt = try sha512.update(withBytes: byteOfSalt)
let result = try sha512.finish(withBytes: updatedSalt)            
print("result: \(result.toBase64())")
//Qzc0r7JRrD4uuKX3yqVa2BinnM/Kvn7huD/7CPO9IOxT5BduCafnXoPxiWspsHdtTQr7KW34/4wAW66cqW5b1w==

**Comment by krzyzanowskim** [comment]
> let result = try sha512.finish(withBytes: updatedSalt) 

should be
```
let result = try sha512.finish(withBytes: byteOfPassword) 
```

**Comment by junweimah** [comment]
I tried and it is still not the same. 

If I were to do that doesn't it mean that the line `let updatedSalt = try sha512.update(withBytes: byteOfSalt)` is not being used?

**Comment by krzyzanowskim** [comment]
`updatedSalt` is partial digest value. I don't know, I can't run this Java code, neither can't verify the Java output.

Correct value for hash:

```swift
let result = "1234512345678".sha512() // hex value
let result = Digest.sha512("1234567890123456".bytes).toBase64() // base64
```

whatever is the output from Java, should be documented or something.
