### ISSUE TITLE
Swift 5

### ISSUE THREAD

**Issue by ViniciusScorsatto** [krzyzanowskim/CryptoSwift#699]
Hello

Xcode 10.2 Beta now comes with Swift 5. Any plans to update it?

Thanks a lot!

**Comment by krzyzanowskim** [comment]
AS far as I'm concerned, so far, it compiles without errors, isn't it?

**Comment by ViniciusScorsatto** [comment]
Hey... 

When trying to convert to Swift5 I am getting this issue, Maybe I am missing something..


Showing All Messages

Module compiled with Swift 4.2.1 cannot be imported by the Swift 5.0 compiler: XXXX/Carthage/Build/iOS/CryptoSwift.framework/Modules/CryptoSwift.swiftmodule/arm64.swiftmodule

Thank you a lot for the code and for answering as well

**Comment by krzyzanowskim** [comment]
rm -rf XXXX/Carthage

**Comment by krzyzanowskim** [comment]
branch: https://github.com/krzyzanowskim/CryptoSwift/tree/swift5
