### ISSUE TITLE
crc32

### ISSUE THREAD

**Issue by DingSoung** [krzyzanowskim/CryptoSwift#7]
crc32根据Poly,初始值,倒序输入,输出和异或的不同会有很多不同的标准，你可以参照[这个](https://github.com/DingSoung/DDT/blob/master/crc/crc32.h) 来完善crc32

**Comment by vincentsong** [comment]
Hi Marcin, do you know how to get the CRC32 of a file, not by reading to memory?

**Comment by krzyzanowskim** [comment]
@vincentsong this is separate question. You can initiate NSData from file with NSDataReadingMappedIfSafe

**Comment by krzyzanowskim** [comment]
the polynomial is documented now
