### ISSUE TITLE
Could not find member 'CBC'

### ISSUE THREAD

**Issue by Naoto-Ida** [krzyzanowskim/CryptoSwift#70]
Hi, I'm encountering a problem where Xcode cannot find the member "CBC".

Here is part of my code using it:
```
let key : [UInt8]       = [UInt8](_AES_KEY.utf8),
     iv : [UInt8]        = [UInt8](_AES_IV.utf8)
let aes = AES(key: NSData.withBytes(key), iv: NSData.withBytes(iv), blockMode: .CBC)
```

I'm using Xcode 6.3.2, with CryptoSwift ver. 0.0.10. Anybody have the same issue? I will try to find a fix.

**Comment by Naoto-Ida** [comment]
Sorry, I think I realized the change. I'll close it.

Can you explain whv the first parameters for AES() changes from NSData to [UInt8]?
I'm not very familiar with encrypting technologies. Thanks!

**Comment by krzyzanowskim** [comment]
it's a matter of decision. From now on array of bytes is a base data structure for the framework instead of NSData.

**Comment by Naoto-Ida** [comment]
@krzyzanowskim okay, thanks for clarifying. I really enjoy your work. Thanks.
