### ISSUE TITLE
Have a lot of \0 characters after decrypting AES 256 with zeroPadding

### ISSUE THREAD

**Issue by vanhung1710** [krzyzanowskim/CryptoSwift#700]
**Describe the bug**
I used your library for my iOS project. But I met this issue.
When I encrypted a short text by using AES 256 with ZeroPadding CBC and I decrypted to get original text. The decryted text has a lot of \0 characters. But When I use Java, I do not meet this issue.
This is my code. You just call testAES() function to see this issue.
**To Reproduce**

    private let ivBytes: Array<UInt8> = Array(repeating: 0, count: 16)

    private func testAES(){
        let msg = "https://drive.google.com/uc?export=download&id=1S_4cOMM0vH8VexApnS5AT5kNzy-FFZ2X"
        let pass = "Abc123"
        let encrypted = encrypt(password: pass, text: msg)
        print("Encrypted=\(encrypted!)")
        let decrypted = decrypt(password: pass, base64: encrypted!)
        print("Decrypted=\(decrypted!)")
    }

    private func encrypt(password: String, text: String) -> [UInt8]? {
        do {
            let sha256 = password.bytes.sha256()
            let aes = try AES(key: sha256, blockMode: CBC(iv: ivBytes), padding: .zeroPadding)
            let ciphertext = try aes.encrypt(Array(text.utf8))
            return ciphertext
        } catch {
            print(error)
        }
        return nil
    }
    
    private func decrypt(password: String, base64: [UInt8]) -> String? {
        do {
            let sha256 = password.bytes.sha256()
            let aes = try AES(key: sha256, blockMode: CBC(iv: ivBytes), padding: .zeroPadding)
            let cipherText = try aes.decrypt(base64)
            let result = String(bytes: cipherText, encoding: .utf8)
            return result
        } catch {
            print(error)
        }
        return nil
    }

**Expected behavior**
   Give original text after decrypting

**Environment (please complete the following information):**
- Swift version: 4.2.1
- Platform (iOS/macOS/Linux/...): macOS
- Installation method (CocoaPods/Carthage/SPM/...): CocoaPods
- Project name:

**Additional context**

**Comment by krzyzanowskim** [comment]
> When I encrypted a short text by using AES 256 with **ZeroPadding** CBC and I decrypted to get original text. The decryted text has a lot of **\0 characters**.

Saying ZeroPadding removal is not applied after decryption? Can you debug it in ZeroPadding class?

**Comment by vanhung1710** [comment]
I have to write a function to remove all ending zero bytes in decrypted byte array. :((

**Comment by krzyzanowskim** [comment]
https://github.com/krzyzanowskim/CryptoSwift/blob/b3614c330728868aa49ad99072fdc26bebe86b77/Sources/CryptoSwift/Padding.swift#L37
