### ISSUE TITLE
hi.

### ISSUE THREAD

**Issue by masoudroosta** [krzyzanowskim/CryptoSwift#702]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by masoudroosta** [comment]
hi. 
I try to use your pod for decryption aes 256 cbc with 32 bit iv. but in your syntax iv length must be 16 bit.
how can I do decryption aes 256 cbc by 32 bit iv? 
thanks

**Comment by krzyzanowskim** [comment]
> how can I do decryption aes 256 cbc by 32 bit iv?

AES uses 128-bit size IV, that is the size of the AES block. If your algorithm needs 32 bit or 32 bytes long IV, then it's most likely not AES. Can't help with that.
What is the software encrypts with such IV?
