### ISSUE TITLE
No Update in HMAC?

### ISSUE THREAD

**Issue by weiqj** [krzyzanowskim/CryptoSwift#705]
Every crypto package I use in every other language has Update method in HMAC.
However I can't seem to find it in CryptoSwift.
Also unlike AES, HMAC doesn't accept slice as parameter.
That alone leaves HMAC very slow because user has to make an extra copy of the content.
Is there any plan for that?

Thanks

**Comment by krzyzanowskim** [comment]
It doesn't copy as long as the input is not modified so I wouldn't bother that. The HMAC is slow by definition (it's acceptable in release build though).

If you think of calculating HMAC along the way... it seems feasible. Want to work on such change?
