### ISSUE TITLE
too long time to decrypt video

### ISSUE THREAD

**Issue by mahdifarshid** [krzyzanowskim/CryptoSwift#708]
Hello
I used the CryptoSwift repository for the project
To decode a video file that is downloaded from the server
My problem is that decoding a 1.5 megabyte video takes 10 seconds while the Android version is crypto. Easily decrypted
Is there a bug of my code

//
//  VideoChapterVC.swift
//  jazire
//
//  Created by farshid on 3/3/19.
//  Copyright © 2019 com.arkadevelope.jazire1. All rights reserved.
//

import Foundation
import UIKit
import AVKit

class VideoChapterVC:UIViewController{
    
    var url = ""
    var keyArray = Array<UInt8>(arrayLiteral: 33, 113, 65, 122, 120, 64, 35, 82, 118, 48, 109, 37, 75, 122, 94, 65)
    
    @IBOutlet var videoView:VideoView!

    func DecryptVideo() {
        do {
            let data = NSData(contentsOfFile: self.url)
            
            if let dataS = data {
                DispatchQueue.global(qos: .background).async {
                    do {
                        let data = Data(referencing: dataS)
                        let bytearray = data.toArray(type: UInt8.self)
                        let aes = try AES(key: self.keyArray, iv: self.keyArray)
                        
                        let out = try aes.decrypt(bytearray)
                        
                        
                        var data2 = NSData(bytes: out, length: out.count)
                        
                        let documentsUrl = FileManager.default.urls(for: .cachesDirectory, in: .userDomainMask).first!
                        
                        let filename: NSString =  (self.url as NSString).lastPathComponent as NSString
                        let pathExtention = filename.pathExtension
                        let pathPrefix = filename.deletingPathExtension
                        
                        let fileURL = documentsUrl.appendingPathComponent(pathPrefix).appendingPathExtension(pathExtention)
                        
                        let nsdata = NSData(bytes: out, length: out.count)
                        let ada = Data(referencing: nsdata)
                        try ada.write(to: fileURL, options: .atomic)
                        
                        print("fileURL  \(fileURL)")
//
                        
                        self.videoView.configure(url: fileURL.description)
                        self.videoView.isLoop = true
                        self.videoView.play()
                        
//                        let player = AVPlayer(url: fileURL)
//                            var playerController = AVPlayerViewController()
//                            playerController.player = player
//                            self.present(playerController, animated: true, completion: {
//                            player.play()
//                        })
                        
                    
                        
                    } catch {
                        print("error \(error)")
                    }
                }
            }
        } catch {
            print("Error info: \(error)")
        }
        
        if url == "" {
            Toast.Make(self.view, "خطایی در دانلود رخ داد", 3.0)
        } else {
            
        }
    }
    
    
    override func viewDidLoad() {
        self.DecryptVideo()
     
    }
    
}

**Comment by krzyzanowskim** [comment]
is this a "release" build?

**Comment by mahdifarshid** [comment]
i use this version
0.14.0
i check new version and tell you

**Comment by krzyzanowskim** [comment]
I've meant "Release" configuration.

**Comment by mahdifarshid** [comment]
no its not release its debug only
are they have deference between release and debug version

**Comment by krzyzanowskim** [comment]
Swift build with Debug configuration can be 1000x slower.
