### ISSUE TITLE
Swift 5.0

### ISSUE THREAD

**Issue by YashJadhav** [krzyzanowskim/CryptoSwift#709]
@krzyzanowskim Please update CryptoSwift to latest verision of swift 5.0.

Thanks in advance.

**Comment by krzyzanowskim** [comment]
it is updated already

**Comment by YashJadhav** [comment]
Hi Krzyzanowskim/Cryptoswift,

When I build my project, it gives 5-6 warnings. My project language is
Swift 5.0.

As you say its already updated, why is it giving warnings.








Thanks & Regards,
Yash A. Jadhav
 iOS Developer
(+91)-8976255103

**Comment by krzyzanowskim** [comment]
you may not use latest version, or your configuration may be specific. I don't know that

**Comment by YashJadhav** [comment]
I am using pod 'CryptoSwift' to install CryptoSwift via cocoapods.








Thanks & Regards,
Yash A. Jadhav
 iOS Developer
(+91)-8976255103

**Comment by krzyzanowskim** [comment]
you need to use v. 1.0.0
