### ISSUE TITLE
String extension `.md5()` -- should it return lowercase?

### ISSUE THREAD

**Issue by LoganWright** [krzyzanowskim/CryptoSwift#71]
If I run crypto on identical strings like so (a is CommonCrypto, b is CryptoSwift): 

```Swift
        let string = "somerandomstringtohash"
        let a = hashable.md5
        let b = hashable.md5()!
        println("a: \(a)")
        println("b: \(b)")
```

I get a readout like so: 

>a: 7c9c695f659046b137f36aa9507e7730
b: 7C9C695F659046B137F36AA9507E7730

-----

Now, I am not the most up to date on security measures, but I need an md5 has for the marvel api, and it only works with lowercase strings.  I get around this by making it lowercase, but I wanted to point it out for you in case it's something that should be fixed.  If it's supposed to be this way, just ignore me :)

Thanks!

**Comment by krzyzanowskim** [comment]
actually it doesn't matter. It's just a string representation of bytes. Sometimes people use lowercase, other time uppercase, sometimes It is preceded by "0x". Although... it may be that lowercase representation is more popular, in this case yes, we should change it. Will you prepare pull request for that ?

**Comment by DaveWoodCom** [comment]
Personally, I'd be cautious about implementing this change since it could break existing users of the library. Any one using the library already that is expecting it to be lower case for comparisons will have already converted the case in their code.

**Comment by krzyzanowskim** [comment]
yea me too.
On the other hand better change it now than later. I did quick check, and seems that lowercase string is more popular.

**Comment by ctews** [comment]
+1 for changing this, had the same troubles here! :)

**Comment by alessiomaffeis** [comment]
Stumbled into the same problem too... +1

**Comment by krzyzanowskim** [comment]
There is PR https://github.com/krzyzanowskim/CryptoSwift/pull/72 but it's not ready to merge. If not updated soon I'll apply this change by myself.

**Comment by krzyzanowskim** [comment]
The work is done.

**Comment by alessiomaffeis** [comment]
🎉

**Comment by robinvpersie** [comment]
I got the same problem, how to get the upper, thanks
