### ISSUE TITLE
how to decrypt video in stream state

### ISSUE THREAD

**Issue by mahdifarshid** [krzyzanowskim/CryptoSwift#711]
hi
 my video size is very large. for this cause decrypting my videos takes too long time

how to decrypt the video in stream state?

**Comment by macroday** [comment]
@mahdifarshid  Do you get any alternatives or solution for the same?

**Comment by krzyzanowskim** [comment]
You can experiment with AES CTR mode

**Comment by blazeios** [comment]
I am using AES algorithm for decryption process using multiple files. So that it takes more time to decrypt. Meanwhile in Android the same AES algorithm takes less time to decrypt of the same files, because they increase buffer size upto 512/1024 something. So I need to know could able to increase the buffer or speed up decryption process of multiple files.

Thanks in Advance.

**Comment by krzyzanowskim** [comment]
The "buffer" size is up to you when you use Updaptable https://github.com/krzyzanowskim/CryptoSwift#incremental-updates

PS. also, always check Release build. Debug configuration is way slower than anything else.

**Comment by blazeios** [comment]
thanks krzyzanowskim...
how can i alter this one 
public func decrypt(_ bytes: ArraySlice<UInt8>) throws -> Array<UInt8> {
        if blockMode.options.contains(.paddingRequired) && (bytes.count % AES.blockSize != 0) {
            throw Error.dataPaddingRequired
        }

        var oneTimeCryptor = try makeDecryptor()
        let chunks = bytes.batched(by: AES.blockSize)
        if chunks.isEmpty {
            throw Error.invalidData
        }

        var out = Array<UInt8>(reserveCapacity: bytes.count)

        var lastIdx = chunks.startIndex
        chunks.indices.formIndex(&lastIdx, offsetBy: chunks.count - 1)

        // To properly remove padding, `isLast` has to be known when called with the last chunk of ciphertext
        // Last chunk of ciphertext may contains padded data so next call to update(..) won't be able to remove it
        for idx in chunks.indices {
            out += try oneTimeCryptor.update(withBytes: chunks[idx], isLast: idx == lastIdx)
        }
        return out
    }

**Comment by krzyzanowskim** [comment]
I'm afraid this kind of support is beyond the CryptoSwift support I can provide here.
