### ISSUE TITLE
Enhancement of Decryption process for multiple files in AES

### ISSUE THREAD

**Issue by Sivavigneshios** [krzyzanowskim/CryptoSwift#713]
I am using AES algorithm for decryption process using multiple files. So that it takes more time to decrypt. Meanwhile in Android the same AES algorithm takes less time to decrypt of the same files, because they increase buffer size upto 512/1024 something. So I need to know could able to increase the buffer or speed up decryption process of multiple files. 

Thanks in Advance.

**Comment by krzyzanowskim** [comment]
This https://github.com/krzyzanowskim/CryptoSwift#incremental-updates is the only thing I can think about
