### ISSUE TITLE
Publish v 1.0 to cocoapods

### ISSUE THREAD

**Issue by arkdan** [krzyzanowskim/CryptoSwift#714]
any plans?

**Comment by krzyzanowskim** [comment]
I did, I remember I did. It should be there
![Screenshot 2019-04-11 at 15 22 26](https://user-images.githubusercontent.com/758033/55960728-a3c07300-5c6d-11e9-9994-d0ea65ef485f.png)

**Comment by arkdan** [comment]
you did!
