### ISSUE TITLE
Swift 4.2/Xcode 10.2 Compiler Errors

### ISSUE THREAD

**Issue by sumagowda** [krzyzanowskim/CryptoSwift#715]
After upgrading Xcode to 10.2
I changed that Target Settings for CryptoSwift to Swift 4.2
But I am still getting 33 compiler errors for CryptoSwift.
I restarted my Xcode (as well as macbook) ...several times to no avail.
Please advice.

**Comment by sumagowda** [comment]
I am using pod 'CryptoSwift', '0.15.0'

**Comment by sumagowda** [comment]
I also deleted ~/Library/Developer/Xcode/DerivedData  ...still getting 33 compiler errors related to CryptoSwift.

**Comment by krzyzanowskim** [comment]
🤷‍♀️
- delete Pods directory
- Re-check it uses SWIFT_VERSION 4.2
- looks good at this end

<img width="768" alt="Screenshot 2019-04-12 at 21 08 01" src="https://user-images.githubusercontent.com/758033/56060424-182b0d00-5d67-11e9-95c8-164ebde24f65.png">

**Comment by sumagowda** [comment]
Thank you for quick response. I did deleted Pod directory & reinstalled it.
Now I am getting a new error "No such module 'CryptoSwift'"
I don't see the module in targets section & when i try to add it in build phases ...i can't find the framework or target. Although the folder for source code (of CryptoSwift) is there.

**Comment by krzyzanowskim** [comment]
Looks like an issue with CocoaPods integration. Try `pod deintegrate` and `pod cache clean`.

**Comment by sumagowda** [comment]
I tried but still getting same error. Where can i find the CryptoSwift.framework file ...it looks like i will need to add that in target files...
I am not able to find that file even after pod install.

**Comment by sumagowda** [comment]
Sorry I found what the problem is. It looks like the system is confusing between the files on my laptop & files that are on iCloud Drive Archive (which is an old version).
Thank you for the help. It's resolved.
