### ISSUE TITLE
AES encryption in Java and Decryption in Swift >> CryptoSwift

### ISSUE THREAD

**Issue by yoursnasir** [krzyzanowskim/CryptoSwift#719]
**Describe the bug**
I am using Java Code to encrypt text and generate Secret Key. Reason : My server side code should be responsible for encryption. 
Using Same Secret Key, I am trying to encrypt in Swift using CryptoSwift. I am getting error as
"Thread 1: Fatal error: Unexpectedly found nil while unwrapping an Optional value". My key getting generated from Java is : "gp0P/helHkSwxdjqYVV7MQ=="

It is failing to convert decrypted bytes into String. It is getting null there. 

Error on below line : 
 let decryptedString = String(bytes: decrypted, encoding: String.Encoding.utf8)!
 

**To Reproduce**
1.  Use Below Java Code to Generate Secret Key. 

        KeyGenerator keyGenerator = KeyGenerator.getInstance("AES");
            SecretKey secretKey = keyGenerator.generateKey();
            byte[] raw = secretKey.getEncoded();
            SecretKeySpec skeySpec = new SecretKeySpec(raw, "AES");
            Cipher cipher = Cipher.getInstance("AES/CBC/PKCS5Padding");
            cipher.init(Cipher.ENCRYPT_MODE, skeySpec, new IvParameterSpec(new byte[16]));
            encryptedTextString = android.util.Base64.encodeToString(cipher.doFinal(text.getBytes(Charset.forName("UTF-8"))), android.util.Base64.DEFAULT);
            Log.i("Secret key ",raw.toString());

Use below code to Decrypt it in Swift : 

```swift
             let key1 = "gp0P/helHkSwxdjqYVV7MQ=="
            let iv1 = "kdf67398DF7383fd"
            let input = "ay24KXf8Ts8d0zNfgTe+JKphynjJBQCvhIGSb49C3n4oCurX3261mo9D9+Ppcsc4NyLNsDWqkxV4\nrPt80OU/opHIOjbaUqM0hhgnpreXd4C8M2NR+eJxeEU/ad2vRR5lbLI0m9LGIDb+MOzU9N7G7Z0I\nKk52btD5faAh+0eofNzPk9kOdA7lAAaxhX2Ag4GRcEM2ygYZg7Ut5ejjwXN5CMqV6IcVLRcLExK+\nS3XgiGglO2tLAe05yVdWBJA/Di3Ul8D3QeQL+Z0X90XEAcekfAYPdeTppmWipF88XPJDDCeR8FLc\nZNyytOpbvpeDeFCC3KXnssz+6mWQOhOOi9C5g50AbbCDyIJ2HdvptUtJ9s1j3KcTj/t9S6SOmkRA\nAGUNFA728Fsv0asDiQlUzBhNmP8NcpfJv2GG99k1TNFIPZUoboMAYw0EcwWq8th44wNeBTd1HISr\n80UFbee9547ZBSJ7zowi6t3TWYM+Av2oKZtA3+MNR/kquRe0nMt06nCYimwemU4TmcHJHoprXlpP\noWXpUiBFbVXDXZTYqRZR/XTmRc3G4n14yIki4xwLDvU44sA+84OGC9FTl9xCt/zqJ/4naJhLS0Y6\nInpJAy0JlBDYZ8wTZgvR8qU9R8DW1qBEPRUpGGtW3Cme1P8/Iak4fztWSDZXGmQVsy69ELtsl7kK\nuSXJWVQCclHPutPXTOW76lh/SOF/yiMbJO50oOc/SoKiHyJnfci27iTEGLeZtmnj/zstfIm9mxOQ\n1vaZnTZ/ydMYxaj0CPw4K1Mdbf0q25VhBIG6bMIttNGHOvaFFjvcAqaBsn2unYcB6fsbe+v2jwp/\n5b55LxavHVdqZ+QL8dbUi+O9yW8IFIN2AvsUC7cPFOZMnNy0ZGYY87S5vXV/W5xQIB3M/KEo7+NB\nxjiOXDP9tm/LrUBwY76xhPAVrfQcmrSGnKh39pJRRyuXjiELbPgWoU09ooOqLThQei+SJQ==\n"
            
            do {
                guard let data = Data(base64Encoded: input, options: Data.Base64DecodingOptions.ignoreUnknownCharacters) else {
                    return false
                }
                let iv = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0] as [UInt8]
                let keyval: Array<UInt8>  = Array(key1.utf8);
                let aes =  try! AES(key: keyval, blockMode: CBC(iv: iv), padding: .pkcs5)
                let decrypted = try aes.decrypt( arrayData)
                //let decData = NSData(bytes: decrypted, length: Int(decrypted.count))
                //let result = NSString(data: decData as Data, encoding: String.Encoding.utf8.)
               // let str = String(result!)
                let decryptedString = String(bytes: decrypted, encoding: String.Encoding.utf8)! // Error on this line 
                print(decryptedString)

            } catch {
                print(error)
            }


```

**Expected behavior**

Exception is on below line of code : 

 let decryptedString = String(bytes: decrypted, encoding: String.Encoding.utf8)!

**Environment (please complete the following information):**
- Swift version:  4.2
- Platform (iOS/macOS/Linux/...):  macOS
- Installation method (CocoaPods/Carthage/SPM/...):  pod install
- Project name: CryptoSwift 

**Additional context**

**Comment by krzyzanowskim** [comment]
is 'decrypted' suppose to be valid string bytes? if not, you most likely should apply  base64 encoding to it first.

**Comment by magneter** [comment]
Hi.I have a same problem . I try to decode the base64 first ,But it still didnot work.I get the error ,need padding.
