### ISSUE TITLE
AES Encryption and Decryption by CryptoSwift 1.0.0

### ISSUE THREAD

**Issue by MohamedLamrabet** [krzyzanowskim/CryptoSwift#720]
Hi there!

I am using "CryptoSwift 1.0.0" and Swift 5 with Xcode 10.2 for an iOS app, CryptoSwift Encryption works fine, and also my PHP server Encryption and Decryption.

But I am getting this error:

```Error Domain=CryptoSwift.AES.Error Code=1 "(null)"```
```Fatal error: Unexpectedly found nil while unwrapping an Optional value```

when this method is getting executed:

``` let cipher = try aes.decrypt(Array(cryptedData))```

This is my code:

**Encryption function**

```
    static func cryptArtisan(strClair: String) -> [String:String] {
        let key = generateStringKey()
        var cryptedMessage = ""
        var cryptedKey = ""
        do {
            let aes = try AES(key: Array<UInt8>(key.utf8), blockMode: ECB(), padding: .pkcs5) // aes128
        
            let ciphertext = try aes.encrypt(Array(strClair.utf8))
            cryptedMessage = ciphertext.toBase64()!
            
            let publicKey = try PublicKey(derNamed: "public")
            let clear = try ClearMessage(string: key, using: .utf8)
            let encrypted = try clear.encrypted(with: publicKey, padding: .PKCS1)
            cryptedKey = encrypted.base64String
        } catch { }
        
        cryptedMessage = cryptedMessage.replacingOccurrences(of: "+", with: "%2B")
        cryptedKey = cryptedKey.replacingOccurrences(of: "+", with: "%2B")

        return ["msg":cryptedMessage, "key":cryptedKey, "clairKey": key]
    }
```

**Decryption function**
```
    static func decryptArtisan(cryptedMessage: String , key:String) -> String? {
        var clairMessage:String? = nil;
        
        if let cryptedData = Data(base64Encoded: cryptedMessage) {
            do {
                let aes = try AES(key: Array<UInt8>(key.utf8), blockMode: ECB(), padding: .pkcs5) // aes128
                let cipher = try aes.decrypt(Array<UInt8>(cryptedData))
                clairMessage = String(bytes: cipher, encoding: .utf8)
            }catch{
                let error = error as NSError
                print(error)
            }
        }
        
        return clairMessage
    }
```
**Environment**
- Swift version:  Swift 5
- Platform :  iOS
- Installation method: CocoaPods

**Comment by krzyzanowskim** [comment]
Could you please make it short (3-4 lines) to demonstrate the issue, with all input data? I can't tell what is the problem. Also, try to not cast error to NSError, you may notice an actual error that was throw.

**Comment by MohamedLamrabet** [comment]
Thank you for your quick response.

I use the ECB algorithm on my php server and on my android application and it all works very well, and I want to apply this algorithm for the iOS version.

the encryption feature of CryptoSwift works for me, because I can decrypt the message on my server and see a clear correct message, so the answer that returned by the server was well decrypted, but when I tried to decrypt it by CryptoSwift method, I encounter an error.

this this my code with input data:

**Encryption function**

`cryptedMessage = 1e3hvfAidrbm6oL2jWMSThKLplAccZKZXL7mWW2I9qhUULj/dhQoo8H9hfq9/M5ISwBRe69fIyJMRa%2BsfS0ZpbF6ajvvZU37U8WDxeXQuqw=*/`

` cryptedKey = Ef72861xaZU8Cab0z9u9vespEStB2r2GEj/CQDkr7BoSBYpH6rS5xg7j2V5wOITTipXd3eQ0/AFVuOw%2BL619Wiad5a73xy8AvY3PVnnMTCIPXOxaCjQAQG9cfqrd4ejaTY4bj/OJ9KUSXga%2B8R7mV3Z8AbA2PVh/4GisXAiofqA=
`

`key = YK~7F7@1[UU=~!8l`

**Decryption function**
`  // just a part of it, because it's very long.` 
` cryptedMessage = JwBIAjf91Y1HqTG9nXZH81/usjcc2eF8yu9zPwnF2dg08FZto/Qi6a49vN7Q2JK7e09S4huBr7V57NRfJ6xj1nI+TsKko9ccHuYNs0m7W1PFozpqmuAGEuUkEDAfojk0on6BBfl2BCjTyUsrcCwVvjRbz52MeadYKzsCjr6NYcRryZ4arbCtuTy08gNAQrJkqwfOUM7GcD7y
`

` cryptedData = 2091 bytes`

` aes = CryptoSwift.AES`

I noticed a dataPaddingRequired error when the decrypt method executed:

`public func decrypt(_ bytes: ArraySlice<UInt8>) throws -> Array<UInt8> { 
          if blockMode.options.contains(.paddingRequired) && (bytes.count % AES.blockSize != 0) {
                    throw Error.dataPaddingRequired 
}`

the two conditions are always true!

I would be grateful for any help you are able to provide.

**Comment by MohamedLamrabet** [comment]
Sorry, my bad, the bug is not from the iOS app, but it is from my PHP encryption function... I apologize for the inconvenience.

Thanks a lot for all your hard work, it is much appreciated.

**Comment by talat-baig** [comment]
Hi, I am getting this bug still till date, any update on this would be appreciated? While decrypting Image data it is showing this error

**Comment by krzyzanowskim** [comment]
@talat-baig it doesn't look like CryptoSwift bug. If you belive it's it's CryptoSwift bug (not invalid input) please fill new bug with reproducible sample of code.
