### ISSUE TITLE
Sound not playing in decrypted video

### ISSUE THREAD

**Issue by JyotiSirswa** [krzyzanowskim/CryptoSwift#721]
Hello, i am using following code to decrypted .mp4 video

import Foundation
import CryptoSwift

extension Data {
    func aesEncrypt(key: String, iv: String) throws -> Data{
        let encypted = try AES(key: Array(key.utf8), blockMode: CTR(iv: Array(iv.utf8)), padding: .noPadding).encrypt(self.bytes)
        return Data(bytes: encypted)
    }
    
    func aesDecrypt(key: String, iv: String) throws -> Data {
   
        let decrypted = try AES(key: Array(key.utf8), blockMode: CTR(iv: Array(iv.utf8)), padding: .noPadding).decrypt(self.bytes)
        return Data(bytes: decrypted)
    }
}

But when i play video not getting soud of video

**Comment by krzyzanowskim** [comment]
so you think it's related to CryptoSwift? how?

**Comment by JyotiSirswa** [comment]
Because its playing in normal video but when i decrypt it sound does not playing from video

**Comment by rishabhmathur1693** [comment]
@JyotiSirswa @krzyzanowskim I'm also facing this same issue. After decrypting, the audio is not playing in the video.

**Comment by krzyzanowskim** [comment]
Guys. I can't talk on a video/audio level about cryptography ;) If you could make it down to bytes, that'd give us some insight. So, compare bytes before encryption and after decryption and see if there is a difference.
