### ISSUE TITLE
SWIFT5 PBKDF2 - Ambiguous use of 'init'

### ISSUE THREAD

**Issue by krrisztian** [krzyzanowskim/CryptoSwift#722]
XCode version: 10.2.1
Swift 5
Build target: iOS 12.2
Install`pod 'CryptoSwift', :git => "https://github.com/krzyzanowskim/CryptoSwift", :branch => "master"`

I copy-pasted the PBKDF2 example from the readme and it is giving me a `Ambiguous use of 'init(password:salt:iterations:keyLength:variant:)'` error.
Not sure what's wrong, tried to look at the definition but didn't help.

Here's my code:
`import CryptoSwift`

```swift
func cryptit(){
        do {
            let password: Array<UInt8> = Array("s33krit".utf8)
            let salt: Array<UInt8> = Array("nacllcan".utf8)
            
            let key = try PKCS5.PBKDF2(password: password, salt: salt, iterations: 4096, variant: .sha256).calculate()
            //error: Ambiguous use of 'init(password:salt:iterations:keyLength:variant:)'
        } catch {
            print("error with pbkdf2")
        }
    }
```

I'm suspecting the problem is with the `.sha256`, I actually have no idea where that is declared.

Thanks

<img width="1105" alt="Screen Shot 2019-05-20 at 23 23 51" src="https://user-images.githubusercontent.com/20590073/58033036-57166480-7b56-11e9-941c-9e3bf363ec54.png">

**EDIT:** the problem also arises when I try to use the [HMAC-based Key Derivation Function](https://github.com/krzyzanowskim/CryptoSwift#hmac-based-key-derivation-function), but not with scrypt.

**Comment by rpinz** [comment]
`let key = try PKCS5.PBKDF2(password: password, salt: salt, iterations: 4096, variant: .sha256).calculate()

//error: Ambiguous use of 'init(password:salt:iterations:keyLength:variant:)'`

The answer is the forgotten keyLength argument.

`let key = try PKCS5.PBKDF2(password: password, salt: salt, iterations: 4096, keyLength: 32, variant: .sha256).calculate()`

**Comment by krzyzanowskim** [comment]
What's best action to address it. fix README?

**Comment by RomanPodymov** [comment]
Hello @krrisztian @rpinz 
Don't get any errors when compiling `func cryptit()`. Could you please check if you use the latest `CryptoSwift` version?
