### ISSUE TITLE
extension Array where Element == UInt8

### ISSUE THREAD

**Issue by ArchieR7** [krzyzanowskim/CryptoSwift#723]
**Describe the bug**
this function `Data(hex: String)` would be wrong while `String` like that `0x111` `111`

**To Reproduce**
1. 

**Sample code**

```swift
print(Data(hex: "111").toHexString())
```

**Expected behavior**
```swift
111
```

but it will print `1101`..
**Environment (please complete the following information):**
- Swift version: 5
- Platform (iOS/macOS/Linux/...): iOS
- Installation method (CocoaPods/Carthage/SPM/...): CocoaPods
- Project name:

**Additional context**

**Comment by krzyzanowskim** [comment]
"0x111" cannot be represented as a single UInt8. While `0x111` is a hexadecimal representation of 273(dec), it cannot be as such represented in array of UInt8.

`0x111` in bytes is `[0x11, 0x01]` therefore the expected output is `0x1101` that is translated to `[0x11, 0x01]`

Works as expected.
