### ISSUE TITLE
Encryption with ECB and decryption with GCM + IV issue

### ISSUE THREAD

**Issue by LBarranco** [krzyzanowskim/CryptoSwift#724]
- CryptoSwift version: (0.13.1)
- Swift version: 4.1
- Platform:  iOS
- Installation method: CocoaPods

# Description
I was used to use the ECB block mode to encrypt data (i.e. biometry informations, profile info etc) inside the memory of the iPhone. Can I now change the block mode to GCM? Are there any issues about decrypting some ECB crypto data with a GCM decryptor?

Thanks for your help!

**Comment by krzyzanowskim** [comment]
you have to basically re-crypt it with new mode. that is decrypt ecb, then encrypt using gcm.

**Comment by LBarranco** [comment]
Thank you! If you can I have another question:
In your guide when you explain how to use AES-GCM I read that you define the IV as AES.randomIV(AES.blockSize) just one time and later you use it to crypt and decrypt all the files. 
Is there a way to append the every Data object the encoding IV in order to use different IV for every crypted object?

Thank you !

**Comment by krzyzanowskim** [comment]
IV is usually at the begining, and is automatically added to the output so you don't have to store it separately.
For every encryption operation you can generate different IV. It depends on the mode, but generally it's good idea to not reuse IV with the same key

**Comment by LBarranco** [comment]
`func aesGCMEncrypt(withKey key: String) -> Data? {
        do {
            let iv = AES.randomIV(AES.blockSize)
            let gcm = GCM(iv: iv, mode: .combined)
            let aes = try AES(key: key.bytes, blockMode: gcm, padding: .noPadding)
            let bytes = try aes.encrypt(self.bytes)
            return Data(bytes: bytes)
        }
        catch {
            return nil
        }
    }
    
    func aesGCMDecrypt(withKey key: String) -> Data? {
        do {
            let gcm = GCM(iv: __WHAT_HERE__ , mode: .combined)
            let aes = try AES(key: key.bytes, blockMode: gcm, padding: .noPadding)
            let bytes = try aes.decrypt(self.bytes)
            return Data(bytes: bytes)
        }
        catch {
            return nil
        }
    }`

**Comment by LBarranco** [comment]
func aesGCMEncrypt(withKey key: String) -> Data? {
        do {
            let iv = AES.randomIV(AES.blockSize)
            let gcm = GCM(iv: iv, mode: .combined)
            let aes = try AES(key: key.bytes, blockMode: gcm, padding: .noPadding)
            let bytes = try aes.encrypt(self.bytes)
            return Data(bytes: bytes)
        }
        catch {
            return nil
        }
    }
    
    func aesGCMDecrypt(withKey key: String) -> Data? {
        do {
            let gcm = GCM(iv: __WHAT_HERE__, mode: .combined)
            let aes = try AES(key: key.bytes, blockMode: gcm, padding: .noPadding)
            let bytes = try aes.decrypt(self.bytes)
            return Data(bytes: bytes)
        }
        catch {
            return nil
        }
    }

**Comment by LBarranco** [comment]
If my point doesn't make any sense please explain me where I am wrong so I can go on and change my plans. On the other side if you think I am right and you think it could be possible to retrieve the IV directly from the encrypted object please show me how. 

Thank you for your work and for your help!

**Comment by krzyzanowskim** [comment]
> you told me that this random IV is automatically added at the beginning of the output.

It's not automatically added. You have to add it if you want. This is because sometimes it's at the beginning, other times it at the end - it's part of dataformat. Usually it's at the beginning.

for AES+GCM, data sequence will look like this: 
`IV|CIPHERTEXT|TAG`

**Comment by LBarranco** [comment]
1) Ah ok so you confirm me that in your repository the IV is not automatically added before of the encrypted data? 

2) What do I have to do if I want to extract the IV directly from the encrypted data?
