### ISSUE TITLE
Error compiling project on Xcode 11 beta

### ISSUE THREAD

**Issue by iPhoNewsRO** [krzyzanowskim/CryptoSwift#725]
**To Reproduce**
1. Install Xcode 11, get CryptoSwift via cocoapods
2. Try to compile
3. Get this error:https://pastebin.com/KvtMjfFC

**Sample code**

The project that worked in Xcode 10 wont work now

**Environment (please complete the following information):**
- Swift version: 5
- Platform (iOS/macOS/Linux/...): iOS
- Installation method (CocoaPods/Carthage/SPM/...): CocoaPods

**Comment by krzyzanowskim** [comment]
> Broken module found, compilation aborted!

most likely DerivedData or any other cache is broken and you have to remove it first.

**Comment by jalmaas** [comment]
I get abort trap 6 when trying to compile my project with crypto swift 1.0.0 via cocoapods. Have tried deleting Pods-folder running pod install again, clean build and deleting derived data

**Comment by iPhoNewsRO** [comment]
> > Broken module found, compilation aborted!
> 
> most likely DerivedData or any other cache is broken and you have to remove it first.

i tried that, wont fix my issue

**Comment by krzyzanowskim** [comment]
try call Apple, and ask for Xcode support. There's nit much I can help you with Xcode beta so far

**Comment by krzyzanowskim** [comment]
Report to Cocoapods and back to me with whatever they find. Report to Apple and back to me with whatever they find.

**Comment by jckarter** [comment]
Try disabling debug info to work around this crash.

**Comment by PorterHoskins** [comment]
I get this same issue when I try to archive the Swift Package in Xcode 11. Hopefully Apple fixes it.

**Comment by jckarter** [comment]
The issues we know about should already be addressed in the Swift development branch. You could try a snapshot toolchain from https://swift.org/download/#snapshots to see if it helps.
