### ISSUE TITLE
license question v1.0.0

### ISSUE THREAD

**Issue by dnd0513** [krzyzanowskim/CryptoSwift#726]
https://github.com/krzyzanowskim/CryptoSwift/blob/1.0.0/LICENSE

There is a difference between the license of the above file and the contents of zlib license.
Is CryptoSwift correct with OSS of zlib license?

http://zlib.net/zlib_license.html

**Comment by krzyzanowskim** [comment]
The license is as it states in the LICENSE file, and this is my answer. You can ask your local lawyer about the expertise ;)
