### ISSUE TITLE
How to decrypt with GCM

### ISSUE THREAD

**Issue by rsardek** [krzyzanowskim/CryptoSwift#727]
Once I have the encrypted data, what is the best way to decrypt it in GCM?
Do I have to always pass in the IV (which of course means that I cache it in inside my app)?
In Readme, there is also suggestion that I can use 'authentication tag' for decryption. Could you elaborate on how to do it?

Many thanks

**Comment by krzyzanowskim** [comment]
IV is not a secret value, it's usually appended to the beginning of the ciphertext so you just read few first bytes and this is your IV

`gcm.authenticationTag` is the value you compare after you decrypt data. You compare it with the tag you got after encryption. It ensures you that message wasn't modified.
