### ISSUE TITLE
integeterWithBytes deprecates 0.8

### ISSUE THREAD

**Issue by freak4pc** [krzyzanowskim/CryptoSwift#73]
I don't see the point in deprecating a method without providing a proper replacement. 

I think you should either
1. remove deprecation status from the method
2. provide a replacement that isn't deprecated...

Otherwise, it makes no sense...

**Comment by krzyzanowskim** [comment]
it's deprecated and it's reminder to not use it, yet replacement is not there. Feel free to provide a replacement for integerWithBytes() with PR, would love to merge that.

**Comment by freak4pc** [comment]
Again, my point is it doesn't seem to me like a very good practice.
Deprecation is a mechanism that is employed when a replacement is available ... Until then, there isn't much reason to deprecate except for creating unwanted warnings (because there's no other method to use at the moment, so there's nothing the developer could do).
