### ISSUE TITLE
CryptoSwift produces different output to OpenSSL

### ISSUE THREAD

**Issue by andy-312** [krzyzanowskim/CryptoSwift#731]
**Describe the bug**
I am not sure it is a bug or I am using CryptoSwift in a wrong way, but CryptoSwift produces different output to OpenSSL.

My code to encrypt is:

**Encryption Code**

```swift
class Encryption {
    static func encryptToBase64(text: String, key: String) -> String? {
        do {
            let aes = try AES(key: [UInt8](key.utf8), blockMode: ECB(), padding: .noPadding)
            let cipherText = try aes.encrypt([UInt8](text.utf8))
            return Data(bytes: cipherText).base64EncodedString()
        } catch {
            return nil
        }
        
    }
}

```
Call encryptionToBase64 with 
key = "4f0fbad47141ef9616ce4d71b459eea9"
text = "0123456789abcdeffedcba9876543210"
outputs: "Zt+9JdbWYOp+QHagRwOdWYrtWIlohN+QR8anoAaZeiE="

Meanwhile, with the same input to OpenSSL

```
echo -n "0123456789abcdeffedcba9876543210" | openssl enc -e -aes-128-ecb -K "3466306662616434373134316566393631366365346437316234353965656139" -a -nopad
```
I get "EdlbUs/uJ5b7Ww4YaybT0MT5+nEO5NMA41LBgA1/sfA="

**Expected behavior**

The outputs of CryptoSwift and OpenSSL should be the same

**Environment (please complete the following information):**
- Swift version: 5
- Platform (iOS/macOS/Linux/...): 
- Installation method (CocoaPods/Carthage/SPM/...): cocoaPods
- Project name: Test

**Additional context**

**Comment by krzyzanowskim** [comment]
I don't think it's a bug. The thing is to provide the same input to CryptoSwift and to OpenSSL. see https://github.com/krzyzanowskim/CryptoSwift/issues/394#issuecomment-277443009 this may help you.

Feel free to reopen if it happen to be a bug.

**Comment by andy-312** [comment]
I don't think its a bug either because it produces the same result as some other libraries like BlueCryptor or CommonCryptor do. After reading #394, I still can't alter input to CryptoSwift to get the same output as of OpenSSL. Could you spend sometime show me how?
Thanks

**Comment by andy-312** [comment]
Never mind. Its my bad calling it with a wrong key.
