### ISSUE TITLE
AES 256 CTR -pkcskcs5

### ISSUE THREAD

**Issue by faith95d** [krzyzanowskim/CryptoSwift#736]
**Describe the bug**
I'm having an encryption problem ctr:
I'm coding block mode ctr: AES 256 - PKCS5: Password-Based Encryption Standard version. 1.5.
After encryption is complete, the encoding results in the IOS side are different from the Android side. I'm thinking the problem is in pkcs5. Can you tell me the reason why IOS encoding results are different from Android?

**Comment by krzyzanowskim** [comment]
Sorry, my crystal ball is quite undecided ;) I'm afraid I cannot analyze your issue without enough information.
