### ISSUE TITLE
AES CTR 256 result incorrect

### ISSUE THREAD

**Issue by tuannt-0937** [krzyzanowskim/CryptoSwift#737]
When I encrypt with algo AES CTR 256, the output of swift is diffirent with PHP (openssl_encrypt) and Android. I check source code in your lib, input and output are need a bytes array (range: 0 -> 255), it is diffirent with PHP and Android (-128 -> 127). This can is a reasion. Can u tell/explain for me why? Thank you!

**Comment by krzyzanowskim** [comment]
because unsigned byte range is 0-255, while signed byte is range -128-127. It's the same value with a different representation.
