### ISSUE TITLE
sha2-384、sha2-512 length

### ISSUE THREAD

**Issue by QLwangqinghai** [krzyzanowskim/CryptoSwift#741]
sha2-384、sha2-512，the appended length of the message in bits, is a 128-bit big-endian integer。

**Comment by krzyzanowskim** [comment]
what's the issue you found?

**Comment by QLwangqinghai** [comment]
https://github.com/openssl/openssl/blob/master/crypto/sha/sha512.c  
line 158， used 128-bit integer。
https://crypto.stackexchange.com/questions/22956/what-is-the-length-field-in-sha-512-padding

And I found that there are not enough Int digits on a 32-bit system, only hash data of no more than 512MB.

**Comment by krzyzanowskim** [comment]
Why do you think CryptoSwift don’t handle it properly? Looks good to me https://github.com/krzyzanowskim/CryptoSwift/blob/0d1095dcded97315d25e3e69f4700cfb8bf2608b/Sources/CryptoSwift/SHA2.swift#L291

**Comment by QLwangqinghai** [comment]
1. On 32-bit platforms, `Int` is the same size as `Int32`, and on 64-bit platforms, `Int` is the same size as `Int64`.
Easily generate processedBytesTotalCount overflow problems on 32-bit systems。
 If hash 1GB data, on the 32-bit platform, the last block of data is [0x80, 0x0, 0x0, 0x0 ...], but on the 64-bit platform, the last block of data is [0x80, 0x2, 0x0, 0x0 ...]。
2.on 64-bit platforms: In theory, `processedBytesTotalCount` overflows beyond 2EB data. This is hard to test.

**Comment by krzyzanowskim** [comment]
I understand Int behavior, I don’t  see how it affects bitPadding function? Can you demonstrate the issue or point me to the line you think is not correct?

**Comment by owlstead** [comment]
I think the problem is in the line before:

    let lengthBytes = lengthInBits.bytes(totalBytes: blockSize / 8) // A 64-bit/128-bit representation of b. blockSize fit by accident.

here `lengthInBits` is a (signed) Int32 on 32 bit systems, so it can only hold a value of 2^32 in bits or 2^29 in bytes, which equates to 512 MiB (or 256 MiB if negative values are not handled well). So we're talking about the padding *including length padding* here.

**Comment by krzyzanowskim** [comment]
@owlstead sounds good to me. thanks for pointing out this one to me.
