### ISSUE TITLE
multiple targets named 'Tests' in: CryptoSwift, Version

### ISSUE THREAD

**Issue by acecilia** [krzyzanowskim/CryptoSwift#742]
The actual `Tests` target is too generic, causing dependency name collisions that [SPM can not handle](https://forums.swift.org/t/multiple-target-issue-with-spm/16696). In this case, I found a collision between this package and https://github.com/mxcl/Version.

After running `swift package generate-xcodeproj` the console shows the following error:
```
error: multiple targets named 'Tests' in: CryptoSwift, Version
```

The solution is to rename the target.

**Comment by krzyzanowskim** [comment]
uhm... Renaming it to `CryptoSwiftTests`, hoping it will unscrew Xcode project generator
