### ISSUE TITLE
Using CryptoSwift to validate iOS app receipts?

### ISSUE THREAD

**Issue by osteslag** [krzyzanowskim/CryptoSwift#744]
Being a hopeless newbie in this whole crypto world, I’m trying to understand whether it is possible to use CryptoSwift to [validate iOS app receipts](https://developer.apple.com/library/archive/releasenotes/General/ValidateAppStoreReceipt/Chapters/ValidateLocally.html). I’d rather not include OpenSSL although the process is fairly well-documented.

As far as I understand I need to be able to
1. load and parse the PKCS#7 receipt container
2. verify Apple’s PKCS#7 signature,
3. decode the DER-encoded ASN.1 payload and 
4. compute a SHA-1 hash (that one seems to definitely be covered)

Will CryptoSwift be able to do this for me (and if so, high-level directions would be much appreciated).

Thanks in advance,
Joachim

**Comment by krzyzanowskim** [comment]
no. you basically need openssl for that.
