### ISSUE TITLE
support for base85 (ascii85)

### ISSUE THREAD

**Issue by holosuda** [krzyzanowskim/CryptoSwift#745]
Hello!

Can you also please consider to include base85 (ascii85) function into the package?

I can't find any reference for Swift, although there are some written for other languages like C.

**Comment by krzyzanowskim** [comment]
base85 is an encoding and nothing in CryptoSwift needs it, so it's unlikely I'll spend time to work on that. If you feel it's good to have, give it a shot and submit PR.
