### ISSUE TITLE
-O and wholemodule enabled for debug cocoapod builds

### ISSUE THREAD

**Issue by ileitch** [krzyzanowskim/CryptoSwift#747]
The [podspec](https://github.com/krzyzanowskim/CryptoSwift/blob/master/CryptoSwift.podspec#L19) defines compiler arguments that aren't suitable for debug builds. I would suggest just removing all of these flags if possible and allow the compiler to use the defaults.

**Comment by krzyzanowskim** [comment]
It was added to improve "debug" build performance a bit (It's painfully bad by default). I agree though that we shouldn't need it.
