### ISSUE TITLE
support swift 2.0

### ISSUE THREAD

**Issue by jonnywang** [krzyzanowskim/CryptoSwift#75]
support swift 2.0 ?

**Comment by krzyzanowskim** [comment]
👍
Will work on this in the weekend probably.

**Comment by jonnywang** [comment]
great!

**Comment by hamchapman** [comment]
I'm also keen to see Swift 2.0 support :)

**Comment by yageek** [comment]
+1 I arrived to the same level as @hamchapman :(

**Comment by krzyzanowskim** [comment]
I'll wait for beta2 to start with this.

**Comment by hamchapman** [comment]
Still failing for me in beta2

**Comment by dickwu** [comment]
Waiting.......

**Comment by krzyzanowskim** [comment]
Working version for Swift 2.0 (beta2) is available on branch **swift20** 💥 - this is work in progress of course.
