### ISSUE TITLE
CBC With IV Error

### ISSUE THREAD

**Issue by ErAshu** [krzyzanowskim/CryptoSwift#750]
Hi, 
I spent more than 4 hour on this topic and didn't get the solution for random IV.

I am attaching the screenshot.
<img width="800" alt="Screenshot 2019-09-24 at 4 41 12 PM" src="https://user-images.githubusercontent.com/4178384/65506850-31291400-deea-11e9-8809-2b80e1de27da.png">

**Pod Version is here**
<img width="240" alt="Screenshot 2019-09-24 at 4 37 54 PM" src="https://user-images.githubusercontent.com/4178384/65506874-3f773000-deea-11e9-8394-a0019c0837d2.png">

**Comment by sanchitgarg1909** [comment]
CBC is defined as a struct in the latest version of CryptoSwift. Try below code :-
`
let encrypted = try! AES.init(key: key.bytes, blockMode: CBC(iv: AES.randomIV(16)), padding: .pkcs7)
`

**Comment by ErAshu** [comment]
Now i am getting this error. 
<img width="774" alt="Screenshot 2019-09-25 at 10 23 21 AM" src="https://user-images.githubusercontent.com/4178384/65570380-8c0c4b00-df7e-11e9-984a-340da7f09442.png">

**Comment by ErAshu** [comment]
`func aesEncrypt(value: String, key: String) -> String {
        let encrypted = try! AES.init(key: key.bytes, blockMode: CBC(iv: AES.randomIV(16)), padding: .pkcs7).encrypt([UInt8](self.data(using: .utf8)!))
        
        return Data(encrypted).base64EncodedString()
    }`

**Comment by krzyzanowskim** [comment]
> But server side not able to decrypt this.

Make sure the server-side uses the same parameters to decrypt, like `key` and `iv`

**Comment by krzyzanowskim** [comment]
I'm closing this one. It looks like client-server misconfiguration. Most likely it uses different IV on both (since you generate random IV on client side)

**Comment by ErAshu** [comment]
Key is same but IV will different because its random.

**Comment by krzyzanowskim** [comment]
yes, however to decrypt you need to use the same IV that is use to encrypt

**Comment by ErAshu** [comment]
Not solve yet after use same IV. 
Please provide me .Net code for decrypt. It will helpful for me.

**Comment by krzyzanowskim** [comment]
@ErAshu such request is beyond the support I can provide here for free. Feel free to contact me for professional support in crypto field.
