### ISSUE TITLE
dataPaddingRequired when decrypted using the same AES encryptor instance 

### ISSUE THREAD

**Issue by MEnnabah** [krzyzanowskim/CryptoSwift#751]
**Describe the bug**

I encrypt some string using CBC mode, using AES class from CryptoSwift. When I decrypt the result on the same AES instance, it throws `dataPaddingRequired ` error.

**To Reproduce**
1. 

**Sample code**

```swift

        
        let username = "MEnnabah"
        let cleanUUID = "AFB6ADD39C294D11800A63442ABBEC4E"
        let iv = "AFB6ADD39C294D11"
        
        var aes: AES!
        do {
            aes = try AES.init(key: cleanUUID, iv: iv)
        } catch {
            print(error)
        }
        
        var encryptedText = ""
        
        do {
            let ciphertext = try aes.encrypt(username.bytes)
            encryptedText = ciphertext.toBase64()!
            print(encryptedText) // 3iQfEz6E/5BvVaAC2t2dFg==
        } catch {
            print(error)
        }
        
        do {
            let text = try aes.decrypt(encryptedText.bytes)
            print(text.toBase64()!)
        } catch {
            print(error) // fails with `dataPaddingRequired`
        }

```

**Expected behavior**

`aes.decrypt(encryptedText.bytes).toBase64()! == "MEnnabah"`

**Environment (please complete the following information):**
- Swift version: 5.1
- Platform (iOS/macOS/Linux/...): iOS 13.0
- Installation method (CocoaPods/Carthage/SPM/...): CocoaPods

**Additional context**

I tried to leave the encrypted message as `[UInt8]`, then decrypt it and convert it to base64 string, but that gave a weird behaviour.

**Comment by Luzanov** [comment]
@MEnnabah Pay attention. You encrypt data and convert it to base64 string.

```swift
let ciphertext = try aes.encrypt(username.bytes)
encryptedText = ciphertext.toBase64()!
```

but then you try decrypt base64 data, not encrypted data itself. You must convert back base64 to encrypted data first. So your last part of code should be something like below:

```swift
let encryptedData = Data(base64Encoded: encryptedText)!
let decryptedData = Data(try aes.decrypt(encryptedData.bytes))
let decryptedText = String(data: decryptedData, encoding: .utf8)
print(decryptedText!) // "MEnnabah"
```
