### ISSUE TITLE
Not working properly in release. 

### ISSUE THREAD

**Issue by klusinyan** [krzyzanowskim/CryptoSwift#752]
**Describe the bug**
Hi, I'm using CryptoSwift in my project. App compiled with Swift 4.2 and the current version that I've tried is 0.11.0 and 0.12.0. So with both versions I'm having some strange issue for iOS 10: encryption is working in Debug correctly but when I'm trying to upload in TestFlight to release, it stops working. The encryption is incorrect, so the encrypted strings are wrong. This I could check with data that app sent to server.
I know that it probably depends on compiled version of application.
So please, let me know if you've ever had such a similar behaviour. 

Thanks in advance.
Karen

**Environment (please complete the following information):**
- Swift version: 4.2
- Platform iOS 10
- Installation method CocoaPods

**Comment by sanchitgarg1909** [comment]
@klusinyan Could your issue be similar to this https://github.com/krzyzanowskim/CryptoSwift/issues/748

**Comment by klusinyan** [comment]
Thank you for reference. I found the solution after some while by trying different solutions.
So found that by unchecking: "Include BitCode for iOS Content" resolved problem, the executable file .ipa becomes twice larger but it works.

Thank you again.
karen

**Comment by krzyzanowskim** [comment]
wait what? did disable bitcode solved your issue @klusinyan?

**Comment by klusinyan** [comment]
Hi, the problem was when I was trying to upload to AppStore.
Yes, by disabling the Bitcode at upload time, and not in target build settings. After that the encryption worked correctly.

Karen

**Comment by krzyzanowskim** [comment]
Christ! this is bad. So bad that I don't even know where to shout. I don't think anybody from apple will look at bugreport in next few years.

Would you be able to file a feedback (bugreport) report with a reference to the app in the store? The app store team would have to look into that.

**Comment by klusinyan** [comment]
Do you mean that I should write to Apple support team to report the bug?

**Comment by klusinyan** [comment]
The strangest point is that the app works correctly when I attach to Dubeg, and when it goes to TestFlight stops working. Never happened to me for any library or app.

Karen

**Comment by krzyzanowskim** [comment]
Yes, please, using https://feedbackassistant.apple.com where you give them more details about binaries you uploaded to AppStore.

Once you report it. Please post report number here for reference.

**Comment by klusinyan** [comment]
Ok. I’ll do!
Thanks again for a great job.
Karen

**Comment by klusinyan** [comment]
Hi,
I sent this bug to Apple.
The reference code is: 7328010

Best,
Karen

**Comment by nhjariwala** [comment]
@klusinyan  I'm having same issue it encryption works fine in debug but not in released. I have also checked #748 but still not getting success. Is there anything else we need to do ?

I tried my previous build it works fine but not the current build. I always used master branch, but I have not updated my pods. 

**Environment (please complete the following information):**

- Swift version: 4.0
- Platform iOS 9.3
- Installation method CocoaPods
