### ISSUE TITLE
PKCS7_verify

### ISSUE THREAD

**Issue by tcurdt** [krzyzanowskim/CryptoSwift#754]
I am trying to figure out the equivalent of using OpenSSL as

```
let store = X509_STORE_new()
X509_STORE_add_cert(store, appleRootX509)
OpenSSL_add_all_digests()
let result = PKCS7_verify(receiptPKCS7, nil, store, nil, nil, 0)
```
https://github.com/IdeasOnCanvas/AppReceiptValidator/blob/master/AppReceiptValidator/AppReceiptValidator/AppReceiptValidator.swift#L145
https://github.com/IdeasOnCanvas/AppReceiptValidator/blob/master/AppReceiptValidator/AppReceiptValidator/AppReceiptValidator.swift#L164

it would be great to be pointed into the right direction of if there was some documentation for this.

**Comment by krzyzanowskim** [comment]
I advice to keep using OpenSSL :) PKCS7 defines many things. X509 certificates buid on top of ASN.1 notation is one. There's nothing to work with that in CryptoSwift.

**Comment by tcurdt** [comment]
Bummer. So out of scope also for the long run it sounds like?
Thanks for the quick reply and the otherwise great library.

**Comment by krzyzanowskim** [comment]
yes, out of scope. thanks for checking though.
