### ISSUE TITLE
Is CryptoSwift FIPS Compliant ?

### ISSUE THREAD

**Issue by pranay90openid** [krzyzanowskim/CryptoSwift#755]
- CryptoSwift version:
- Swift version:
- Platform (iOS/macOS/Linux/...):
- Installation method (CocoaPods/Carthage/SPM/...):
- Project name:

# Description

> To whom may be concerned: I offer professional support to all my open source projects.

# Steps to reproduce

Sample code to reproduce the issue:

```swift
import CryptoSwift

// Code goes here

```

**Comment by krzyzanowskim** [comment]
CryptoSwift wasn’t audited for FIPS Compliance, and is not FIPS Certified.
