### ISSUE TITLE
Unpadding after Decryption (default internal process?)

### ISSUE THREAD

**Issue by nunosilvamourao** [krzyzanowskim/CryptoSwift#760]
I've a process where the encryption is done in Python (using a sha 256 hashed password as key, and random IV). Some padding is done to the data before encrypting.
On Python, when decrypting, the unpadding is done after the decryption takes process and it decrypts properly.

Now I'm trying to decrypt the same data in Swift.
Is there any way to do the Unpadding only after the decryption on CryptoSwift? I've been trying several ways (always with same IV and Key), and always get "Data Padding Required".

Does CryptoSwift by default apply the unpadding after the decryption is done? And if it does how to do manual unpadding instead?

Sorry if the question it's unclear or shouldn't be made here, first time using Swift and AES Crypto.

**Comment by nunosilvamourao** [comment]
I'm using the .pkcs7 padding, that's what makes me wonder why the error still says Data Padding Required, code snippet below
```
  let aes = try AES(key: privkey, blockMode: CBC(iv: myIV), padding: .pkcs7)
  let cipherText = try aes.decrypt(myEncoded)
```
the data encrypted from python contains content+iv. And on swift I get the last 16 bytes (myIV) and the remaining would be the myEncoded variable. Would this possibly break the decryption?

**Comment by krzyzanowskim** [comment]
maybe python side uses different padding scheme?

**Comment by nunosilvamourao** [comment]
In theory the code used in Python is mimicking the pkcs7 padding mechanism.. but it might be the issue then. CryptoSwift shows as error Data Padding Required when it doesn't recognize the padding as being the one passed to the AES?

myEncoded is bytes variable, although I receive a string, I'm applying .bytes function to convert it before passing it to the decrypt.

**Comment by krzyzanowskim** [comment]
> although I receive a string, I'm applying .bytes function to convert it before passing it to the decrypt.

it doesn't sound right. First you have to decode your string from whatever encoding it uses. so if its hex, see https://github.com/krzyzanowskim/CryptoSwift#data-types-conversion

```swift
let bytes = Array<UInt8>(hex: "0x010203")
```

**Comment by nunosilvamourao** [comment]
In fact the issue was that we were receiving a base64 encoded string in Swift, that after the base64 decode it still had to be split at a byte level, as the IV+data were encrypted and encoded together as a single string.

Just as a reference, if anyone faces the same with a similar python to swift solution:
1 - decode base 64
2 - cast from Data to UInt8
3 - split the UInt8 depending on the python byte composition
4 - apply the cipher with the IV
