### ISSUE TITLE
ios 10.3 bug

### ISSUE THREAD

**Issue by miadparizadian** [krzyzanowskim/CryptoSwift#772]
hi 
im using  aes 256 cbc in iphone 5 (ios 10.3)
but encryption has been problem
3 is right up to the first encryption and others wrong
how to fix theme????!!!!!!
this is fource

**Comment by krzyzanowskim** [comment]
Looks like LLVM bug discussed here https://github.com/krzyzanowskim/CryptoSwift/issues/748#issuecomment-547363969

**Comment by miadparizadian** [comment]
> Looks like LLVM bug discussed here [#748 (comment)](https://github.com/krzyzanowskim/CryptoSwift/issues/748#issuecomment-547363969)

What does llvm mean and how to solve it؟؟

**Comment by krzyzanowskim** [comment]
LLVM in short means: it's a compiler bug. Not much you acn do. Likely fix will be released soon and available in Xcode.

**Comment by miadparizadian** [comment]
> LLVM in short means: it's a compiler bug. Not much you acn do. Likely fix will be released soon and available in Xcode.

in xcode 11 has problem???

**Comment by krzyzanowskim** [comment]
> in xcode 11 has problem???

I don't know, I'm not updated about Apple products anyway.

**Comment by krzyzanowskim** [comment]
Closing this issue as a duplicate of #748
