### ISSUE TITLE
Possible error?

### ISSUE THREAD

**Issue by FranTagliani** [krzyzanowskim/CryptoSwift#773]
Hello there,

     Im developing a small app using CryptoSwift for iOS and other libraries for Android.
In both apps im using AES CBC 256 PKCS5 encryption and decryption, but some times only on iOS when I encrypt some string the Base64 output is created with an "illegal" character, this character is the "+", always when the encryption return randomly the +, in the server or android libraries of AES CBC 256 PKCS5 encryption and decryption returns illegal character or padding error. I tried change the padding in both cases, front-end or back-end. but still same.
I tried use other configurations in CryptoSwift but still same.

Here is the code of the encryption:
```
public func encryptString(key: String, text: String) -> String? {
        let iv = generateIV()
        let str = text.bytes
        
        do {
            let enc = try AES(key: key, iv: iv, padding: .pkcs7).encrypt(str)
            let encData = NSData(bytes: enc, length: Int(enc.count))
            let base64String: String = encData.base64EncodedString(options: NSData.Base64EncodingOptions(rawValue: 0));
            return iv + base64String
        } catch {
            return nil
        }
}
```
And Im creating the IV with this function:

```
public func generateIV() -> String {
        let iv_lenght = 16
        let ivChars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
        var ivStr = ""
        
        for _: Int in 0..<iv_lenght {
            ivStr.append(contentsOf: String(ivChars[Int.random(in: 0..<ivChars.count)]))
        }
        
        return ivStr
}
```

**Comment by krzyzanowskim** [comment]
> the Base64 output is created with an "illegal" character, 

I don't understand this part. `+` is a valid char in base64.

> decryption returns illegal character or padding error.

Padding is in the last byte. Let's find out if this is a padding issue first. Can you please attach the result of encryption that you suspect has incorrect padding?

> return iv + base64String

are you sure about that? I'd say IV should be added before base64 encoding, then encoded. The `generateIV` doesn't look good to me ( I had to point it). Maybe you can use this  https://github.com/krzyzanowskim/CryptoSwift/blob/9bddccf5a0c3c948fbb440553578c47002622587/Sources/CryptoSwift/Cryptors.swift#L39-L41

**Comment by FranTagliani** [comment]
Hello!, Thanks for reply, about the IV, Im using the same steps to encrypt and decrypt in front-end and back-end, the encryption will return 16 bytes of random string (IV), and I add the base64 encoded string after IV, to decrypt, I extract the first 16 characters, split the encrypted string in IV & Base64 Data, the IV extracted is the IV I use to decrypt the string without the first 16 characters.

This is a invalid encryption:
`6Jslmp253yvAlDtRV3wJYTEgHL+5i13/lHoKdA== `

This is a valid encryption:
`ksamvyFp6FZLyAU5aRliARTJpfArFhQ6qGMdFA==`


My decryption code now is this:

```
public func decryptString(key: String, text: String) -> String? {
        
        let indexIv = text.index(text.startIndex, offsetBy: 16)
        let indexData = text.index(text.endIndex, offsetBy: 0)
        
        let iv = String(text[..<indexIv])
        let str = String(text[indexIv..<indexData])
        
        do {
            let aes = try AES(key: key, iv: iv, padding: .pkcs7)
            let decryptStr = try str.decryptBase64(cipher: aes)
            let finalStr = String(data: NSData(bytes: decryptStr, length: decryptStr.count) as Data, encoding: .utf8)

            return finalStr!
        } catch {
            return nil
        }
}
```

**Comment by krzyzanowskim** [comment]
I don't see an issue tbh. Most likely your Android and iOS use different input data and/or different parameters. Also, I can't tell what is valid encryption because I don't have all data to reproduce it on my side.

**Comment by FranTagliani** [comment]
If no way to generate a base64 of Data that didn't contains the character "+"?

For example in the encryption code if I add this lines, always works fine, but I think is not the best solution:

```
var base64String: String = "+"
            
repeat {
     base64String = encData.base64EncodedString(options: NSData.Base64EncodingOptions(rawValue: 0))
} while (base64String.contains("+"))
```

**Comment by krzyzanowskim** [comment]
`+` is a valid Base64 character. There's data behind that and this is what you should focus on, not the `+` sign itself.

**Comment by FranTagliani** [comment]
Yes, of course, im not referring to replace the `+`, because the base64 is encrypted, if I replace the `+`, the encryption it would not make sense
I mean about if exist a method to exclude some character of base64 before encode it
