### ISSUE TITLE
Encrypted String is wrong in swift

### ISSUE THREAD

**Issue by BKudale** [krzyzanowskim/CryptoSwift#774]
**Describe the bug**

**Reproduce**
My Code 
```swift
extension String {
    func aesEncrypt() throws -> String {
        let secreteKey = getSecreteKey()
        let iv : Array<UInt8> = "0000000000000000".utf8.map {$0}
        guard let data = self.data(using: .utf8) else { return ""}
        let encrypted = try AES(key: secreteKey, blockMode: CBC(iv: iv), padding: .pkcs5).encrypt([UInt8](data))
        let encryptedData = Data(encrypted)
        return encryptedData.base64EncodedString()
    }
    
    func aesDecrypt() throws -> String {
        let secreteKey = getSecreteKey()
        let iv : Array<UInt8> = "0000000000000000".utf8.map {$0}
        guard let data = Data(base64Encoded: self) else { return "" }
        let decrypted = try AES(key: secreteKey, blockMode: CBC(iv: iv), padding: .pkcs5).decrypt([UInt8](data))
        let a = decrypted[0]
        let b = decrypted[1]
        let c = decrypted[2]
        let d = decrypted[3]
        let str1 = "\(a)\(b)\(c)\(d)"
        return str1
    }
    func getSecreteKey()-> Array<UInt8> {
        let password: Array<UInt8> = KEY.utf8.map {$0}
        let salt: Array<UInt8> = SALT.utf8.map {$0}
        let value = try! PKCS5.PBKDF2(password: password, salt: salt, iterations: 65536, keyLength: 32, variant: .sha256).calculate()
        return value
    }
}
```

From above code i decrypted the message sent from server successfully 

1) Server Encrypted message -  `iOoo2F6tAwvHG5OI1YX86A==` .   After decrypt - 6666   successfully decrypted

2) Tried to encrypt 6666 using above func got output -  `kiAwAbhS7IgXAPgwDVE8Vg==`
Which is different . Please suggest what is wrong in above code , Thank you.

**Comment by krzyzanowskim** [comment]
> let iv : Array<UInt8> = "0000000000000000".utf8.map {$0}

most likely this is not what you think it is. This is `[48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48]`, not array of zeroes.

**Comment by krzyzanowskim** [comment]
> let data = self.data(using: .utf8)

this won't encrypt `6666`, it will encrypt `"6666"` (a string) - those are different values

**Comment by BKudale** [comment]
yes i am encrypting the string "6666" but getting output wrong . Please suggest

**Comment by krzyzanowskim** [comment]
encrypted 6666 and "6666" has different output. `iOoo2F6tAwvHG5OI1YX86A==` is for 6666, while `kiAwAbhS7IgXAPgwDVE8Vg==` is for "6666". This is as expected.

**Comment by BKudale** [comment]
Code updated , converted string to int but still getting the same result

**Comment by BKudale** [comment]
> encrypted 6666 and "6666" has different output. `iOoo2F6tAwvHG5OI1YX86A==` is for 6666, while `kiAwAbhS7IgXAPgwDVE8Vg==` is for "6666". This is as expected.

Checked with backend code  output `iOoo2F6tAwvHG5OI1YX86A==` is for string "6666" .

**Comment by krzyzanowskim** [comment]
> Checked with backend code output iOoo2F6tAwvHG5OI1YX86A== is for string "6666" .

that doesn't make sense, you wouldn't decrypt that with the function you've built

this 
```
        let a = decrypted[0]
        let b = decrypted[1]
        let c = decrypted[2]
        let d = decrypted[3]
```

is for `[6,6,6,6]`, not `"6666"`, not even `6666`

I didn't run the code, I just use what you provided.

**Comment by BKudale** [comment]
@krzyzanowskim ok please suggest what can i do to match the encrypted code 'iOoo2F6tAwvHG5OI1YX86A==' for string "6666" (as it is entered by user) . can i convert it to int ? then pass bytes array of converted int to encrypt func .

**Comment by BKudale** [comment]
> > Checked with backend code output iOoo2F6tAwvHG5OI1YX86A== is for string "6666" .
> 
> that doesn't make sense, you wouldn't decrypt that with the function you've built
> 
> this
> 
> ```
>         let a = decrypted[0]
>         let b = decrypted[1]
>         let c = decrypted[2]
>         let d = decrypted[3]
> ```
> 
> is for `[6,6,6,6]`, not `"6666"`, not even `6666`
> 
> I didn't run the code, I just use what you provided.

@krzyzanowskim After decrypt we got byte array [6,6,6,6,60,60,60,60,60,60,60,60,60,60,60,60] which contain ascii values which is not an int or string.

**Comment by krzyzanowskim** [comment]
You have to figure out correct input data and match it with whatever is done on the server. The easiest approach would be to deal with bytes (UInt8) on both sides. Your problem is most likely due do implicit conversions and/or encodings on the way.

Sorry, I can't help you more here.

**Comment by sagaraussizz** [comment]
Issue has been resolved. Please check following code.


    func getSecreteKey()-> Array<UInt8> {
        let password: Array<UInt8> = plainText.utf8.map {$0}
        let salt: Array<UInt8> = saltKey.utf8.map {$0}
        let value = try! PKCS5.PBKDF2(password: password, salt: salt, iterations: 65536, keyLength: 32, variant: .sha256).calculate()
        return value
      }

    func encrypt(content: String) throws -> String {
        let secreteKey = getSecreteKey()
        let iv : Array<UInt8> = "0000000000000000".utf8.map {$0}
        guard let data = content.data(using: .utf8) else { return ""}
        let encrypted = try AES(key: secreteKey, blockMode: CBC(iv: iv), padding: .pkcs5).encrypt([UInt8](data))
        let encryptedData = Data(encrypted)
        return encryptedData.base64EncodedString()
     }
    
    func decrypt(content: String) throws -> String {
        let secreteKey = getSecreteKey()
        let iv : Array<UInt8> = "0000000000000000".utf8.map {$0}
        guard let data = Data(base64Encoded: content) else { return "" }
        let decrypted = try AES(key: secreteKey, blockMode: CBC(iv: iv), padding: .pkcs5).decrypt([UInt8](data))
        let str1 = Data(decrypted)
        return String(data: str1, encoding: .utf8) ?? "Empty"
    }

**Comment by bovillaios** [comment]
@sagaraussizz , Is the above code working. I am trying it now. It is not working. Can you plz help me out.
        print(try! encrypt(content: "123456"))
        print(try! decrypt(content: encrypt(content: "123456")))
