### ISSUE TITLE
File Encrypted by WebCrypto JS is not getting Decripted in CryptoSwift and Vice-versa

### ISSUE THREAD

**Issue by ankitthakur** [krzyzanowskim/CryptoSwift#776]
**Describe the bug**

Web is using [SubtleCrypto](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto) for encrypting file. 

**Reproduce**
1. Select any file of 20-30 KB
2. Encrypt file content in chunks of 4KB with particular key and iv in web with AES256, and padding pkcs5 WITH SubtleCrypto.
```
let encrypted = await crypto.subtle.encrypt({ 'name': 'AES-CBC', iv }, key, e.target.result);
let file = new File([encrypted], originalFile.name);
downloadFile(file, "encrypt");
```
3. Send that encrypted file to iOS client with same key and iv.
4. Try to decrypt contents of file in iOS using our AES256, and padding pkcs5.
```
let decryptedBytes = try AES(key: Array<UInt8>(key!), blockMode: CBC(iv: ivDataArray), padding: .pkcs5).decrypt(fileDataByte)
```

here `fileDataByte` is 4KB encrypted chunk. and then using stream, fetch 4KB next fileDataBytes and decrypt it, and give to OutputStream in iOS to write in decrypted file.

Decrypted file gets invalid.
Same is in reverse order.

**Comment by krzyzanowskim** [comment]
I'm not familiar with SubtleCrypto API. It looks to me that your problem is due to confisuing data encoding (key, iv in particular)
