### ISSUE TITLE
Fix typo

### ISSUE THREAD

**Issue by bystritskiy** [krzyzanowskim/CryptoSwift#777]
Fix typo in word "leng**ht**"

https://github.com/krzyzanowskim/CryptoSwift/blob/9bddccf5a0c3c948fbb440553578c47002622587/Sources/CryptoSwift/BlockMode/GCM.swift#L44

**Comment by bystritskiy** [comment]
/// For decryption, the lenght of given authentication tag is used.

**Comment by krzyzanowskim** [comment]
where's your PR :-)

**Comment by bystritskiy** [comment]
I have not seen guide in CONTRIBUTING.md about pull requests and thought you did not accept them :)

**Comment by bystritskiy** [comment]
I did PR
https://github.com/krzyzanowskim/CryptoSwift/pull/778
