### ISSUE TITLE
Converting PHP AES-256-CBC to Swift produces different result and can't decode it back

### ISSUE THREAD

**Issue by javierdemartin** [krzyzanowskim/CryptoSwift#780]
**Describe the bug**
I am currently writing some PHP code in Swift to do AES-256-CBC encryption on some Strings.

```
$string = "MyStringToEncrypt";

$secret_key = sha1('MySecretKey');
$secret_iv = sha1('MySecretIV'); 

$output = false;
$encrypt_method = "AES-256-CBC";
$key = hash( 'sha256', $secret_key );
$iv = substr( hash( 'sha256', $secret_iv ), 0, 16 );

$output = base64_encode( openssl_encrypt( $string, $encrypt_method, $key, 0, $iv ));

return $output;
```

**Reproduce**

My attempt to write it in Swift would be the following,

```
import CryptoSwift

let secretKey = "MySecretKey".sha1()
let secretIv = "MySecretIV".sha1()

let keyString: String = String(secretKey.sha256().prefix(32))
let ivString: String = String(secretIv.sha256().prefix(16))

let data = "MyStringToEncrypt".data(using: String.Encoding.utf8)

var result = ""

do {

    let enc = try AES(key: key, iv: iv).encrypt(data!.bytes)
    let encData = NSData(bytes: enc, length: Int(enc.count))
    let base64String: String = encData.base64EncodedString(options: NSData.Base64EncodingOptions(rawValue: 0));
    result = String(base64String)

} catch {
    print("Error \(error)")
}
```

This will produce a String but it won't be the same produced by the PHP code. Note that I am using the same Key and IV. If I try to decode back the resulting String from the Swift code I'm getting an empty String. Am I missing something here? Are the AES implementations in CryptoSwift and PHP different?

**Comment by krzyzanowskim** [comment]
> Are the AES implementations in CryptoSwift and PHP different?

no. AES is AES.

> This will produce a String but it won't be the same produced by the PHP code.

It looks like a iv and key encoding mixup. string vs bytes vs base64 vs hex vs whatever.
"CryptoSwift uses array of bytes aka Array<UInt8> as a base type for all operations. "
