### ISSUE TITLE
Cryptoswift error swift compiler 5

### ISSUE THREAD

**Issue by peterkuch** [krzyzanowskim/CryptoSwift#785]
I can't compile successfully . how can fixed? if you know.
<img width="882" alt="Screen Shot 2019-12-14 at 5 08 28 PM" src="https://user-images.githubusercontent.com/14107698/70847235-b5a98400-1e94-11ea-96c7-39dcee0bc2c9.png">

**Comment by alexykuan** [comment]
Same problem after install CryptoSwift.

**Comment by krzyzanowskim** [comment]
The current code requires Swift 5.1 compiler. See https://github.com/krzyzanowskim/CryptoSwift#swift-versions-support
It looks like you use Swift 5.0 compiler here.

**Comment by krzyzanowskim** [comment]
I just released 1.3.0 to Cocoapods, this should solve this issue for cocoapods (I hope)
