### ISSUE TITLE
AES128 ECB gives error

### ISSUE THREAD

**Issue by Gokulakrishnan123** [krzyzanowskim/CryptoSwift#787]
AES 128 Encryption with cipher mode ECB gives an error when I try to encrypt the string

**Reproduce**
I used the below code for encrypting the string using Crypto String Encryption but I could not get the result.Instead, it shows the error CryptoSwift.AES.Error.invalidKeySize error.

How to solve this issue?

extension String {
func aesEncrypt(key: String) throws -> String {
        var result = ""
        do {
            let key: [UInt8] = Array(key.utf8) as [UInt8]
            let aes = try! AES(key: key, blockMode: ECB() , padding:.pkcs7) // AES128 .ECB pkcs7
            let encrypted = try aes.encrypt(Array(self.utf8))
            result = encrypted.toBase64()!
            print("AES Encryption Result: \(result)")
        } catch {
            print("Error: \(error)")
        }
        return result
    }
}

Here I call the above method in the View Controller for encrypting 

 let encryptedValue = try! stringValue.aesEncrypt(key: strEncryptionKey)
 print(encryptedValue)

<img width="1019" alt="AES128EncryptionECB_Error_Issue" src="https://user-images.githubusercontent.com/58732003/71437044-e8197380-2715-11ea-968c-21ecf0a0a616.png">

1.
<img width="1132" alt="AES128EncryptionPassingStringAndKey" src="https://user-images.githubusercontent.com/58732003/71437500-14ce8a80-2718-11ea-917f-00a199e389be.png">

2. 
<img width="1137" alt="CryptoSwiftAESEncryptionKeyCoding" src="https://user-images.githubusercontent.com/58732003/71437670-adfda100-2718-11ea-88b6-6752f7b84e37.png">

3.  
<img width="1137" alt="CryptoSwiftAESEncryptionKeyCodingError" src="https://user-images.githubusercontent.com/58732003/71437686-b9e96300-2718-11ea-9e13-4d2223b16601.png">

**Comment by krzyzanowskim** [comment]
invalidKeySize - means you didn't provide the correct key, spwcifically the lenght of the key is invalid. It has to be exactly 16 bytes
