### ISSUE TITLE
I'm try to decrypt string with "AES/CTR/NoPadding"

### ISSUE THREAD

**Issue by CodegeekTechnosoft** [krzyzanowskim/CryptoSwift#789]
**Describe the bug**
I'm try to decrypt string with "AES/CTR/NoPadding"

**Reproduce**
   ```
func aesDecrypt(key: String, iv: String) throws -> String {
            let ctr = CTR(iv: Array(iv.utf8))
            let decrypt = try! AES(key:Array(key.utf8),blockMode:ctr,padding:.noPadding).decrypt(Array(self.utf8)).toHexString()
           return String.init(data:Data(hex123: decrypt), encoding: .utf8) ?? ""
   
      }

extension Data {
    public init(hex123: String) {
        self.init(Array<UInt8>(hex: hex123))
    }
}
```
by using this func but i got empty string every time 
please help me 
thank you

**Comment by krzyzanowskim** [comment]
one option is that decrypted value is not valid String, hence it cannot be a String. Check decrypted bytes before you try to make a String out of it.

The same apply to what you decrypt. Looks like you decrypt a String, that may or may not be valid encrypted value.
