### ISSUE TITLE
(Resolved) Result of AES 256 Encryption ECB Mode is different from .Net version

### ISSUE THREAD

**Issue by ekahoo** [krzyzanowskim/CryptoSwift#79]
Hi,

I find that result of AES 256 Encryption in CryptoSwift is different from that in .Net version
I tested several times with standard setting.
Hope we can find out root cause together.
Thanks a lot.

================================================================

Detail as follow:
Mode: AES 256, ECB
textString = "abcdef123456"
keyString = "QHTLkl\*ka%k!)825as\*a2svgi2qpc%(!"

bytes[32] of key, (Dec value) =
[81, 72, 84, 76, 107, 108, 42, 107, 97, 37, 107, 33, 41, 56, 50, 53, 97, 115, 42, 97, 50, 115, 118, 103, 105, 50, 113, 112, 99, 37, 40, 33]

Result of encryptedData in CryptoSwift: bytes[16] only,  (Dec value) =
[49, 196, 135, 122, 225, 121, 10, 247, 72, 154, 101, 241, 162, 73, 118, 5]

Result of encryptedData in .Net: bytes[32],  (Dec value) =
[152, 207, 82, 173, 79, 188, 32, 221, 108, 190, 26, 112, 195, 137, 126, 238, 60, 255, 194, 130, 23, 222, 113, 6, 197, 70, 139, 83, 97, 184, 67, 237]

================ CryptoSwift Code ===========================================
let textString = "abcdef123456"
let textData = textString.dataUsingEncoding(NSUTF8StringEncoding, allowLossyConversion: false)!
let textBytes:[UInt8] = textData.arrayOfBytes()

 if let aes = AES(key: "QHTLkl\*ka%k!)825as\*a2svgi2qpc%(!",  iv:"", blockMode: .ECB){
          let encryptedData = aes.encrypt(textBytes, padding: PKCS7())
}

================ ASP .Net Code ================================================
// Using standard .Net framework: System.Security.Cryptography

var myRijndael = new RijndaelManaged()
            {
                Padding = PaddingMode.PKCS7,
                Mode = CipherMode.ECB,
                KeySize = 256,
                BlockSize = 256
            };
   
var plainText = "abcdef123456";
var key = Encoding.ASCII.GetBytes("QHTLkl\*ka%k!)825as\*a2svgi2qpc%(!");
var IV = Encoding.ASCII.GetBytes("");   // no need in ECB mode

var encryptor = myRijndael.CreateEncryptor(key, IV);
var msEncrypt = new MemoryStream();
var csEncrypt = new CryptoStream(msEncrypt, encryptor, CryptoStreamMode.Write);

var toEncrypt = Encoding.ASCII.GetBytes(plainText);
          
csEncrypt.Write(toEncrypt, 0, toEncrypt.Length);
csEncrypt.FlushFinalBlock();

var encryptedData = msEncrypt.ToArray();

================================================================

Thanks.

**Comment by krzyzanowskim** [comment]
Your key is 30 bytes long, as a result, AES variant is unknown. I don't know what is .NET doing, maybe they fill it with zeroes to specified keysize

**Comment by ekahoo** [comment]
Hi ,
I forgot to escape asterisk.
The key should be this (32 bytes)
QHTLkl\*ka%k!)825as\*a2svgi2qpc%(!

bytes[32] of key = 
[81, 72, 84, 76, 107, 108, 42, 107, 97, 37, 107, 33, 41, 56, 50, 53, 97, 115, 42, 97, 50, 115, 118, 103, 105, 50, 113, 112, 99, 37, 40, 33]

**Comment by krzyzanowskim** [comment]
remember to escape it in string as well

**Comment by ekahoo** [comment]
OK, I just escape all asterisk in my original post.
By using that key, the result is significantly different between CryptoSwift and .Net
Am I using any incorrect setting? Thanks.

**Comment by krzyzanowskim** [comment]
build key array of bytes, instead of string, and then compare, i think its about different key used because of conversion from string. outputh have to be 32 bytes long on both.

**Comment by ekahoo** [comment]
I try to do another test to init bytes directly.
CryptoSwift cannot output 32 bytes long.

Result of encryptedData in CryptoSwift: (16 bytes only)
Dec: [102, 14, 27, 48, 111, 122, 32, 146, 49, 88, 76, 191, 126, 40, 59, 127]
Hex: [66, 0e, 1b, 30, 6f, 7a, 20, 92, 31, 58, 4c, bf, 7e, 28, 3b, 7f]

Result of encryptedData in .Net: (32 bytes)
Dec: [125, 161, 86, 76, 150, 67, 197, 51, 242, 211, 47, 198, 97, 101, 245, 119, 126, 10, 91, 63, 37, 114, 245, 10, 120, 91, 176, 209, 116, 77, 100, 244] 
Hex: [7D,A1,56,4C,96,43,C5,33,F2,D3,2F,C6,61,65,F5,77,7E,0A,5B,3F,25,72,F5,0A,78,5B,B0,D1,74,4D,64,F4]

=============================CryptoSwift==================================
let testTextBytes:[UInt8] = [0x61,0x62,0x63,0x64,0x65,0x66,0x31,0x32,0x33,0x34,0x35,0x36]
let testKeyBytes:[UInt8] = [0x51, 0x48, 0x54, 0x4C, 0x6B, 0x6C,
             0x41, 0x6B, 0x61, 0x42, 0x6B, 0x43,
             0x44, 0x38, 0x32, 0x35, 0x61, 0x73,
             0x45, 0x61, 0x32, 0x73, 0x76, 0x67,
             0x69, 0x32, 0x71, 0x70, 0x63, 0x46,
             0x50, 0x41]
let testIVBytes:[UInt8] = []

 if let aes = AES(key: testKeyBytes,  iv:testIVBytes, blockMode: .ECB){
            
            let encryptedData = aes.encrypt(testTextBytes, padding: PKCS7())
}

**Comment by ekahoo** [comment]
Hi, I found out the cause of problem
It is because CryptoSwift is using 16 bytes for Block Size according AES.swift.
So, in .Net should set back BlockSize to 128bits 

================ part of  ASP .Net Code =====================================
// Using standard .Net framework: System.Security.Cryptography

var myRijndael = new RijndaelManaged()
{
Padding = PaddingMode.PKCS7,
Mode = CipherMode.ECB,
KeySize = 256,  //bits
BlockSize = 128  //bits
};

=============================================================
Thanks.

**Comment by krzyzanowskim** [comment]
AES is a variant of Rijndael which has a fixed block size of 128 bits - that's why.
