### ISSUE TITLE
Cannot convert value of type 'UnsafeRawPointer?' to expected argument type 'Array<UInt8>?'

### ISSUE THREAD

**Issue by larryricker** [krzyzanowskim/CryptoSwift#790]
**Describe the bug**
Cannot convert value of type 'UnsafeRawPointer?' to expected argument type 'Array<UInt8>?'

**Reproduce**
1. pod update
Pull latest version of the code 1.3.0
Also tried version 1.0.0 and version 0.15.0
I was trying to figure out whether this was an issue related to compiling with Swift 4.2 so I tried prior versions.
2.  Compile application for 'macCatalyst' target, or iPhone target, or iPad target.  Same result any way  with any code base version and any target.
Compile error is happening on line 19 of String+Extension.swift
3.  A second compiler error is also occurring on line 71 of the same file:
Value of type '[UInt8]' has no member 'toBase64'
4.  If I was at my day job, I would tend to think that one of our developers forgot to check in a file.
5.  There was another issue, that may or may not be related.  After updating to the latest version the compiler complained that a file was not available called 'RandomBytesSequence.swift'.
This file does not exist so I cannot confirm if this is related by viewing the source because nothing opens when I click on it, so I disassociated it with the target and attempted the build.

**Comment by krzyzanowskim** [comment]
> or iPhone target, or iPad target. Same result any way with any code base version and any target.
Compile error is happening on line 19 of String+Extension.swift

this doesn't seem right. That would mean the project doesn't compile at all, that is not true. Can you attach sample project that doesn't compile for you? Use latest release: 1.3.0
