### ISSUE TITLE
Failed to generate AES with CBC BlockMode

### ISSUE THREAD

**Issue by kikisasha** [krzyzanowskim/CryptoSwift#794]
Hi,
I bumped into some issues while upgrading from swift 3 to swift 4.
On swift 3 I was using version 0.7.0 and all works well.

What I did was I went on some trials from version 0.7.1 , 0.7.2, 0.8.0-0.15.0 and the result was :

On version 0.7.1 and 0.7.2 , AES successfully generated but failed with EXC_EXCEPTION when trying to encrypt the value
```swift
try chiper.encrypt(Array(text.utf8))
```

While on version greater than 0.7 the result was a failure to generate AES with a result of nil value.

Here are some snap of the related codes :

```swift
static private func generateKey(salt: String, text: String, keyLength: Int? = 128, iterations: Int = 1000) throws -> [UInt8] {
        let utf8Text = Array(text.utf8)
        let hexSalt = salt.hexaBytes
        let generator = try PKCS5.PBKDF2(password: utf8Text,salt: hexSalt,iterations: iterations,keyLength: keyLength,variant: HMAC.Variant.sha1)
        return try generator.calculate()
    }
```

```swift
init?(salt: String, iv: String, password: String, keyLength: Int? = 128, iterations: Int = 1000) {    
        self.password = password
        do {
            let chiperKey = try Chiper.generateKey(salt: salt,password: password,keyLength: keyLength,iterations: iterations)            
            let blockMode = CBC(iv: iv.hexaBytes)            
            self.chiper = try AES(key: chiperKey, blockMode: blockMode)            
        } catch {
            return nil
        }
    }
```

Any suggestions?

**Comment by kikisasha** [comment]
I think the exceptions comes regarding changes from Swift itself. I'm using swift 4.2 to be exact.

**Comment by krzyzanowskim** [comment]
please capture the error and check what error is thrown. I can't tell what's the problem here, it can be anything, you're missing input values.

**Comment by kikisasha** [comment]
Hi, sorry for the late reply.
Regarding the missing input values, the input value should be range of 6-12 of alphanumerics.

On version 0.7.0, I got a 
**Thread 1: EXC_BREAKPOINT (code=1, subcode=0x10348b9f4)**
on
```try chiper.encrypt(Array(text.utf8)) ```
while trying to encrypt using the **chiper** I successfully generated.

**Comment by krzyzanowskim** [comment]
> the input value should be range of 6-12 of alphanumerics.

depends what you thing is an input, length is constant and it's defined for the cipher. Most likely you should catch throws and see what's error is throw there. If you attach the code I can run without guessing, so few lines that has all date, I can take another look at it. It looks like invalid input values to me.

Also version 0.7 is a bit old, and I can't support all versions

**Comment by kikisasha** [comment]
Hi, after numerous attempt, the solution to this issue was the length of the key itself when generating key and creating the ChiperModel. Changing keylength default value from 128 to 16 solve my issues.
