### ISSUE TITLE
`Scrypt.blockMixSalsa8` method took a lot of time for compiler to type check

### ISSUE THREAD

**Issue by jamztang** [krzyzanowskim/CryptoSwift#795]
**Describe the bug**
The `Scrypt.blockMixSalsa8` method took a lot of time for compiler to type check, we can prevent it by breaking it down into smaller piece.

**Reproduce**
1. Specify the debug flags for time checking in xcode Other Swift Flags:
```
-Xfrontend -warn-long-function-bodies=10
-Xfrontend -warn-long-expression-type-checking=10
```

2. Try building and you see the following warnings:
<img width="1319" alt="Screenshot 2020-01-21 at 1 53 13 PM" src="https://user-images.githubusercontent.com/852375/72778994-8afdd880-3c55-11ea-95da-7dfa4a8ff5e2.png">

To resolve this, you can:

```
  @inline(__always) func blockMixSalsa8(_ bin: UnsafePointer<UInt32>, _ bout: UnsafeMutablePointer<UInt32>, _ x: UnsafeMutablePointer<UInt32>) {
    /* 1: X <-- B_{2r - 1} */
    UnsafeMutableRawPointer(x).copyMemory(from: bin + (2 * self.r - 1) * 16, byteCount: 64)

    /* 2: for i = 0 to 2r - 1 do */
    for i in stride(from: 0, to: 2 * self.r, by: 2) {
      /* 3: X <-- H(X \xor B_i) */
      self.blockXor(x, bin + i * 16, 64)
      self.salsa20_8_typed(x)

      /* 4: Y_i <-- X */
      /* 6: B' <-- (Y_0, Y_2 ... Y_{2r-2}, Y_1, Y_3 ... Y_{2r-1}) */
      let a: UnsafeMutablePointer<UInt32> = bout + i * 8
      UnsafeMutableRawPointer(a).copyMemory(from: x, byteCount: 64)

      /* 3: X <-- H(X \xor B_i) */
      let src: UnsafePointer<UInt32> = bin + i * 16 + 16
      self.blockXor(x, src, 64)
      self.salsa20_8_typed(x)

      /* 4: Y_i <-- X */
      /* 6: B' <-- (Y_0, Y_2 ... Y_{2r-2}, Y_1, Y_3 ... Y_{2r-1}) */
      let b: UnsafeMutablePointer<UInt32> = bout + i * 8 + self.r * 16
      UnsafeMutableRawPointer(b).copyMemory(from: x, byteCount: 64)
    }
  }
```

<img width="1299" alt="Screenshot 2020-01-21 at 1 59 01 PM" src="https://user-images.githubusercontent.com/852375/72779203-36a72880-3c56-11ea-9224-85df9406614d.png">

**Comment by krzyzanowskim** [comment]
Can you report it to https://bugs.swift.org and link to this ticket? Mayby somebody will improve that at some point
