### ISSUE TITLE
Can add namespace for extensions to avoid conflicts?

### ISSUE THREAD

**Issue by alexlee002** [krzyzanowskim/CryptoSwift#797]
I think it's better that the extensions of native-classes, e.g.: String, Array, etc,  should using namespace to avoid conflicts with other frameworks.

E.g.:

```swift
let _ = "123".md5()
```
use namespace like this:

```swift
let _ = "123".crypt.md5()
```
where `crypt` is the namespace for `CryptoSwift`,  or you can use another one.

**Comment by krzyzanowskim** [comment]
that'd be an API breaking change, I don't plan to do that now. I'll keep it in mind for the future.
