### ISSUE TITLE
CryptoSwift encrypts data differently dependent upon iOS version.

### ISSUE THREAD

**Issue by ChrisAndrews1133** [krzyzanowskim/CryptoSwift#798]
**Describe the bug**

CryptoSwift encrypts data differently dependent upon iOS version. 
The library encrypts the data as expected when using xcode 11.3.1 for iOS 11. but not for iOS 13 using the same xcode.   
The project is using running swift 4.2 and I am using CryptoSwift version 1.3.0

**Reproduce**
        
let cryptoLib = CryptLib()
let encyptedData = cryptoLib.encryptPlainText(with: JSON.init(rawValue: self.parameters as Any)?.rawString(), key: "MySecretKey", iv: "MySharedKey")

encyptedData seems to output different data dependent upon os.

I have heard there are issues relating to 34bit devices but this issues seems to occur on both 64 and 32bit architectures.  

Any help would be greatly appreciated,
Chris

**Comment by krzyzanowskim** [comment]
can you attach code that uses CryptoSwift, so I can try to reproduce it on my end, please?

**Comment by ChrisAndrews1133** [comment]
Ahh my apologies I have a bad case of Monday brain, I thought that the CryptoLib object was part of CryptoSwift library. Thanks @krzyzanowskim for replying so quickly!
