### ISSUE TITLE
PBKDF2 is very slow

### ISSUE THREAD

**Issue by p-barabas** [krzyzanowskim/CryptoSwift#799]
**Describe the bug**
PBKDF2 key derivation is very slow.

**Reproduce**
1. Generate a 32 bytes length salt.
2. Use a 44 bytes long password.
3. Iterations count is 4096, hash algorithm is SHA1.
4. Key derivation takes more than 30sec.

Comparing with CommonCrypto, the difference is very significant, it take less then 1 sec. Both solutions are checked in debugger.

**Comment by krzyzanowskim** [comment]
Swift debug build is known to be magnitudes slower than release build.

**Comment by p-barabas** [comment]
But in case of CommonCrypto why not?

**Comment by krzyzanowskim** [comment]
because CommonCrypto is a C framework, delivered to you as a Release build.

**Comment by p-barabas** [comment]
Thanks.
