### ISSUE TITLE
dyld: Symbol not found: xxx

### ISSUE THREAD

**Issue by imfaker** [krzyzanowskim/CryptoSwift#800]
**Describe the bug**

**Reproduce**
1.  Xcode.11.3.1.     af
compile success。 But error appear after run begin .

Error: dyld: Symbol not found: _$s11CryptoSwift4SHA3C7VariantO9keccak256yA2EmFWC
  Referenced from: /private/var/containers/Bundle/Application/2B2EB54D-8D7C-43A8-8CE6-AA8BD73907B0/CZR_Wallet.app/Frameworks/xxx.framework/CryptoEthereumSwift
  Expected in: /private/var/containers/Bundle/Application/2B2EB54D-8D7C-43A8-8CE6-AA8BD73907B0/CZR_Wallet.app/Frameworks/xxx.framework/CryptoSwift
 in /private/var/containers/Bundle/Application/2B2EB54D-8D7C-43A8-8CE6-AA8BD73907B0/xxx.app/Frameworks/CryptoEthereumSwift.framework/CryptoEthereumSwift

What could be the reason?

**Comment by krzyzanowskim** [comment]
The reason is your app project setup. Most likely it doesn't embed CryptoSwift.framework in the bundle, or something similar.

**Comment by imfaker** [comment]
alright！ I found  reason that  is add CryptoSwift twice . The old    One in cocoapods ,  the new import from Carthage.  Success After remove the old one
