### ISSUE TITLE
'try!' expression unexpectedly raised an error: CryptoSwift.AES.Error.invalidKeySize

### ISSUE THREAD

**Issue by KetanMalu** [krzyzanowskim/CryptoSwift#802]
Sometimes Application is crashing with Invalid key size error while decrypting data. My sample code

extension String {

    func toDataArray() -> Array<UInt8> {
        return [UInt8](self.data(using: .utf8)!)
    }
    func fromDataArray() -> Array<UInt8> {
        return [UInt8](self.data(using: .utf8)!)
    }
    func aesEncrypt(key: String, iv: String) throws -> String{
        let encrypted = try AES(key: key.toDataArray(), blockMode: CBC(iv: iv.toDataArray()), padding: Padding.pkcs7).encrypt(toDataArray())
        let encryptedData = Data(encrypted)
        return encryptedData.base64EncodedString()
    }

    func aesDecrypt(key: String, iv: String) throws -> String {
        let data = Data(base64Encoded: self)!
        let decrypted = try AES(key: key, iv: iv, padding: .pkcs7).decrypt([UInt8](data))
        let decryptedData = Data(decrypted)
        if String(bytes: decryptedData.bytes, encoding: .utf8) == nil {
            Answers.logCustomEvent(withName: "AES Decryption error", customAttributes: [:])
        }
        return String(bytes: decryptedData.bytes, encoding: .utf8) ?? ""
    }

 }

Please Guide. If I am missing something

**Comment by krzyzanowskim** [comment]
the size of the key you provide is invalid for encryption, as per error `invalidKeySize`

**Comment by KetanMalu** [comment]
Sir I am getting this error randomly.

**Comment by krzyzanowskim** [comment]
there's nothing random in symmetric encryption though. Make sure you input data is valid, meaning your key is valid size, and you're good.
