### ISSUE TITLE
The operation couldn’t be completed. (CryptoSwift.CCM.Error error 2.)

### ISSUE THREAD

**Issue by purnendu-roy** [krzyzanowskim/CryptoSwift#803]
**Describe the bug**

**Reproduce**
```swift
    let inputData: [UInt8] = [167, 98, 202, 56, 76, 121, 81, 90, 1, 90, 224, 27, 163, 192, 244]
    let nonce: [UInt8] = [227, 184, 45, 84, 234, 157, 227, 184, 45, 84, 234, 157, 0]
    var key: [UInt8] = [0x11, 0x12, 0x22, 0x35, 0x23, 0x55, 0x32, 0x8, 0x9, 0x12, 0xAA, 0xBB, 0xCC, 0xEE, 0xEF, 0xFE]
    let additionalAuthenticateData: [UInt8] = [0x79, 0x75, 0x6c, 0x75, 0x5f, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74]

private func decryptData() -> [UInt8] { //AES-128 Decryption
        do {
let ccm = CCM(iv: self.nonce, tagLength: 2, messageLength: self.inputData.count, additionalAuthenticatedData: self.additionalAuthenticateData)
            let decrypted = try AES(key: self.key, blockMode: ccm, padding: .noPadding).decrypt(self.inputData.drop{$0<0})
            print("decrypted ---> ", decrypted)
            return decrypted
        } catch {
            print(error.localizedDescription)
        }
        return [[UInt8]](())
    }
```

Please fix this asap, I'm facing this problem since long back.

**Comment by krzyzanowskim** [comment]
if you catch the error using `do { } catch { print(error) }`, most likely you'll get a more detailed error type that can give a hint about the nature of the problem you're facing

**Comment by purnendu-roy** [comment]
> if you catch the error using `do { } catch { print(error) }`, most likely you'll get a more detailed error type that can give a hint about the nature of the problem you're facing

After catching the response using "print(error.localizedDescription)" It showing *The operation couldn’t be completed. (CryptoSwift.CCM.Error error 2.)*

and  After catching the response using "print(error)"  It showing *fail*

Please help me

**Comment by purnendu-roy** [comment]
Would you please run above code snippet, and please do let me know are you getting the same error. @krzyzanowskim
