### ISSUE TITLE
Errors in pod files after update

### ISSUE THREAD

**Issue by ajay2c9** [krzyzanowskim/CryptoSwift#805]
Hi,
I'm using CryptoSwift in my project. After updating the project from swift 3.0 to 4.2. I updated the pod with version 0.15.0(Suggested in the document). But there are a lot of issues displaying in files like AES.swift, GCM.swift, Blowfish.swift, scrypt.swift. How to update this pod without causing issues. Below are the screenshots of the errors list. I'm using XCode 10.1, swift 4.2
![Screen Shot 2020-03-18 at 1 00 15 PM](https://user-images.githubusercontent.com/9112899/76936214-87ff2b80-6918-11ea-93a1-7b6c400b1716.png)

![Screen Shot 2020-03-18 at 12 59 58 PM](https://user-images.githubusercontent.com/9112899/76936230-90effd00-6918-11ea-91a9-26683b0e4eec.png)

**Comment by krzyzanowskim** [comment]
rm Pods and re-do pod integration. This happens when wrong swift version is used
