### ISSUE TITLE
Cocoapods: Error when trying to update to 1.3.1

### ISSUE THREAD

**Issue by valmir-massoni-ifood** [krzyzanowskim/CryptoSwift#806]
**Describe the bug**
When I tried to update the dependency to version 1.3.1 cocoa pods returned the following error:

PS: With the version, 1.3.0 cocoapods found the version correctly.

```
[!] CocoaPods could not find compatible versions for pod "CryptoSwift":
  In Podfile:
    CryptoSwift (= 1.3.1)

None of your spec sources contain a spec satisfying the dependency: `CryptoSwift (= 1.3.1)`.

You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
```

**Reproduce**
1. Add crypto swift  1.3.1 as dep on podfile and run `pod repo update` command.

**Comment by krzyzanowskim** [comment]
ups. I forgot to push it to CocoaPods repository. Will do it asap

**Comment by krzyzanowskim** [comment]
🚀  CryptoSwift (1.3.1) successfully published
 📅  April 15th, 23:25
 🌎  https://cocoapods.org/pods/CryptoSwift
