### ISSUE TITLE
AES256GCM 

### ISSUE THREAD

**Issue by malisanjay5433** [krzyzanowskim/CryptoSwift#808]
**Describe the solution you'd like**
I would like to implement AES25CGM, Where my Client_Secret_KEY and Client_Secret_IV are 32 Bytes. 

**Reference: SwiftGCM,SecureCompatibleEncryptionExamples**

**Backend team uses C#  and Android Team uses Java code for Encryption and Decryption**
In iOS i'm unable to do decryption and encryption is working(Changed some code according to backend)-

Does cryptoSwift provides AES256 GCM
Example: Client_Secret_KEY is using for encryption 
```

let Client_Secret_KEY = "78214125442A472D4B6150645367566B" 
let Client_Secret_IV = "78214125442A472D4B6150645367566B"
let plainText = "India"
let encryptedText = "Xf8hOYTfQm3tnN/7y2Q1EjtLBR9z45HNFHoB5RIPH24Ny8rQ7p5APslNqW6bw0ETispBO+Q="
let decrptionText = "India"

```

**Comment by krzyzanowskim** [comment]
> Does cryptoSwift provides AES256 GCM

it does, see [README.md#aes-gcm](https://github.com/krzyzanowskim/CryptoSwift#aes-gcm)
