### ISSUE TITLE
CMAC restricted to 128 bit keys

### ISSUE THREAD

**Issue by overheadhunter** [krzyzanowskim/CryptoSwift#809]
**Describe the bug**
While other libraries (including OpenSSL and BouncyCastle) can operate on any key sizes supported by the block cipher in use, CryptoSwift's CMAC implementation checks for a specific key size:

https://github.com/krzyzanowskim/CryptoSwift/blob/9bddccf5a0c3c948fbb440553578c47002622587/Sources/CryptoSwift/CMAC.swift#L28-L30

I guess the reason why this has been done in the first place is, that this implementation is done according to AES-CMAC defined in RFC 4493, which specifically defines AES-128. 

Note that CMAC itself, as desribed in [NIST.SP.800-38B](https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-38B.pdf) is defined for any block ciphers with 64 and 128 bit block size, not mentioning such a restriction at all.

In fact the key is only used for the block cipher, not for the MAC itself. The subkey generation depends on the cipher's block size, not the key length.

Since other modern ciphers depend on CMAC, I'd like to request to remove this limitation.

[Official test vectors](http://www.nuee.nagoya-u.ac.jp/labs/tiwata/omac/tv/omac1-tv.txt) are defined for AES with 128, 192 and 256 bit keys.

**Reproduce**
1. `let mac = try CMAC.init(key: [UInt8](repeating: 0x00, count: 32))`

**Comment by krzyzanowskim** [comment]
you're right, the current implementation has the block length assumption 
https://github.com/krzyzanowskim/CryptoSwift/blob/9bddccf5a0c3c948fbb440553578c47002622587/Sources/CryptoSwift/CMAC.swift#L23

we should remove this assumption

**Comment by overheadhunter** [comment]
Just to avoid confusion: My main concern is about the _key size_, not the block size!

**Comment by krzyzanowskim** [comment]
right, AES is hardcoded, because of AES-CMAC. It doesn't have to be hardcoded to CMAC as you pointed out.

from https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-38B.pdf

> The forward cipher function is a permutation on bit strings of a fixed length; the strings are called blocks.  The bit length of a block is denoted b, and the length of a block is called the block size.  For  the  AES  algorithm,  b =  128;  for  TDEA,  b =  64.    The  key  is  denoted  K,  and  the  resulting  forward cipher function of the block cipher is denoted CIPHK.

I think It's feasible to make it work with any cipher - not that CryptoSwift has many to offer.

**Comment by overheadhunter** [comment]
Maybe split this issue then?
1. Remove key size restriction, thus allow any key sizes, the block cipher allows
2. Allow any block ciphers

The first one should be fairly easy to fix and will allow AES-192 and AES-256 simply by removing the check in line 28.
