### ISSUE TITLE
Array index out of range while trying to encrypt/decrypt

### ISSUE THREAD

**Issue by imrielruchi** [krzyzanowskim/CryptoSwift#81]
Hi,

I am trying to encrypt using AES with CryptoSwift. when i run below code it throws error "fatal error: Array index out of range".

   let key = "1234567890123456" // key
   let iv = "1234567890123456" // random
   let message = "This is test string"

    // encrypt
    let encrypted = AES(key: key, iv: iv, blockMode: .CBC)
    let enc =  encrypted?.encrypt(message.utf8Array, padding: PKCS7())
    println("enc >>  \(enc)")

    // decrypt
    let decrypted = AES(key: key, iv: iv, blockMode: .CBC)
    let dec =  encrypted?.decrypt(enc!, padding: PKCS7())
    println("dec >>  \(dec)")

**Comment by krzyzanowskim** [comment]
what is utf8Array() ?

**Comment by imrielruchi** [comment]
it is converting String to byte array.

extension String {
    var utf8Array: [Byte] {
        return Array(utf8)
    }
}

**Comment by imrielruchi** [comment]
also tried using this code..still throw same error.

let key = "1234567890123456" // key
let iv = "1234567890123456" // random
let message = "This is test string"
let encrypted = message.aesEncrypt(key, iv: iv)

import CryptoSwift
extension String { 
func aesEncrypt(key: String, iv: String) -> String {
    let data = self.dataUsingEncoding(NSUTF8StringEncoding)
    let enc = AES(key: key, iv: iv, blockMode:.CBC)?.encrypt(data!.arrayOfBytes(), padding: PKCS7())
    let encData = NSData(bytes: enc!, length: Int(enc!.count))
    let base64String: String = encData.base64EncodedStringWithOptions(NSDataBase64EncodingOptions(rawValue: 0));
    let result = String(base64String)
    return result
}

func aesDecrypt(key: String, iv: String) -> String {
    let data = NSData(base64EncodedString: self, options: NSDataBase64DecodingOptions(rawValue: 0))
    let dec = AES(key: key, iv: iv, blockMode:.CBC)?.decrypt(data!.arrayOfBytes(), padding: PKCS7())
    let decData = NSData(bytes: dec!, length: Int(dec!.count))
    var result = NSString(data: decData, encoding: NSUTF8StringEncoding)
    return String(result!)
}
}

**Comment by krzyzanowskim** [comment]
can you pleas split it into some small chunk where the issue actually occurs ? then look at the debugger. I do it later today.

**Comment by imrielruchi** [comment]
yes i have debug the code and the issue occuring on this line of AES.swift

return [4,6,8][self.rawValue - 1] // this cause the array index out of range.

**Comment by krzyzanowskim** [comment]
are you using the most update version? (master branch)

**Comment by imrielruchi** [comment]
I am using this code https://github.com/krzyzanowskim/CryptoSwift

and using xcode 6.3.2

**Comment by imrielruchi** [comment]
ohhh i see..i think develop branch may work..i will try.

**Comment by krzyzanowskim** [comment]
no, master branch, with the most recent change.

**Comment by imrielruchi** [comment]
alright..thanks a lot for help.

**Comment by imrielruchi** [comment]
Hi,

When i am using master branch error coming...in develop branch no error coming.

**Comment by archie** [comment]
We've run into the same problem. 

From the [Swift documentation](https://developer.apple.com/library/ios/documentation/Swift/Conceptual/Swift_Programming_Language/Enumerations.html)

> Unlike C and Objective-C, Swift enumeration members are not assigned a default integer value when they are created. In the CompassPoint example above, North, South, East and West do not implicitly equal 0, 1, 2 and 3. Instead, the different enumeration members are fully-fledged values in their own right, with an explicitly-defined type of CompassPoint.

We're suggesting the following patch to force the enumeration start at 1: 

```
diff --git a/CryptoSwift/AES.swift b/CryptoSwift/AES.swift
index d8665af..7f052e8 100644
--- a/CryptoSwift/AES.swift
+++ b/CryptoSwift/AES.swift
@@ -11,7 +11,7 @@ import Foundation
 final public class AES {

     public enum AESVariant:Int {
-        case aes128, aes192, aes256
+        case aes128 = 1, aes192, aes256

         var Nk:Int { // Nk words
             return [4,6,8][self.rawValue - 1]
```

**Comment by krzyzanowskim** [comment]
oh damn, this is my last change removing "unknown" case ;) NICE ONE! @archie can you prepare PR?

**Comment by archie** [comment]
Just about to leave the office. Feel free to do the edit yourself, no PR needed ;)

**Comment by archie** [comment]
:clap: 

Thanks @krzyzanowskim !

**Comment by shashidev** [comment]
Hi krzyzanowskim ,
I am getting "Reason:Image Not Found"exception on ipad pro for iOS9.3. But for iOS 10 it is working fine. So may I assume that the CryptoSwift Library only support for ios10 or if I am wrong plz tell us the solution.

**Comment by shashidev** [comment]
This Exception I am getting when I try to build the plication on less than IOS10 .
dyld: Library not loaded: @rpath/CryptoSwift.framework/CryptoSwift
  Referenced from: /var/containers/Bundle/Application/FCB597A2-E486-4AE9-88E4-B97C4E1839D4/SwiftEncryptDecrypt.app/SwiftEncryptDecrypt
  Reason: image not found .
