### ISSUE TITLE
Change copyright statement for contributed source code

### ISSUE THREAD

**Issue by overheadhunter** [krzyzanowskim/CryptoSwift#811]
Moving the discussion from [this PR](https://github.com/krzyzanowskim/CryptoSwift/pull/242#discussion-diff-59982612) to its own issue, since it longer than expected and getting off-topic for the pull request.

TL;DR: Project initiator wants everyone to add this line to contributed source code files:

https://github.com/krzyzanowskim/CryptoSwift/blob/3a59b258ebf17078eb44a1b4499680a78b4f452c/CONTRIBUTING.md#L16

I think it is incorrect.

**Describe the solution you'd like**

I suggest to change the statement to `Copyright (C) The CryptoSwift Contributors`, as the contributors are listed in a separate file and from a legal perspective we're dealing with shared code ownership anyway (at least in the EU, see directive 2009/24/EC, Article 2).

**Rationale (and continued discussion)**

To continue the aforementioned discussion: @krzyzanowskim last wrote:

> What I can't and don't want to accept is `All rights reserved.`.

I fully agree on that! I don't think this is applictable anyway, since contributors give up most right by contributing code under a set license. (Still they are the copyright holders of their contribution 😉)

> [...] As long as the code has a history, the author's information is accessible line per line.

This is indeed what many open source projects do: Start with the copyright statement of one author and add further authors line by line in case of further contributions. This isn't what I have seen in this project, though. :thinking:

Anyway, IMO this isn't very practicable: Contributors might forget to add themselves and in the meantime it might be hard to revert each single file to list every single contributor.

Since you already have a `CONTRIBUTORS.txt`, I'd rather suggest to change the statement `Copyright (C) The CryptoSwift Contributors`.

> From a legal perspective, leaving “// Copyright (C) Marcin Krzyżanowski marcin@krzyzanowskim.com” in the headers does not affect the contributors’ rights.

I disagree. I'm not a lawyer and I can't speak for the legal situation in every single country on the world. But at least in some member states of the EU you have the burden of proof if you claim to be the author of some code and it says otherwise. I don't say this proof is impossible (git history to the rescue), but at least it is incorrect to say it doesn't affects the contributors rights.

**Comment by krzyzanowskim** [comment]
> I'm not a lawyer and I can't speak for the legal situation in every single country on the world.

From a legal perspective (based on my own research and imitating some big corps in that matter) header or no header does not affect the contributors’ rights. It does repeat the license, and the code that land to this repo have to be licensed to be usable at all and this is my preferred way to keep it that way.

**Comment by overheadhunter** [comment]
If you are convinced that from a legal standpoint it doesn't matter anyway, why do you insist of putting your name on the work of others?

**Comment by krzyzanowskim** [comment]
> why do you insist of putting your name on the work of others?

I don't, as already I explained.

I don't see the point of this discussion any further. I don't want to re-license the code of this project. I don't want to change the license. Thank you for your thoughts but I believe I cleared it out.

I ask to follow https://github.com/krzyzanowskim/CryptoSwift/blob/master/CONTRIBUTING.md before I can accept code to the repository. I'm not going on crusade if anyone doesn't feel comfortable with that.

**Comment by overheadhunter** [comment]
> I don't

Glad to hear that.

In this case I obviously misunderstand `CONTRIBUTING.md`. I had the impression you want contributors to _literally_ include the line `Copyright (C) Marcin Krzyżanowski <marcin@krzyzanowskim.com>`, not that it was meant as a template and one is free to put in ones own name.

So your comment in #242 was not about the authors name, but about the "All rights reserved." statement, then?
