### ISSUE TITLE
AES - GCM - 256 | Random value at the end

### ISSUE THREAD

**Issue by KaanYT** [krzyzanowskim/CryptoSwift#813]
**Describe the bug**
Hi,
When I encrypt with GCM, I encounter random characters at the end of the input. I tested this on NodeJS and [CyberChef](https://gchq.github.io/CyberChef/#recipe=AES_Decrypt(%7B'option':'Base64','string':'41G2xFCJpFVryg1lKRXFtZpNeqkId78wzkyWcovRYBU%3D'%7D,%7B'option':'Base64','string':'Uqwc8VO2FMDYUsCGWYDSkg%3D%3D'%7D,'GCM','Hex','Raw',%7B'option':'Base64','string':'MdDanuat2BeISFt3BGJwHA%3D%3D'%7D)&input=ODVDODhCNkE2RkZERDQyNTcxNjM4NEI2RDhDMDk0Q0VGRjJFOTIwMjk2NkNGMjIwQjdCQTRCNzA2NEI4M0VERg). When I decrypted with CryptoSwift, I did not have any problems.

PS: NodeJS has [autopadding](https://nodejs.org/api/crypto.html#crypto_cipher_setautopadding_autopadding) which use PKCS7. I believe this might be padding issue. 

**Reproduce**
```swift
    private static let TAG_SIZE_IN_BYTE = 16;
    fileprivate static let KEY_SIZE = 32;
    // MARK: - AES
    func encryptWithAES1(data:String) -> String {
       let iv: Array<UInt8> = AES.randomIV(AES.blockSize)
       let key = AES.randomIV(KEY_SIZE)
       do {
           let mode = GCM(iv: Array(iv), tagLength:TAG_SIZE_IN_BYTE, mode: .combined)
           let encrypted = try AES(key: key, blockMode: mode, padding: .pkcs7).encrypt(Array(data.utf8))
           let all = (encrypted + iv).toBase64()!
           print("IV:" + (iv).toBase64()!)
           print("Key:" + (key).toBase64()!)
           print("Tag:" + (mode.authenticationTag!).toBase64()!)
           let enc = Array(encrypted.dropLast(TAG_SIZE_IN_BYTE))
           print("Enc:" + (enc).toBase64()!)
           print("Enc In Hex:" +bytesConvertToHexstring(byte: enc))
           return all
       } catch {
           Log.e(error)
       }
       return ""
    }
    static func bytesConvertToHexstring(byte : [UInt8]) -> String {
        var string = ""
        for val in byte {
            string = string + String(format: "%02X", val)
        }
        return string
    }
encryptWithAES1(data: "{Test Test Test test}")
```
**Example**

```
Input:{Test Test Test test}
IV:Uqwc8VO2FMDYUsCGWYDSkg==
Key:41G2xFCJpFVryg1lKRXFtZpNeqkId78wzkyWcovRYBU=
Tag:MdDanuat2BeISFt3BGJwHA==
Enc:hciLam/91CVxY4S22MCUzv8ukgKWbPIgt7pLcGS4Pt8=
Enc In Hex:85C88B6A6FFDD425716384B6D8C094CEFF2E9202966CF220B7BA4B7064B83EDF
Output :{Test Test Test test}
```

**Other Tests**
I also test this in [SwCrypt](https://github.com/soyersoyer/SwCrypt). It did not produce any random strings(<0x0b>) at the end.
```swift
let keyData = Data(bytes: key, count: key.count)
let ivData = Data(bytes: iv, count: iv.count)
let encrypted = try CC.cryptAuth(.encrypt, blockMode: .gcm, algorithm: .aes, data: data, aData: Data(), key: keyData, iv: ivData, tagLength:TAG_SIZE_IN_BYTE)
```

**Comment by krzyzanowskim** [comment]
You don't need padding, look at https://github.com/krzyzanowskim/CryptoSwift#aes-gcm

```
AES(key: key, blockMode: mode, padding: .nopadding)
```

> PS: NodeJS has autopadding which use PKCS7. I believe this might be padding issue.

it doesn't mean the padding is always added. For GCM padding makes a little sense, so I guess it automatically doesn't do that.
