### ISSUE TITLE
CryptoSwift uses weak hash MD5 & SHA1

### ISSUE THREAD

**Issue by aviraj-ios** [krzyzanowskim/CryptoSwift#815]
We ran the security check on the application and we got to know that CryptoSwift uses weak hash MD5 & SHA1 which are a risky cryptographic algorithm.

<img width="847" alt="Screenshot 2020-05-19 at 6 52 26 PM" src="https://user-images.githubusercontent.com/57542769/82332625-4287d900-9a03-11ea-9e64-9b56b28f5748.png">
<img width="839" alt="Screenshot 2020-05-19 at 6 44 57 PM" src="https://user-images.githubusercontent.com/57542769/82332640-47e52380-9a03-11ea-8145-c19ff596ecb6.png">

**Comment by krzyzanowskim** [comment]
>  CryptoSwift uses weak hash MD5 & SHA1

Thank you. I'm not sure what's your point? CryptoSwift is a collection of cryptographic algorithms, including MD5, SHA1, and others.

**Comment by aviraj-ios** [comment]
@ krzyzanowskim
Apologies for not being descriptive. Actually our application needs to pass all securities check and our application OR any library used by our application must not use weak cryptographic algorithms, including MD5, SHA1. Is there any way in CryptoSwift library where I can remove/block the usage of these two cryptographic algorithms?
