### ISSUE TITLE
Cant build universal library

### ISSUE THREAD

**Issue by ScottieY** [krzyzanowskim/CryptoSwift#82]
when i run the script it gives me this error

fatal error: lipo: can't open input file: build/Release-iphoneos/CryptoSwift.framework/CryptoSwift (No such file or directory)

**Comment by krzyzanowskim** [comment]
can you fix the script, with PR?

**Comment by krzyzanowskim** [comment]
Can't confirm the issue.
![screen shot 2015-08-22 at 10 59 31](https://cloud.githubusercontent.com/assets/758033/9423341/3edc1544-48c0-11e5-95bc-9f568c53ac39.png)


Not further details - closing.

**Comment by alexrmacleod** [comment]
hey I'm having the same problem, my framework folder is empty, where do I download the contents for this framework folder?

**Comment by krzyzanowskim** [comment]
check this: https://github.com/krzyzanowskim/CryptoSwift/issues/113#issuecomment-133670461
