### ISSUE TITLE
运行在Xcode10上报错，missing return a function

### ISSUE THREAD

**Issue by yuantan** [krzyzanowskim/CryptoSwift#823]
var Nk: Int { // Nk words
      [4, 6, 8][self.rawValue - 1]
    }

    var Nb: Int { // Nb words
      4
    }

    var Nr: Int { // Nr
      self.Nk + 6
    }

运行在Xcode10上会报错，是因为语法匹配不上的缘故吗？但是Xcode10上面已经支持4、4.2、5的语言了

**Comment by krzyzanowskim** [comment]
You need choose the right CryptoSwift version for the Swift compiler version. See https://github.com/krzyzanowskim/CryptoSwift#swift-versions-support
