### ISSUE TITLE
[Carthage] CryptoSwift fails to build on 12.0 beta 3 (12A8169g)

### ISSUE THREAD

**Issue by pigfly** [krzyzanowskim/CryptoSwift#824]
**Describe the bug**

- CryptoSwift fails to build on 12.0 beta 3 (12A8169g)

```
Build Failed
	Task failed with exit code 1:
	/usr/bin/xcrun lipo -create /Users/ajiang1/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A8169g/CryptoSwift/1.3.1/Build/Intermediates.noindex/ArchiveIntermediates/CryptoSwift/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/CryptoSwift.framework/CryptoSwift /Users/ajiang1/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A8169g/CryptoSwift/1.3.1/Build/Products/Release-iphonesimulator/CryptoSwift.framework/CryptoSwift -output /Users/ajiang1/Documents/Projects/tonline-ios-app/Carthage/Build/iOS/CryptoSwift.framework/CryptoSwift
```

**Reproduce**
Steps to reproduce:

1. Delete derived Carthage Cache.
2. Delete Carthage directory in project.
3. Uninstall Carthage and install again.
4. `xcode-select --switch` to choose the Xcode 12 beta
5. Remove `/Library/Caches/org.carthage.CarthageKit/DerivedData/`
6. `carthage update --platform iOS --no-use-binaries`

**Comment by pigfly** [comment]
Hi there, Want to give an update on this, CryptoSwift fails to compile on **Version 12.0 beta 4 (12A8179i)** using Carthage

**Comment by s-hintz** [comment]
The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'CryptoSwift' from project 'CryptoSwift')

**Comment by pigfly** [comment]
Hi @s-hintz,  I presume this something within the `CryptoSwift` itself, just went to the checkout folder inside carthage, found the `IPHONEOS_DEPLOYMENT_TARGET` is 8.0.

**Comment by s-hintz** [comment]
@pigfly Yes. I think if you increase it to 9.0 it should work with the new Xcode.

**Comment by pigfly** [comment]
@s-hintz thanks for that. But for CI which is SAAS (e.g. bitrise), we don't have direct access to the server, so changing the `IPHONEOS_DEPLOYMENT_TARGET` manually is not possible..

Could you please include this fix in the next release ?

I'll go and test out the `IPHONEOS_DEPLOYMENT_TARGET` bump locally and let you know.

**Comment by krzyzanowskim** [comment]
Mind you make a PR?

**Comment by pigfly** [comment]
@krzyzanowskim yeah, I'll make one once verified working

**Comment by pigfly** [comment]
Hi @s-hintz , @krzyzanowskim:

Looks like it fails with `IPHONEOS_DEPLOYMENT_TARGET` set to 9.0 in both target and project with `carthage build CryptoSwift --platform iOS`

![Screen Shot 2020-08-24 at 10 16 37 am](https://user-images.githubusercontent.com/1074069/90992639-69ead500-e5f4-11ea-8fb2-12b766f2c722.png)


Failed on the step for `lipo create`:

```
Build Failed
	Task failed with exit code 1:
	/usr/bin/xcrun lipo -create /Users/ajiang1/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A8179i/CryptoSwift/1.3.0/Build/Intermediates.noindex/ArchiveIntermediates/CryptoSwift/IntermediateBuildFilesPath/UninstalledProducts/appletvos/CryptoSwift.framework/CryptoSwift /Users/ajiang1/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A8179i/CryptoSwift/1.3.0/Build/Products/Release-appletvsimulator/CryptoSwift.framework/CryptoSwift -output /Users/ajiang1/Documents/Projects/iOS12/Carthage/Build/tvOS/CryptoSwift.framework/CryptoSwift

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/6n/fq73zkxs7bs6chc6ssn5lk0htntwwg/T/carthage-xcodebuild.ouGLOC.log
```

One thing I noticed in the carthage xcodebuild log is it saying **BUILD SUCCEEDED** for the following command:

```
CreateUniversalBinary /Users/ajiang1/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A8179i/CryptoSwift/1.3.0/Build/Products/Release-appletvsimulator/CryptoSwift.framework/CryptoSwift normal arm64\ x86_64 (in target 'CryptoSwift' from project 'CryptoSwift')
    cd /Users/ajiang1/Documents/Projects/iOS12/Carthage/Checkouts/CryptoSwift
    /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo -create /Users/ajiang1/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A8179i/CryptoSwift/1.3.0/Build/Intermediates.noindex/CryptoSwift.build/Release-appletvsimulator/CryptoSwift.build/Objects-normal/arm64/Binary/CryptoSwift /Users/ajiang1/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A8179i/CryptoSwift/1.3.0/Build/Intermediates.noindex/CryptoSwift.build/Release-appletvsimulator/CryptoSwift.build/Objects-normal/x86_64/Binary/CryptoSwift -output /Users/ajiang1/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A8179i/CryptoSwift/1.3.0/Build/Products/Release-appletvsimulator/CryptoSwift.framework/CryptoSwift

Touch /Users/ajiang1/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A8179i/CryptoSwift/1.3.0/Build/Products/Release-appletvsimulator/CryptoSwift.framework (in target 'CryptoSwift' from project 'CryptoSwift')
    cd /Users/ajiang1/Documents/Projects/iOS12/Carthage/Checkouts/CryptoSwift
    /usr/bin/touch -c /Users/ajiang1/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A8179i/CryptoSwift/1.3.0/Build/Products/Release-appletvsimulator/CryptoSwift.framework
```

**Comment by s-hintz** [comment]
I switched from Carthage to Swift packages for CryptoSwift.
This seems to fix the compilation problems for me.

**Comment by s-hintz** [comment]
The underlying problem seems to be related to Carthage, since also other frameworks can not be build with Carthage anymore under Xcode 12.
https://github.com/Carthage/Carthage/issues/3019

**Comment by pigfly** [comment]
@s-hintz 

Thanks for that, tried the following seems to bypass the `lipo create` fails to generate fat framework.

```
EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_simulator__NATIVE_ARCH_64_BIT_x86_64=arm64 arm64e armv7 armv7s armv6 armv8
EXCLUDED_ARCHS=$(inherited) $(EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_$(EFFECTIVE_PLATFORM_SUFFIX)__NATIVE_ARCH_64_BIT_$(NATIVE_ARCH_64_BIT))
```
