### ISSUE TITLE
Symbol not found: _$s11CryptoSwift7PaddingO5pkcs7yA2CmFWC

### ISSUE THREAD

**Issue by chrisShick** [krzyzanowskim/CryptoSwift#825]
I have two private frameworks (3rd party) that use CryptoSwift. 

Framework 1 suggests installing with cocoapods while Framework 2 suggests using carthage.

When installing with cocoapods, Framework 2 throws the below error at run time on the device:
dyld: Symbol not found: _$s11CryptoSwift7PaddingO5pkcs7yA2CmFWC
  Referenced from: /private/var/containers/Bundle/Application/94E49A38-E3C0-4CDB-8EE7-D49767C0630F/Redacted/Frameworks/Framework1.framework/FMService
  Expected in: /private/var/containers/Bundle/Application/94E49A38-E3C0-4CDB-8EE7-D49767C0630F/Redacted/Frameworks/CryptoSwift.framework/CryptoSwift
 in /private/var/containers/Bundle/Application/94E49A38-E3C0-4CDB-8EE7-D49767C0630F/Redacted/Frameworks/Framework1.framework/FMService

The same is thrown from framework 2 when using carthage to install CryptoSwift:
dyld: Symbol not found: _$s11CryptoSwift7PaddingO5pkcs7yA2CmFWC
  Referenced from: /private/var/containers/Bundle/Application/94E49A38-E3C0-4CDB-8EE7-D49767C0630F/Redacted/Frameworks/Framework2.framework/GWService
  Expected in: /private/var/containers/Bundle/Application/94E49A38-E3C0-4CDB-8EE7-D49767C0630F/Redacted/Frameworks/CryptoSwift.framework/CryptoSwift
 in /private/var/containers/Bundle/Application/94E49A38-E3C0-4CDB-8EE7-D49767C0630F/Redacted/Frameworks/Framework2.framework/GWService

**Comment by krzyzanowskim** [comment]
transitive dependencies, there's nothing I can do about it.
I don't think that Cocoapods will see Carthage dependencies and vice-versa unless you set up linking manually. Better to ask Cocoapods and/or Carthage it they have any support for that situation (I doubt it, but who knows).

**Comment by deepesh-vasthimal-cko** [comment]
@chrisShick were you able to solve this issue. I have a similar crash but in my case I am only using one one deependency manager both in framework and app which is cocopods. See this : https://stackoverflow.com/questions/64657668/custom-framework-dyld-symbol-not-found-s11cryptoswift7paddingo5pkcs7ya2cmf
