### ISSUE TITLE
How to extract string from certificate with help of CryptoSwift? 

### ISSUE THREAD

**Issue by anis-applocum** [krzyzanowskim/CryptoSwift#828]
Help Needed

For SSL Pinning I've to compare two strings.
First one is retrieved using below code in terminal. I've used github host.
4PhpWPCTGkqmmjRFussirzvNSi4LjL7WWhUSAVFIXDc=
//download certificate in local
openssl s_client -connect github.com:443 </dev/null | openssl x509 -outform DER -out git.cer

// Generate key
openssl x509 -inform DER -in git.cer |\
openssl x509 -pubkey -noout |\
openssl rsa -pubin -outform DER |\
openssl dgst -sha256 -binary |\
openssl enc -base64

I want to know how Can I generate same string from Cryptoswift using certificate.

4PhpWPCTGkqmmjRFussirzvNSi4LjL7WWhUSAVFIXDc=

**Comment by krzyzanowskim** [comment]
you can't do this with CryptoSwift as CryptoSwift does not have support for x509 nor RSA

**Comment by anis-applocum** [comment]
Okay thanks
