### ISSUE TITLE
Thread mamagment

### ISSUE THREAD

**Issue by benjimkh** [krzyzanowskim/CryptoSwift#831]
Hello.
First of all sorry if the English is not very good.

So here is the thing,i have this app that get  chunks of the Data with stream, wich are all encrypted and i do decrypt each chunk one by one and after that i save it to a local repo and make a new data with all those decrypted data.

The problem is it is soo so so laggy and when i try to mamage threads and handle the decipher and decryption process in the back thread it gave me lots of errors in the lib(crypto swift) it self.
What should i do.is thia library made to be used in back thread or am i using it wrong?

**Comment by krzyzanowskim** [comment]
It really depends on how you use it. You have to synchronize data by yourown. If you process parts of data in parallel, you have to care about synchronization. There's no magic to it.
