### ISSUE TITLE
1.3.4 / 1.3.5 break swift package generate-xcodeproj

### ISSUE THREAD

**Issue by valeriomazzeo** [krzyzanowskim/CryptoSwift#839]
Since `1.3.4` (and `1.3.5`) includes of the binary framework, is no longer possible to generate an xcodeproject using `swift package generate-xcodeproj`.

Example `Package.swift` that works fine:
```swift
import PackageDescription

let package = Package(
    name: "MyLibrary",
    platforms: [
       .macOS(.v10_15), .iOS(.v12)
    ],
    products: [
        .library(
            name: "MyLibrary",
            targets: ["MyLibrary"]),
    ],
    dependencies: [
        .package(url: "https://github.com/krzyzanowskim/CryptoSwift.git", .exact("1.3.3"))
    ],
    targets: [
        .target(
            name: "MyLibrary",
            dependencies: ["CryptoSwift"]),
        .testTarget(
            name: "MyLibraryTests",
            dependencies: ["MyLibrary"]),
    ]
)
```

Output with `1.3.4` and `1.3.5`:
```
$ MyLibrary % swift package generate-xcodeproj
Fetching https://github.com/krzyzanowskim/CryptoSwift.git
Cloning https://github.com/krzyzanowskim/CryptoSwift.git
Resolving https://github.com/krzyzanowskim/CryptoSwift.git at 1.3.5
[13280/13280] Downloading binary artifacts
Fatal error: file Xcodeproj/pbxproj.swift, line 400
zsh: illegal hardware instruction  swift package generate-xcodeproj
```

**Comment by krzyzanowskim** [comment]
huh, because it has a binary target and script can't handle the scale.
You'd need to comment out that part in `Package.swift` then run the generation script.

Why would you need to run it though? There's provided Xcode project in the repo you can use.

**Comment by valeriomazzeo** [comment]
Hi @krzyzanowskim,

>Why would you need to run it though? There's provided Xcode project in the repo you can use.

Not sure I understand what you mean. I am trying to import `CryptoSwift` as a dependency into one of my packages. It's been working fine until (and excluded) `v1.3.4+`.

**Comment by krzyzanowskim** [comment]
why do you need to run 'swift package generate-xcodeproj'? You shouldn't need it. I'm curious in what scenario it may be needed.

either use Xcode project that is already in the repo, or integrate as Swift Package Manage package.

**Comment by krzyzanowskim** [comment]
oh wait, do you mean that when CryptoSwift is a transient dependency, and you generate Xcode project for another SPM package maybe? (I wish SPM support that scenario with binary targets properly)

**Comment by krzyzanowskim** [comment]
https://bugs.swift.org/browse/SR-13870

**Comment by krzyzanowskim** [comment]
> `swift package generate-xcodeproj` is officially deprecated now: https://github.com/apple/swift-package-manager/pull/3062

[SR-13870](https://bugs.swift.org/browse/SR-13870?focusedCommentId=59833#comment-59833)

**Comment by krzyzanowskim** [comment]
Given the circumstances, closing as: won't-fix ;-(
