### ISSUE TITLE
1.3.5 - Released framework contains no symlinks

### ISSUE THREAD

**Issue by edualm** [krzyzanowskim/CryptoSwift#841]
The framework that's distributed as a binary framework for `1.3.5` appears to be invalid.

When archiving the macOS app for distribution, Xcode complains:

```
Multiple binaries share the same codesign path:
/Applications/AppName.app/Contents/Frameworks/CryptoSwift.framework/Versions/Current

Binaries:
/Applications/AppName.app/Contents/Frameworks/CryptoSwift.framework/Versions/Current/CryptoSwift
/Applications/AppName.app/Contents/Frameworks/CryptoSwift.framework/CryptoSwift
```

And if you check the `xcframework` file that you are distributing...

<img width="314" alt="image" src="https://user-images.githubusercontent.com/387713/99892236-c8af0180-2c6a-11eb-8c03-d0d3febd0744.png">

`Current` should be a symlink, not a folder - and that's just an example.

If I download the project, and compile the framework for macOS myself, it's generated correctly:

<img width="234" alt="image" src="https://user-images.githubusercontent.com/387713/99892268-1b88b900-2c6b-11eb-95fe-58dc46d2b265.png">

This is probably just an issue with the way you generated the `zip` file. :)

**Comment by krzyzanowskim** [comment]
make sense. it may be zip command thing. I'll take a look at it. Do you have proper zip command around by any chance?

**Comment by edualm** [comment]
I'm afraid I don't know that, *but* I tried to create the `zip` file using Finder (right-click the framework, compress) and it worked just fine!

**Comment by krzyzanowskim** [comment]
I'm pretty sure I didn't use anything else than Finder. that's odd

**Comment by edualm** [comment]
That's weird, yes.

If you want to share the command you used to create the xcframework I can give it a try, and see how it works for me.

**Comment by edualm** [comment]
I just tried again using Finder and it worked fine.

You can also try the following in Terminal: `zip --symlinks -r output-file.zip input.framework/`. That worked for me also.

**Comment by krzyzanowskim** [comment]
> If you want to share the command you used to create the xcframework I can give it a try, and see how it works for me.

run `./scripts/build-framework.sh` that's the script that I use to build xcframework

https://github.com/krzyzanowskim/CryptoSwift/blob/e849d9857a23a2308e2dd72667afd99e4af9bfc3/scripts/build-framework.sh#L99

**Comment by krzyzanowskim** [comment]
@edualm I think I figured. Can you check the attached archive?

[CryptoSwift.xcframework.zip](https://github.com/krzyzanowskim/CryptoSwift/files/5579527/CryptoSwift.xcframework.zip)

**Comment by edualm** [comment]
Appears right to me!

**Comment by krzyzanowskim** [comment]
thanks. Closing now. I'll release binary updates as v1.3.6
