### ISSUE TITLE
Swift 5 / XCode 12 - Several warnings for specialized export

### ISSUE THREAD

**Issue by utdrmac** [krzyzanowskim/CryptoSwift#848]
Added library to my project. Complied:

Got this warning about 10 times across 3 files (UInt64+Extension, UInt32+Extension, Generics)

`'exported: true' has no effect in '_specialize' attribute`

Don't know what it means, nor what to do to remove the warnings. I understand safe to ignore, but I like having clean builds.

**Comment by krzyzanowskim** [comment]
what version did you pull? this warning was addressed at some point and it's not in there since 1.3.2 or so.

**Comment by utdrmac** [comment]
Looks like I got 1.3.1. This library is a dependency for the main library I am using in my app. I'll open an issue with the author and ask them to update the dependency. Thanks!

**Comment by adham-ashraf77** [comment]
can you provide the solution

**Comment by krzyzanowskim** [comment]
@adham-ashraf77 the solution is an update. this code is not in the codebase for almost a year now.

**Comment by adham-ashraf77** [comment]
i'm using flutter and run pod update and get version 0.15.0 don't know why don't get the last version

**Comment by krzyzanowskim** [comment]
I don't know either

<img width="470" alt="Screenshot 2021-05-04 at 10 56 39" src="https://user-images.githubusercontent.com/758033/116981147-6bae8180-acc7-11eb-8b42-ce762b4b0f51.png">

**Comment by adham-ashraf77** [comment]
is there a way to force update

**Comment by krzyzanowskim** [comment]
I think delete `Podfile.lock` and `Pods` directory should force cocoapods to refetch deps
