### ISSUE TITLE
AES GCM (256) decryption not working in detached mode

### ISSUE THREAD

**Issue by sreekanthps** [krzyzanowskim/CryptoSwift#850]
**Describe the bug**

While decrypting the data (encrypted in detached mode) is not working, where in the same is working fine for combined mode

**Reproduce**
Steps to reproduce:
1. Create Xcode project with CryptoSwift cocoa depedency
2. Add the below code for encryption and decryption

===================

keyData =  try! randomData(ofLength: 32)
ivData = try! randomData(ofLength: 16)

public func randomData(ofLength length: Int) throws -> Data? {
        var bytes = [UInt8](repeating: 0, count: length)
        let status = SecRandomCopyBytes(kSecRandomDefault, length, &bytes)
        if status == errSecSuccess {
            return Data(bytes)
        }
        // throw an error
        return nil
    }
    
    func encryptKey() {
        if let iv = ivData?.hexEncodedString(), let key = keyData?.hexEncodedString() {
            // In combined mode, the authentication tag is directly appended to the encrypted message. This is usually what you want.
            let gcm = GCM(iv: [UInt8](hex: iv), mode: .detached)
            let aes = try! AES(key: [UInt8](hex: key), blockMode: gcm, padding: .noPadding)
            encrypted = try! aes.encrypt(plaintext)
            let tag = gcm.authenticationTag
            
        
        }
          
        
    }
    
    func decryptKey() {
        do {
            // In combined mode, the authentication tag is appended to the encrypted message. This is usually what you want.
            if let iv = ivData?.hexEncodedString(), let key = keyData?.hexEncodedString() {
                let gcm = GCM(iv:  [UInt8](hex: iv), mode: .detached)
                let aes = try AES(key: [UInt8](hex: key), blockMode: gcm, padding: .noPadding)
                let plaintext =  try aes.decrypt(encrypted)
                print("plaintext ::::::: \(plaintext)")
                if let stringtext = String(bytes: plaintext, encoding: .utf8) {
                    print("stringtext ::::::: \(stringtext)")
                }
            }
            
        } catch {
            print(error.localizedDescription)
        }
    }

**Comment by Craz1k0ek** [comment]
When decrypting you're required to insert the authentication tag into the cipher, which you're not doing in your example code.
```swift
let gcm = GCM(iv: Array(ivData!), authenticationTag: tag, mode: .detached)
```

Another minority, you can omit the `.noPadding` in the creation of the AES object. GCM works like (works like **≠** is) a stream cipher.

Another thing I'd like to point out, instead of going from `Data` to `String` to `[UInt8]`, by using hex, consider using it directly.
```swift
let key = try! randomData(ofLength: 32)
let keyBytes = Array(key)
```

**Comment by CristianMoreno45** [comment]
tks @Craz1k0ek, you are the best!!!

**Comment by krzyzanowskim** [comment]
@Craz1k0ek thank you. It looks like useful piece of documentation that could land in README somewhere. Mind creating PR?

**Comment by Craz1k0ek** [comment]
> It looks like useful piece of documentation

You're talking about the 12 byte Initialization Vector? I can create a PR for that!
