### ISSUE TITLE
Implement AES 128 

### ISSUE THREAD

**Issue by ShashankOodles1** [krzyzanowskim/CryptoSwift#857]
Hi
I want to implement AES 128 and i am using encoder and decoder for parsing data but I want how i can use Crypto swift to implement this here is my code snippet
 let secureKey =  obj1.randomString(length: 31) as String
                let iv = obj1.randomString(length: 15) as String
        let cryptoLib = cry
                username = cryptoLib.encryptPlainText(with: username1, key: secureKey, iv: iv)
                password = cryptoLib.encryptPlainText(with: password1, key: secureKey, iv: iv)

backened team  using this https://medium.com/@jpatwa/java-encryption-javascript-decryption-using-aes-algorithm-4037ce09a2d3

**Comment by NathanFallet** [comment]
See https://github.com/krzyzanowskim/CryptoSwift/blob/master/README.md#aes for details and examples about how to implement AES 128 encryption. You might end with something like this:

```swift
do {
    // Your key and IV generation
    // Don't forget to store them somewhere to decrypt data later
    let secureKey = obj1.randomString(length: 16) as String // Note that for AES128, key and IV should be 16 bytes long (else, use AES192 or AES256)
    let iv = obj1.randomString(length: 16) as String

    // AES instance
    let aes = try AES(key: secureKey, iv: iv) // aes128

    // Encrypt your data
    let username = try aes.encrypt(Array(username1.utf8))
    let password = try aes.encrypt(Array(password1.utf8))
} catch { }
```

Also, note that a password is always hashed and not encrypted with techniques like AES (and the hash is compared to know if the password is correct), else the password can also be decrypted, which is not secure.
