### ISSUE TITLE
Block size & IV size not equal

### ISSUE THREAD

**Issue by jkritikos** [krzyzanowskim/CryptoSwift#86]
Hi there,

I'm using the latest version on the master branch and I'm trying to decrypt text that has been encrypted using Crypto-JS (AES 256 bits). Here's my test function:

    func testEncryption() {
            let keyRaw = "57622f526916f52becfa91db932acb0cbc2c0046fb30fc41ab3502d5ac3b6d08"
            let ivRaw = "bba6707d3f018b645166b47fd9c5e83b"
        
            let key = keyRaw.dataUsingEncoding(NSUTF8StringEncoding)?.arrayOfBytes()
            let iv = ivRaw.dataUsingEncoding(NSUTF8StringEncoding)?.arrayOfBytes()
        
            let messageRaw = "super secret!"
            let messageBytes = messageRaw.dataUsingEncoding(NSUTF8StringEncoding)?.arrayOfBytes()
        
            let encryptedData = AES(key: key!, iv: iv!, blockMode: CipherBlockMode.CBC)?.encrypt(messageBytes!)
        
            // 3. decrypt with the same key and IV
            let decryptedData = AES(key: key!, iv: iv!, blockMode: CipherBlockMode.CBC)?.decrypt(encryptedData!)
        
            println("plain text \(messageRaw)")
            println("encrypted \(encryptedData)")
            println("decrypted \(decryptedData)")
        }

However, I'm getting the following error:
assertion failed: Block size and Initialization Vector must be the same length!: file /Users/jace/dev/swift_lessons/xchallenge/xchallenge/Pods/CryptoSwift/CryptoSwift/AES.swift, line 117

I would *really* appreciate some help on this..Thanks a lot!

**Comment by krzyzanowskim** [comment]
you have key and iv in hex string representation. its not the valid input format. Convert it to bytes first. hex is 2 chars per byte.

**Comment by jkritikos** [comment]
You're absolutely right - but as you can see on the post I am already converting them using arrayOfBytes() - isn't that the correct way of doing the byte conversion?

**Comment by krzyzanowskim** [comment]
nope. you converted single characters to array of bytes, you need to convert hex representation. You need function that is opposite to `toHexString()` https://github.com/krzyzanowskim/CryptoSwift/blob/master/CryptoSwift/NSDataExtension.swift#L91

so as the result, IV will be 16 bytes long
