### ISSUE TITLE
Building issue on Xcode 12.5

### ISSUE THREAD

**Issue by sandeepgs1984** [krzyzanowskim/CryptoSwift#863]
Hi,

Recently, I have updated the XCode to the latest version v12.5 and there are errors occurring in the following framework files:
- Generics.swift
- UInt8+Extension.swift
- UInt16+Extension.swift
- UInt32+Extension.swift
- UInt64+Extension.swift

**error: 'exported: true' has no effect in '_specialize' attribute @_specialize(exported: true, where T == UInt8)**

Please fix these errors and release the new version.

Thanks,

**Comment by krzyzanowskim** [comment]
You're using old version of CryptoSwift and need to update it.

**Comment by sandeepgs1984** [comment]
Hi @krzyzanowskim, thanks for the quick reply. Sorry it was my mistake, I thought v1.2.0 is the latest!.

Thanks again.
