### ISSUE TITLE
CryptoSwift Build Errors in Xcode 12.5 

### ISSUE THREAD

**Issue by Coryhowell** [krzyzanowskim/CryptoSwift#864]
**Describe the bug**
'exported: true' has no effect in '_specialize' attribute errors in Generics.swift  

![CryptoSwift](https://user-images.githubusercontent.com/8327093/116584159-10eee180-a8e5-11eb-8534-ce47891e508b.png)

**Reproduce**
Steps to reproduce:
1. Project unable to build in Xcode 12.5 (12E262)  -> Running on M1 Mac

**Comment by krzyzanowskim** [comment]
you have an old version and you need to update CryptoSwift

**Comment by bajjajjrajjesh** [comment]
I updated the version yet I am getting error. I updated to 1.3.2

**Comment by krzyzanowskim** [comment]
your project must still link old version. this code was removed 9 months ago, starting 1.3.2

**Comment by bajjajjrajjesh** [comment]
what's the way to update? by install pod right?

**Comment by krzyzanowskim** [comment]
the CocoaPods it's `pod update`, I think.
https://guides.cocoapods.org/using/pod-install-vs-update.html

**Comment by Coryhowell** [comment]
I had trouble with pod update as well. it still linked the old version. I removed the pod version and installed the Swift Package version and version 1.4.0 installed and the issue went away.

**Comment by adham-ashraf77** [comment]
@Coryhowell  can you provide us the solution

**Comment by thomaskellough** [comment]
If you're using 12.5 Xcode consider downgrading to 12.4. You can download it from https://developer.apple.com/download/more/ assuming you have a developer account. This fixed the problem for me.

**Comment by krzyzanowskim** [comment]
what? wait, people! Don't downgrade Xcode.

This is an integration issue, something somewhere in your project that continues to use an old version of CryptoSwift. I don't know what exactly is it, and why, but as soon as it'll fetch an update it will solve the problem for you.

delete `Podfile.lock`, `Pods/`, or maybe `pod deintegrate` will clear caches that maight get in some bogus tate.

**Comment by AKThakur15** [comment]
yes Don't need to downgrade the Xcode. I am agree with @krzyzanowskim.

These steps resolve my issue.

1. Run pod deintegrate
2. Inside pod file add.  " pod 'CryptoSwift', '~> 1.4.0'  " 
3. Run pod install.

This will solve your issue.
Note* if you got any error after doing all these steps then you need to resolve those issue. In my case after doing all these steps I am facing some encryption decrytption error, so I need to modify that code, accordingly which is mentioned here https://github.com/krzyzanowskim/CryptoSwift

This solve my issue, hope you will also able to solve the issue, with these guidelines. Thanks.

**Comment by arancauchi** [comment]
Downgrading to 12.4 solved the issue for me. This library was a dependency of another, so unfortunately, I couldn't directly link newer versions of cryptoswift.

**Comment by sunflowerlabapps** [comment]
> erified the pod install worked and CryptoSwift was removed from the project. Now in Xc

@Coryhowell after pod install _`CryptoSwift`_  was not removed from my Pods
