### ISSUE TITLE
Getting Different values for Different XCode Vesion 

### ISSUE THREAD

**Issue by sumit-kasaudhan** [krzyzanowskim/CryptoSwift#866]

**Comment by krzyzanowskim** [comment]
You forget to add the "Steps to reproduce" section. an Xcode sample project would suit best

**Comment by sumit-kasaudhan** [comment]
My bad , wrote issue on some other library . Deleting comment

**Comment by krzyzanowskim** [comment]
I'm intrigued! what library is it?
