### ISSUE TITLE
Unclear minimum iOS version

### ISSUE THREAD

**Issue by Eckelf** [krzyzanowskim/CryptoSwift#867]
After the 1.4.0 release we've encountered an unexpected bump of the minimum iOS version to 12 (previously 9).
But it looks like that change was made only for the Xcode project and not for any of the other spec files (CocoaPods, SPM). The release notes also don't include any reference to that change.

Therefore the question: Which iOS version is the current minimum?

Thanks!

Blame: https://github.com/krzyzanowskim/CryptoSwift/commit/0cc931e771769e97809a227a9a6fb455dc7a5284#diff-bc450bae2cdc2752e103618c23149a69bd4af63376801c34f9db39cd7a4f68e5R11

**Comment by krzyzanowskim** [comment]
AFAIR the change to iOS 12 came with Xcode 12 settings update.
I'd like to keep the lowest target possible. I believe it should be v9
