### ISSUE TITLE
CBC NoPadding not work, CryptoSwift.AES.Error.dataPaddingRequired

### ISSUE THREAD

**Issue by HXPaul-S** [krzyzanowskim/CryptoSwift#869]
**Describe the bug**

i try this code:

let input: Array<UInt8> = [0,1,2,3,4,5,6,7,8,9]
        let encrypted: Array<UInt8> = try! AES(key: Array("secret0key000000".utf8), blockMode: CBC(iv: Array("0123456789012345".utf8)), padding: .noPadding).encrypt(input)

but i got error:
CryptoSwift.AES.Error.dataPaddingRequired

i use swift5 and Xcode 12.5

**Comment by krzyzanowskim** [comment]
CBC requires padding, that's why. It's by design.
