### ISSUE TITLE
NSData wrong values on hexString

### ISSUE THREAD

**Issue by ed-mejia** [krzyzanowskim/CryptoSwift#87]
Hi I'm doing this:

var imageData = UIImageJPEGRepresentation(image, 1)
if let hash = imageData.md5() {
fileName = hash.hexString.stringByTrimmingCharactersInSet(NSCharacterSet.whitespaceCharacterSet())+".jpg"
}

fileName output is : "1e b4 2f ae 03 ab 3c 40 aa 74 b2 81 a2 23 31 0e.jpg"

But I think this should be "1eb42fae03ab3c40aa74b281a223310e.jpg"

What I'm doing wrong?

Thanks.

**Comment by krzyzanowskim** [comment]
I don't know, all looks good, except the result you presented, don't know how you get it but it's not result of the code you presented.

**Comment by njovy** [comment]
I am having the same issue here. When it converts an NSData object into a hex string, it prints out with space. I have no idea why this is formatted with a space. 
Whenever a hex string is converted with a whitespace, hexString in NSDataExtension is not called. At least, it didn't stop breakpoints inside NSDataExtension.swift.

**Comment by ed-mejia** [comment]
I have not been able to work around this issue, author indicates nothing is wrong but the issue appears to be there for others not just me :(

**Comment by njovy** [comment]
@ed-mejia stringByTrimmingCharactersInSet(NSCharacterSet.whitespaceCharacterSet() was my first try and it didn't help so I used stringByReplacingOccurrencesOfString(" ", withString: "").
I am uncertain why it adds whitespaces there but it did a trick there.

**Comment by ed-mejia** [comment]
Hey @njovy  thanks mate, I will try that :)
