### ISSUE TITLE
Unable to decrypt if app is in background

### ISSUE THREAD

**Issue by anonyhacker93** [krzyzanowskim/CryptoSwift#875]
Hi
I am not able to decrypt the data if the app is background. In my scenario, my app is in background when a push notification comes, my job is to decrypt the push notification data. But it is returning nil. I am using AES to decrypt the data.

**Comment by krzyzanowskim** [comment]
It's hard to tell what's the problem. It's unlikely the CryptoSwift itself though. You should watch for throwing errors from CryptoSwift, it may be helpful. Most likely it's about an invalid key, or invalid input or something like that. This should guide you.
