### ISSUE TITLE
string after decryption AES 128 CBC

### ISSUE THREAD

**Issue by Piyush08** [krzyzanowskim/CryptoSwift#876]
**Describe the bug**

**Reproduce**
Steps to reproduce:
1. When I convert data to string using utf8 after decryption, it shows nil
2. If I convert bytes to string using utf8 after decryption, it shows some invalid characters in beginning.

let str1 = String(data: decryptedData, encoding: .utf8) ---> shows nil
let str2 = String(decoding: decryptedBytes, as: UTF8.self) ---> some invalid character in beginning

result from 2: 
"V���i(�K9�\u{1D}\u{12}\u{07}�m0166NMCVECFH8YJ3EQL45........"

How can I resolve this? @eneko @kylef

**Comment by eneko** [comment]
Hi @Piyush08, is this issue related to CryptoSwift?

**Comment by Piyush08** [comment]
> Hi @Piyush08, is this issue related to CryptoSwift?

Hi @eneko  I think so because I am not able to get string after decryption by anyhow.

Algorithm is decrypted well then it should return string.
I am still checking and I will happy to contribute if I found something.
Thank you,
