### ISSUE TITLE
Decrypt AES-128 encrypted data to string?

### ISSUE THREAD

**Issue by MrTheCoder** [krzyzanowskim/CryptoSwift#88]
Hi Marcin,

I'd like to thank you for the efforts that you're putting on this framework.

After all the research, I couldn't solve the small problem that I have.

At the moment, I'm working on a swift project that is scanning QR codes and getting encrypted AES-128 data and I want to decrypt it.

So, I have the key for decryption and encrypted string. What I should do to decrypt that encrypted string?

Any hint and help is much appreciated.

**Comment by thehellsoul** [comment]
try this: 
let encryptedData = NSData(base64EncodedString: encryptedString, options: NSDataBase64DecodingOptions.allZeros)

let aes = Cipher.AES(key: keyData.arrayOfBytes(), iv: ivData.arrayOfBytes(), blockMode: CipherBlockMode.CBC)

let decryptedString = NSString(data: NSData.withBytes(aes.decrypt(stringData.arrayOfBytes())!), encoding: NSUTF8StringEncoding) as! String

println(decryptedString)

**Comment by MrTheCoder** [comment]
Hi thehellsoul,

Thank you for your answer, but I have some errors like its displayed below.

Seems like iv and stringData causing the problem.

![screen shot 2015-06-30 at 17 48 35](https://cloud.githubusercontent.com/assets/9693175/8433806/9ccfa0e2-1f50-11e5-995b-76a3d5b7eced.png)

Thanks,

**Comment by krzyzanowskim** [comment]
@MrTheCoder: The conversion by thehellsoul is wrong. Don't use it. You can't assume that if input are ASCII bytes, so output will be mapped to ASCII as well (the same applies to UTF). Encryption is done on bytes, not letters for a reason.

That said. Input and output are bytes, you can do with it whatever you want, convert it to whatever format you want: bytes, hex representation of bytes, lossless conversion to string... whatever

**Comment by MrTheCoder** [comment]
I see,

thank you for your answer.

How do you suggest me to achieve this?, any kind of code snippet, tutorial or sample would be nice.

These are my values:
var keyData = "B7zqj4TAXnPevYZAR4T26969"
var encryptedString = "zWDzClfre4aOjTumzGsnpqh4Sje7sFsbKceA3/OSH3nKRwc7/6fYUajBr/bLh9BB"

and I need to find a way to decrypt this.

**Comment by krzyzanowskim** [comment]
I'm not fully understand the problem here. You have raw data from QR module, and want to decrypt it. Don't know what is "encrypted string" - it can be in any form, hex, base64, literally anything. So what you have to do is:

1. Transform input to array of bytes, if from NSData then with this helpers: https://github.com/krzyzanowskim/CryptoSwift#conversion-between-nsdata-and-uint8
2. decrypt
3. Transformt output array to whatever you need 

because you can't operate on string, you have to operate on bytes.

**Comment by thehellsoul** [comment]
@krzyzanowskim your answer is what i mean.
my **keyData** means var **key** type of **NSData**, same for **encryptedString** and **encryptedString**

**Comment by MrTheCoder** [comment]
Hi Marcin,

"encryptedString" is my variable name and it holds the data that came from QR. To not confuse I re-named them like this.

var key     = "B7zqj4TAXnPevYZAR4T26969"
var qrData  = "zWDzClfre4aOjTumzGsnpqh4Sje7sFsbKceA3/OSH3nKRwc7/6fYUajBr/bLh9BB"

That data from QR encrypted with the following: 
Cipher : AES 128bit key size.
Mode of Operation : CBC
Padding : PKCS7
Data derived from : Base64

Like you said, I have problem on 1st item in the list that you described. If I could transform it correctly I believe I could do the rest.

Would be really nice, if you could help me on transformation.
Thanks.

**Comment by krzyzanowskim** [comment]
Your `qrData` looks like base64 encoded data. 

```swift
let arrayOfBytes = NSData(base64EncodedString: qrData, options: NSDataBase64DecodingOptions.allZeros).arrayOfBytes()
```
