### ISSUE TITLE
CryptoSwift 'exported: true' has no effect in '_specialize' attribute 

### ISSUE THREAD

**Issue by gizemgizg** [krzyzanowskim/CryptoSwift#881]
**Describe the bug**

CryptoSwift 'exported: true' has no effect in '_specialize' attribute  error persists. can you help me
![Ekran Resmi 2021-07-07 14 26 06](https://user-images.githubusercontent.com/64318805/124751423-4a6c4a80-df2f-11eb-9662-95e944beb4ce.png)
?
**Reproduce**
Steps to reproduce:
1.

**Comment by krzyzanowskim** [comment]
you need to update, it's removed some time ago already

**Comment by gizemgizg** [comment]
Problem is still not solved. I don't know how to update. Do you have any documents?

**Comment by krzyzanowskim** [comment]
depends on what did you use to integrate framework, you have to use this tool to update to the latest version, that is 1.4.0 at the moment. Either by editing manifest file like Podfile or Package.swift or by downloading current version
