### ISSUE TITLE
No bitcode warning in simulator builds

### ISSUE THREAD

**Issue by chwo** [krzyzanowskim/CryptoSwift#883]
### Describe the bug

We use CryptoSwift in a (local) Swift Package which we use in our app.

Building the app on real devices works fine but building on simulators gives the following warning in the "Link WatchKit Extension" step:

> ld: warning: all bitcode will be dropped because '/Users/xxx/Library/Developer/Xcode/DerivedData/xxx-dbccudsxpcsrweavggraaecgvprn/Build/Products/Debug-watchsimulator/CryptoSwift.o' was built without bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. 

(`ENABLE_BITCODE=YES` is set in the Xcode Project and all targets.)

### Expected outcome

CryptoSwift should have `ENABLE_BITCODE=YES` so that there is no warning when building on iOS simulators.

I have looked into `CryptoSwift-Shared.xcconfig` and noticed that `ENABLE_BITCODE=YES` is already set there. Is it possible that iOS simulator builds have an issue with the `ENABLE_BITCODE[sdk=macosx*] = NO` setting?

### Steps to reproduce:
1. Create a (local) Swift Package
    - platforms: `.iOS(.v12), .watchOS(.v5)`
    - dependencies: `.package(url: "https://github.com/krzyzanowskim/CryptoSwift.git", .upToNextMajor(from: "1.4.1"))`
2. Use this package in the app and in the WatchKit Extension target
3. Build on an iOS simulator

### Environment
- Xcode Version 12.5.1 (12E507)
- iOS 14.7
- CryptoSwift 1.4.1

**Comment by krzyzanowskim** [comment]
This may be specific to WatchKit Extension, and frankly, it may be Xcode SPM issue. The SPM integration doesn't really have a way to specify whether bitcode is enabled or not.

> Is it possible that iOS simulator builds have an issue with the ENABLE_BITCODE[sdk=macosx*] = NO setting?

Bitcode is not available on macOS, therefore it's disabled. This shouldn't affect the simulator at all.

**Comment by chwo** [comment]
It turned out that this has nothing to do with CryptoSwift. The root cause was explicitly setting `ENABLE_BITCODE=YES` in the watchOS extension target. This applies bitcode to all builds whereas with the default setting bitcode is only selectively applied by Xcode.

**Comment by krzyzanowskim** [comment]
interesting! thanks for the update here. appreciated
