### ISSUE TITLE
Take too long time when Scrypt!!!

### ISSUE THREAD

**Issue by tuannm2** [krzyzanowskim/CryptoSwift#884]
Thank for awesome library :))

I have issue, when I run this code, it took too much time (about 3 minutes) to caculate. Am I wrong any where?:

 **let derivedKeys = try Scrypt(password: _password, salt: _salt!.bytes, dkLen: crypto.kdfparams.dklen, N: crypto.kdfparams.n!, r: crypto.kdfparams.r!, p: crypto.kdfparams.p!).calculate();**

Here is my code:
<img width="691" alt="Screen Shot 2021-07-13 at 15 26 06" src="https://user-images.githubusercontent.com/85265921/125418191-075d79ae-5483-494f-9609-58e14432162c.png">

Here is my params: 
crypto: {
					ciphertext: 'f7068d2b16e72d7ac6c4b5619dca7b00a99c52fbcd233f7d3778bb621e550041',
					cipherparams: { iv: 'b215370f6e897aa9d203fcd8865a0c0d' },
					cipher: 'aes-128-ctr',
					kdf: 'scrypt',
					kdfparams: {
						dklen: 32,
						salt: 'c10fdddfb81b89d3a6113f63500ca6cbb6c71ef55402e7260ec5a4a9d885ae1e',
						n: 131072,
						r: 8,
						p: 1,
					},
					mac: '81fbee335bb32437a7eed9a2b3849965bcf4e4aa7e5301270f1e942df0c97ef6',
				},

**Comment by tuannm2** [comment]
> this is swift debug performance thing, it's fast in release build (aka optimized swift). Can't make Swift faster.

Thank you for yor reply.

Could you tell me how fast is it when app in release, please !!

**Comment by krzyzanowskim** [comment]
up to x1000 faster
