### ISSUE TITLE
Missing iOS deployment target causes warning

### ISSUE THREAD

**Issue by AseeTucek** [krzyzanowskim/CryptoSwift#885]
**Describe the bug**
The project is missing iOS deployment target property and because of that when you build an app that has  deployment target lower than iOS 12.0 it produces an Xcode warning:
`ld: warning: dylib (/Users/ltucek/Library/Developer/Xcode/DerivedData/<PATH>/CryptoSwift.framework/CryptoSwift) was built for newer iOS version (12.0) than being linked (11.0)` 

**Reproduce**
Steps to reproduce:
1. Build an app with iOS deployment target lower than iOS 12.0

**Comment by krzyzanowskim** [comment]
1. delete `DerivedData`.
2. CryptoSwift project is set to deployment target v. 9.0 https://github.com/krzyzanowskim/CryptoSwift/blob/master/config/Project-Shared.xcconfig#L11

Looks like an integration issue. How did you integrate CryptoSwift?
