### ISSUE TITLE
can't install 1.4.1 version

### ISSUE THREAD

**Issue by Trecobat** [krzyzanowskim/CryptoSwift#888]
Hello
I'm trying to install your last version 1.4.1 (needed for another pod I'm using) but I can't : I get this error when running pod install :
[!] CocoaPods could not find compatible versions for pod "CryptoSwift":
  In Podfile:
    CryptoSwift (= 1.4.1)

If I don't put any version in my podfile, it would install 1.4.0 version.

Any suggestion ?

**Comment by krzyzanowskim** [comment]
1.4.1 is published properly https://github.com/CocoaPods/Specs/blob/master/Specs/3/e/b/CryptoSwift/1.4.1/CryptoSwift.podspec.json

maybe you need update pods source or something, if it can't see current data.

`pod search --simple CryptoSwift` should list `CryptoSwift (1.4.1)`

you can try `pod cache clean` just in kase
