### ISSUE TITLE
CryptoSwift with CryptoJS, revisited

### ISSUE THREAD

**Issue by johnqh** [krzyzanowskim/CryptoSwift#890]
**Describe the bug**

Yes, I have read #654 

The Swift code does not decode to the original message "hello"

**Reproduce**
Steps to reproduce:
1. Run this code

```
                let mdata = Data(base64Encoded: "U2FsdGVkX183L9KMplOrdQv4gxqPQayV+hAbc3vwO5M=")!
                let count = [UInt8](mdata).count
                let mbytes = Array([UInt8](mdata)[AES.blockSize ..< count])
                let miv = Array([UInt8](mdata)[0 ..< AES.blockSize])
                let mkey = try! PKCS5.PBKDF2(password: "@!abcdef@".bytes, salt: miv, iterations: 4096, keyLength: 16, variant: .md5).calculate()

                if let aes = try? AES(key: mkey, blockMode: CBC(iv: miv)) {
                    if let decrypted = try? aes.decrypt(mbytes) {
                        if let mresult = String(bytes: decrypted, encoding: .utf8) {
                            print(mresult)
                        }
                    }
                }
```

2, Expected result: mresult should be "hello", as this is the input in #654
3, decrypted is a byte array of 
  - 0 : 121
  - 1 : 1
  - 2 : 113
  - 3 : 58
  - 4 : 122
  - 5 : 200
  - 6 : 59
  - 7 : 146
  - 8 : 45
  - 9 : 6
  - 10 : 77
  - 11 : 206
  - 12 : 99
  - 13 : 67
  - 14 : 203
  - 15 : 45
4, mresult is nil because decrypted is not an UTF-8 string (or UTF-16)

**Comment by krzyzanowskim** [comment]
If any default changed since https://github.com/krzyzanowskim/CryptoSwift/issues/596#issuecomment-381341586 somebody needs to re-read CryptoJS sources to get the reason what it does now by default. The most likely key is derived uses different parameters by default (or different function)

**Comment by krzyzanowskim** [comment]
this comment stands https://github.com/krzyzanowskim/CryptoSwift/issues/613
CryptoJS defaults (afaik) to `EVP_BytesToKey`, that is deprecated in OpenSSL itself. What you should do is to make CryptoJS don't use default, but PBKDF2 instead, with parameters as in sample code

**Comment by astrokin** [comment]
if someone decided to use default CryptoJS functionality - i've finally[ make it work on iOS and Android ](https://medium.com/@alex.strok/cross-platform-encrypt-decrypt-ios-android-web-5f4ec26c2cef):)
