### ISSUE TITLE
Note that it uses an unstable format and may leak internal project details, it should not be distributed alongside modules

### ISSUE THREAD

**Issue by imotoboy** [krzyzanowskim/CryptoSwift#891]
CryptoSwift.framework/Modules/CryptoSwift.swiftmodule/Project/arm64-apple-ios.swiftsourceinfo' is either malformed or generated by a different Swift version. Note that it uses an unstable format and may leak internal project details, it should not be distributed alongside modules

**Comment by imotoboy** [comment]
<img width="1380" alt="截屏2021-09-15 下午1 25 28" src="https://user-images.githubusercontent.com/54018634/133375614-dfe1cfa3-adf4-49c5-8bda-d5f1e6f4cbd9.png">
:: Xcode 13 RC

**Comment by krzyzanowskim** [comment]
beautiful. So what is says is that binary has to be rebuilt with Xcode 13. I'm not sure at this moment whether it stop working with Xcode 12, so need to investigate a bit. For the time being, either ignore the warning or switch to Source-based distribution. I'm sorry for any inconvenience Xcode 13 may cause to you

**Comment by krzyzanowskim** [comment]
@imotoboy what version do you have installed exactly?

**Comment by imotoboy** [comment]
> @imotoboy what version do you have installed exactly?

Hello, I tested the Xcode13 RC version today and encountered this problem. Ignore the warning and it can run normally. I just want to report this problem to you. Thank you for your contribution to the open source community.

**Comment by imotoboy** [comment]
> @imotoboy what version do you have installed exactly?

1.4.1
