### ISSUE TITLE
SPM Suggest #binaryTarget#

### ISSUE THREAD

**Issue by imotoboy** [krzyzanowskim/CryptoSwift#901]
add CryptoSwift.xcframework (release) to repo, and use  binaryTarget

let package = Package(
    name: "CryptoSwift",
    products: [
        // Products define the executables and libraries a package produces, and make them visible to other packages.
        .library(
            name: "CryptoSwift",
            targets: ["CryptoSwift"]),
    ],
    targets: [
        .binaryTarget(name: "CryptoSwift", path: "CryptoSwift.xcframework")
    ]
)

**Comment by krzyzanowskim** [comment]
SPM suggests a binary target, where?

**Comment by imotoboy** [comment]
Reslove this issues

![Screenshot_20211201-064823.jpg](https://user-images.githubusercontent.com/54018634/144140715-32f4c023-04a0-4618-9970-2104b10fcb6d.jpg)

**Comment by krzyzanowskim** [comment]
I don't follow. what is the issue?
