### ISSUE TITLE
android  had githud link?

### ISSUE THREAD

**Issue by burning-git** [krzyzanowskim/CryptoSwift#906]
<img width="1002" alt="图片" src="https://user-images.githubusercontent.com/8384858/146907728-4ee73025-f5da-47d7-9593-3a68c434dad2.png">

I can't find android githud link.

**Comment by NBH7** [comment]
Can you unsubscribe me please I don’t want all these shit emails now don’t send me anymore thanks 


Sent from Yahoo Mail for iPhone


On Sunday, July 17, 2022, 2:10 pm, Marcin Krzyzanowski ***@***.***> wrote:




Closed #906 as completed.
