### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by SodaSurfer** [krzyzanowskim/CryptoSwift#909]
Hello

I am trying to install this repo using a pod file.
I am using macOS with m1.

I am getting this error:
`Could not find module 'CryptoSwift' for target 'arm64-apple-ios-simulator'; found: i386, x86_64-apple-ios-simulator, x86_64, i386-apple-ios-simulator`

**Comment by krzyzanowskim** [comment]
since it builds from source, I assume your cocoapods integration issue maybe?

**Comment by SodaSurfer** [comment]
This is my full pod file if that what you mean by my cocoa pods integration (it's a very thin project, just for.a playground):
```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ssl_example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ssl_example
  pod 'OpenSSL-Universal'
  pod 'CryptoSwift', '~> 1.4.1'

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
    config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
  end
  
  
  # Fix openssl incompatibility on case-sensitive fs
  unless File.exist? "pods"
    ['ios-arm64_arm64e_armv7_armv7s', 'ios-arm64_i386_x86_64-simulator', 'ios-arm64_x86_64-maccatalyst', 'macos-arm64_arm64e_x86_64'].each do |d|
      system("cd Pods/OpenSSL-Universal/Frameworks/OpenSSL.xcframework/#{d} && ln -Fs {OpenSSL,openssl}.framework")
    end
  end
end

end

```

**Comment by SodaSurfer** [comment]
I've tried to remove it, but didn't work.

**Comment by Mrscherry** [comment]
SUN DEFi
 👉 Today's leading electronic financial application.
 👉Sun Defi investment is profitable.
 Annual profit up to 1440%.
 👉High security, absolute safety, quick and quick deposit and withdrawal procedures.
 👉New member promotion when inviting you to join someone get 20 USDt.
 Sun Defi will help you become a Finance expert.
 Quickly click on the link to join Sun Defi:

 https://www.funawealth.com?share_address=0x1813752628964484E01744527388ed5429024926
