### ISSUE TITLE
Issue with branch rename

### ISSUE THREAD

**Issue by idoodler** [krzyzanowskim/CryptoSwift#910]
**Describe the bug**
I am just migrating an existing project to my new PC but I am having issues with the branch name change from `master`  to `main`.

I am unable to edit the branch name as the entry `CryptoSwift` doesn't exist in xCode, when I try to re-add it I get greeted with an warning that doesn't fix the issue.

**Reproduce**
Steps to reproduce:
1. Try to add CryptoSwift to an project which previously used the `master` branch
<img width="1088" alt="Bildschirmfoto 2022-02-25 um 16 47 18" src="https://user-images.githubusercontent.com/6825153/155745840-1ba4ba5a-3967-4636-a781-091019ea3b0d.png">

**Comment by krzyzanowskim** [comment]
that's Xcode issue. try report to Apple.
Possible resolution is delete SPM systemwide cache.

**Comment by idoodler** [comment]
I cleared Derived Data `~/Library/Developer/Xcode/DerivedData`, and cleared the SPM cache `~/Library/Caches/org.swift.swiftpm` but reopened Xcode but it didn't resolve the issue.

I created an issue at Apple, @krzyzanowskim May you be able to create the "master" branch again?

**Comment by krzyzanowskim** [comment]
> May you be able to create the "master" branch again?

technically it's possible, however, I'm unlikely to update both branches. I guess it's better if you fork it or something on your own. There should be a way to unscrew Xcode somehow 🤦‍♂️

you can try whether any of this Xcode commands help

<img width="560" alt="Screen Shot 2022-02-25 at 20 08 40" src="https://user-images.githubusercontent.com/758033/155773595-e15a78f5-5e5f-45a7-9b39-7d9e37bed2da.png">

**Comment by idoodler** [comment]
> you can try whether any of this Xcode commands help

Yes, I did that already, nothing worked. I just can't find where xCode references the SPM. `Kingfisher` is referenced in `project.pbxproj` however I am not able to find `CryptoSwift`.

I will try to forking for now

**Comment by idoodler** [comment]
Just forking won't work, as the old package is still somewhere around and I now get a new error. As there is the same module with different branches now. I'll try to adopt the package name
<img width="779" alt="Bildschirmfoto 2022-02-25 um 20 56 11" src="https://user-images.githubusercontent.com/6825153/155786399-e0239285-74db-44e4-86fd-d1a53c597738.png">

**Comment by idoodler** [comment]
@krzyzanowskim Ok, It won't work:/ It'll be real nice if you add the `master` branch again just for legacy reason to circumvent that issue.

**Comment by idoodler** [comment]
Fixed! I overlocked, that we had a sub-dependency using CryptoSwift. I was able to easily change the branch from `master` to `main`. 😅
