### ISSUE TITLE
Can’t install pod in iOS 

### ISSUE THREAD

**Issue by RahulTak** [krzyzanowskim/CryptoSwift#916]
I already installed pod ‘CryptoSwift’ and now I want to add one another pod to install so you pos is blocking me to add another pod into my project.
![Screenshot 2022-04-16 at 1 01 22 AM](https://user-images.githubusercontent.com/17697120/163624935-9ffcf288-0ced-4f1a-b123-2962b4f82b7f.png)
 Please help ASAP

**Comment by krzyzanowskim** [comment]
> The version of CocoaPods used to generate the lockfile (1.10.2) is higher than the version of the current executable (1.10.0.beta.1)

this looks like your cocoapods installation/use problem. Looks like you should update cocoapods on your machine.
