### ISSUE TITLE
SPM BigInt framework conflict

### ISSUE THREAD

**Issue by yaroslavyaroslav** [krzyzanowskim/CryptoSwift#917]
When we're using you're lib at `1.5.0` version with [BigInt](https://github.com/attaswift/BigInt) repo it produces `ambiguous BigInt` error on building.

This happening coz you're add same type into source code at the last days minor updates.

We're make quick fixups for ourself to fetch exact last working version (1.4.3), but it's not in best practices to add breaking changes within minor updates.
 

**Reproduce**
Steps to reproduce:
1. This SPM wouldn't build (Coz `web3swift` lib includes two dependencies: `BigInt` and `CryptoSwift`) It were building well before 1.5.0 release.
```swift
// swift-tools-version:5.5
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "Web3SwiftBuilding",
    platforms: [
        .iOS(.v13),
        .macOS(.v10_15)
    ],
    dependencies: [
        .package(url: "https://github.com/skywinder/web3swift.git", .exact("2.6.1"))
    ],
    targets: [
        // Targets are the basic building blocks of a package. A target can define a module or a test suite.
        // Targets can depend on other targets in this package, and on products in packages this package depends on.
        .executableTarget(
            name: "Web3SwiftBuilding",
            dependencies: ["web3swift"]),
        .testTarget(
            name: "Web3SwiftBuildingTests",
            dependencies: ["Web3SwiftBuilding"]),
    ]
)
```

Updated: change package a bit, since without `.exact("2.6.1")` bit of code this project would be build successfully, since patch released.

**Comment by krzyzanowskim** [comment]
cc @NathanFallet we should either rename types or make sure these are not public

**Comment by mloit** [comment]
> cc @NathanFallet we should either rename types or make sure these are not public

Curious as to the reason the sources have been directly incorporated, instead of just including `BigInt` as a dependency?

**Comment by NathanFallet** [comment]
> Curious as to the reason the sources have been directly incorporated, instead of just including `BigInt` as a dependency?

I wanted to add the package as an external dependency. It worked for SPM, but apparently it was a problem for building as a framework. So @krzyzanowskim told be to add the source like this.

@krzyzanowskim Are you sure there is no way to BigInt as an external dependency that works with building as a framework?

**Comment by yaroslavyaroslav** [comment]
To all folks who met this issue until patch would be released, this would help:
`.package(url: "https://github.com/krzyzanowskim/CryptoSwift.git", .exact("1.4.3"))`

**Comment by krzyzanowskim** [comment]
@yaroslavyaroslav you should update your code too. When two modules export the same name (that is not uncommon) you can be explicit on which one you want to use, eg. `CryptoSwift.BigInt` vs `BigInt.BigInt`. Swift is not the best at supporting that in some scenarios when names clash.

**Comment by krzyzanowskim** [comment]
> @krzyzanowskim Are you sure there is no way to BigInt as an external dependency that works with building as a framework?

there is a way technically. I choose to not. Maintaining transient dependency compatibility is a hell I don't want to live in.

**Comment by krzyzanowskim** [comment]
can you please check the `main` branch now and let me know whether it works in your setup, before I release it as an update?

**Comment by krzyzanowskim** [comment]
This has been resolved with [v1.5.1](https://github.com/krzyzanowskim/CryptoSwift/releases/tag/1.5.1)

**Comment by yaroslavyaroslav** [comment]
> @yaroslavyaroslav you should update your code too. When two modules export the same name (that is not uncommon) you can be explicit on which one you want to use, eg. `CryptoSwift.BigInt` vs `BigInt.BigInt`. Swift is not the best at supporting that in some scenarios when names clash.

Well, I'd just don't expect any `BigInt` type within minor `CryptoSwift` update, more than that there're no such type in 1.4.3 as I can see.

**Comment by krzyzanowskim** [comment]
it ok to add new types as long as it's additive. I didn't anticipate the name conflict tho.
