### ISSUE TITLE
Support for Carthage?

### ISSUE THREAD

**Issue by sugarwyc** [krzyzanowskim/CryptoSwift#93]
Support for Carthage?

**Comment by zenkimoto** [comment]
@sugarwyc 

I noticed there isn't official support for carthage indicated in the documentation, but I tried it myself and it seems to work fine.  Just add:

```code
github "krzyzanowskim/CryptoSwift"
```
to your cartfile.

**Comment by krzyzanowskim** [comment]
is it? this is great news!

**Comment by zenkimoto** [comment]
@sugarwyc 

Do you want to confirm this?  I can try it on another project and see.  But what I've tried so far seems to work.

@krzyzanowskim 

Great job on this awesome library!

**Comment by zenkimoto** [comment]
I just tried it on another project with the current version 0.11 and it works.  Let me know if you run into any issues @sugarwyc
