### ISSUE TITLE
Consider subspecs for individual functions

### ISSUE THREAD

**Issue by keith** [krzyzanowskim/CryptoSwift#95]
Currently we're just using the MD5 implementation from CryptoSwift since that's all our application needs. Since we don't want to include the entire project through CocoaPods just for this one file we've elected to copy that file into our project. Obviously this is horrible and we'd much prefer to use CocoaPods for this. It would be ideal if the spec was broken into multiple subspecs to enable this sort of usage.

**Comment by krzyzanowskim** [comment]
It always introduce maintenance complication to separate everything into the separate files. In this case there are extensions and enums that would need to be split or omitted, in result providing partial interface. I'm not sure if it worth it. There is nothing wrong with using just one piece of framework after all, is it ?

**Comment by keith** [comment]
I just noticed that it got more complicated in the swift 2 branch. I'd just prefer not to include a framework with ~30 files when I will definitely never use the others.

**Comment by krzyzanowskim** [comment]
As for today you need copy HashProtocol.swift, Utils.swift, MD5.swift. Can't guarantee it won't change in the future though. In particular I don't know easy way to test subspec like this, any idea?

**Comment by keith** [comment]
Each subspec would just have to include the files necessary. Then running `pod spec lint` on it should verify it's setup correctly. I understand that this might complicate things though

**Comment by krzyzanowskim** [comment]
@keith anyway, can you make a PR for MD5 subspec? to swift20 branch please.

**Comment by keith** [comment]
After investigating this it looks like a lot more files than expected would have to be included which kind of defeats the purpose. Thanks though!

**Comment by markst** [comment]
Sad times
