### ISSUE TITLE
Not sure whether i'm using AES128 or AES256.

### ISSUE THREAD

**Issue by ptmjanish** [krzyzanowskim/CryptoSwift#96]
I'm new to encryption. Using CryptoSwift. I am not sure whether i'm using AES128 or AES256. I am getting AES.blockSize = 16. How can i change from 128 to 256 if it is 128?

**Comment by krzyzanowskim** [comment]
You can't change block size. AES128,AES256 depends on length of your key if not specified otherwise.

**Comment by ptmjanish** [comment]
Thanks, it's working. Can u provide me a code to randomly generate AES256 key.
i just hard coded it now.

**Comment by krzyzanowskim** [comment]
It's just random data. you can use use arc4random() or whatever you'll find convenience.

**Comment by ptmjanish** [comment]
Thank u.
