### ISSUE TITLE
Please Add GCM feature

### ISSUE THREAD

**Issue by Arkanji** [krzyzanowskim/CryptoSwift#97]
Awesome library, very impressive work, keep it up

thank you so much

**Comment by fproulx-pbox** [comment]
Would be a really nice addition, indeed.

**Comment by cikpis** [comment]
Hi @krzyzanowskim, could you please implement the GCM BlockMode? Thanks in advance!

**Comment by wukongzhikong** [comment]
It would be great if you can add supports to GCM.

**Comment by cikpis** [comment]
At the end I'm using https://github.com/soyersoyer/SwCrypt

**Comment by krzyzanowskim** [comment]
GCM is available on master branch and will be released with 0.10.0
