### ISSUE TITLE
importing from cocoapods xcode always detect build errors

### ISSUE THREAD

**Issue by mohand007** [krzyzanowskim/CryptoSwift#99]
hii ,I have a problem importing importing CryptSwift  in swift (xcode 6.1.1) when I use cocoaPods , that imports the files but xcode always detect errors in the swift files imported making the project fail to build is that due to the xcode version (xcode 6 1.1) ? and what is the solution ?

(	
pod : version 0.37.2 , xcode : 6.1.1 , 
I'm tryig to import Cryptoswift and my podfile : 

platform :ios, '8.0' 
use_frameworks! 
pod 'CryptoSwift'
)

**Comment by krzyzanowskim** [comment]
Current version is for swift 1.2 so yes, xcode 6.1 is swift 1.0
